### ISSUE TITLE
Date Picker Directive Error Concluded in Approval

### ISSUE THREAD

**Issue by maektwain** [openMF/community-app#1279]
![image](https://cloud.githubusercontent.com/assets/8274610/6637884/c0c00628-c9a5-11e4-84e2-4fe8cfbb7e41.png)

I am getting this error when i am going to approve the Loan, for a client, 

On the Approval Screen I am getting the Following error 

![image](https://cloud.githubusercontent.com/assets/8274610/6638022/7fda2a88-c9a7-11e4-9f4e-4116218e2a5b.png)

Why am i getting this error is it because of incorrect setting in the MIFOS X APP 

OS:UBUNTU 14.04,
https://184.173.24.10:8443/community-app/#
Username and password 
decimus 
1234

**Comment by maektwain** [comment]
I have the community app which was previously cloned from repository which doesn't have much broader loan approval details is working fine, !

**Comment by maektwain** [comment]
I was able to resolve the No.1 Screen Shot, error by editing datepicker.js 
The seconds issue i am still facing @vishwasbabu

**Comment by vishwasbabu** [comment]
If you are cloning the community app from the develop branch, you would have to run it against the develop branch of the platform code. 

By default, the community app connects to the platform code deployed on the demo server (which is the latest stable release, currently 1.26.0)

Let me know if you are still facing the error when you are running against the platfrom code taken from the develop branch and I would be happy to debug the same
