### ISSUE TITLE
Failed to instantiate module MifosX_Application due to: Error: [$injector:unpr] Unknown provider: $idleProvider

### ISSUE THREAD

**Issue by ashokjp93** [openMF/community-app#1285]
I have followed all the steps mentioned in community app installation including bower install and npm install, while running the grunt serve application showing error Unknown provider  $idleProvider.

Please kindly guide me.

**Comment by vishwasbabu** [comment]
It looks like ng-Idle has had an update with breaking changes https://github.com/HackedByChinese/ng-idle/wiki/Migrating-to-version-1.0.0-from-0.x ....

https://github.com/openMF/community-app/commit/59ed3462d50109026ac6d6d203eefb1a41ffa997 should fix the issue

**Comment by ashokjp93** [comment]
Thank you. Now I can able to run mifosx community app.
