### ISSUE TITLE
Search On Client Screen 

### ISSUE THREAD

**Issue by theupscale** [openMF/community-app#1313]
When searching a client from the client screen , the feature only allows to search within 14 clients which get pulled off from the api call now consider that there are 1000 clients and the desired client is on 10th page so that means we have to go to the 10th page to view it 

Solution 
Can't we implement something that displays the search result on the same page without paginating it?

**Comment by vishwasbabu** [comment]
You can search for a client on the search icon at the top right corner of the screen.

The filter you have on the client screen only filters within the selected page (agree this is confusing though)

**Comment by theupscale** [comment]
Ok,Probably i am going to implement the full search without pagination
