### ISSUE TITLE
How to configure repayment strategy

### ISSUE THREAD

**Issue by theupscale** [openMF/community-app#1314]
I am looking at the 
While creating a loan product there is field :repayment strategy where all the data is populated 

How to modify that data

Can we configure it using the API

**Comment by vishwasbabu** [comment]
You can read about repayment strategies at https://demo.openmf.org/api-docs/apiLive.htm#paymentapplicationlogic

While you can select amongst the repayment strategy for a loan product, you would have to make a code level change for creating a new repayment strategy of your own

Can you please forward any other questions you may have to our mailing lists at https://mifosforge.jira.com/wiki/display/MIFOSX/Getting+started+-+Contributing+to+MifosX#Gettingstarted-ContributingtoMifosX-MifosXMailingLists (we do not regularly monitor github issues and you would get a much quicker response on the mailing lists)?
