### ISSUE TITLE
Missing meta viewport tag

### ISSUE THREAD

**Issue by ad-os** [openMF/community-app#1491]
I was skimming through the code and found that the **index.html** file is missing the meta viewport tag.
When a page does not specify a viewport, mobile browsers will render that page at a fallback width ranging from 800 to 1024 CSS pixels.The page scale factor is adjusted so that the page fits on the display, forcing users to zoom before they can interact with the page.
This is how the view looks on ipad when the viewport tag is not included
![before](https://cloud.githubusercontent.com/assets/8019601/13552648/c2ec003a-e391-11e5-96d3-4d390363e880.png)
This is how the view looks on ipad after the viewport tag has been included.
![after](https://cloud.githubusercontent.com/assets/8019601/13552649/eeb0f676-e391-11e5-89d9-d4378c581b64.png)
Verify this so that I can make a pull request :smile: 
Thanks
Adhyan

**Comment by mdew192837** [comment]
@ad-os Is this still a problem? I can maybe fix for GCI. :)

**Comment by ad-os** [comment]
Hi @mdew192837,
I discussed this issue with other mentors, like whether we should fix this issue. We reached to a conclusion that including this viewport tag would require us to configure all the pages of community app because inclusion of this tag is distorting the mobile view for most of the pages.So, I am closing this issue for now. Thanks, for your interest.
P.S:- Sorry for the late reply :)
