### ISSUE TITLE
Improve Loan Page Layout

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1612]
See https://mifosforge.jira.com/browse/MIFOSX-970 for full details and comments.

Rather than address the bugs in the current loan page layout, perhaps we can just implement this redesign. 

![screen shot 2016-02-02 at 5 16 20 pm](https://cloud.githubusercontent.com/assets/823454/19275783/8009643e-8f89-11e6-9bd8-0d11f7ab6efe.png)

**Comment by edcable** [comment]
Right now all the pages are on one screen and not separate tabs. We need to implement the tabbed view but propose we do it with the new improved layout. 

![screen shot 2016-10-11 at 7 30 28 am](https://cloud.githubusercontent.com/assets/823454/19276465/391a6f30-8f8b-11e6-88f6-27594893ddc4.png)
![screen shot 2016-10-11 at 7 30 41 am](https://cloud.githubusercontent.com/assets/823454/19276466/3920a2ba-8f8b-11e6-9ed3-5ec07a525903.png)

**Comment by mbj36** [comment]
Fixed
