### ISSUE TITLE
Input fields for new savings account are smushed together. 

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1613]
See

![screen shot 2016-10-11 at 7 26 08 am](https://cloud.githubusercontent.com/assets/823454/19275991/0ba5f1b0-8f8a-11e6-9689-8620e7249199.png)

**Comment by shubhpatel108** [comment]
This too is solved!

**Comment by mbj36** [comment]
@shubhpatel108 This issue refers to the new UI which is yet to be merged.

**Comment by mbj36** [comment]
Fixed
