### ISSUE TITLE
Center the buttons for uploading/capturing photo on client page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1614]
![screen shot 2016-10-11 at 7 26 45 am](https://cloud.githubusercontent.com/assets/823454/19276086/35b49e98-8f8a-11e6-8cc4-ba52df01af52.png)

**Comment by mdew192837** [comment]
@edcable I just tested this and I think this is fixed. See this screenshot on my local install. https://postimg.org/image/4u8df0qel/43d05b0f/

**Comment by mbj36** [comment]
@mdew192837  please only look on those issue which has a GCI tag, Some issues are produced here for the code which is yet to be merged

**Comment by gkrishnan724** [comment]
@mbj36 @edcable https://github.com/openMF/community-app/issues/198. I'm working on this

**Comment by gkrishnan724** [comment]
@mbj36 could you close this please :)

**Comment by mbj36** [comment]
@santoshmath retest and close it
