### ISSUE TITLE
Auto-select of clients doesn't seem to work while creating a group

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1615]
I assume as you type the name of a client that belongs to the office it should populate as an option to select to adding to the group. On both the re-skinned app as well as the current Community App, nothing gets populated and I can click add but it just adds a blank value.

![screen shot 2016-10-11 at 8 21 28 am](https://cloud.githubusercontent.com/assets/823454/19276938/db75ec18-8f8c-11e6-9bf9-3f79005f8032.png)
![screen shot 2016-10-11 at 8 29 51 am](https://cloud.githubusercontent.com/assets/823454/19276946/e65e0e1c-8f8c-11e6-9c99-b6c5e5d6099d.png)

**Comment by mbj36** [comment]
I find it fixed @edcable at https://demo.openmf.org/#/, Any inputs ?

**Comment by santoshmath** [comment]
Tested it on demo(newbeta). It  is resolved.
