### ISSUE TITLE
Reskin&oldSkin: Auto-select of groups while creating a new center doesn't work

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1616]
Same issue as with the selection of clients while creating a group. On both the current web client and the re-skinned one, I select an office that I know has groups belonging to it and then try typing the name of an existing group to add to the center but nothing populates in the search to be selected.

See screenshots. On beta server, I was trying for the group test within in the Head Office. On the demo4 server I was searching for a Santa Maria group under the Regional Office. 
![screen shot 2016-10-11 at 8 33 01 am](https://cloud.githubusercontent.com/assets/823454/19277148/98827420-8f8d-11e6-94ad-ae66f604c847.png)
![screen shot 2016-10-11 at 8 33 09 am](https://cloud.githubusercontent.com/assets/823454/19277147/988175b6-8f8d-11e6-9d7e-1a8145b4f2d1.png)

**Comment by edcable** [comment]
Still not working on https://demo.openmf.org/newbeta/#/createcenter

If you go to p2p institutional as office and M,Mary as staff or any group that doesn't belong to a staff person, no groups show up in the dropdown to add to the center.

See

![screen shot 2017-02-27 at 2 23 18 pm](https://cloud.githubusercontent.com/assets/823454/23382878/c710dcea-fcf8-11e6-9908-99b7be0f3b0e.png)

**Comment by mbj36** [comment]
@gkrishnan724 can u look at this ?

**Comment by gkrishnan724** [comment]
I'll work on this :+1:

**Comment by gkrishnan724** [comment]
Hi @mbj36 I don't think this is a front-end issue. I just checked the `CreateCenterController.js`  and we see that we are looking for something called as `groupMembersOptions` for our group data which is not being loaded. Also, when I checked the API that we are fetching the data from: [link](https://demo.openmf.org/fineract-provider/api/v1/centers/template?tenantIdentifier=default&pretty=true). I found that we have StaffOptions for the staff and OfficeOptions for the office but there is no data on groups or group options.  could you verify it?

**Comment by santoshmath** [comment]
@avikganguly01 , @mbj36 , Do you think it's front end issue too?

**Comment by mbj36** [comment]
@botraunak Can you recheck ?

**Comment by botraunak** [comment]
@mbj36 Yes the template should be returning `groupMemberOptions` as the available groups available for the creation of center. But this issue is still solvable from the front-end side. [#REF](https://demo.openmf.org/api-docs/apiLive.htm#centers_template)

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
This issue is not  yet fixed. Drop-down  menu for selecting group in Create center page lists groups but after submission the group is not shown on center page. More over , you can add more  than one group for a center in a 'Create Center' page

**Comment by mbj36** [comment]
Fixed
