### ISSUE TITLE
Column for navigation should be same length for all headers.

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1617]
See

![screen shot 2016-10-11 at 8 36 36 am](https://cloud.githubusercontent.com/assets/823454/19277272/fc384fda-8f8d-11e6-9d95-0d1825a6771c.png)
![screen shot 2016-10-11 at 8 37 28 am](https://cloud.githubusercontent.com/assets/823454/19277273/fc397c84-8f8d-11e6-90ac-6a89a6c052fa.png)

**Comment by shubhpatel108** [comment]
This seems to be solved. Shall we close this one?

**Comment by edcable** [comment]
Still exists at https://demo.openmf.org/newbeta/#/bulkloan

**Comment by mbj36** [comment]
Fixed
