### ISSUE TITLE
Reskin&oldSkin: Clean up Bulk JLG Loan Application Layout

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1618]
See screenshots
![screen shot 2016-10-11 at 8 43 25 am](https://cloud.githubusercontent.com/assets/823454/19277632/3431c2c6-8f8f-11e6-9675-8eab64a06e9d.png)
![screen shot 2016-10-11 at 8 46 11 am](https://cloud.githubusercontent.com/assets/823454/19277633/344f9184-8f8f-11e6-8d63-c5b813b2d8a9.png)

**Comment by gkrishnan724** [comment]
I'll try working on this :+1:

**Comment by gkrishnan724** [comment]
@mbj36 I think it looks good now? can we close this?
