### ISSUE TITLE
Bulk Loan Reassignment Client and Group lists misaligned

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1625]
See

![screen shot 2016-10-12 at 7 05 27 am](https://cloud.githubusercontent.com/assets/823454/19313148/590c2e2c-904a-11e6-8c8f-41a78a7aeb3d.png)

**Comment by shubhpatel108** [comment]
@edcable This seems to be solved: 
<img width="1280" alt="screen shot 2016-11-19 at 7 54 54 pm" src="https://cloud.githubusercontent.com/assets/4345133/20456068/3865fcaa-ae92-11e6-8531-1957ab36ff25.png">

Btw, the new UI is totally different than the one attached by you. Or am I looking at the wrong one?

**Comment by mbj36** [comment]
@shubhpatel108  Above UI by @edcable is still in process to be merged, Duplex is working on it.

**Comment by shubhpatel108** [comment]
@mbj36 which child repo/branch I can find the new code?

**Comment by mbj36** [comment]
https://demo.openmf.org/beta it's hosted here, Code can be found on reskin branch

**Comment by edcable** [comment]
Fixed on https://demo.openmf.org/newbeta/#/bulkloan
