### ISSUE TITLE
MIFOSX-2753:  Insert Correct Labels for “Add Client Identifier” page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1638]
Copied over from https://mifosforge.jira.com/browse/MIFOSX-2753

Within the Mifos X Web App (Community App), the labels for adding a client identifier are incorrect. To reproduce, navigate to any client, click Identities and then +Add. The labels for the first two input fields are incorrect. The first one reads “Status” and should be “Document Type”. The second reads “label.input.status” and should be “Document Status”

You can test this out at https://demo.openmf.org (mifos/password). This can be changed by updating the Mifos X Web App (Community App) with source code located at https://github.com/openMF/community-app. Please reference this Getting Started Guide to familiarize with the codebase.
![client identifier](https://cloud.githubusercontent.com/assets/823454/20239807/586385ce-a8be-11e6-80e9-bfd15022a9a7.png)

**Comment by mdew192837** [comment]
This is my first change with Mifos. I am very excited. Please let me know of any convention issues, and if it is good, I will make a pull request. @mbj36 @gauravsaini03

**Comment by gauravsaini03** [comment]
@mdew192837 This change looks good.

**Comment by mdew192837** [comment]
@gauravsaini03 What is the best way to contact you? It seems like you aren't on Gitter. I respect your time, but I just want to be able to get a more timely response and a faster way to contact you. :) By the way, should I submit the GCI task now?
