### ISSUE TITLE
Search bar on Groups page overlap with sidebar

### ISSUE THREAD

**Issue by shubhpatel108** [openMF/community-app#1651]
Go to Cilents > Groups, from the header. 
<img width="1246" alt="screen shot 2016-11-19 at 5 38 39 pm" src="https://cloud.githubusercontent.com/assets/4345133/20455315/1803c9e6-ae7f-11e6-8d40-39750e539f4f.png">

Similar bug for Centers page. (Go to Clients > Centers).

**Comment by mbj36** [comment]
@shubhpatel108 PR has been submitted for above earlier https://github.com/openMF/community-app/pull/1545 

Better to close it :)

**Comment by shubhpatel108** [comment]
Thanks @mbj36! Sorry, didn't notice that PR.  
There are a lot of them pending!
