### ISSUE TITLE
Not able to attach Client while creating the Group

### ISSUE THREAD

**Issue by mbj36** [openMF/community-app#1654]
1. Create a Client and activate it. 
2. Click on Groups -> Create Group - In Create Group page click on add Clients, Even after typing the characters of the existing clients not getting populated in the same page.

Moved over from  - https://mifosforge.jira.com/browse/MIFOSX-2546

**Comment by abhaychawla** [comment]
@santoshconflux It seems the issue is resolved. Please verify and close.

**Comment by santoshconflux** [comment]
@abhaychawla, thanks for pointing it out. This ticket is indeed resolved. As this ticket is not tagged with the PR, I don't know when it was resolved.  Closing it.
