### ISSUE TITLE
MIFOSX-2513: 'Required Field" should not get populated after clicking on cancel button

### ISSUE THREAD

**Issue by mbj36** [openMF/community-app#1655]
In the community app after clicking on cancel button "Required Field" get populated in the particular page.

Moved over from - https://mifosforge.jira.com/browse/MIFOSX-2513

Eg. In organisation>>manageoffices>>Create Office page if Cancel button is clicked then "Required Field" will get populated. 

Issues exist in pages are listed below (will be updated as it is found) :- 

- [ ]  Create Office page

- [ ]  Create Holiday page 

- [ ] Products>>Savingproducts>>create savingproducts

**Comment by edcable** [comment]
Closed, not able to reproduce.
