### ISSUE TITLE
MIFOSX-2741: In search field if the client is searched then External ID not getting displayed

### ISSUE THREAD

**Issue by mbj36** [openMF/community-app#1656]
Click on Clients -> Client -> enter the external ID attached for the above client in the search field (in the right which performs search in multiple pages) and click on search button.
> The client get displayed but the external ID is not getting displayed.

Moved over from https://mifosforge.jira.com/browse/MIFOSX-2741

Red Box is missing 
![image](https://cloud.githubusercontent.com/assets/9936881/20544835/ee6c4dfa-b131-11e6-8447-cb3258090c3d.png)

**Comment by TypicalGitHubUser** [comment]
Hi, @mbj36 
I fixed this issue. Could you review?.

**Comment by mbj36** [comment]
It's working fine.
