### ISSUE TITLE
Report of Loan Transactions should be formatted to be width of whole page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1658]
I've split out the issue at https://mifosforge.jira.com/browse/MIFOSX-1059 into a bug and an enhancement

For the ability to export transactions to PDF report, the report columns should adjust to width of the page. 

To reproduce:

1. Navigate to a loan of any client
2. Go to transactions tab and select Export
3. Generate and view report. 

<img width="1120" alt="screen shot 2016-11-22 at 4 10 40 pm" src="https://cloud.githubusercontent.com/assets/823454/20547036/4b39d520-b0ce-11e6-9b0e-137583d96342.png">

**Comment by MYKatz** [comment]
Looking through the API, I'm fairly certain that the whole process of generating the PDF occurs on the server-side.  Perhaps this issue should be moved to the fineract side?

**Comment by bharathcgowda** [comment]
closing this issue after discussing with Ed.
Not a report or community app issue
