### ISSUE TITLE
Fields in 'More' dropdown not showing properly on 'Groups and Client' page.

### ISSUE THREAD

**Issue by simmimourya** [openMF/community-app#1667]
Moved over from MifosForge: https://mifosforge.jira.com/browse/MIFOSX-2806

Step by step guide to reproduce the issue:

Navigate to Clients -> Groups.

![imageedit_2_6248877406](https://cloud.githubusercontent.com/assets/8150326/20639526/5388280a-b3ec-11e6-8ef3-481ee993593d.gif)

Click 'Create Group'.

![2](https://cloud.githubusercontent.com/assets/8150326/20639535/ab6d43e8-b3ec-11e6-952c-e89ee6ca5bb5.png)

Fill the details and submit.

![3](https://cloud.githubusercontent.com/assets/8150326/20639720/4b876b34-b3f1-11e6-8318-4814117d5e7c.png)

Click 'Add'.

![imageedit_1_8756427705](https://cloud.githubusercontent.com/assets/8150326/20639649/54111cac-b3ef-11e6-9d8a-6f5e59bc41c4.gif)

Fill details and submit. Make sure you check `Open savings account` Checkbox.

![imageedit_1_6739163119](https://cloud.githubusercontent.com/assets/8150326/20639715/11d57f70-b3f1-11e6-9ae4-c250f87c4efe.gif)

Click on 'More'. You can see that the drop-down isn't visible properly.

![imageedit_1_7944153703](https://cloud.githubusercontent.com/assets/8150326/20639630/c9838f0c-b3ee-11e6-8107-a118df6ea5fb.gif)

P.S: Although, you can see the dropdown options when you unmaximize the browser window. 

![screenshot from 2016-11-26 16 03 10](https://cloud.githubusercontent.com/assets/8150326/20639766/43397f16-b3f2-11e6-8ac5-04d4e8fbe8a3.png)

You can test this out at https://demo.openmf.org (mifos/password). This can be changed by updating the Mifos X Web App (Community App) with source code located at https://github.com/openMF/community-app. Please reference this Getting Started Guide to familiarize with the codebase.

**Comment by smitthakkar96** [comment]
There are two work arounds possible:
  - Remove Class dropdown-menu-right
  - Add a media query for larger screens

``` css
@media (min-width:1025px) { 
    .dropdown-menu-right{
      left:0;
    }
}

```

**Comment by Trodrige** [comment]
I am new to the community. I am interested in this issue. I can't get pass the third screenshot/step. I get this error when I try adding members to the group     
 **_

> field is required
> This action caused a group Validation Error: Number of Clients must be between `10` and ``

_**

Please how can I resolve this?
Thanks

**Comment by santoshconflux** [comment]
Not able to reproduce.
