### ISSUE TITLE
Can not link a Saving account to during Group Loan Application

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1678]
Reported  by Lajeo at https://mifosforge.jira.com/browse/MIFOSX-1372

While creating Loan application for a client using loan product, there is option 'Link to Savings'.

The same option is not present when creating loan application for a Group.

**Comment by edcable** [comment]
Adi will explore if this is supported at the back-end and if so the remaining work is just exposing it at UI level.

**Comment by edcable** [comment]
Move to Apache Fineract issue tracker.

**Comment by santoshmath** [comment]
This issue raised here and resolved: https://issues.apache.org/jira/browse/FINERACT-379

**Comment by v3ss0n** [comment]
The bug is still there , There is error after linking saving account.
