### ISSUE TITLE
Issues related to created entries in datatables with bit, DateTime fields

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1687]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-1731
Original Description:
1. Click on Admin-> System -> Manage data tables -> Create data table with Boolian, Date and Time for Client.
2. Click on the Clients -> any created client -> Click on the datatable created above -> Enter valid inputs for Boolian, Date & Time and submit it. 

3. Click on the Clients ->Click on the above datable created for that client -> Click on the entry made in that datable -> Click on any entry -> Click on Edit button,
> Only date is displaying but previoiusly entered time is not displaying.

**Comment by edcable** [comment]
Closed as Fixed.
