### ISSUE TITLE
On editing savings application(after undoing approval ) >> "weekly charge" date format is not shown hence unable to submit loan with weekly charge.

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1722]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-2556
>> Create savings account with weekly charge, 
>> Click on submit, to submit new savings application, 
>> click on modify application, 
>> In the modification savings page, for weekly charge - Date field is not available. 
Expected:- 
>> Date field should be displayed for weekly charge on the modification page.

**Comment by ShruthiRajaram** [comment]
@santoshconflux why do we require a date field in weekly charge? . When when I add a weekly charge without date I am able to submit the application.https://staging.openmf.org/#/viewsavingaccount/68
Kindly clarify.

**Comment by ShruthiRajaram** [comment]
@santoshconflux it looks like I took the wrong charge. my mistake. As discussed kindly retest again

**Comment by santoshconflux** [comment]
Not able to reproduce in recent version.
