### ISSUE TITLE
On editing existing weekly charge, it doesn't show the repeats every field hence cant edit repeats every.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1723]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-2557
Original Description:
>> Create savings account with weekly charge, 
>> Click on submit, to submit new savings application, 
>> click on Undo approval, 
>> In the modification savings page, for weekly charge - Repeats every field is not available. 
Expected:- 
>> Repeats every field should be displayed for weekly charge on the modification page.

**Comment by AkashBhave** [comment]
@santoshmath This bug should be fixed with my pull request: https://github.com/openMF/community-app/pull/2706
