### ISSUE TITLE
Reskin&oldSkin: If Invalid input is given for the datatable created then no proper error message is displaying

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1725]
Reported by Subramanya at  https://mifosforge.jira.com/browse/MIFOSX-2627

1. Create datatable for Group, with field name as Number.
2. Navigate to existing Group and click on the datatable created for the Group.
3. Make entry in the Number field as "Number" and click on save button.
> No proper error message is displayed, rather it displays as "Error".

![datatable entry](https://cloud.githubusercontent.com/assets/23022667/21391112/31ead4a4-c7b0-11e6-94d8-070670bf8798.png)

**Comment by DanCarl857** [comment]
Fixed this. Will send PR once issue with Travis CI is fixed. Here is the screenshot: 
![screen shot 2017-05-10 at 8 43 06 am](https://cloud.githubusercontent.com/assets/9010142/25888220/399080ee-355d-11e7-8add-d4669bef9b38.png)

**Comment by Mastermaulik** [comment]
@DanCarl857 Please send a PR now, @mbj36 can you please look into this?

**Comment by DanCarl857** [comment]
Already did but here is the link: https://github.com/openMF/community-app/pull/2236

**Comment by mbj36** [comment]
Tested and fixed
