### ISSUE TITLE
Completed Teller transactions aren't displayed in proper currency - only shows as $

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1732]
Reported by Subramanya  at https://mifosforge.jira.com/browse/MIFOSX-2732

Original Description:
1. Set currency as Indian Rupees, US Dollar, UAE Dirhams, in currency configuration. 
2. Create teller and add cashier to it.
3. Add office financial mapping for main cash at vault and for cash at teller/cashier.
4. Allocate cash in Indian Rupees, and Settle cash in UAE Dirhams,
5. Click on search Journal entries in which all entries got created with $ symbol.
It should be with particular currency symbol with which transaction has been done.

**Comment by Mastermaulik** [comment]
@botraunak Please look into this issue

**Comment by botraunak** [comment]
This is JSON posted to the API, correct currency codes are sent to the server and can be verified as the summary shows appropriate results. `{
    "txnDate":"31 May 2017", 
    "currencyCode":"AFN",
    "txnAmount":"100",
    "txnNote":"test",
    "locale":"en",
    "dateFormat":"dd MMMM yyyy"
}`

The journal entries are created I guess automatically for the API endpoint. See Doc Link attached. [https://demo.openmf.org/api-docs/apiLive.htm#allocateCashToCashier](https://demo.openmf.org/api-docs/apiLive.htm#allocateCashToCashier)

So it might be a Fineract Issue? @Mastermaulik can you confirm?

**Comment by santoshconflux** [comment]
@Mastermaulik or @nazeer1100126 , please confirm before I move this issue to Fineract.

**Comment by santoshconflux** [comment]
@ShruthiRajaram , we will see whether it's Fineract side issue.

**Comment by ShruthiRajaram** [comment]
@santoshconflux  I am looking into old journal entries and can see specific currency symbols displayed.
![image](https://user-images.githubusercontent.com/26407376/50470327-10bd3f00-09d6-11e9-92e0-918788c8bda7.png)
Kindly check and confirm

**Comment by santoshconflux** [comment]
Not able to reproduce in recent version.
