### ISSUE TITLE
In search field if the client is searched then External ID not getting displayed

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1734]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-2741

Original Description:
1. Create a client under pending approval state with the external ID attached.
2. Click on Clients -> Client -> enter the external ID attached for the above client in the search field (in the right which performs search in multiple pages) and click on search button.
> The client get displayed but the external ID is not getting displayed.

**Comment by TypicalGitHubUser** [comment]
@santoshmath  I belive this issue duplicates another one. #1656
