### ISSUE TITLE
Reskin&oldSkin: Attendence details page (Under Center/group) if valid inputs are not given proper error messages should be displayed

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1735]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-2793
Original Description:
1.Create center with meeting attached, Click on More -> Attendance -> Delete the meeting date and click on submit button -> No proper error message displayed.
2. Create center with meeting attached, Click on More -> Attendance -> Enter the date than meeting date and click on submit button -> No proper error message displayed.
3. If on the meeting date (with already attendance is added), again the attendance is added then no proper error message is displayed.

**Comment by Mastermaulik** [comment]
@Anh3h Please look into this issue

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This  issue is resolved.
