### ISSUE TITLE
Reskin&oldSkin:Not able to attache the Group While creating the center

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1737]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-2545

Original Description:
1. Create a Group and activate it. 
2. Click on Centers -> Create Center - In Create center page click on Select and add groups, Even after typing the characters of the existing groups not getting populated in the same page.

**Comment by mdew192837** [comment]
@mbj36 You stated on the jira bug that this was fixed. Can you confirm? If so, let's close this issue. :)

**Comment by mbj36** [comment]
This is the PR in reference to this issue but it needs some change i guess https://github.com/openMF/community-app/pull/1648 @mdew192837

**Comment by Mastermaulik** [comment]
@mbj36 Please look into this.

**Comment by santoshmath** [comment]
Duplicate of #1616 which is still open. Closing this issue.
