### ISSUE TITLE
Reskin&oldSkin:Information displaying in the Collection sheet is not proper

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1738]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-1140

Original Description:
1. Due to up gradation of Bootstrap3 the fields are scattered in collection sheet.
2. In the Group total the amount displayed is including the charges due on the particular meeting date, but in the charges field it is displaying as zero.
other details are marked in the screenshot attached.

![s2](https://cloud.githubusercontent.com/assets/23022667/21451342/7b632918-c924-11e6-80f0-5d2cc4552038.png)

**Comment by Mastermaulik** [comment]
@botraunak Please look into this issue

**Comment by botraunak** [comment]
@santoshmath Can you tell me the details to enter in the form to retrieve collection sheet. I'm getting empty results.

**Comment by santoshmath** [comment]
@botraunak , Collection sheet is for JLG loan. Disburse JLG loan for any three in the group. And then provide next repayment date in collection sheet with group name, office name, etc.

**Comment by botraunak** [comment]
Is this not the expected output? @santoshmath ?
Old Skin:
![screen shot 2017-05-30 at 4 16 07 pm](https://cloud.githubusercontent.com/assets/7816559/26579900/7e787b66-4553-11e7-8a69-949d53be2b40.png)
Reskin: 
![screen shot 2017-05-30 at 4 15 28 pm](https://cloud.githubusercontent.com/assets/7816559/26579905/814c955c-4553-11e7-9b0f-81a9fb03b42b.png)

**Comment by botraunak** [comment]
I'm getting this on retrying the steps is this not the expected output?
![screen shot 2017-05-30 at 4 16 07 pm](https://cloud.githubusercontent.com/assets/7816559/26579989/d116f4d8-4553-11e7-8eb1-b6464e616ad0.png)

**Comment by santoshmath** [comment]
@botraunak , little alignment issue still exist in old skin(after Group Total) and more alignment issue is there on reskin.

**Comment by botraunak** [comment]
@santoshmath Okay I'll work on the alignment issues 👍

**Comment by botraunak** [comment]
Current Reskin
![screen shot 2017-05-30 at 5 29 18 pm](https://cloud.githubusercontent.com/assets/7816559/26582138/91018872-455d-11e7-9678-6d4421cffadd.png)

Proposed Reskin 
![screen shot 2017-05-30 at 5 23 58 pm](https://cloud.githubusercontent.com/assets/7816559/26582147/9efbfbce-455d-11e7-90d2-6404ffaad4b3.png)

@santoshmath Let me know if this alignment looks fine to you I'll send a PR for the same then

**Comment by santoshmath** [comment]
@botraunak , Alignments looks good . Send the PR.

**Comment by mbj36** [comment]
@santoshmath retest and close it
