### ISSUE TITLE
Reskin&oldSkin: Bulk JLG Loan Application shows nothing(warning or error) after selecting loan product if there are no clients present in the group

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1742]
Reported by Nayan at https://mifosforge.jira.com/browse/MIFOSX-1627
Original Description:
Steps to reproduce
1> Create a group
2> Go to group profile and click on "Bulk JLG Loan Application"
3> Select the loan product
this action results into internal server error

**Comment by santoshmath** [comment]
This issue is resolved at back-end side. Fineract-333

**Comment by Mastermaulik** [comment]
@mbj36 Please provide some status on this issue

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
@mbj36 ,  now it's not showing any internal server error but  still it's not throwing any validation error like 'no clients in the  group'. I am not sure whether it's only back-end issue or both. For back-end issue has already been raised. @nazeer1100126 , please let us know .

**Comment by mbj36** [comment]
Fixed
