### ISSUE TITLE
Clients won't display

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1751]
Existing and newly created clients aren't displayed.

To reproduce
* click any existing client or create a new client - view for the client record is not displayed.

Test Instance
Tested on https://demo.openmf.org/reskin which is running Mifos X 16.11.01

**Comment by edcable** [comment]
<img width="1277" alt="screen shot 2016-12-27 at 7 09 48 am" src="https://cloud.githubusercontent.com/assets/823454/21502269/87c804b2-cc03-11e6-9be4-052d4408ae13.png">

**Comment by mbj36** [comment]
#1814 closed
