### ISSUE TITLE
No Groups or Centers displayed in list/tabular view

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1752]
Centers and Groups exist but none are displayed.

See screenshot

Tested on https://demo.openmf.org/reskin with 16.11.01
<img width="1184" alt="screen shot 2016-12-27 at 7 14 42 am" src="https://cloud.githubusercontent.com/assets/823454/21502370/2a7156fa-cc04-11e6-9986-8c14c3d2aac6.png">

**Comment by mbj36** [comment]
Solved
