### ISSUE TITLE
Improve alignment of button and summary data from Accounting Transaction View

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1753]
Complete any accounting transaction manually and view the transaction or complete a frequent posting and view transaction.

Reverse button is mis-aligned along with the four fields of data at the top.

See

<img width="1280" alt="screen shot 2016-12-27 at 7 28 18 am" src="https://cloud.githubusercontent.com/assets/823454/21502666/54ad7618-cc06-11e6-808b-389f1d2f7bc8.png">

and see the screenshot from the old skin:
<img width="922" alt="screen shot 2016-12-27 at 7 30 00 am" src="https://cloud.githubusercontent.com/assets/823454/21502673/60712602-cc06-11e6-8998-32df9c6ba592.png">

**Comment by mbj36** [comment]
Fixed
