### ISSUE TITLE
Remove extraneous space on Search Journal Entries view

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1754]
Go to https://demo.openmf.org/reskin/#/searchtransaction 

to see the extra space at the top of the page that is not needed. 
<img width="1233" alt="screen shot 2016-12-27 at 8 40 49 am" src="https://cloud.githubusercontent.com/assets/823454/21503992/30cd1f0a-cc10-11e6-9ca9-bcd777f9d4ee.png">

**Comment by mbj36** [comment]
Fixed
