### ISSUE TITLE
Align Edit/Delete buttons on same level as Title for View Financial Activity Mappings

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1755]
See https://demo.openmf.org/reskin/#/viewfinancialactivitymapping/13

<img width="1239" alt="screen shot 2016-12-27 at 8 42 51 am" src="https://cloud.githubusercontent.com/assets/823454/21504033/83941856-cc10-11e6-9fc8-32840ff18193.png">

versus

<img width="1206" alt="screen shot 2016-12-27 at 8 43 02 am" src="https://cloud.githubusercontent.com/assets/823454/21504038/89b0b938-cc10-11e6-8aa2-cba5545f6ef8.png">

**Comment by mbj36** [comment]
Fixed
