### ISSUE TITLE
Title and Header Accounts for Account Types not showing in Tree View of Chart of Accounts

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1757]
See https://demo.openmf.org/reskin/#/accounting_coa

<img width="1176" alt="screen shot 2016-12-27 at 8 52 54 am" src="https://cloud.githubusercontent.com/assets/823454/21504237/ee58dda6-cc11-11e6-985e-7bfbfc5b647e.png">

<img width="1176" alt="screen shot 2016-12-27 at 8 53 14 am" src="https://cloud.githubusercontent.com/assets/823454/21504239/f18f7f66-cc11-11e6-917c-6d8322100b40.png">

vs.

https://demo.openmf.org/reskin/#/accounting_coa

**Comment by mbj36** [comment]
Fixed
