### ISSUE TITLE
Align Create Closure button at level of title for Accounting Closures page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1758]
See https://demo.openmf.org/reskin/#/accounts_closure

<img width="1228" alt="screen shot 2016-12-27 at 8 55 12 am" src="https://cloud.githubusercontent.com/assets/823454/21504274/42ab5b36-cc12-11e6-8fea-d2d636dbf630.png">

vs.

<img width="988" alt="screen shot 2016-12-27 at 8 55 31 am" src="https://cloud.githubusercontent.com/assets/823454/21504277/478b256e-cc12-11e6-813c-8c6a180fb7fa.png">

**Comment by mbj36** [comment]
fixed
