### ISSUE TITLE
No offices displayed in List View for Offices

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1760]
See https://demo.openmf.org/reskin/#/offices

<img width="1230" alt="screen shot 2016-12-27 at 9 11 01 am" src="https://cloud.githubusercontent.com/assets/823454/21504518/7e0081fa-cc14-11e6-9288-6bf84b34d5ff.png">

vs. 

<img width="1199" alt="screen shot 2016-12-27 at 9 12 50 am" src="https://cloud.githubusercontent.com/assets/823454/21504537/abcfc58c-cc14-11e6-9f3f-af9a03f5b19e.png">

**Comment by mbj36** [comment]
Solved
