### ISSUE TITLE
List of holidays don't display

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1761]
Go to holidays in https://demo.openmf.org/reskin/#/holidays

Select an office and list of holidays should appear. 

See

<img width="1224" alt="screen shot 2016-12-27 at 9 20 31 am" src="https://cloud.githubusercontent.com/assets/823454/21504658/bf3ae84e-cc15-11e6-9ac3-d73f9745c047.png">

vs

<img width="962" alt="screen shot 2016-12-27 at 9 21 16 am" src="https://cloud.githubusercontent.com/assets/823454/21504669/db558cfa-cc15-11e6-80d8-e285e0443839.png">

**Comment by mbj36** [comment]
Solved
