### ISSUE TITLE
Employees not displayed on Manage Employees list

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1762]
See https://demo.openmf.org/reskin/#/employees

<img width="1237" alt="screen shot 2016-12-27 at 9 24 06 am" src="https://cloud.githubusercontent.com/assets/823454/21504736/42be8810-cc16-11e6-9394-7453f21205db.png">

vs.

<img width="1027" alt="screen shot 2016-12-27 at 9 24 13 am" src="https://cloud.githubusercontent.com/assets/823454/21504740/4a291c82-cc16-11e6-9098-2e9a17c1e32a.png">

**Comment by mbj36** [comment]
Solved
