### ISSUE TITLE
Full button for error log not displayed on standing instructions page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1763]
See

https://demo.openmf.org/reskin/#/standinginstructions/history

<img width="1224" alt="screen shot 2016-12-27 at 10 01 30 am" src="https://cloud.githubusercontent.com/assets/823454/21505374/898a6462-cc1b-11e6-9430-d4ee329312cd.png">

vs
<img width="902" alt="screen shot 2016-12-27 at 10 02 14 am" src="https://cloud.githubusercontent.com/assets/823454/21505376/925c839a-cc1b-11e6-8943-9563eab1393a.png">

**Comment by mbj36** [comment]
@edcable I can't replicate this issue

**Comment by mbj36** [comment]
Fixede
