### ISSUE TITLE
General ledger accounts not displaying in Liability and Expense Dropdowns on Create Provisioning Criteria page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1764]
Navigate to https://demo.openmf.org/reskin/#/createprovisioningcriteria

Create provisioning criteria and attempt to select a liability or expense account. A drop down of accounts should appear but only a message string does.

<img width="1229" alt="screen shot 2016-12-27 at 10 04 14 am" src="https://cloud.githubusercontent.com/assets/823454/21505433/31398738-cc1c-11e6-9022-89ba75e761d0.png">

**Comment by mbj36** [comment]
Fixed
