### ISSUE TITLE
List of selectable clients extends beyond border of section on Bulk Loan Reassignment page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1765]
See https://demo.openmf.org/reskin/#/bulkloan

<img width="1228" alt="screen shot 2016-12-27 at 10 15 43 am" src="https://cloud.githubusercontent.com/assets/823454/21505578/739053b8-cc1d-11e6-8749-34018efdec0c.png">

**Comment by mbj36** [comment]
Fixed
