### ISSUE TITLE
Delete button is missing on manage payments page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1767]
See https://demo.openmf.org/reskin/#/viewpaymenttype/

<img width="1237" alt="screen shot 2016-12-27 at 11 03 26 am" src="https://cloud.githubusercontent.com/assets/823454/21506333/32061a84-cc24-11e6-9ae2-6100452c7a4c.png">

vs.

<img width="988" alt="screen shot 2016-12-27 at 11 04 13 am" src="https://cloud.githubusercontent.com/assets/823454/21506340/3f313cfc-cc24-11e6-9858-77b2b324891f.png">

**Comment by Trodrige** [comment]
Hi edcable,

Please I need help on this issue. I would like to handle this, but the interface i see following this (https://demo.openmf.org/reskin/#/viewpaymenttype/) is different from what i have locally.

Thanks.

**Comment by skprabhanjan** [comment]
Hey @edcable, @nazeer1100126 and @mbj36 
I have figured it this out and fixed the bug, Waiting for my previous PR to get merged in order to commit this change , Can you please help me and see if this fix seems rite.? I have attached the screenshot of the fix here.

![screen shot 2017-02-08 at 8 54 14 pm](https://cloud.githubusercontent.com/assets/17094832/22743654/cd5bfb8c-ee40-11e6-9d74-f868e127f6c2.png)

**Comment by mbj36** [comment]
Send PR please

**Comment by skprabhanjan** [comment]
@mbj36 , I will be sending a PR for this today Evening.
Thanks for the help:)

**Comment by skprabhanjan** [comment]
@mbj36 , I have fixed this issue on my local machine, Waiting for PR #1897 to be merged  so that I can make one more PR with a fix to this issue, Should I follow creating a new branch for every issue on my fork and then create a PR from that so that I could make multiple PR's.?
Thanks:)

**Comment by mbj36** [comment]
Create new branch for every PR, don't wait for the PR to get merged

**Comment by skprabhanjan** [comment]
@mbj36 As I have already created a PR in this branch new_reskin , Shall I wait for this to be merged and for all next PR's I will create a new branch or shall I close that PR and follow this from first again.?
Sorry for the trouble,Thanks:)

**Comment by mbj36** [comment]
Fixed
