### ISSUE TITLE
Label not properly displayed on Edit Payment Type breadcrumb

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1768]
See https://demo.openmf.org/reskin/#/editPaymentType/4

<img width="1234" alt="screen shot 2016-12-27 at 11 04 44 am" src="https://cloud.githubusercontent.com/assets/823454/21506358/6453e02a-cc24-11e6-8ad1-f3195ea8b3a9.png">

vs. 

<img width="1177" alt="screen shot 2016-12-27 at 11 06 01 am" src="https://cloud.githubusercontent.com/assets/823454/21506365/7bc12042-cc24-11e6-9ee3-16f09aadf487.png">

**Comment by mbj36** [comment]
Fixed
