### ISSUE TITLE
SMS Campaigns Listing Table Extends beyond page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1769]
I know that no work has been done with the reskin on the new SMS campaigns feature but noting that the table of existing SMS Campaigns extends beyond the page.

https://demo.openmf.org/reskin/#/smscampaigns

<img width="1274" alt="screen shot 2016-12-27 at 11 12 22 am" src="https://cloud.githubusercontent.com/assets/823454/21506486/61b77998-cc25-11e6-8e74-95ea021c1b4b.png">

**Comment by gkrishnan724** [comment]
@edcable  This issue also exists with Admin>>Organisation .

**Comment by mbj36** [comment]
It's working perfect in https://demo.openmf.org/newbeta/#/smscampaigns
So closing the issue
