### ISSUE TITLE
Reskinned view/workflow for Create SMS Campaign needs to be added. 

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1770]
I know that no work has been done for the reskin on the new SMS campaigns feature so logging this issue here:

https://demo.openmf.org/reskin/#/createsmscampaign

<img width="1267" alt="screen shot 2016-12-27 at 11 13 54 am" src="https://cloud.githubusercontent.com/assets/823454/21506523/93018e12-cc25-11e6-958d-479bf2b24d53.png">

**Comment by edcable** [comment]
oh - you fixed the error message?

**Comment by mbj36** [comment]
It was already fixed in newbeta and github repo.

**Comment by mbj36** [comment]
Fixed
