### ISSUE TITLE
List of Data Tables not displayed

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1771]
See https://demo.openmf.org/reskin/#/datatables

<img width="1239" alt="screen shot 2016-12-27 at 11 24 12 am" src="https://cloud.githubusercontent.com/assets/823454/21506689/0bdac118-cc27-11e6-95a7-f5c7a5c0586a.png">

vs.

<img width="1213" alt="screen shot 2016-12-27 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/823454/21506695/1638d73a-cc27-11e6-99b2-ebd2f862acbd.png">

**Comment by mbj36** [comment]
Solved
