### ISSUE TITLE
Add visual queue to denote entity to entity mapping rows are links

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1775]
See https://demo.openmf.org/reskin/#/entitytoentitymapping. Each row can be clicked to be edited. In the old skin, upon hover, the row changes to blue. Some of visual queue should be made so user knows that these are distinct links.

<img width="1229" alt="screen shot 2016-12-27 at 2 57 47 pm" src="https://cloud.githubusercontent.com/assets/823454/21510154/04fbd68e-cc45-11e6-869a-bde81d25b6b3.png">

vs.

<img width="1030" alt="screen shot 2016-12-27 at 2 58 58 pm" src="https://cloud.githubusercontent.com/assets/823454/21510157/099fa4c2-cc45-11e6-9f5f-001396dbda5a.png">

**Comment by mbj36** [comment]
Fixed
