### ISSUE TITLE
Audit trail results table should fill entire width of section. 

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1776]
See https://demo.openmf.org/reskin/#/audit

Table should fill 100% of width of this section.

<img width="1219" alt="screen shot 2016-12-27 at 3 04 03 pm" src="https://cloud.githubusercontent.com/assets/823454/21510217/bb5b3776-cc45-11e6-92bb-f9a05be7bf36.png">

vs

<img width="867" alt="screen shot 2016-12-27 at 3 02 48 pm" src="https://cloud.githubusercontent.com/assets/823454/21510218/c21179c2-cc45-11e6-9c5f-84d179f47763.png">

**Comment by mbj36** [comment]
@gkrishnan724 Have u solved the issue ? We are looking to close all the reskin issues by today. Waiting for your PR :)

**Comment by mbj36** [comment]
Fixed
