### ISSUE TITLE
List of reports under Manage Reports not displayed

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1777]
Reports are not displayed.

See 
<img width="1219" alt="screen shot 2016-12-27 at 3 04 03 pm" src="https://cloud.githubusercontent.com/assets/823454/21510251/13014524-cc46-11e6-889c-ee43d77c86a6.png">
https://demo.openmf.org/reskin/#/reports

vs

<img width="1234" alt="screen shot 2016-12-27 at 3 05 41 pm" src="https://cloud.githubusercontent.com/assets/823454/21510270/42a38a9e-cc46-11e6-8f84-539a058a48e3.png">

**Comment by mbj36** [comment]
Solved
