### ISSUE TITLE
Properly align the input fields along with correct spacing for Create Reports view

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1778]
See https://demo.openmf.org/reskin/#/createreport

<img width="1232" alt="screen shot 2016-12-27 at 3 11 42 pm" src="https://cloud.githubusercontent.com/assets/823454/21510321/cf758b84-cc46-11e6-8ce6-059b8a1d284a.png">

vs.

<img width="882" alt="screen shot 2016-12-27 at 3 11 47 pm" src="https://cloud.githubusercontent.com/assets/823454/21510322/d56c59b4-cc46-11e6-8883-70da9781aacb.png">

**Comment by mbj36** [comment]
@Anh3h  I see you have created a commit. Have you fixed the issue ?  Please send the PR

**Comment by Anh3h** [comment]
Could you check this https://github.com/openMF/community-app/pull/1932 out. I need a clean fork to avoid conflicts before i can send a PR. If i do a new fork. I think the travis build for that PR wil hav a prob.

**Comment by mbj36** [comment]
Fixed
