### ISSUE TITLE
Error log icon not fully displayed on Manage Scheduler Jobs page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1779]
See https://demo.openmf.org/reskin/#/jobs

<img width="1219" alt="screen shot 2016-12-27 at 3 14 16 pm" src="https://cloud.githubusercontent.com/assets/823454/21510348/28ddf8a0-cc47-11e6-8ddb-d868227cdd83.png">

**Comment by mbj36** [comment]
Solved
