### ISSUE TITLE
Icon for enabled/disabled is not displayed for Global Configurations page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1780]
See https://demo.openmf.org/reskin/#/global

<img width="991" alt="screen shot 2016-12-27 at 3 15 56 pm" src="https://cloud.githubusercontent.com/assets/823454/21510375/696a2754-cc47-11e6-8d97-5b6eec1b2c22.png">

vs

<img width="934" alt="screen shot 2016-12-27 at 3 16 03 pm" src="https://cloud.githubusercontent.com/assets/823454/21510379/6cb66986-cc47-11e6-8937-2062df31460e.png">

**Comment by skprabhanjan** [comment]
Hey @edcable , @nazeer1100126 and @mbj36 , I Have Fixed this bug and here is a screenshot of the same, Waiting for my PR of old bug fixes to be merged, So meanwhile can you please look into this fix and let me know about this and help me on this.?

![screen shot 2017-02-08 at 9 35 02 pm](https://cloud.githubusercontent.com/assets/17094832/22745415/7af5ab44-ee46-11e6-8292-15675981671b.png)

**Comment by mbj36** [comment]
@skprabhanjan Are you up to this issue ?

**Comment by mbj36** [comment]
Fixed

**Comment by skprabhanjan** [comment]
@mbj36 , Should i Send a PR for this issue.? As it says closed by mbj36? What should i do on this issue now.? As I had fixed it but I had not made any PR due to Travis CI check error, Please help me on what to do next here.
Thanks.

**Comment by mbj36** [comment]
@skprabhanjan  Revert your commit and rebase your branch with new_reskin branch and look into other issues as it is fixed now
