### ISSUE TITLE
SMS Service Configuration needs to be formatted like other external services

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1782]
See https://demo.openmf.org/reskin/#/externalservices

<img width="1228" alt="screen shot 2016-12-27 at 3 20 24 pm" src="https://cloud.githubusercontent.com/assets/823454/21510428/11f418d0-cc48-11e6-841d-d8a237528a4d.png">

**Comment by Mastermaulik** [comment]
I solved this issue, here is how the new skin looks like:
<img width="1280" alt="screen shot 2017-02-18 at 2 39 29 pm" src="https://cloud.githubusercontent.com/assets/5520612/23092003/3078d3bc-f5e8-11e6-95d6-ac216d6f7c04.png">

**Comment by mbj36** [comment]
Fixed
