### ISSUE TITLE
Create loan product view extends off screen 

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1784]
See https://demo.openmf.org/reskin/#/createloanproduct

<img width="1249" alt="screen shot 2016-12-27 at 3 24 51 pm" src="https://cloud.githubusercontent.com/assets/823454/21510475/ac5c76d8-cc48-11e6-93f2-4a8c62442e96.png">

**Comment by skprabhanjan** [comment]
I worked on this bug and have made attempts to fix it and I suppose it's fixed. Please check the below screenshot and let me on the feasibility of this fix.

![screen shot 2017-02-03 at 9 41 38 pm](https://cloud.githubusercontent.com/assets/17094832/22598470/9bf96c36-ea59-11e6-88a3-45c57f67e84e.png)
