### ISSUE TITLE
Reskin:Improper alignment of help option in side nav

### ISSUE THREAD

**Issue by anu-007** [openMF/community-app#1786]
help option in side nav is not properly aligned like other options.hope it is clear from the image.
![screenshot from 2016-12-29 14-35-03](https://cloud.githubusercontent.com/assets/20153241/21540443/016714d4-cdd5-11e6-9bd3-e1688a87a45b.png)
it can be seen here( https://demo.openmf.org/reskin/#/home)

**Comment by santoshmath** [comment]
@anu-007 , Do you expect  it should  be  aligned just like other options?

**Comment by anu-007** [comment]
@santoshmath yes it would be great if it is aligned   like other options.

**Comment by Mastermaulik** [comment]
@gkrishnan724 Please look into this issue

**Comment by mbj36** [comment]
Tested and Fixed
