### ISSUE TITLE
improper alignment of loader on loading the community-app

### ISSUE THREAD

**Issue by anu-007** [openMF/community-app#1790]
on loading the app first the loader appears at extream left of the screen and the suddenly align itself to center.The loader is expected to appear only in the center.The translation is quick but noticeable.

it can be seen here( https://demo.openmf.org/#/).

**Comment by mbj36** [comment]
@anu-007 Can u work on it ?

**Comment by anu-007** [comment]
sure, I will send a pr shortly.
