### ISSUE TITLE
Not understandable error when rescheduling reason is empty

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1797]
During rescheduling of the loan, when you leave "Reason for Rescheduling" empty, the system throws an error which is not clear to a user

![reschedulingreason](https://cloud.githubusercontent.com/assets/8160209/21601378/fd618eae-d19a-11e6-9b2f-92422e24d6c3.png)

You can produce this in https://demo.openmf.org by creating a loan, approve and disburse, then go to more and select Reschedule, in rescheduling form don't fill the drop down for Reason for Rescheduling.

**Comment by mbj36** [comment]
Fixed
