### ISSUE TITLE
Reskin&oldSkin:Not understandable error when the grace period in loan reschedule is empty

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1798]
During loan reschedule, when Reschedule for Installment, Reason for Rescheduling and Submitted date is filled but the remaining fields are not filled. When submitted through an error which seems to mean the grace period for principal can not be blank but the error is not clear to a normal user.

![reschedulegrace](https://cloud.githubusercontent.com/assets/8160209/21603314/516701de-d1ad-11e6-8069-3de97ccba78c.png)

Can be reproduced at https//demo.openmf.org by filling the form of reschedule loan but don't check on "Change Repayment Date", "Introduce Mid-term Grace Period", "Extend Repayment Period" and "Adjust Interest rate for the remainder of loan" then submit.

**Comment by santoshmath** [comment]
@MexinaD , the error message should be  
"Select any one of the below options before submitting:
"Change Repayment Date", 
"Introduce Mid-term Grace Period",
 "Extend Repayment Period" 
 "Adjust Interest rate for the remainder of loan"

**Comment by MexinaD** [comment]
@santoshmath Yeah, that error is understandable

**Comment by austinmarcum** [comment]
I can tackle this.

**Comment by Mastermaulik** [comment]
@botraunak , please look into this issue.

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
This issue is not yet resolved. Check the screenshot.:
![reschedule](https://cloud.githubusercontent.com/assets/23022667/26781874/5fdb4296-4a0e-11e7-9121-0cac2833c2a8.png)

**Comment by mbj36** [comment]
Fixed
