### ISSUE TITLE
Typos and grammatical errors found in web app

### ISSUE THREAD

**Issue by mdew192837** [openMF/community-app#1802]
This is a list of typos and grammatical errors and improvements I propose for the web app:
File location: community-app/tree/reskin/app/global-translations/locale-en.json

Unify spacing between message key and message definition. Either put a space after the colon or don't.

Simplification
- [ ] "label.heading.next":"Pagination: Next" - Just "Next"?
- [ ] "label.heading.prev":"Pagination: Previous" - Just "Previous"?

Capitalize
- [ ] "label.input.between": "between" - Capitalized?
- [ ] "label.heading.externalid": "External Id" - Should "Id -> "ID"?
- [ ] "label.heading.externalid": "External Id" - Should "Id" -> "ID"?
- [ ] "label.heading.is_creditcheck_mandatory":"is creditcheck mandatory?" - the "is" should be capitialized.
- [ ] "label.heading.skip_credit_check_in_failure":"skip credit check in failure?" - the "skip" should be capitalized
- [ ] "label.input.between": "between" - Should "between" be capitalized?
- [ ] "label.heading.dividends": "dividends" -> "Dividends"
- [ ] "label.input.externalid": "External id" -> "External ID"
- [ ] "label.button.addcb": "Add credit Bureau" -> "Credit"
- [ ] "label.button.mapcblp": "Map credit Bureau to Loan Product" -> "Credit"
- [ ] "label.button.newcharge": "Add charge" -> "Charge"
- [ ] "label.button.clientscreenreports":"Client screen reports" -> "Client Screen Reports"
- [ ] "label.uniquelyidentifiedwithid": "Uniquely identified with Id" -> "ID"
- [ ] "label.and": "and" -> "And"
- [ ] "label.anchor.clientscreenreport": "Client screen reports" -> "Client Screen Reports"
- [ ] "label.input.clientId":"Client Id" -> "Client ID"
- [ ] "error.msg.client.not.active.exception": "The Client with id `{{params[0].value}}` is not active." -> "ID"
- [ ] "validation.msg.clientIdentifier.documentKey.cannot.be.blank": "Identification # is mandatory." -> "Number"
- [ ] "error.msg.image.type.upload": "Only files of type GIF,PNG or JPG are allowed." - fix the grammatical issues with commas. Or use something like "Supported file types: GIF, PNG, and JPG"
- [ ] "error.msg.client.close.loan.non-closed": "Client cannot be closed because of non-closed loans." - add the at the beginning
- [ ] "error.msg.client.close.non-closed.savings.account": "Client cannot be closed because of non-closed savings." - add the at the beginning
- [ ] "error.msg.client.close.is.under.transfer": "Client under Transfer cannot be closed" -> "A client undergoing a transfer can not be closed."
- [ ] "error.msg.group.not.active.exception": "The Group with id `{{params[0].value}}` is not active." -> "ID"
- [ ] "error.msg.group.duplicate.externalId": "Group with external id `{{params[0].value}}` already exists." -> "ID"
- [ ] "error.msg.center.duplicate.externalId": "Center with external id `{{params[0].value}}` already exists." -> "ID"

Less capitalization
- [ ] "label.heading.due.savings.collections":"Due Savings Collections" -> Due savings collections
- [ ]  "label.input.isbaselendingrate" : "Is Base Lending Rate?" -> Is this a base lending rate?
- [ ] "label.button.submitandprint": "Submit And Print" -> "Submit and Print"
- [ ] "label.select":"Select an Option" -> "Select an option"
- [ ] "resourceId.not.integer": "ID should be an Integer." -> "integer"
- [ ] "label.button.ok" : "OK" -> "Ok"
- [ ] "validation.msg.client.staffId.cannot.be.blank": "Please Select staff." -> "select"
- [ ] "label.input.searchformember": "Search for a Member" -> "Search for a member"
- [ ] "label.input.invaliddaterange":"Please Select Valid Date Range" -> "Please select a valid date range."
- [ ] "label.input.searchforgroup":"Search for a Group" -> "Search for a group"
- [ ] "label.heading.debittags": "Debit Tags" -> "tags"

Should we add colons after certain messages? (This needs further discussion, many messages could use this)
- [ ] "label.heading.enterclientsactivationdate":"Enter Clients Activation Date" - Perhaps there should be a colon at the end? (This is a pretty widespread issue and we can look deeper into this
- [ ] "label.heading.provisioningpercentage":"Percentage"
- [ ] "label.heading.fromdate":"From Date"
- [ ] "label.heading.updatedby": "Update By"
- [ ] "label.heading.fromdate":"From Date"
- [ ] "label.input.enternote": "Enter note"
- [ ] "label.input.enteractivationdate": "Enter activation date"
- [ ] "label.input.dueforcollectedon":"Due for collection on"
- [ ] "label.nextmeetingon": "Next meeting on"
- [ ] "label.heading.transferringto": "Transferring To"

Needs clarification
- [ ]  "label.heading.arrears":"Arrears" - What does this mean?
- [ ] "validation.msg.floatingrate.isDifferentialToBaseLendingRate.cannot.be.true.for.baselendingrate":"isDifferentialToBaseLendingRate cannot be true for floating rate marked as Base Lending Rate" - This message needs to be rewritten.

Better message
- [ ] "label.heading.shareaccount": "Share Account#" -> "Share Account Number"
- [ ] "label.heading.totalamountreceivedorreturned": "Total Amount Receivable/Returned" - "Receivable" -> "Received"
- [ ] "label.input.accno": "Account#" -> "Account Number"
- [ ] "label.heading.stale_period":"stale_period" - should be something like "Stale Period"
- [ ] "label.heading.is_active":"is_active" - should be something like "Is Active" perhaps even with a question mark
- [ ] "label.heading.accnum": "Account #" - should replace "#" with "Number"
- [ ] "label.heading.reject": "Reject" is misindented
- [ ] "label.heading.savingaccount": "Saving Account" - "Saving" -> "Savings"?
- [ ] "label.input.filterbynameorstatusoroffice": "Filter by name/status/office" -> "name, status, or office"
- [ ] "label.input.resetconfirmationtext" : "Do you want to remove all your changes done upto now and reset to original Schedule?" -> "Do you want to remove all your change done up to now and reset to the original schedule?"
- [ ] "label.input.incorpValidityTillDate":"Incorporation Validity Till Date" -> "Incorporation Valid Until"
- [ ] "label.button.advancesearch": "Advance Search" -> "Advanced Search
- [ ] "label.button.submitandnextcenter": "Submit and Next center" -> "Submit and Proceed to Next Center
- [ ] "label.outstanding.amount":"Loan outstanding amount" -> "Outstanding Loan Amount"
- [ ] "label.message.password.expired":"Your password is expired, please reset your password"-> "has expired, and period at the end."
- [ ] "error.login.failed": "Please try again, your credentials are not valid." -> "Invalid credentials. Please try again."
- [ ]  "error.msg.command.unsupported": "Programmer error: The `command` issued is not supported." -> "Code error:
- [ ] "error.msg.not.authorized": "Insufficient privileges to perform this action." -> "You are not authorized to perform this action."
- [ ] "error.msg.role.associated.with.users" : "Role associated with users can not be modify." -> "This role associated with users can not be modified."
- [ ] "error.msg.role.associated.with.users.deleted" : "Role associated with users can not be deleted." -> "This role associated with users can not be deleted."
- [ ] "error.msg.role.associated.with.users.disabled" : "Role associated with users can not be disabled." -> "This role associated with users can not be disabled."
- [ ] All these need to be have 'the' and then 'field after. Ex. "The Title field is mandatory." This holds true for pretty much every validation message. Please let me know what you think on this.
    * "validation.msg.calendar.title.cannot.be.blank": "Title is mandatory.",
    * "validation.msg.calendar.startDate.cannot.be.blank": "Start Date is mandatory.",
    * "validation.msg.calendar.typeId.cannot.be.blank": "Calendar Type is mandatory.",
    * "validation.msg.calendar.recurrence.cannot.be.blank": "Recurrence is mandatory.",
    * "validation.msg.calendar.description.cannot.be.blank": "Description cannot be blank.",
    * "validation.msg.calendar.location.cannot.be.blank": "Location cannot be blank.",
    * "validation.msg.calendar.endDate.cannot.be.blank": "End date cannot be blank.",
    * "validation.msg.calendar.repeating.cannot.be.blank": "Repeating cannot be blank.",
    * "validation.msg.calendar.duration.cannot.be.blank": "Duration cannot be blank.",
    * "validation.msg.calendar.remindById.cannot.be.blank": "Reminder type cannot be blank.",
    * "validation.msg.calendar.firstReminder.cannot.be.blank": "First reminder cannot be blank.",
    * "validation.msg.calendar.secondReminder.cannot.be.blank": "Second reminder cannot be blank.",
- [ ] "validation.msg.collectionsheet.dueDate.cannot.be.blank": "Date of transaction is mandatory to generate collection sheet." -> "The Date of transaction is required..."
- [ ] "error.msg.calendar.new.start.date.before.existing.date": "New meeting start on or after date cannot be a date before existing meeting start date." -> "The new meeting start date can not be a date before an existing meeting date."
- [ ] "error.msg.entity.transfers.with.active.savings.accounts": "Cannot transfer Clients/Groups having active Savings accounts" -> "which have active savings accounts."
- [ ] "error.msg.groups.bulk.client.transfers.to.different.office": "Bulk Transfers of clients between Groups in different branches not allowed " -> "are not allowed"
- [ ] "error.msg.client.transfers.destination.group.absent": "Destination Group for transfer of clients originally linked to a group not selected " -> needs an is before "not selected"
- [ ] "error.msg.client.transfers.with.active.accounts.between.groups.with.different.meeting.frequency": "Cannot transfer Clients with active accounts between groups with different meeting frequency" -> frequency should be plural
- [ ] "error.msg.client.transfers.with.active.accounts.to.group.with.no.meeting.frequencys": "Cannot transfer Client with active accounts to a groups with no meeting frequency" -> "You can not transfer a client with active accounts to a group with no meeting frequency."
- [ ] "error.msg.loan.repayment.or.waiver.cannot.be.made.before.client.transfer.date": " Cannot make (or edit) repayments and waivers prior to than client's transfer date of ({{params[0].value}})  " -> Change "than" to "to"
- [ ] The following messages need the article "the" before "loan account"
    * "error.msg.loan.submittal.cannot.be.before.client.transfer.date": " The date on which a loan is submitted cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    * "error.msg.loan.approval.cannot.be.before.client.transfer.date": " The date on which a loan is approved cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    * "error.msg.loan.approval.cannot.be.undone.before.client.transfer.date": " The date on which a loan is approved cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    * "error.msg.loan.disbursal.cannot.be.before.client.transfer.date": " The date on which a loan is disbursed cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    "error.msg.loan.repayment.or.waiver.cannot.be.made.before.client.transfer.date": " Cannot make (or edit) repayments and waivers prior to than client's transfer date of ({{params[0].value}})  ", - change "than" to "the"
    * "error.msg.loan.reject.cannot.be.before.client.transfer.date": " The date on which a loan is rejected cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    * "error.msg.loan.withdraw.cannot.be.before.client.transfer.date": " The date on which a loan is withdrawn cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    * "error.msg.loan.writeoff.cannot.be.undone.before.client.transfer.date": " The date on which a write off is made cannot be earlier than client's transfer date of ({{params[0].value}}) ",
    * "error.msg.loan.close.cannot.be.undone.before.client.transfer.date": " The date on which the loan is repaid in full cannot be earlier than client's transfer date of ({{params[0].value}}) ",
- [ ] "validation.msg.floatingrate.isDifferentialToBaseLendingRate.no.baselending.rate.defined":"Base Lending rate doesn't exists" -> "The base lending rate does not exist."
- [ ] "label.anchor.advsearch":"Advance search" -> "Advanced search"
- [ ] "label.youneedtologintoaccessthisarea": "You need to login to access this area" - Add a period?
- [ ] "label.search.query.matched.results.exceeds.max.length":"Searched query resulted more than 200 records, showing first 200 records." -> "This query shows only the first 200 records."
- [ ] "validation.msg.collectionsheet.calendarId.cannot.be.blank":"Collection sheet cannot be generated for center/group without attach meeting define" - Add "a" before "center", "attach" -> "attached", "define" -> "defined"
- [ ] "label.heading.uniqueidentification": "Unique ID #" - "#" -> "Number"
- [ ] "label.heading.identitydocs": "Identity Documents" -> "Identification Documents"
- [ ] "label.heading.numofloancycle":"# of Loan Cycle" -> "Number of Loan Cycle(s)"
- [ ] "label.heading.clientno":"Client #" -> "Client Number"
- [ ] "label.anchor.addclientidentities": "Add Client Identities" -> "Add Client Identifiers"
- [ ] "label.input.filterbynameaccno": "Filter display by name/client#/staff/office" -> "client number"
- [ ] "label.input.searchByNameAccNo" : "Find by name/mobile#/client#/externalId/identifier#" - replace "#" with "number" and "Id" and "ID"
- [ ] "label.input.uniqueidentification": "Unique ID #" -> "Unique ID Number"
- [ ] "label.input.reactivationdate":"Re Activation date" -> "Re-activation Date"
- [ ] "label.input.reopeneddate":"Re Opened Date" -> "Re-opened Date"
- [ ] "label.numofloancycles": "# of loan cycles" -> "Number of loan cycle(s)"
- [ ] "label.numofactiveloans": "# of active loans" -> "Number of active loan(s)"
- [ ] "label.numofactivesavings": "# of active savings" -> "Number of active saving(s)"
- [ ] "client.search.not.allowed": "Not Allowed to Use Client Search." -> "Client Search is not allowed."
- [ ] "loan.search.not.allowed": "Not Allowed to Use Loan Search." -> "Loan Search is not allowed."
- [ ] "validation.msg.client.id.no.name.details.passed": "Details related to the clients name are mandatory and none have been provided." -> "Details related to the client's name are mandatory."
- [ ] "label.input.calendar.changes.effective.from":"above changes are effective from " -> "The above changes are effective from: "
- [ ] "validation.msg.group.clientMembers.cannot.be.empty": "No clients are selected for associating with group." -> "A group cannot have no clients."
- [ ] "label.input.searchByNameExternalId" : "Find by name/externalId" -> "Search by name or external ID"
- [ ] "label.heading.manualentriesallowed": "Manual Entries Allowed" -> "Are Manual Entries Allowed?"
- [ ] "label.heading.transferringfrom": "Transferring From Details" -> "Transferred From Details"
- [ ] "validation.msg.periodicaccrual.accrueTill.is.greater.than.date":"Date can't be in future" - "can't" -> "cannot"
- [ ] "label.advancesearchoptionforjournalentries": "Advance search option for journal entries" -> "Advanced"
- [ ] "label.norepaymentsanddisbursalareavailable":"No repayments and disbursal are available for selected Group and meeting date" -> "group"
- [ ] "error.msg.financialActivityAccount.exists":"Financial activity account already defined" -> "Financial activity account is already defined."
- [ ] "validation.msg.report.reportSubType.cannot.also.be.provided.when.reportType.is.Table": "Report Subtype cannot be entered" - Add "because the report type is a table"
- [ ] "validation.msg.report.reportSubType.cannot.also.be.provided.when.reportType.is.Pentaho": "Report Subtype cannot be entered" - Add "because the report type is Pentaho."
- [ ] "label.heading.loanaccountnum": "Loan account#" -> "Loan Account Number"
- [ ] "loanPreClosureInterestCalculationStrategy.tillPreClosureDate":"Calculate till pre closure date" -> "until pre-closure"
- [ ] "loanPreClosureInterestCalculationStrategy.tillRestFrequencyDate":"Calculate till rest frequency date" -> "until"

More/less dots (All should be 3 dots) Now that I think about this, the dots go with a tree structure, so I don't think this needs to be done.
- [ ] "#Menu Links": ".." -> "..."
- [ ] "#Anchors": ".." -> "..."
- [ ] "#Inputs": ".." -> "..."
- [ ] "#Buttons": ".." -> "..."
- [ ] "#Misc Labels": ".." -> "..."
- [ ] "#Enumeration & Error Messages": ".." -> "..."
- [ ] "#Common loan/saving charges": "...." -> "..."
- [ ] "#Headings": ".." -> "..."
- [ ] "#Anchors": ".." -> "..."
- [ ] "#Inputs": ".." -> "..."
- [ ] "#Index": "...." -> "..."
- [ ] "#Menu Links": ".." -> "..."
- [ ] "#Anchors": ".." -> "..."
- [ ] "#Inputs": ".."
- [ ] "#Search": ".."
- [ ] "#Buttons": ".."
- [ ] "#Misc Labels": ".."
- [ ] "#Enumeration & Error Messages": ".."
- [ ] "#Clients": "...."
- [ ] "#Headings": ".."
- [ ] "#Anchors": ".."
- [ ] "#Inputs": ".."
- [ ] "#Buttons": ".."
- [ ] "#Misc Labels": ".."
- [ ] "#Enumeration & Error Messages": ".."
- [ ] "#Groups": "...."
- [ ] "#Headings": ".."
- [ ] "#Menu Links": ".."
- [ ] "#Anchors": ".."

Typos
- [ ] "label.input.is_active":"is Active ?" -> "Is Active?"
- [ ] "label.input.closurereasons": "Closure reason" -> "Closure reasons" (If this is not needed, then the whole message isn't because we already have label.input.closurereason
- [ ] "validation.msg.floatingrate.ratePeriods.cannot.be.empty" : "Floating rate reriods can not be empty" => "periods"
- [ ] "validation.msg.client.active.pending.status.not.allowed": "Configuration does not allow client's to be created as `Pending`. " - "client's" -> "a client"
- [ ] "label.button.groupsavingapplication": "Group Saving Application" -> "Savings"
- [ ] "label.button.disassociatemember": "Dissociate Member" -> "Disassociate Member"
- [ ] "error.msg.client.attach.to.group.invalid.office": "The group and its client's must belong to the same office." - "client's" -> "clients"
- [ ] "label.execute.periodic.accounting":"Accrues income, expenses and liabilities as on the provided date" -> "Accrued"
- [ ] "label.periodicaccrual.tilldate":"Accrue Till" -> "Until"

Unsure of, but I think this is better
- [ ] "label.heading.accountingclosures": "Accounting Closures" -> "Account Closures"
- [ ] "label.heading.viewaccountingclosures": "View Accounting Closures" -> "Account"
- [ ] "label.heading.accountingclosuredate": "Accounting Closure Date" -> "Account"
- [ ] "label.heading.closeaccountingcreatedby": "Close Accounting Created by" -> "Account"

Duplicate messages
- [ ] "label.requirefield":"Required Field" and "label.requiredfield": "Required field",
- [ ] "label.nextmettingon":"Next meeting on" and "label.nextmeetingon": "Next meeting on"

**Comment by edcable** [comment]
@mdew192837 All these so far look fine and would be good fixes. 

Where is the Arrears label?

**Comment by MexinaD** [comment]
Is there anyone who is working on this?

**Comment by Mastermaulik** [comment]
@Anh3h Can you pick you pickup this issue?

**Comment by i-am-g2** [comment]
is it still open? I want to work on this.

**Comment by awasum** [comment]
> is it still open? I want to work on this.

Yes. GO ahead and work on this.

**Comment by bharathcgowda** [comment]
merged, thank you @lizeth9797
