### ISSUE TITLE
Reskin&oldSkin: Asterisk sign needed to indicate that  Address Type and street are mandatory fields 

### ISSUE THREAD

**Issue by fboniphace** [openMF/community-app#1806]
Asterisk sign needed to indicate that  **Address Type** and **Street** are mandatory fields in the client creation form at the address category. 
![mf](https://cloud.githubusercontent.com/assets/20817569/22062856/f94b9352-dd8c-11e6-894f-2159c361c26d.PNG)

**Comment by gkrishnan724** [comment]
Hi, I would like to work on this. Can you please provide the list of all fields which are mandatory in this page ? It seems Address Type and Street are not the only field which is required.

**Comment by Mastermaulik** [comment]
@gkrishnan724 @santoshmath Please provide details about the required fields so that gopala can start working on this.

**Comment by santoshmath** [comment]
@Mastermaulik , according reporter of this issue, we need asterisks for 'Address Type' and 'Street' fields only. Not entering any values in these fields yields validation error.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 2/6/2017 on new_reskin branch. This issue is fixed.
