### ISSUE TITLE
No exception thrown during payment type creation

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#1807]
No exception thrown during payment type creation, when Payment type(Mandatory field) or Position or both are not filled once the form is submitted.
And it looks like the Position field is treated as mandatory field, because if there is no input the form is not submitted as well.
![payment](https://cloud.githubusercontent.com/assets/13551795/22063977/8b3907e0-dd92-11e6-8360-464742d140fd.png)

**Comment by gkrishnan724** [comment]
Hi, the issue is already create in Jira https://mifosforge.jira.com/browse/MIFOSX-2782?filter=-1.

**Comment by Agnessy** [comment]
Thanks

**Comment by gkrishnan724** [comment]
#1808

**Comment by gkrishnan724** [comment]
Hi, you could create this issue in  the core (apache/incubator-fineract). I have done the front-end part.
