### ISSUE TITLE
improper z index of textbox under groups and centers

### ISSUE THREAD

**Issue by anu-007** [openMF/community-app#1809]
textbox appears over the side nav under groups and centers. hope it is clear from the image below.
![screenshot from 2017-01-04 02-30-32](https://cloud.githubusercontent.com/assets/20153241/22070079/b7626ef0-ddc0-11e6-99b4-a581660e7480.png)

**Comment by mbj36** [comment]
We have been workin on reskin so it will be fixed on that. Closing the issue
