### ISSUE TITLE
Pagination overlaps side nav

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#1811]
The active item of pagination is overlapping the side navigation bar. This could be observed in Clients>>Groups

It is also possible that it is a problem with all pages which have pagination. 

![screenshot from 2017-01-18 21-33-12](https://cloud.githubusercontent.com/assets/21004514/22071635/c57588ec-ddc5-11e6-8ae0-1728718065f4.png)

**Comment by mbj36** [comment]
We have been reskining the community app that will soon be merged. So closing the issue
