### ISSUE TITLE
Client Page not Displaying any Content - Accounts, etc (only tabs)

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1814]
See https://demo.openmf.org/newbeta/#/viewclient/5

Navigate to any client and you're unable to view the details of their clients and accounts. Only the tabs are available at top. The tabs at the top also don't display any information - only some links.

![screen shot 2017-01-24 at 10 46 36 am](https://cloud.githubusercontent.com/assets/823454/22261594/6d577628-e222-11e6-8922-95348fbab386.png)

**Comment by kamdjouduplex** [comment]
Hey Ed,

I have fixed this issue and sent a PR to the new_reskin branch
Thanks,
Duplex

**Comment by edcable** [comment]
@mbj36 Has this been merged? I didn't notice it being fixed in the latest build that @nazeer1100126 deployed.

**Comment by mbj36** [comment]
PR which @kamdjouduplex sent was failing test cases. I had asked him  to rebase with new_reskin branch and send the PR again

**Comment by mbj36** [comment]
Fixed
