### ISSUE TITLE
Cannot create a new client. Field is required error.

### ISSUE THREAD

**Issue by thynn11** [openMF/community-app#1815]
In the new UI, we cannot create a new client. Even though all mandatory fields are filled out including address lines, state, zip, it's still prompting 'field is required'. 

1) Some javascript error regarding 'getCurrentStep' -- please see attachment.
2) Would be nice if it displays which field is required.

![reskin-newclienterror](https://cloud.githubusercontent.com/assets/5354099/22267636/92f143c0-e252-11e6-88b6-221ff3ebc825.jpg)

**Comment by mbj36** [comment]
Fixed
