### ISSUE TITLE
Arrange the accounts that fall under one account type in order of their GL codes

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1818]
Also reported https://mifosforge.jira.com/browse/MIFOSX-2825

Accounts in chart of accounts are arranged by their account type but those accounts in the specific account type are randomly arranged.
I was recommending for the accounts in the same account type to be arranged by their GL code. Since the relating accounts will be under one header and so their GL codes will be following each other and bring presentable arrangement. (accounts in the same header, their GL codes should have relation)

**Comment by santoshmath** [comment]
@MexinaD , this issue is resolved at fineract side: https://issues.apache.org/jira/browse/FINERACT-389

**Comment by gkrishnan724** [comment]
@MexinaD I believe this has already been solved I see the Accounts ordered according to the `glCode` could you please verify?

**Comment by mbj36** [comment]
CC @santoshmath

**Comment by MexinaD** [comment]
I can see now, the accounts are arranged according with their GL codes @gkrishnan724

**Comment by gkrishnan724** [comment]
@MexinaD Then should we close this issue? or would you like to add some changes?

**Comment by MexinaD** [comment]
@gkrishnan724  the issue can be closed now
