### ISSUE TITLE
Reskin&oldSkin: No exception thrown during teller creation

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#1819]
No exception thrown during teller creation, when Description(mandatory) is not filled once the form is submitted.
![teller](https://cloud.githubusercontent.com/assets/13551795/22415642/1a1c67e0-e6da-11e6-9c07-f144a3d73e2b.png)

**Comment by aayusharora** [comment]
Hi @Agnessy Can I work on this.

**Comment by aayusharora** [comment]
Proposed UI
![om](https://cloud.githubusercontent.com/assets/12194719/22775925/c6b20748-eed3-11e6-8598-dae6ac5a9895.png)

**Comment by Agnessy** [comment]
Ok 
Thanks.

**Comment by edcable** [comment]
Per @santoshmath for consistent behavior with other description fields, the asterisk has been put here in error and should be removed rather than make description field mandatory.

**Comment by mbj36** [comment]
Fixed
