### ISSUE TITLE
Reskin&oldSkin: Improvement in the column name of Data tables

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1821]
Also reported at https://mifosforge.jira.com/browse/MIFOSX-2826

The system when configuring Data tables, in the field of column name it does not allow some of the characters which it could be better to be allowed. For instance when you want to call your column "Mother's  name" or "A/C No" the system through an error because of character ' and /
I would suggest for the system to be able to allow other characters rather than alpha-numeric only.

![datatable](https://cloud.githubusercontent.com/assets/8160209/22541944/82df4416-e93a-11e6-981e-720717530edf.png)

**Comment by gkrishnan724** [comment]
Hi, I believe this is a back end issue since form validations are done in the back-end. I guess this issue should be reported to Fineract. @mbj36 @Mastermaulik

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
@MexinaD , this issue is related to fineract and already raised here as  reported by you.
https://issues.apache.org/jira/browse/FINERACT-388

Closing here
