### ISSUE TITLE
Reskin&oldSkin: Asterisks are missing in the fields of creation of Cashier to show mandatory fields

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1822]
Also reported at https://mifosforge.jira.com/browse/MIFOSX-2827

In the form to create a Cashier for Teller the fields "Cashier/Staff", "From" and "To" are mandatory but there is no asterisks to show that, only when you submit without filling them is when you will know.

![cashier](https://cloud.githubusercontent.com/assets/8160209/22543572/2975156a-e942-11e6-8902-c86fc6c91933.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 2/6/2017 on new_reskin branch. This issue is fixed.
