### ISSUE TITLE
Multiple error in the form to deposit in a saving account

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1830]
1. Create a saving product Admin->Products->Saving Product
2. Apply a saving account to an active client and submit Clients->View client-> New saving
3. Deposit in the saving account 
On the form of making deposit, the field for "Payment type" is labeled "Payment type id"
Also the field of "Payment type" is marked as mandatory while it's not

![depositsaving](https://cloud.githubusercontent.com/assets/8160209/22695573/4907e2fe-ed5c-11e6-9a90-00694a29bfd5.png)

**Comment by MexinaD** [comment]
https://github.com/openMF/community-app/pull/1833

**Comment by nazeer1100126** [comment]
PR merged https://github.com/openMF/community-app/pull/1833
