### ISSUE TITLE
Reskin&oldSkin: No Exception Message when Edit teller is submitted with blank values

### ISSUE THREAD

**Issue by aayusharora** [openMF/community-app#1835]
Steps to reproduce
- Create a new teller and submit it.
- Now edit teller by clicking edit button on right side.
- Leave input boxes blank and click submit

No exception message is thrown.

**Comment by santoshmath** [comment]
Check the following screenshot of 'Edit' Teller . 
![demo](https://cloud.githubusercontent.com/assets/23022667/24283777/adb99c20-108d-11e7-99a4-56bee14187ec.png)

If you keep , For example, Description(its mandatory)  input blank and submit, no error is getting displayed.
Expected: If any mandatory field is blank it should show, for example, 'Description' is mandatory

**Comment by Mastermaulik** [comment]
@Anh3h Please look into this issue

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
