### ISSUE TITLE
Reskin&oldSkin: Submit Button Missing While Foreclosing The Loan For The User Having Foreclosure Permissions

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1836]
1. Create a loan account for a client(Without Interest Recalculation)
2. Create an User with role having permissions of 'Read Client', 'Read Loan', 'Foreclosure Loan' and 'Foreclosure Loan Checker'. 
3. Login with User.
4. Go to the Client>>Loan Account and click on 'Foreclosure' button.
>> In Foreclosure page, 'Submit' button is missing.

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
@mbj36 , This issue is not yet resolved. This issue exists for the user (not superuser, like 'mifos') other than superuser who has permissions Read Client, Read Loan and Foreclosure Loan

**Comment by santoshmath** [comment]
This issue is resolved with latest code fetch.
