### ISSUE TITLE
MIFOSX-2827: Asterisks are missing in the fields of creation of Cashier to show mandatory fields

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1837]
Migrated over from https://mifosforge.jira.com/browse/MIFOSX-2827

I
![cashier](https://cloud.githubusercontent.com/assets/823454/22827811/9212a31e-ef4e-11e6-88c2-e6bf592cfc7b.png)
n the form to create a Cashier for Teller the fields "Cashier/Staff", "From" and "To" are mandatory but there is no asterisks to show that, only when you submit without filling them is when you will know.

**Comment by mbj36** [comment]
https://github.com/openMF/community-app/issues/1822  replicates this issue and i have also created a PR for the same 
PR link - https://github.com/openMF/community-app/pull/1827
