### ISSUE TITLE
Connect Mifos and Stellar to each other.

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1848]
Reportec by Myrle Krantz at https://mifosforge.jira.com/browse/MIFOSX-2376

Original Description:

Create a BridgeComponent using the new Stellar SDK to route Mifos transactions into a Stellar network and to route Stellar transactions into a Mifos network for tenants who wish to allow it.
If no explicit permission has been granted, the default is to not allow transactions from the tenant into the Stellar network to be created.
Transactions will be routed through special tenant accounts, with a memo specifying the destination account within the tenant.

**Comment by santoshmath** [comment]
Sub Tasks of this task:
1. https://github.com/openMF/community-app/issues/1849

2. https://github.com/openMF/community-app/issues/1850

3. https://github.com/openMF/community-app/issues/1851

4. https://github.com/openMF/community-app/issues/1852

5. https://github.com/openMF/community-app/issues/1853

6. https://github.com/openMF/community-app/issues/1854

7. https://github.com/openMF/community-app/issues/1855
