### ISSUE TITLE
View Receipt (Pentaho viewer) asked for authentication again

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1858]
Reported by Thynn Win at https://mifosforge.jira.com/browse/MIFOSX-2811

Original Description:
Whenever we try to view receipt, it prompts for username and password again.
To reproduce this:
1. Go to a client (say test verify on demo server)
2. Click on his loan, then 'Transactions' and then 'View Receipt'.
Receipt is opened
See the attachment. (receipt opens a pentaho report but session is not passed correctly and asking user to enter the credentials again. failing to do so will give unauthorized error.).

![auth_box](https://cloud.githubusercontent.com/assets/23022667/22878016/f6d2bb84-f1fd-11e6-8f86-3bda20755a4e.jpg)

![receipt](https://cloud.githubusercontent.com/assets/23022667/22878024/001b6506-f1fe-11e6-89cc-57857f2f8c72.jpg)

**Comment by bharathcgowda** [comment]
it is working as expected.
closing this issue after discussing with Ed.
