### ISSUE TITLE
Reskin&oldSkin: Asterisk is missing in the field of "Create Fixed Deposit Product" to show mandatory field

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#1866]
In the form of Create Fixed Deposit Product, the field **"Minimum Deposit Term"**  is mandatory..  but there is no asterisk to show that, only when you submit without filling it is when you will know.
![fdp](https://cloud.githubusercontent.com/assets/13551795/22919907/743b2cb4-f2a3-11e6-85e6-7bd30fbc2556.png)
![fdp2](https://cloud.githubusercontent.com/assets/13551795/22919915/7b1d9102-f2a3-11e6-9770-d75a494f76a4.png)

**Comment by skprabhanjan** [comment]
This issue has a commit that fixed it but still exists in the new_reskin branch, @mbj36 I will be sending a PR fixing this issue soon, Is that fine.?
Thanks:)

**Comment by skprabhanjan** [comment]
@mbj36 , Made a PR to fix this issue, Please find and review.
Thanks:)

**Comment by Mastermaulik** [comment]
@mbj36 Please look into this issue

**Comment by mbj36** [comment]
@santosh retest and close it

**Comment by mbj36** [comment]
Fixed

**Comment by santosh** [comment]
Lol, who called me in this chat? Call @santoshmath instead.
