### ISSUE TITLE
Reskin&oldSkin: In create Gurantor, Typehead is not working as expected( doesn't display all clients in database)

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1868]
Reported by @Ippezrobert  at https://mifosforge.jira.com/browse/MIFOSX-2543

Original Description:
Create a loan application
Before approving, Click on More>Create Guarantor menu
Some client's names are not displayed.
This is a big blocker for loans with "Place Guarantor Fund on hold" configuration as it can't be approved especially if the Guarantor's name is missing when actually it exists in the system.
Could this be resolved urgently as we are getting stuck.

![mifos x client 2016-02-29 16-19-27](https://cloud.githubusercontent.com/assets/23022667/23008084/342e2b58-f433-11e6-87ef-304d40bf5178.png)

**Comment by edcable** [comment]
@nazeer1100126 What is status of work on this issue?

**Comment by santoshmath** [comment]
@Ippezrobert , I just tried to reproduce your scenario but unable to do it. Although it doesn't display all the clients at once, but as we go on typing it filters out and displays the client names. I didn't face that any existing client is not getting displayed.

**Comment by santoshmath** [comment]
@Ippezrobert , this issue exists when there is more than 1000 clients. The typehead filters out only upto 1000 clients.

**Comment by Ippezrobert** [comment]
I was thinking of one of these could help: 
1. Remove the limit of 1000 from getAllClients
2. Use getAllClientsWithoutLimit instead other than  from ResourceFactoryProvider.js

**Comment by botraunak** [comment]
Same issue reported here.
 [https://github.com/openMF/community-app/issues/2206](https://github.com/openMF/community-app/issues/2206)

@santoshmath Sent a PR on that issue.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
@Ippezrobert , Will you confirm this is resolved, swiftly?

**Comment by santoshmath** [comment]
As discussed with Robert on mail, this issue is resolved.
