### ISSUE TITLE
Dashboard label is not showing proper action

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1871]
Reported by Amit Jain at https://mifosforge.jira.com/browse/MIFOSX-2112

Dashboard label for disbursement is showing a perfect label when you select the office before any selection is shows proper label.

![dashboard_error](https://cloud.githubusercontent.com/assets/23022667/23016246/df440012-f45b-11e6-8f93-b29d1a2080a2.png)
![dashboard_error_2](https://cloud.githubusercontent.com/assets/23022667/23016247/df6c04ea-f45b-11e6-8047-1b52e35eb7ba.png)

**Comment by skprabhanjan** [comment]
@mbj36 , Can you please let me know if this is still not fixed as it says "open" and if i can work on this.?
Thanks:)

**Comment by mbj36** [comment]
Check if this issue still exists in new_reskin branch then we are happy to
accept PR

**Comment by nazeer1100126** [comment]
merged PR https://github.com/openMF/community-app/pull/1932
