### ISSUE TITLE
Closed Center, Group& Clients are shown on User Interface

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1872]
Reported by Amit Jain at https://mifosforge.jira.com/browse/MIFOSX-2109

Original Description:
1.If we closed any Center, Group & Client even any loan it Should not comes on user Interface 2.Presently it comes on User Interface.
3.I proposed a "Show All" button on UI it works when a user need to view details including closed items.
4. In reports the balance shown is 0 always when the account has been closed I think it should not comes in reports.After a certain level of organisation it creates panic.

![closed client](https://cloud.githubusercontent.com/assets/23022667/23016394/5b42a10a-f45c-11e6-9e41-ea2f57de9225.png)

**Comment by jhonatanbds** [comment]
I'm working on it
