### ISSUE TITLE
XBRL reporting seems to be broken

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1873]
Reported by Vishwas at XBRL reporting seems to be broken

XBRL reporting seems to be broken on the community app.
Details of expected functionality : https://mifosforge.jira.com/wiki/display/RES/GSOC+2013+-+XBRL+Reporting+Integration
In the community app: Reports -> XBRL reporting

**Comment by bharathcgowda** [comment]
![image](https://user-images.githubusercontent.com/65952533/84376232-6bfce480-abfe-11ea-97ae-32add35f75cf.png)
![image](https://user-images.githubusercontent.com/65952533/84376243-70290200-abfe-11ea-8930-2519773be35f.png)

**Comment by bharathcgowda** [comment]
closing this issue after discussing with Ed.
