### ISSUE TITLE
On resizing nav-bar hides

### ISSUE THREAD

**Issue by divyanshu-rawat** [openMF/community-app#1893]
On resizing nav-bar hides instead of collapsing.
Here I am attaching before and after resizing images.

Before Resizing
![original](https://cloud.githubusercontent.com/assets/13464678/23141708/2373f906-f7de-11e6-9460-e168f1526229.png)

After Resizing
![navbar_missing](https://cloud.githubusercontent.com/assets/13464678/23141688/0b98a62e-f7de-11e6-9ccc-7761a68d1506.png)

**Comment by mbj36** [comment]
@divyanshu-rawat We are into the reskin release of the community app, where all the UI enhancements is been going on, currently this is the old skin where we are not taking any UI issues.

checkout the new_reskin branch of the community app
