### ISSUE TITLE
Individual Collection Sheet issue

### ISSUE THREAD

**Issue by Mastermaulik** [openMF/community-app#1896]
Checkout https://demo.openmf.org/reskin/#/individualcollectionsheet

<img width="1280" alt="screen shot 2017-02-21 at 4 34 42 pm" src="https://cloud.githubusercontent.com/assets/5520612/23162376/c7059e88-f853-11e6-8ba3-637a25506e0f.png">
@gkrishnan724 can you look into this?

**Comment by gkrishnan724** [comment]
sure @Mastermaulik  I'll try :+1:

**Comment by mbj36** [comment]
Fixed
