### ISSUE TITLE
Overlapping screen in Groups and Centers Tab

### ISSUE THREAD

**Issue by Mastermaulik** [openMF/community-app#1901]
I noticed that in 
[https://demo.openmf.org/newbeta/#/centers](https://demo.openmf.org/newbeta/#/centers)
and in
[https://demo.openmf.org/newbeta/#/groups](https://demo.openmf.org/newbeta/#/groups)

The screen looks like:
<img width="1277" alt="screen shot 2017-02-22 at 5 38 30 am" src="https://cloud.githubusercontent.com/assets/5520612/23191369/446c4cf4-f8c3-11e6-8fe0-0921064597c7.png">

@gkrishnan724  can you look into this?

**Comment by Anh3h** [comment]
I will like to take up this issue

**Comment by mbj36** [comment]
Fixed
