### ISSUE TITLE
In productive collection sheet if staff is not assigned error message should be displayed in same page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1905]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-2237

Original Description:
In productive collection sheet if staff is not assigned error message should be displayed in same page rather than navigating to next page.

![107](https://cloud.githubusercontent.com/assets/23022667/23198486/f9b2f1c4-f8ed-11e6-8e76-65ece604cf21.png)

**Comment by iamsk9** [comment]
@santoshmath  I understood the issue.Can i work on this?

**Comment by santoshmath** [comment]
Sure.. you can.

**Comment by nazeer1100126** [comment]
PR https://github.com/openMF/community-app/pull/1922 merged.
