### ISSUE TITLE
Create Account screen

### ISSUE THREAD

**Issue by Mastermaulik** [openMF/community-app#1911]
Checkout:
[https://demo.openmf.org/reskin/#/createglaccount](https://demo.openmf.org/reskin/#/createglaccount)

Screenshot:
<img width="1280" alt="screen shot 2017-02-22 at 9 47 26 pm" src="https://cloud.githubusercontent.com/assets/5520612/23220662/b2b9e1a0-f948-11e6-86f3-0b9c8332ab21.png">

**Comment by mbj36** [comment]
@Mastermaulik  I see it's already fixed in new_reskin branch so closing the issue
