### ISSUE TITLE
Create new unified view of Savings Account similar to Loan Summary

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1919]
Reported by Ed Cable at https://mifosforge.jira.com/browse/MIFOSX-2506

Original Description:
In line with both the original Mifos 2.x software and Deanna's mockups at the top-level loan pages, we should cleanly display the Account Summary table above the account details.
This table shouldn't occupy too much room and should be distinct from the other information on this top level page.
We'll also create mockups for the other deposit products - fixed deposits, recurring deposits, etc.

![screen shot 2016-02-02 at 5 55 17 pm](https://cloud.githubusercontent.com/assets/23022667/23244662/e35062bc-f9ac-11e6-9fc1-7c1802a4b22f.png)
![screen shot 2016-02-02 at 5 55 17 pm 1](https://cloud.githubusercontent.com/assets/23022667/23244661/e34a5962-f9ac-11e6-9252-8bc722577bdc.png)

**Comment by gkrishnan724** [comment]
Hi, should the min required balance only be subtracted from the current balance only when the `enforceMinRequiredBalance` is true?

**Comment by gkrishnan724** [comment]
Also, I am assuming that the minimum balance is the minimum required opening balance?

**Comment by santoshmath** [comment]
@gkrishnan724 , minimum balance is the amount which need to be maintained in the savings account failing which lead to penalty or  system doesn't even allow you  to withdraw below minimum balance. (enforceMinRequiredBalance is true). MInimum opening balance is the the amount need to be  present in savings account while  activating  savings account

**Comment by mbj36** [comment]
@santoshmath please retest and close it

**Comment by gkrishnan724** [comment]
Hey, @santoshmath I have some questions for the mockups of Loan summary:
![loan summary page](https://user-images.githubusercontent.com/21004514/27679401-3e70a954-5cd6-11e7-97bc-d7f15cdbaa37.png)


About the field `Amount due ( as of dd/mm/yyy):` could you explain me the use case of this please?

**Comment by gkrishnan724** [comment]
Also, in the savings summary what is meant by `savings goal %` and `amount as collateral`

**Comment by santoshmath** [comment]
Hi @edcable , Savings Summary  now looks like this. Please give your comments before we close this issue.

![savingssummary](https://user-images.githubusercontent.com/23022667/27680776-929a06de-5cda-11e7-88fc-8dc94bdbcd33.png)

![savingsummary2](https://user-images.githubusercontent.com/23022667/27680793-9c84af6e-5cda-11e7-839c-f23ad1ff147b.png)

**Comment by edcable** [comment]
Hi @gkrishnan724 Sorry I never replied to your comment. Savings Goal is something that doesn't yet exist so that can be ignored.

Amount as collateral refers to the amount of the savings balance that has been pledged as a guarantee for a loan. For now we can leave it out too and re-visit later.

@santoshmath we can mark this issue closed.

**Comment by abdugere** [comment]
Savings Goal is something that doesn't yet exist so that can be ignored.

Amount as collateral refers to the amount of the savings balance that has been pledged as a guarantee for a loan. For now we can leave it out too and re-visit later.
