### ISSUE TITLE
All fields for new savings account applications aren't being displayed

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1941]
Navigate to https://demo.openmf.org/newbeta/#/new_client_saving_application/25 and select a savings product to create a new account for.

Fields are both smushed together as reported at #1613 and non-existent.

See

![screen shot 2017-02-27 at 2 15 57 pm](https://cloud.githubusercontent.com/assets/823454/23382574/87080cd2-fcf7-11e6-89f7-e8e821b3d1ea.png)

**Comment by Mastermaulik** [comment]
@edcable , I have already solved this Issue, sending a PR

**Comment by mbj36** [comment]
Fixed
