### ISSUE TITLE
Can't render view loan account page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1943]
Attempted to view https://demo.openmf.org/newbeta/#/viewloanaccount/687

and this is what I see:

![screen shot 2017-02-27 at 2 32 39 pm](https://cloud.githubusercontent.com/assets/823454/23383093/a4c747ea-fcf9-11e6-839d-a12097c9db33.png)

**Comment by DanCarl857** [comment]
Working on this

**Comment by mbj36** [comment]
Fixed
