### ISSUE TITLE
Asterisks are missing to show Selected Roles is mandatory in User creation

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#1958]
Can be reproduced by
Admin -> User -> Create User

![usercreation](https://cloud.githubusercontent.com/assets/8160209/23459197/52e2158e-fe90-11e6-9663-0a87ee688d43.png)

**Comment by edcable** [comment]
This is also present on the reskin. Asterisk needs to be added to the selected roles section.

**Comment by botraunak** [comment]
I'll try this!

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is resolved.

**Comment by Agnessy** [comment]
@MexinaD @mbj36 @santoshmath  The issue works fine when creating User,
Not yet for user edition. 'Selected Role' doesn't have asterisk
![user](https://user-images.githubusercontent.com/13551795/30954553-4822ce64-a439-11e7-877b-3180adf8e5f5.png)

**Comment by santoshmath** [comment]
That's true @Agnessy .  Reopening this issue.

**Comment by shr33narayan** [comment]
@santoshmath @mbj36 You can assign me this issue, I'd like to work on it now.

**Comment by mbj36** [comment]
You are free to work on it
