### ISSUE TITLE
No indication showing  "code values" status 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#1959]
Go to System >> Manage Codes>> Add codes
Then add code values
The list of all code values doesn't retrieve their status in the Active column, to show either the code value is active or not 
![code values](https://cloud.githubusercontent.com/assets/13551795/23459414/4aed23a4-fe91-11e6-9842-b0ffe841cd94.png)

**Comment by botraunak** [comment]
I'll Try this.

**Comment by skprabhanjan** [comment]
Is this still open.? I see a commit that says "fix #1959" but the the issue is still open. @mbj36 can you please let me know the status of this so that i can work on this or if this is already done then I can work on something else.
Thanks:)

**Comment by mbj36** [comment]
Raunak has created PR for the same,  let me find time and review it
