### ISSUE TITLE
Reskin:Password field already entered with right password on opening page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1965]
When you open the mifos with URL, https://demo.openmf.org/newbeta, on opening page, password field is already entered with the password.
![password](https://cloud.githubusercontent.com/assets/23022667/23497880/28a85ac4-ff4b-11e6-835e-cbfa292a6a1b.png)

**Comment by gkrishnan724** [comment]
@santoshmath  I guess this is because you saved the password. Also, This only exists in chrome browser.

**Comment by santoshmath** [comment]
@gkrishnan724 I agree the issue is with cache and chrome browser. But when we load previous community app(without reskin) even  on chrome browser with password saved, the password autofills only after typing username.

**Comment by R7467** [comment]
@santoshmath will you please link the page.

**Comment by gastonche** [comment]
What about setting the form's autocomplete attribute to off so as to prevent the browser from ever auto filling the inputs?

**Comment by chaitanyaparashar** [comment]
#2123 Resolved, Please review it

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Just clear the  cache in browser.
