### ISSUE TITLE
Reskin:Drop-down menus are not getting compressed after selecting the appropriate parameter

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1967]
Some of the drop-down  menus, For ex: Client create page, Office create page, Creating Employee, or Financial activity. Once we click on drop-down menu it  expands and  after we select any parameter it doesn't compress back. 

![dropdown](https://cloud.githubusercontent.com/assets/23022667/23501401/b9e2dcf4-ff59-11e6-8ad9-c452ae1d7642.png)

**Comment by gkrishnan724** [comment]
I'll  try this :+1:

**Comment by Anh3h** [comment]
I don't face this issue on new_reskin

**Comment by Mastermaulik** [comment]
This issue is visible here on the newbeta [website](https://demo.openmf.org/newbeta).

But this issue is not faced locally, locally this is working fine.

**Comment by santoshmath** [comment]
I tested it here and found the issue;
https://demo.openmf.org/newbeta/
But when  I run it locally drop-down  menus are working fine.

Some of the CSS files are not getting loaded in https://demo.openmf.org/newbeta/
1. Styles.css
2.ui-bootstrap.csp.css
3.chosen.css
4.ng-scrollbar.css

**Comment by Anh3h** [comment]
I don't event see drop-down for here : https://demo.openmf.org/newbeta/#/createoffice

![test](https://cloud.githubusercontent.com/assets/20562458/23505758/5d6a38f0-ff45-11e6-96c4-58b16766d2f4.png)

**Comment by santoshmath** [comment]
For the above four files, developer tool showing '404 not found'

**Comment by kamdjouduplex** [comment]
Please I just want to be sure that, you have rebuild the production package of a working local of this and put it on the server and it was still not working?

**Comment by santoshmath** [comment]
@kamdjouduplex , I mailed you regarding this and tagged @mbj36 .

**Comment by mbj36** [comment]
@santoshmath This major issue is resolved

**Comment by mbj36** [comment]
Tested on newbeta and issue is resolved
