### ISSUE TITLE
Reskin&oldSkin: No exception thrown during "loan product" creation 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#1969]
No exception thrown during "loan product" creation ,  when Calculate interest for exact days in partial period(Mandatory) AND Account moves out of NPA only after all arrears have been cleared?(Mandatory)
Fields are not Checked.. still the form can be submitted successfully.
![ll1](https://cloud.githubusercontent.com/assets/13551795/23506284/8d8618f2-ff58-11e6-9837-cc0d9211eaf7.png)

![l2](https://cloud.githubusercontent.com/assets/13551795/23504160/6015e568-ff4f-11e6-948c-03a77fc0071e.png)

**Comment by santoshmath** [comment]
@Agnessy , Actually labels or parameter names having single radio buttons should not be mandatory, in general.

**Comment by Mastermaulik** [comment]
@Anh3h Please look into this issue

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by Agnessy** [comment]
@santoshmath @mbj36 
I think this issue still exist.
