### ISSUE TITLE
Reskin&oldSkin: Any character is allowed on creation of client, user and employee

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1971]
Reported by Mexina at https://issues.apache.org/jira/browse/FINERACT-413

Original Description:
The system allows any character in firstname, middlename, lastname and username during creation of user/client/employee. A user of the system can enter "." in both fields and the system will allow to submit. Practically i don't think if this is correct
Reproduce this by:
Client->Create client
Fill '.' (dot) In the field for first name, middle name and last name and other mandatory fields.
The system will allow the submission successful 
You do the same in User creation and Employee creation

**Comment by botraunak** [comment]
@santoshmath Is this an issue for the new_reskin or the develop, I'll try this.

**Comment by mbj36** [comment]
@botraunak check if this issue still exists in new_reskin then PRs accepted

**Comment by santoshmath** [comment]
It's related to develop, not reskin


On Mar 4, 2017 10:20 AM, "Raunak Sett" <notifications@github.com> wrote:

@santoshmath <https://github.com/santoshmath> Is this an issue for the
new_reskin or the develop, I'll try this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openMF/community-app/issues/1971#issuecomment-284127451>,
or mute the thread

**Comment by botraunak** [comment]
@mbj36 Can I try this for the develop branch?, I'll take up this issue then.

**Comment by santoshmath** [comment]
Sure . You can..

**Comment by botraunak** [comment]
![screen shot 2017-03-05 at 9 44 33 pm](https://cloud.githubusercontent.com/assets/7816559/23589098/6373c39c-01ed-11e7-84b7-7c6219b11200.png)

Generating a PR for same. @mbj36

**Comment by TechnicaVoyage** [comment]
![screenshot 83](https://cloud.githubusercontent.com/assets/20579129/23717937/c9f58248-045b-11e7-9d40-7c13c7380358.png)
Some names have special character in them. Keeping those in mind I took this approach.

**Comment by santoshmath** [comment]
@mbj36 , is PR merged for this?

**Comment by mbj36** [comment]
@santoshmath No, i will review today

**Comment by MexinaD** [comment]
This issue is also in new_reskin

**Comment by gkrishnan724** [comment]
@mbj36  PR https://github.com/openMF/community-app/pull/2076  has been sent for this issue from @TechnicaVoyage  Please review it

**Comment by mbj36** [comment]
Fixed
