### ISSUE TITLE
In  Reskin, Entity Data Table Check not showing proper labels and can't do any operation

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1985]
Go to Admin>>Organization>> Entity Data Table Check. The view page of entity data table check shows like this. You cannot do create or delete entity data table checks .

![entity-datatablecheck](https://cloud.githubusercontent.com/assets/23022667/23597180/a69a466e-0256-11e7-8755-23e0cf2a0ef6.png)

**Comment by mbj36** [comment]
@santoshmath It was fixed here https://github.com/openMF/community-app/issues/1975

**Comment by santoshmath** [comment]
Sorry.. It's duplicate.. Closing it. :) I am checking it on https://demo.openmf.org/newbeta, it is still broken?

**Comment by mbj36** [comment]
Because it was fixed after nazeer deployed

**Comment by santoshmath** [comment]
Ok. got it.
