### ISSUE TITLE
Reskin: View cashier page is not showing proper labels

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1987]
Go to Organization>>Teller cashier Management and then create a teller and then cashier for the teller. 

![cashier](https://cloud.githubusercontent.com/assets/23022667/23597563/efe05180-0259-11e7-8f7b-4d3ee92eec92.png)

**Comment by botraunak** [comment]
@santoshmath I'll try this!

**Comment by botraunak** [comment]
@santoshmath the blue view icon and red delete icon are also not showing proper icons, I'll fix them as well! 👍

**Comment by santoshmath** [comment]
@botraunak , Good Catch!! That is also a bug...

**Comment by botraunak** [comment]
@santoshmath I've opened a PR for same. 👍

**Comment by santoshmath** [comment]
@mbj36 , Will you check @botraunak PR?

**Comment by mbj36** [comment]
I will review later today

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is resolved.
