### ISSUE TITLE
Reskin: Working Days page not showing parameter for 'Payment Due on non working days', 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1988]
Go to Organization>> Working  Days. Select any parameter (same day, move to next working day, etc) for 'Payment due on non working days' and submit it. When you view 'working days'  page, the parameter for 'Payment due on non working days' shows blank:

![workingdays](https://cloud.githubusercontent.com/assets/23022667/23597735/70e59cb2-025b-11e7-8057-5fbeaf5721c8.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it , I have merged PR

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is fixed.
