### ISSUE TITLE
Reskin: added codes(System>>Manage codes) are not getting highlighted when mouse cursor hovered on them

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1989]
In demo server, I hovered mouse on 'Asset account tags' and it is highlighted:

![demo](https://cloud.githubusercontent.com/assets/23022667/23598514/f05652c0-0260-11e7-97e5-d268de0c0e99.png)

But in reskin, it is not getting highlighted.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23598526/00db5f28-0261-11e7-9465-62324dc5ac9a.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is resolved.
