### ISSUE TITLE
Reskin: hovering mouse on any report name(System>Manage Reports) masks its name and unable to read. 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1991]
>Go to Admin>System>Manage Reports, which displays list of available reports
>Hover mouse on any report , and you cannot read the report name. It is because both font color and selection color are blue; 

![managereports](https://cloud.githubusercontent.com/assets/23022667/23598746/674f9e3a-0262-11e7-851c-2d10753f9c0e.png)

**Comment by mbj36** [comment]
@santoshmath I have merged, retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue has been fixed.
