### ISSUE TITLE
Reskin: Multiple Issues in 'Edit Report' page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1992]
Go to Admin>System>Manage Reports. And select any report and click on Edit button.

![query](https://cloud.githubusercontent.com/assets/23022667/23598998/3a1c5e60-0264-11e7-8e97-a8836bd23145.png)

>As shown in above pic, text box for entering SQL query should be wide enough  to read the queries properly.
>When we add parameter the button to delete parameter(Actions) is missing. And also it should be wide enough. Check the screenshot from demo server.

![demo](https://cloud.githubusercontent.com/assets/23022667/23599050/8c0f8f9e-0264-11e7-81cf-4de69a89c0fb.png)

**Comment by DanCarl857** [comment]
Submitted a PR for this @santoshmath. @mbj36 could you please review?

**Comment by skprabhanjan** [comment]
@santoshmath , is this issue still open.? Can you please clarify so that I could work on this, if its still open and not solved.
Thanks:)

**Comment by santoshmath** [comment]
@skprabhanjan , go ahead, it's still open.

**Comment by skprabhanjan** [comment]
@santoshmath , Sure, I will fix this:)

**Comment by skprabhanjan** [comment]
@santoshmath , Sorry I had not checked it in new_reskin(just saw the issue was open), seems like it is already fixed in new_reskin's latest code, the text box for entering sql queries is wide enough and there is a delete button also.
So this issue is fixed rite.?
Thanks:)

**Comment by santoshmath** [comment]
confirm with @mbj36 .

**Comment by skprabhanjan** [comment]
@mbj36 , Can you please confirm on this.? It looks fixed in the latest new_reskin code but the issue is still open.
Thanks:)

**Comment by santoshmath** [comment]
Tested it  on 10/5/2017 on new_reskin branch. This issue is fixed.
