### ISSUE TITLE
Reskin: 'Filter by name' for global configurations (System>Configurations) is not working

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1993]
Go to Admin>System>Configurations and try to filter out required configuration using 'Filter by name', it's not filtering out. Check the screenshot.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23599479/5b15c7f2-0267-11e7-81b4-2ae9e11fea8b.png)

Filtering is working in demo instance.

![demo](https://cloud.githubusercontent.com/assets/23022667/23599487/6ea7c482-0267-11e7-97a0-f43246836b44.png)

**Comment by botraunak** [comment]
@santoshmath I'll work on this

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue has been resolved.
