### ISSUE TITLE
Reskin: Direction buttons are not displaying in Create or edit 'Product Mix' page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1994]
Go to Admin>Products>Product Mix. Create a product mix or edit existing product mix . You will see the below screenshot.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23600658/a432c998-026d-11e7-8959-ef68cf267106.png)

**Comment by botraunak** [comment]
@santoshmath I'll take up this issue!

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is resolved.
