### ISSUE TITLE
Reskin: Unable to create a charge

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1995]
Go to Products >>Charges and click on 'Create a charge', then the application is continuously loading and shows improper parameters in the drop-down menu.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23601744/04c5b608-0273-11e7-978b-80c4652417af.png)

**Comment by gkrishnan724** [comment]
I'm working on this ...

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 13/3/2017 on new_reskin branch. This issue is fixed.
