### ISSUE TITLE
Reskin: View/Edit Interest Rate Chart page is broken for FD & RD 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1996]
1. Create any FD or RD product with added interest rate chart.
2.   On Summary page of FD or RD product, click on 'View/Edit Interest Rate Chart'. The following page is broken.
![reskin](https://cloud.githubusercontent.com/assets/23022667/23602210/69fd6bc2-0275-11e7-81fe-62a476a60c53.png)

**Comment by botraunak** [comment]
@santoshmath I'll try to solve this issue!

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin. This issue is resolved. There are other issues related to it and I will rise as separate issue.
