### ISSUE TITLE
Reskin: Actions to deselect the charge is not showing while creating or editing the loan product

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1998]
Check the screenshot in demo instance:

![demo](https://cloud.githubusercontent.com/assets/23022667/23602683/9b5a6e2a-0277-11e7-9a84-54cf6dfe3dc9.png)

Check the screenshot in reskin(newbeta) instance:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23602699/b3cd28c6-0277-11e7-95e7-d370c95e09c7.png)

Similar to one of the issue here: https://github.com/openMF/community-app/issues/1992

I think Actions to 'deselect' is not working at most of the scenarios in reskin.

**Comment by DanCarl857** [comment]
Let me get this

**Comment by DanCarl857** [comment]
PR submitted

**Comment by mbj36** [comment]
@santoshmath we should close this

**Comment by santoshmath** [comment]
Created a checklist related to this at #2126 . Closing here.
