### ISSUE TITLE
Reskin:Asterisks for mandatory fields should not be of same color of field names

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1999]
It is difficult to highlight mandatory fields if both field names and asterisk have same color. 

Ex:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23603110/aa71f7d2-0279-11e7-8b26-ff291c13bc1b.png)

**Comment by botraunak** [comment]
@santoshmath I'll take this up!

**Comment by mbj36** [comment]
@santosh FYI

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue has been fixed.
