### ISSUE TITLE
Reskin: Share Product Summary View is showing some text box between Edit and Dividends label

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2000]
Check the screenshot.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23603368/ece9cfc6-027a-11e7-8d1a-7f00438f9dfb.png)

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin, this issue has been fixed.
