### ISSUE TITLE
Reskin: Large gap between Field Name and it's corresponding radio button

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2002]
Check the screenshots for some of the cases:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23603935/085c0eb6-027d-11e7-9aae-6c0d3b9acab3.png)

![reskin1](https://cloud.githubusercontent.com/assets/23022667/23603934/08563392-027d-11e7-80d6-71448f764ad3.png)

![reskin2](https://cloud.githubusercontent.com/assets/23022667/23603933/08530622-027d-11e7-9d7a-2274ea077b9c.png)

**Comment by DanCarl857** [comment]
Hi Santosh, could you please specify what pages I can find this issue on?

**Comment by santoshmath** [comment]
@DanCarl857 , you can check it on 'Create Loan Product' page. I have given only 3  examples here. But there are some of similar issues in other pages as well.

**Comment by MexinaD** [comment]
Fixed https://github.com/openMF/community-app/pull/2066

**Comment by santoshmath** [comment]
@mbj36 , check the PR

**Comment by Anh3h** [comment]
I will like to take up this issue

**Comment by santoshmath** [comment]
@mbj36 , did you check PR by @Anh3h ?

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on new_reskin branch. This issue is fixed.

**Comment by MexinaD** [comment]
@santoshmath i see this issue already closed, but i can still find the gaps in new_reskin branch 
![gaps](https://user-images.githubusercontent.com/8160209/26972162-406779e4-4d19-11e7-83cd-0b91039de6f9.png)
and others

**Comment by santoshmath** [comment]
@MexinaD , Fetch the latest code and retest again

**Comment by MexinaD** [comment]
@santoshmath  i just did and it shows my forked branch is even with open_mf/reskin https://github.com/MexinaD/community-app/tree/new_reskin
