### ISSUE TITLE
Reskin: Misplaced drop-down menu in Create Saving Product. 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2003]
Screenshot of demo instance:

![demo](https://cloud.githubusercontent.com/assets/23022667/23604504/242ac914-027f-11e7-9780-cd893e5fd7b5.png)

Screenshot of reskin showing misplaced drop-down menu:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23604535/43b2b526-027f-11e7-8d5c-9c13516ce498.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is fixed.
