### ISSUE TITLE
Reskin:Action to deselect the charge added to savings product is missing.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2004]
Check the screenshot:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23604930/b266bda4-0280-11e7-9b69-76bea36d26f2.png)

**Comment by santoshmath** [comment]
Similar to https://github.com/openMF/community-app/issues/1998

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is resolved at savings product level. 

@mbj36  'Action' to deselect charges in savings account level, loan product  level, loan account level still exists. This deselect problem ,can it be solved once for all scenarios?

**Comment by mbj36** [comment]
Changes should be done according to corresponding files.  Create issue where the same problem exists and i will take up
