### ISSUE TITLE
Reskin:In Frequent Postings & Add Journal Entries text box for Transaction Date is showing different color

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2006]
Check the screenshot:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23605629/7a7c3664-0283-11e7-8c23-2d17edc45864.png)

![reskin](https://cloud.githubusercontent.com/assets/23022667/23643902/9c370692-032a-11e7-9ed4-7e35a1f1bfcc.png)

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 9/3/2017 on new_reskin, this isssue is resolved.
