### ISSUE TITLE
Reskin:'Create Entity Data table check' page is broken 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2008]
Go to Organization>Entity Data table check and click on 'Create Entity Data table check' and you get following screen:

![entity](https://cloud.githubusercontent.com/assets/23022667/23605943/a5e1d1fa-0284-11e7-89cb-4dd97fb32871.png)

**Comment by gkrishnan724** [comment]
I'll work on this ASAP :+1: sorry didn't notice that.

**Comment by santoshmath** [comment]
@mb36, PR #2034 is merged?

**Comment by mbj36** [comment]
@santoshmath Fix was not proper, so i commented on PR and requested to make changes

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 13/3/2017 on new_reskin branch. This issue is resolved.
