### ISSUE TITLE
Reskin:On Client's page, 'Charge Overview' is getting displayed though client has no 'Client Charge'

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2011]
Check the screenshot:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23606907/d30ee8b2-0288-11e7-82db-d54c565b85ad.png)

**Comment by gkrishnan724** [comment]
I'll look into this

**Comment by iamsk9** [comment]
@santoshmath Please view the pull request [#2075](https://github.com/openMF/community-app/pull/2075) regarding this issue.

**Comment by santoshmath** [comment]
@mbj36 FYI #2075

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 13/3/2017 on new_reskin branch. This issue is fixed.
