### ISSUE TITLE
Reskin:Error messages are displaying with different colors at different scenarios

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2014]
Check this screenshot where error message is displaying with red color.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23607384/ca516fd6-028a-11e7-9f95-6895a148dc0a.png)

and here, it is dipalaying with black color:

![reskin1](https://cloud.githubusercontent.com/assets/23022667/23607400/dd38e9f8-028a-11e7-89a1-eb5e45769638.png)

**Comment by iamsk9** [comment]
@santoshmath Created a PR #2084 resolving this issue. 
Please check.

![screenshot 21](https://cloud.githubusercontent.com/assets/10477029/23824121/e3145924-0696-11e7-8e5e-5c39bbb05fd3.png)

**Comment by santoshmath** [comment]
@mbj36 , @iamsk9 , All the error messages displayed in any part of the mifos(client, group, loan, datatables, etc) should be of same color(Red is preferable)

**Comment by iamsk9** [comment]
@santoshmath Most of the error messages in mifos are in red color. I didn't find anyother with black color.

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
@mbj36 , this issue is resolved related new savings application and closing it. But error messaages are displaying  in different colors(black or red) in other scenarios well. We have to make checklist and make same color(red) for all error messages.
