### ISSUE TITLE
Reskin&oldSkin: Group Loan Application is displaying duplicate rows under 'Meeting Details'

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2016]
The screenshot:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23608173/1fd4f9a2-028e-11e7-9a0d-b3db67c28cd9.png)

**Comment by gastonche** [comment]
I am unable to reproduce this bug.

**Comment by santoshmath** [comment]
@gastonche , Check here. https://demo.openmf.org/#/newgrouploanaccount/113
I think this issue is the result of changing meeting (editing) dates frequently.

**Comment by skprabhanjan** [comment]
hey @santoshmath , @mbj36 I have fixed this issue , I have added a custom filter that filters out duplicate meetings (written my own filtering function) , I will go ahead and send a PR for this. 
Can you please review it.?
Thanks:)

**Comment by santoshmath** [comment]
@mbj36 , Is PR for this merged?

**Comment by prab07** [comment]
@santoshmath, I have fixed this issue and had sent a PR but i did not follow the naming conventions so it was closed, i wlil rebase with new_resking and send a PR for this ASAP.
Thanks:)

**Comment by santoshmath** [comment]
@mbj36 FYI

**Comment by santoshmath** [comment]
This issue is raised again here: #2410. And closing this one.
