### ISSUE TITLE
Reskin:Symbols are not displayed properly on Group's  page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2018]
For Group loan and group saving application symbols are not getting displayed properly.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23608340/ef36a380-028e-11e7-8131-81efca47d911.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is fixed.
