### ISSUE TITLE
Reskin: Moratorium Fields are not properly aligned.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2022]
In screenshot , check moratorium on interest:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23609996/c4b39930-0296-11e7-9e03-c516a1400f1a.png)

**Comment by gastonche** [comment]
@santoshmath Please i would like to work on this issue. on which page is that screen shot from?

**Comment by santoshmath** [comment]
@gastonche, it's "Loan Application page" for client/group

**Comment by skprabhanjan** [comment]
@santoshmath , I have fixed this issue , if you could please tell if the interface is fine , I would go ahead and send a PR for this.
I have attached a Screenshot of the fix here .
Thanks:)

![screen shot 2017-03-06 at 9 44 26 pm](https://cloud.githubusercontent.com/assets/17094832/23618409/403bb4ba-02b6-11e7-873c-d06868177dba.png)

**Comment by skprabhanjan** [comment]
@santoshmath Sorry, I have updated the UI. Please review this Screenshot.
Thanks:)

![screen shot 2017-03-06 at 9 46 59 pm](https://cloud.githubusercontent.com/assets/17094832/23618521/8fd66f10-02b6-11e7-9d0a-b9e3a5f3b301.png)

**Comment by santoshmath** [comment]
@skprabhanjan , It's good if Moratorium  is left aligned.

**Comment by gastonche** [comment]
Then i'll go ahead and submit my pull request, i fixed the issue and have the moratorium left aligned

**Comment by santoshmath** [comment]
@gastonche , sure

**Comment by R7467** [comment]
Can you tell me if this issue is fixed or not. The Moratorium fields do not appear to be  aligned.
![screen shot 2017-03-13 at 9 56 14 pm](https://cloud.githubusercontent.com/assets/17959638/23864287/0dc29fee-0838-11e7-82ae-1e39139e5a62.png)

**Comment by skprabhanjan** [comment]
@santoshmath , Is this still open.? If yes, I will send a PR again
Thanks:)

**Comment by santoshmath** [comment]
@skprabhanjan , it's still open.

**Comment by skprabhanjan** [comment]
@santoshmath, okay I will fix this and send a PR soon :)

**Comment by mbj36** [comment]
@santoshmath close it

**Comment by santoshmath** [comment]
Tested it on new_reskin branch. This issue is resolved.
