### ISSUE TITLE
Reskin:'More' button is not working on Client's/Group's loan approval page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2025]
on demo instance:
![demo](https://cloud.githubusercontent.com/assets/23022667/23610319/0bb8ed70-0298-11e7-8264-aa9646f33cd4.png)

on reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23610340/16bf65fa-0298-11e7-9a55-c78398bd727d.png)

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is fixed.
