### ISSUE TITLE
Reskin: In Loan Account, Transaction Tab is showing no entry

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2026]
Transaction Tab:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23610649/4b33d7a2-0299-11e7-831a-9a979ff5af92.png)

Corresponding Repayment Schedule:

![reskin1](https://cloud.githubusercontent.com/assets/23022667/23610661/59efe83a-0299-11e7-8359-f7986e73a38b.png)

This is one of the major issue of reskin and must be fixed sooner.

**Comment by DanCarl857** [comment]
working on this now

**Comment by DanCarl857** [comment]
Submitted a PR: https://github.com/openMF/community-app/pull/2033

**Comment by santoshmath** [comment]
@mb36 FYI

**Comment by santoshmath** [comment]
@mbj36, FYI

**Comment by santoshmath** [comment]
@mbj36 , Is pull request #2033 , merged?

**Comment by DanCarl857** [comment]
I don't think so yet.

**Comment by mbj36** [comment]
@santoshmath I have merged, retest and close it

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. Transaction tab is showing disbursement and repayment entries.
