### ISSUE TITLE
Reskin: Savings Account Page under groups is broken

### ISSUE THREAD

**Issue by DanCarl857** [openMF/community-app#2032]
When you try to view the savings account page under groups, the page is completely broken.
Go to Groups->Clients(select any client)->SavingsAccount

![screen shot 2017-03-06 at 3 02 46 pm](https://cloud.githubusercontent.com/assets/9010142/23613033/01953d22-027e-11e7-9bb9-2ff38f098b0a.png)

**Comment by gkrishnan724** [comment]
I'll work on this :+1:

**Comment by santoshmath** [comment]
@DanCarl857 , This issue exists even after when you 'submit' new savings application for any client or group .and also when you try to view savings account for any client.

**Comment by DanCarl857** [comment]
Ok @gkrishnan724 could look into that as he is working on the issue

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is resolved.
