### ISSUE TITLE
Reskin: Misaligned Fields in New Share Account Application for a client

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2035]
Go to any client's page, and click on 'New Share Application'. and you will get following page:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23644482/8776cbf4-032d-11e7-8bd9-0bba6e7e280c.png)

Here, product, submitted on and external ID alignment are not proper and also minimum active  period and lock-in period not properly aligned.  You can check without reskin 'New Share Application' page;

![demo](https://cloud.githubusercontent.com/assets/23022667/23644594/118f5c98-032e-11e7-9686-4750204f6dcb.png)

**Comment by DanCarl857** [comment]
Let me work on this

**Comment by DanCarl857** [comment]
![screen shot 2017-03-07 at 8 15 55 am](https://cloud.githubusercontent.com/assets/9010142/23645831/67941810-030e-11e7-8e70-e472a77c4f24.png)

**Comment by santoshmath** [comment]
@DanCarl857 , Could you make alignment just like in the without reskin. (screenshot in description). Doesn't it look good?

**Comment by DanCarl857** [comment]
@santoshmath please I don't understand. I made it exactly like the old one

**Comment by santoshmath** [comment]
@DanCarl857 , in your changes,for example,  Submitted on is center-aligned. In old, it is right aligned.

**Comment by DanCarl857** [comment]
Ok let me fix that

**Comment by DanCarl857** [comment]
![screen shot 2017-03-07 at 10 52 24 am](https://cloud.githubusercontent.com/assets/9010142/23650954/32a24ce2-0324-11e7-9735-c47217e44aaa.png)

**Comment by mbj36** [comment]
@santoshmath Merged this one, retest and close it

**Comment by santoshmath** [comment]
@mbj36 ,@DanCarl857 , When  I create New Share Account Application page, alignment issue is resolved. But I Submit it by entering  required inputs. And in next page I click  on 'Modify Application' , the previous misalignment again comes back.

**Comment by mbj36** [comment]
Please look at it @DanCarl857  and send  new PR

**Comment by anu-007** [comment]
@mbj36 @santoshmath i have created a PR solving this problem  please review ( https://github.com/openMF/community-app/pull/2098 ). thanks!!

**Comment by anu-007** [comment]
@mbj36 i followed your review on ( https://github.com/openMF/community-app/pull/2098 ) and send a new PR please review ( https://github.com/openMF/community-app/pull/2110 )

**Comment by amarlearning** [comment]
@mbj36 Looks like community member is not reading the `issue` title properly!
there is a spelling mistake,  which should be corrected!

**Comment by santoshmath** [comment]
@amarlearning Corrected.. :)

**Comment by anu-007** [comment]
@santoshmath @mbj36 please review ( https://github.com/openMF/community-app/pull/2117 ).

**Comment by mbj36** [comment]
@santoshmath I don't see any alignment issue here can you please confirm ?

**Comment by santoshmath** [comment]
@DanCarl857 @mbj36 , Everything looks good except 'Submitted on' should be right aligned 'Decimal Places' , Today's price. etc. Check the screenshot:
![reskin](https://cloud.githubusercontent.com/assets/23022667/24280965/fb27316a-107a-11e7-9a7f-0e9bc1a1562a.png)

**Comment by mbj36** [comment]
@santoshmath We can close this as of now with present solution
