### ISSUE TITLE
Reskin: After adding clients while creating group, the deselect button blurred with color

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2036]
Go to Groups and click on Create a group. 
Provide the necessary inputs and click on Add clients, search and add the client.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23644846/4a71600a-032f-11e7-9510-b0683021885c.png)

Without reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23644859/5bf6ee30-032f-11e7-8a9b-be797e3c0e7d.png)

**Comment by DanCarl857** [comment]
Working on this now

**Comment by DanCarl857** [comment]
Let me fix this

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
This issue is fixed.
