### ISSUE TITLE
Reskin:'Create Client' page is not showing 'Submit' or 'Cancel' button

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2039]
Go to Clients and click on '+Create Client' button:
The create client page is not showing 'Submit' or 'Cancel' button.

![1](https://cloud.githubusercontent.com/assets/23022667/23647271/0af6de26-033b-11e7-8eff-52669f3001b4.png)

Go to System>Configurations and search for "Enable-Address" and enable it. Then you can see 'Submit' or Cancel button on Create Client page.

This is one of the major blocker issue and must be fixed very soon.

**Comment by botraunak** [comment]
@santoshmath Will Take Up this issue!

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 9/3/2017 on new_reskin  branch, This issue is resolved.
