### ISSUE TITLE
Reskin:Create Client page is not showing '+' button or 'x' button in address module

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2040]
Go to System > Configurations and search for 'Enable-Address' and enable it.
Go to clients and click on '+Create Client' to Create client page:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23647559/738a77c6-033c-11e7-9661-b22f462f8411.png)

Without reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/23647572/8829bd72-033c-11e7-8a36-de6d90899282.png)

**Comment by gastonche** [comment]
I have this displaying on mine 
![client](https://cloud.githubusercontent.com/assets/11961056/23648878/9df86902-031c-11e7-800c-eef6f26a7a97.PNG)

**Comment by DanCarl857** [comment]
Are you on the new skin @gastonche. Because when I activate the address module, it doesn't show on mine

**Comment by gkrishnan724** [comment]
Let me have a look at this :+1:

**Comment by gkrishnan724** [comment]
@santoshmath  I already had discussed about the '+' button in the gitter channel. 

The `+`  and `x` seems to be showing in the demo page:https://demo.openmf.org/newbeta/#/createclient. However, the icon is not loading in the localhost. A possible fix will be using Font awesome icons. Also I plan to add tooltips to the `+` and `x`.

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 9/3/2017 on new_reskin branch. This issue is fixed.
