### ISSUE TITLE
Reskin: Once group or center attached with meeting, 'Attach Meeting' option is still showing in 'More' drop-down

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2042]
>Create a center or group. Attach Meeting. But in 'More' drop-down 'Attach meeting option is still displaying.
With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23648376/75fb2434-0340-11e7-9250-44379b6b0c69.png)

Without Reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23648385/80691c1e-0340-11e7-86a8-696414233d7f.png)

**Comment by botraunak** [comment]
@santoshmath I'll take this up!

**Comment by botraunak** [comment]
![screen shot 2017-03-08 at 7 23 00 pm](https://cloud.githubusercontent.com/assets/7816559/23706551/ae5461de-0434-11e7-84a5-94bb96726bbe.png)

Cannot reproduce on new_reskin. @santoshmath

**Comment by santoshmath** [comment]
@botraunak,  I shared screenshot from new_reskin itself.  Let me test it again and come back

**Comment by dart-wakar** [comment]
@santoshmath @mbj36 I have created a pull request #2156

**Comment by mbj36** [comment]
@santoshmath There is no such bug in new_reskin. I am unable to reproduce

**Comment by santoshmath** [comment]
Hi @mbj36 , This is the  regression issue  of reskin. This issue still exists. 
1. Create a group and activate it. Go to 'More' and click on 'Attach meeting'. provide the inputs and submit.
2. Once you attach meeting ,it will show on group page. Then if you go to 'More' on group page, 'Attach meeting' is still getting displayed. 
Check here. https://demo.openmf.org/newbeta/#/viewgroup/739. 
Meeting is already attached but in More 'Attach Meeting' is still displaying. 
This issue doesn't exist  for the  groups which are created and attached meeting on old skin.

**Comment by mbj36** [comment]
Agreed @santoshmath I found out the issue

**Comment by Anh3h** [comment]
Does this issue still persist?
I followed the step @santoshmath described but I don't see this issue

**Comment by santoshmath** [comment]
@Anh3h , this issue still exists. Try again. it's simple to notice or ping me on hangout

**Comment by Anh3h** [comment]
@santoshmath Have seen the issue. I will take up this issue

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 05/06/2017 on new_reskin release. This issue is fixed.
