### ISSUE TITLE
Reskin: Create Loan Product page displaying loan cycle parameters though 'Terms Vary Based on Loan Cycle' is unchecked. 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2047]
See the  screenshot from reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23652218/11fcda5a-034e-11e7-8a78-d31e010ade91.png)

Once you check 'Terms Vary Based on Loan Cycle' and uncheck again , loan  cycle parameters disappear as usual.

**Comment by iamsk9** [comment]
@santoshmath I would like to work on this. :100:

**Comment by santoshmath** [comment]
@iamsk9 , go ahead..

**Comment by iamsk9** [comment]
@santoshmath I created a pull request to this issue. Please view [#2074](https://github.com/openMF/community-app/pull/2074)

**Comment by mbj36** [comment]
@santoshmath restest and close it

**Comment by santoshmath** [comment]
Tested it on 13/3/2017 on new_reskin branch. This issue has been resolved.
