### ISSUE TITLE
Reskin: Prepay Loan page is not displaying all fields

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2048]
Go to any active loan account page and click on 'Prepay Loan' 

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23653674/6509c316-0353-11e7-8ffc-f9a516587721.png)

Without Reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23653691/6ff0b4d8-0353-11e7-9331-ac8609d947b7.png)

**Comment by botraunak** [comment]
@santoshmath, This is also related to #2052 
Need Someone to confirm.

**Comment by santoshmath** [comment]
@botraunak , Loan disbursement page(#2052) and Prepay loan page , both are different one.

**Comment by gkrishnan724** [comment]
@santoshmath  I believe this is fixed:
![screenshot from 2017-03-10 17-55-51](https://cloud.githubusercontent.com/assets/21004514/23795301/d82a9910-05ba-11e7-98cb-a70bd8cd0fe7.png)

**Comment by botraunak** [comment]
@santoshmath from the code point of view they were being handled in the same file. so fixing #2052 should have fixed these.

**Comment by mbj36** [comment]
Fixed
