### ISSUE TITLE
Reskin: Loan Foreclosure page is broken

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2050]
Go to any  loan account and click on 'Foreclosure' button. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/23654550/311cc036-0357-11e7-81cf-aa11a47846c6.png)

**Comment by botraunak** [comment]
@santoshmath I'll work on this!

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin. This issue  has been fixed.
