### ISSUE TITLE
Reskin: 'Make Repayment' page is not displaying all fields 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2051]
Go to any  loan account and click on 'Make Repayment' tab.

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23655037/73d04bb2-0359-11e7-8172-db18bb368078.png)

Without Reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/23655043/814e8b28-0359-11e7-97a4-c34a9f6ff13b.png)

**Comment by botraunak** [comment]
@santoshmath This is I guess related to #2052 , If @mbj36 can confirm.
Fixing #2052 will solve this 👍

**Comment by santoshmath** [comment]
@botraunak , loan disbursement page and make repayment page, both are different one.

**Comment by DanCarl857** [comment]
actually I think @botraunak is right. Don't know why fixing #2052 didn't solve this

**Comment by santoshmath** [comment]
@DanCarl857 ,Tested it on 9/3/2017 on new_reskin branch. This issue is resolved.
