### ISSUE TITLE
Reskin:Loan Disbursement page is not showing all fields

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2052]
Create a loan account for a client: Submit and approve it. and then click on 'Disburse' button:

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23655288/67ef9220-035a-11e7-90c0-bb9ab04f734a.png)

Without Reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/23655301/751ad98c-035a-11e7-81a0-a14c84f9919e.png)

Even 'Disburse to Savings' also not showing 'Transaction Amount'.

**Comment by botraunak** [comment]
@santoshmath I'll try working on this!

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin. This issue is resolved.
