### ISSUE TITLE
Reskin: 'More' Button is not working on the page after loan is approved.(Blue color)

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2053]
Create a loan:Submit and approve it and next page click on 'More' button. 

Similar Issues:
#1966  #2025

**Comment by gkrishnan724** [comment]
@santhoshmath can you guide me on how to reproduce this issue? thanks

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 8/3/2017 on new_reskin branch. This issue is fixed.
