### ISSUE TITLE
Reskin - big gap between "Create standing instructions at disbursement" and its checkbox in apply new loan

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2060]
At the form of applying a loan there is a big gap between the text "Create standing instructions at disbursement" and its checkbox, for quick look user might think there is no a checkbox attached

Create a loan product
Apply a loan to an active client and you will see this 

![reskin-checkbox](https://cloud.githubusercontent.com/assets/8160209/23695240/388a00b6-03ef-11e7-8b72-257aa9c96921.png)

**Comment by mbj36** [comment]
@MexinaD could you please fix and send PR ?

**Comment by MexinaD** [comment]
Okay @mbj36

**Comment by MexinaD** [comment]
Its PR: https://github.com/openMF/community-app/pull/2061

**Comment by santoshmath** [comment]
@MexinaD , @mbj36 , This issue is already rised here: https://github.com/openMF/community-app/issues/2002

**Comment by MexinaD** [comment]
Sure, i see its labeled gsoc, does that mean i can not fix it?

**Comment by santoshmath** [comment]
@MexinaD, go ahead. No issues.

**Comment by santoshmath** [comment]
@MexinaD , I am closing this issue as it's duplicate of #2002
