### ISSUE TITLE
Reskin: Duplicate field of "First repayment on" and "interest charged from" in loan application

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2062]
In loan application, the row that contain fields "First repayment on" and "interest charged from" is duplicated.

![duplicate field](https://cloud.githubusercontent.com/assets/8160209/23697343/7d94149a-03f8-11e7-87ed-fe8eaa31787f.png)

**Comment by DanCarl857** [comment]
Fixed

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 9/3/2017 on new_reskin branch and this issue is fixed.
