### ISSUE TITLE
Reskin: Approve/Reject navbar in check inbox & tasks, Affix not working.

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#2091]
If we scroll down, the Approve/Reject navbar should remain below the Mifos navbar. Also, If possible change all the icons to font-awesome icons so that they can load in localhost.

New Skin:
![abc](https://cloud.githubusercontent.com/assets/21004514/23867360/b27424e6-0841-11e7-8244-17c296bcb96b.png)

Old skin:
![abcd](https://cloud.githubusercontent.com/assets/21004514/23867380/beb404c4-0841-11e7-9a45-84c71014a26c.png)

**Comment by gkrishnan724** [comment]
I'm working on this :)

**Comment by santoshmath** [comment]
@gkrishnan724 , Are you able to resolve this issue?

**Comment by gkrishnan724** [comment]
@santoshmath I'm not able to resolve it, still looking at it.  However,  I don't mind if someone resolves and sends a PR

**Comment by gkrishnan724** [comment]
It seems the jquery code which is supposed to make the affix is not working:
```
$(window).scroll(function () {
                if ($(this).scrollTop() > 100) {
                    $('.head-affix').css({
                        "position": "fixed",
                        "top": "50px"
                    });

                } else {
                    $('.head-affix').css({
                        position: 'static'
                    });
                }
            });
```
I also noticed that the window scroll event is not firing properly, hence I tried to replace it by `angular.element($window).bind("scroll")` which also did not fire properly.
Another thing is, the scroll events worked on the login page but did not work when the view was loaded.

**Comment by santoshmath** [comment]
@mbj36, @gkrishnan724 ,  is it resolvable?

**Comment by Mastermaulik** [comment]
@gkrishnan724 @mbj36 ,please provide a status update on this

**Comment by mbj36** [comment]
@santoshmath Retest and close it

**Comment by santoshmath** [comment]
Tested it on 2/6/2017  on new_reskin branch. This issue is  fixed.
