### ISSUE TITLE
Reskin: Improper alignment of fields in New  Fixed Deposit(FD) application page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2092]
> Create any FD product
>Go to any client page and click on 'More' and click on New Fixed Deposit. On next page, select the FD Product.
Screenshot from reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23899328/b2db7f6c-08da-11e7-9463-8f754499c40a.png)

Screenshot without reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23899346/c2a7991c-08da-11e7-9ae7-2c6193e6efb3.png)

**Comment by gkrishnan724** [comment]
@santoshmath the PR I have sent will fix this issue too :)

**Comment by iamsk9** [comment]
@santoshmath I am on it.

**Comment by gkrishnan724** [comment]
Nevermind, my PR wont fix this one sorry

**Comment by iamsk9** [comment]
@santoshmath created PR for this issue. Please review #2100 

@gkrishnan724 Your PR won't fix it, but helpful. :) :+1:

**Comment by iamsk9** [comment]
@mbj36 Created a new PR for this issue #2107

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 16/3/2017 on new_reskin branch. This issue is fixed.
