### ISSUE TITLE
Reskin: Improper alignment of fields in New Recurring Deposit(RD) application page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2093]
>Create an RD Product.
>Go to any client's page and click on 'More' button and then click on 'New Recurring Deposit'
>Select the RD product from drop-down menu.

Reskin Screenshot:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23899533/8183a3e4-08db-11e7-9102-4fe3ef520d01.png)

Screenshot without reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23899541/8a386baa-08db-11e7-905f-860a46d0c24a.png)

**Comment by gkrishnan724** [comment]
@santoshmath  This will be fixed if my PR gets merged

**Comment by gkrishnan724** [comment]
![rd](https://cloud.githubusercontent.com/assets/21004514/23908687/b507ede6-08fa-11e7-8505-f1dd9d1c3c72.png)

**Comment by santoshmath** [comment]
@mbj36 , FYI

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 16/3/2017 on new_reskin branch, This issue is resolved.
