### ISSUE TITLE
Reskin: Checker Inbox and Tasks page is displaying  extra buttons

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2094]
On left navigation bar , click on Checker Inbox & Tasks

On reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/23900033/9d3df704-08dd-11e7-8197-91847a93c119.png)

Without Reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23900047/a9cbf2e6-08dd-11e7-9f51-234902f4ed4b.png)

**Comment by gkrishnan724** [comment]
@santoshmath I guess it is proper you sent the screenshot of client approval on the old skin not checker inbox. here is the old skin one:
![screenshot from 2017-03-14 18-40-45](https://cloud.githubusercontent.com/assets/21004514/23902077/cdb07bfc-08e5-11e7-89cd-81f2ddcd0f75.png)

Also, I have fixed the icons. I'll be sending a PR soon after I fix this issue: https://github.com/openMF/community-app/issues/2091
![screenshot from 2017-03-14 18-42-09](https://cloud.githubusercontent.com/assets/21004514/23902123/fed51a58-08e5-11e7-897d-88091185d3e6.png)

**Comment by santoshmath** [comment]
@gkrishnan724 , Yes. That's my mistake. At least those two buttons are blurred next to search text box. We will close this issue after resolving it. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/23934583/5994045a-096c-11e7-9dfb-1dd717bc695b.png)

**Comment by mbj36** [comment]
@santoshmath This is resolved

**Comment by santoshmath** [comment]
Tested it on 24/3/2017 on new_reskin branch. This issue is fixed.
