### ISSUE TITLE
Reskin:'More' button is not working in share account.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2095]
> Create any share product.
> Go to client page and click on 'New Share Account' 
>Submit, Approve and Activate it. 
During these all above stages, if you click on 'More' button, it is not displaying anything.

**Comment by anu-007** [comment]
@santoshmath I am on it.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
tested it on 16/3/2107 on new_reskin branch. This issue is fixed.
