### ISSUE TITLE
Reskin: Misalignment of fields after Modifying Savings Application

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2096]
> Create a saving product.
> Go to client and click on New Saving. Fill all the required details and submit. 
>On next page, click on Modify Application. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/23900840/b5bbf468-08e0-11e7-81d4-b773c7e0e5ce.png)

**Comment by gkrishnan724** [comment]
@santoshmath I'll send a PR asap

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 16/3/2017 on new_reskin branch. This issue is fixed.
