### ISSUE TITLE
 Designs should be same for New Loan/Saving/Share/FD/RD applications

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2097]
Currently on reskin, you can see different designs, placing of 'Cancel' buttons:

![reskin1](https://cloud.githubusercontent.com/assets/23022667/23901315/b1f42650-08e2-11e7-9bee-409a2f3d2e45.png)

![reskin2](https://cloud.githubusercontent.com/assets/23022667/23901318/b1fb8576-08e2-11e7-9d5d-1b6cff6f69c0.png)

![reskin3](https://cloud.githubusercontent.com/assets/23022667/23901316/b1fab86c-08e2-11e7-8e0b-58af3d8402f5.png)

![reskin4](https://cloud.githubusercontent.com/assets/23022667/23901317/b1fb718a-08e2-11e7-8f77-17e4739148c9.png)

![reskin5](https://cloud.githubusercontent.com/assets/23022667/23901319/b1fd6ecc-08e2-11e7-84f1-b532639eb667.png)

**Comment by anu-007** [comment]
@santoshmath I would like to work on this and i think we should align the cancel button centrally on all pages.

**Comment by santoshmath** [comment]
@anu-007 , I think it looks good if 'Cancel' button is just next to drop-down menu.

**Comment by anu-007** [comment]
@santoshmath agreed ,will send a PR shortly. thanks!!

**Comment by anu-007** [comment]
@santoshmath @mbj36 please review ( https://github.com/openMF/community-app/pull/2106 )

**Comment by santoshmath** [comment]
@mbj36, review PR and let me know

**Comment by mbj36** [comment]
PR is closed due to merge conflicts

**Comment by AkashBhave** [comment]
Which design out of the 5 should be used?

**Comment by AkashBhave** [comment]
@santoshmath @mbj36 This issue should be resolved with my pull request here: https://github.com/openMF/community-app/pull/2735
