### ISSUE TITLE
Reskin:XBRL page is missing  tabs

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2101]
>Click on 'Reports' tab then in drop-down menu click on XBRL.
Without reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/23934857/12a116b2-096e-11e7-937c-069ca5b47075.png)

With reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/23934864/2063fa26-096e-11e7-9e08-d3d0fe94fddd.png)

**Comment by iamsk9** [comment]
@santoshmath I am working on it.

**Comment by DanCarl857** [comment]
@santoshmath fixed this. Could you review:
![screen shot 2017-03-18 at 4 30 51 am](https://cloud.githubusercontent.com/assets/9010142/24068631/155f9176-0b94-11e7-9c8a-ec2482f01ee4.png)

**Comment by DanCarl857** [comment]
PR:  https://github.com/openMF/community-app/pull/2115

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/3/2017 on new_reskin branch. This issue is fixed.
