### ISSUE TITLE
Reskin: Drop-down menu of  'Add Charge' for Savings Account is showing invalid characters

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2102]
>Create any Saving product and any Savings Charge
>Go to client page, and click on 'New Saving'. Enter the inputs and submit it. 
>Click on 'Add Charge' and observe the drop-down menu.

![reskin](https://cloud.githubusercontent.com/assets/23022667/23935139/269ca5e4-0970-11e7-974c-ee8b3ac39e87.png)

Same thing happen even you try to add charge after approving the saving account and also adding Client Charge

**Comment by iamsk9** [comment]
@santoshmath I am working on it.

**Comment by iamsk9** [comment]
@santoshmath Created PR for this issue #2104. Please review it.

**Comment by santoshmath** [comment]
@mbj36 FYI

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/4/2017  on new_reskin branch. This issue is fixed.
