### ISSUE TITLE
Reskin: Actions to deselect the Advanced Accounting Rule is not showing while creating or editing the loan product

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2118]
Check the screenshot in demo instance:
![accc1](https://cloud.githubusercontent.com/assets/13551795/24101413/4fbb5688-0d89-11e7-9de1-e7e575f9a549.png)
Check the screenshot in reskin(newbeta) instance:
![acccc2](https://cloud.githubusercontent.com/assets/13551795/24101427/608d2900-0d89-11e7-857d-8cc4d28330f4.png)

**Comment by mbj36** [comment]
Hi Agnessy
This issue exists in more places in community app

Can you please find those and provide a checklist here :) ?

**Comment by Agnessy** [comment]
ok @mbj36

**Comment by Agnessy** [comment]
@mbj36 The same applies to Saving, Fixed and Reccuring Products.

**Comment by mbj36** [comment]
You can create checklist here where it's missing

**Comment by santoshmath** [comment]
Hi @Agnessy , @mbj36 , I have created checklist here: https://github.com/openMF/community-app/issues/2126

**Comment by santoshmath** [comment]
Hi @Agnessy , I've added this issue to the checklist #2126. I am closing it here.
