### ISSUE TITLE
Reskin: Standing instruction Destination field issue

### ISSUE THREAD

**Issue by fboniphace** [openMF/community-app#2122]
Hellow there,
I've experienced an issue during creating standing instruction where by  when the  **destination** field is selected as **own account** and the form is submitted. It always appear as  **With in Bank** when viewing that standing instruction. consider the screenshots bellow.
![11](https://cloud.githubusercontent.com/assets/20817569/24106676/abac9618-0d99-11e7-86a6-12882b89a241.jpg)

![12](https://cloud.githubusercontent.com/assets/20817569/24106669/a5aa578c-0d99-11e7-85d8-6e252ba59523.PNG)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/3/2017 at new_reskin branch. This issue is resolved.
