### ISSUE TITLE
Reskin:Tabs are missing in client's savings account page 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2124]
>Create a saving product(Admin>products) and create a saving account and activate it for a client. Then go to client's savings account page:
In reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/24138210/5ec95c88-0e3d-11e7-81ca-149eafe7286c.png)

without reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/24138225/68cf4620-0e3d-11e7-96dc-90a3cf362a39.png)

**Comment by MegaAlex** [comment]
I would like to work on this.

**Comment by dart-wakar** [comment]
I have created a pull request #2125

**Comment by santoshmath** [comment]
@mbj36, check the pull request and let me know

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/3/2017 at new_reskin branch. This issue is resolved.
