### ISSUE TITLE
Reskin: Deselect Issues in multiple areas

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2126]
I noticed that if you add some parameter from drop-down menu(Ex: Charge) , After adding you cannot remove it because 'Deselct' (x) button is missing. I am creating Checklist here. 

- [x] Create a loan product and add charge in product level and try to remove charge.

- [x] Create a saving product and add charge in product level and try to remove charge.

- [x] Create a loan application for a client/group , add charge in loan application level and try to remove the charge

- [x] Create a JLG loan applicaton for a client(First create a group and create a client for the group and got to group page and click on JLG loan application), add charge in loan application level and try to remove it.

- [x] Create a saving application for a client/group , add charge in savings application level and try to remove the charge.

- [x] Create a share product and add charge in product level and try to remove the charge.

- [x]  Create a share account for a client and add charge and try to remove it.

- [x] Create a Fixed Deposit Product , add charge in product level and try to remove it.

- [x] Create a Recurring  Deposit Product, add charge in product level and try to remove it.

- [x] Create a Fixed Deposit Application for a client, add charge in application level and try to remove it.

- [x] Create a RD application for a client, add charge in application level and try to remove it. 

- [x] Create a Center Savings Application, add charge in application level and try to remove it. 

- [x] Actions to deselect the Advanced Accounting Rule is not showing while creating or editing the loan product. Check the screenshots.
Without Reskin:
![1](https://cloud.githubusercontent.com/assets/23022667/24183911/16aef35e-0ef1-11e7-9fe0-bc48a0d453c2.png)

With Reskin:
![2](https://cloud.githubusercontent.com/assets/23022667/24183916/1f5f84a0-0ef1-11e7-97a6-f2071bc6dbe1.png)

- [x] Go to Admin>>Products>>Manage Tax Configurations>>Manage Tax Groups and click on Create Tax Group
On next page, click on 'Add' button.

Without Reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/24188635/28378eee-0f08-11e7-96ee-24519770916e.png)

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/24188643/3204a7e0-0f08-11e7-8a4f-24135f781382.png)

- [x]  Go to Admin>System>Manage Data tables , then click on Create Data table. Then add column by providing name and column type and then try to deselect it.

Without reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/24199428/7da47c9e-0f2f-11e7-91ea-ee0b76cbcf6a.png)

With reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/24199441/892b0b8c-0f2f-11e7-971a-eba9a1086353.png)

**Comment by santoshmath** [comment]
Hi All, if you find any deselect issues in other areas of application ,  please let me know so that we can add it to the checklist.

**Comment by Agnessy** [comment]
Hi @santoshmath 
Create Tax Group, on adding Tax component try to remove it

**Comment by santoshmath** [comment]
@Agnessy , I updated the same.

**Comment by Agnessy** [comment]
@santoshmath , Add column when creating data table, try to remove it

**Comment by DanCarl857** [comment]
@santoshmath let me work on this

**Comment by santoshmath** [comment]
@Agnessy I updated for datatable too!! Thanks for helping. :)

**Comment by Agnessy** [comment]
@santoshmath Create hook, add an event, try to remove it
                         Add/Edit Currency Configuration, try to remove it

**Comment by mbj36** [comment]
@santoshmath I have created PR every cases of deselect button in whole community app, now there won't be any issue of deselect, please retest and close it

**Comment by santoshmath** [comment]
Very good work @mbj36 . I tested all above checklist and they have been resolved. We will keep this open for next 3-4 days, in case if we find this issue in other pages. If we close now and if this issue reappears again we may have to create again another new issue rather than adding checklist here.

**Comment by Agnessy** [comment]
Hi @mbj36 @santoshmath 
Have you resolve in floating rates also? when adding Floating Rate Periods

**Comment by mbj36** [comment]
Can you check @santoshmath in your local machine?  It must be fixed

**Comment by santoshmath** [comment]
@Agnessy , @mbj36 , Floating Rate Period can also be deselected. Tested it on locally.

**Comment by Agnessy** [comment]
Ok Thanks @santoshmath @mbj36

**Comment by mbj36** [comment]
Let's close this @santoshmath

**Comment by santoshmath** [comment]
As no more new issues noticed related to 'deselect' problem, This issue will be considered as fixed. If anyone notices related to it, please let me know.
