### ISSUE TITLE
Reskin: Viewing standing instruction buttons not shown clearly

### ISSUE THREAD

**Issue by fboniphace** [openMF/community-app#2127]
Halow there,
I've also noticed that during viewing a standing instruction, a view and delete buttons are not shown clearly. Consider a screen-shot bellow
![screenshot from 2017-03-22 11-42-36_li](https://cloud.githubusercontent.com/assets/20817569/24190180/db2792a2-0ef8-11e7-9bcd-ebfa3d0c4ee5.jpg)

**Comment by dart-wakar** [comment]
I created a pull request #2128

**Comment by santoshmath** [comment]
@mbj36 test  #2128  PR.

**Comment by mbj36** [comment]
PR is closed due to failing tests

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/4/2017 on new_reskin branch. This issue is resolved.
