### ISSUE TITLE
Reskin:Icons are missing for tabs(Ex: New Loan, New savings, etc) on client's page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2130]
With Reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/24232886/1c534508-0fb4-11e7-84a6-a82db8747fb5.png)

Without Reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/24232892/297b7fa2-0fb4-11e7-86a6-974053add20d.png)

**Comment by syylabs** [comment]
Working on this. Will send the PR soon.

**Comment by ThisuraThejith** [comment]
Working on this. Will send the PR soon.

**Comment by ThisuraThejith** [comment]
PR sent at https://github.com/openMF/community-app/pull/2137

**Comment by ThisuraThejith** [comment]
New PR sent at https://github.com/openMF/community-app/pull/2149

**Comment by santoshmath** [comment]
Tested it on new_reskin branch. This issue is resolved.
