### ISSUE TITLE
Reskin: Upload client image and signature are not working

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2131]
- [x] Go to any client's page and click on 'More' and then click on 'Upload client signature'. Select the file(any image) and then click on 'Upload' button. The 'Upload' button is not working. 

- [x] Go to any client's page and at the right side  click on 'Upload client image'. Select the file(any image) and then click on 'Upload' button. The 'Upload' button is not working.

![reskin](https://cloud.githubusercontent.com/assets/23022667/24233066/a7c5536e-0fb5-11e7-870f-c9cef3fb52c0.png)

- [x] Go to any client's page and at the right side  click on 'Capture client image'. Then click on capture button. The capture button is not working. Probably 'Upload' button too. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/24233166/71f921e2-0fb6-11e7-8b91-e8c44066f07c.png)

**Comment by santoshmath** [comment]
@mbj36 , did you check the PR for this?

**Comment by santoshmath** [comment]
@mbj36:    @MegaAlex  , Is your commit addressing all three issues mentioned in description?

**Comment by MegaAlex** [comment]
@santoshmath , Yes, the three issues are fixed in my commit.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/4/2017 on new_reskin branch. This issue is resolved.
