### ISSUE TITLE
Reskin: Unable to Add Notes on Client's page 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2132]
Go to any Client's page and click on 'Notes' . Type something and then click on 'Add' button. Add button is not working. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/24233263/1ca521b8-0fb7-11e7-9b37-20afc6d265ff.png)

**Comment by mbj36** [comment]
@MegaAlex Can you look at this ?

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 24/3/2017  on new_reskin branch. This issue is fixed.
