### ISSUE TITLE
Fixed Deposit Product: Period/Amount range must end as open for interest rate chart error on submitting 

### ISSUE THREAD

**Issue by dmiepub** [openMF/community-app#2141]
We are getting error on creating Fixed Deposit Product. Please suggest how to resolve this:

Period/Amount range must end as open for interest rate chart
[168-interest-rate-chart.pdf](https://github.com/openMF/community-app/files/867515/168-interest-rate-chart.pdf)

**Comment by santoshmath** [comment]
Hi @dmiepub , you have to '+add' one more row for period/range if you want to mention 'To' for both period and amount range.
