### ISSUE TITLE
Reskin&oldSkin: Make datatable tabs in viewclient, viewgroup and viewcenter look organised

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#2160]
If we have a lot of datatables for a client, group or center, the tabs in the respective pages look messy:

Eg: viewclient page
![cluster](https://cloud.githubusercontent.com/assets/21004514/24830150/d6b055a8-1c9d-11e7-8a70-1eb59dd4aab9.png)

We can replace these datatable tabs to a responsive sliding menu similar to http://www.bootply.com/QhA0MPMKtI

@edcable  @mbj36  @pranjal-goswami  @gauravsaini03

**Comment by gkrishnan724** [comment]
I'll be working on this

**Comment by mbj36** [comment]
@santoshmath This is a great feature implemented by @gkrishnan724 , Please have a look, retest and close it

**Comment by santoshmath** [comment]
Tested it. This improvement really working fine.
