### ISSUE TITLE
Reskin: Description in Interest Rate Chart is not shown in FD and RD

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2161]
Description in Interest Rate Chart is not shown , when viewing both fixed and Recurring Deposit accounts.
![interest rate chart](https://cloud.githubusercontent.com/assets/13551795/24899313/89a0a094-1ea8-11e7-91d9-9e2827cc472e.png)

**Comment by DanCarl857** [comment]
Hi @Agnessy could you please explain how to reproduce this so I can work on it?

**Comment by Agnessy** [comment]
@DanCarl857 When you view the specific FD or RD the description are not shown/retrieved
but when view/edit interest rate chart of that product , it shows description 
![irc](https://cloud.githubusercontent.com/assets/13551795/24945716/0a2bf130-1f69-11e7-9af0-419889a3f776.png)
You can open the link https://demo.openmf.org/newbeta/#/viewrecurringdepositproduct/17

**Comment by DanCarl857** [comment]
Ok thats not what I meant but ok. Please what I mean is when creating an issue its good to put the process so someone can easily reproduce it. Let me look into the issue

**Comment by santoshmath** [comment]
Steps to reproduce:

>Go to Admin>Products>Fixed Deposit Products(or Recurring Deposit Products) 

>Create a Fixed Deposit Product with entering all necessary values and submit it.

>Try to view Summary page of Fixed Deposit Product(or Recurring Deposit Product)

Without Reskin:(Ex: Fixed Deposit Product)

![demo](https://cloud.githubusercontent.com/assets/23022667/24992997/ec245270-2041-11e7-866e-ef43a8641c52.png)

With Reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/24993003/f7c72b7a-2041-11e7-9df0-3e516e991af1.png)

**Comment by DanCarl857** [comment]
https://github.com/openMF/community-app/pull/2220

**Comment by Mastermaulik** [comment]
@mbj36 Please look into this issue

**Comment by gkrishnan724** [comment]
Sent PR,  this issue exists in old skin too..

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed related to description.
