### ISSUE TITLE
Reskin - After assigning loan officer, the label should be "Change loan officer"

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2162]
1. Create a loan product: Admin -> Product -> Loan Product ->Create
2. Apply a loan to an active client: Clients -> View client -> New Loan 
3. Fill all the necessary fields including the "loan officer" and then submit.
When you view the loan profile, navigate to "More" you will find the label for "Assign loan officer", it should be "Change loan officer"

![loanofficerassign1](https://cloud.githubusercontent.com/assets/8160209/24999554/9ea8f168-2046-11e7-816b-5eae53c4806f.png)

Also when you approve the loan, view the loan profile. The label "Assign loan officer" also it should be "Change loan officer"

![loanofficerassign](https://cloud.githubusercontent.com/assets/8160209/24999611/e3becc32-2046-11e7-85b9-1d37616289d9.png)

**Comment by santoshmath** [comment]
@MexinaD , This issue is not just related to reskin, but community-app overall.

**Comment by MexinaD** [comment]
@santoshmath  so someone has to work on it under develop or new_reskin branch?

**Comment by santoshmath** [comment]
@MexinaD , sorry for delayed reply. I think it's better to work on new_reskin branch

**Comment by gkrishnan724** [comment]
@santoshmath I have sent a PR for this https://github.com/openMF/community-app/pull/2253

**Comment by santoshmath** [comment]
@mbj36, check the PR #2253 and let me know.

**Comment by mbj36** [comment]
When the loan is approved, it still shows the Assign loan officer , please have a look

**Comment by gkrishnan724** [comment]
@santoshmath I have a question here, when we click on change loan officer, should we also record the unassigned date of the previously assigned loan officer?

**Comment by santoshmath** [comment]
@gkrishnan724 , No. It's all about label. If no loan officer assigned, the label should be 'Assign Loan Officer'. If loan officer already assigned and want to change, then label should be 'Change Loan Officer'.

**Comment by gkrishnan724** [comment]
I am asking this because, when a loan is approved and a loan officer is assigned previously, there is no option to assign the loan officer again since you have to unassign the previously assigned loan officer. Then only an option comes

**Comment by gkrishnan724** [comment]
I don't see anything in the user manual for being able to change the loan officer. I think this is a bug, since the option of assigning loan officer should not be there when the previous loan officer is not unassigned, what do you think? This scenario however, is working fine when the loan is approved ( There is no button to assign loan officer because loan officer is already assigned ) see the screenshot:
![assign](https://cloud.githubusercontent.com/assets/21004514/26569191/cedaff8e-4526-11e7-99b5-70b1448783d5.png)

@santoshmath @MexinaD.

**Comment by santoshmath** [comment]
@gkrishnan724 , check the following screenshot. After Loan is 'Approved'(or even after 'Submitted', you can see it on 'More') with assigned loan officer, you can see the label 'Assign Loan Officer'. All we need is the label 'Change Loan Officer' in this case. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/26569299/68f68c6e-4527-11e7-8858-61f7b79cf1cc.png)


In your example , it is the case of after loan is 'Disbursed'. At that time, it is not necessary. :)

**Comment by gkrishnan724** [comment]
Oh okay! Thanks, I understood the problem :)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
