### ISSUE TITLE
Reskin - Page to add datatable entry shows it from Manage Hooks

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2163]
1. Create a datatable and associate it with either client/group/center/loan : Admin -> System -> Manage Data tables -> Create Datatables
2. Go to the where you associated the datatable (i.e group) and view one of the active group : Clients -> Groups -> View group
3. Navigate to the datatable you created.
The page shows it from "System -> Manage Hooks" 

![datatables](https://cloud.githubusercontent.com/assets/8160209/25006680/8efdf694-2066-11e7-86a0-622166e377a5.png)

**Comment by wmay1991** [comment]
Is this in the JIRA?

**Comment by skprabhanjan** [comment]
Hey @santoshmath , I am not able to figure out where is this bug in new_reskin, Can you please help me figure it out so that I can resolve this issue. I am not able to reproduce this bug in my localhost.
Thanks:)

**Comment by MexinaD** [comment]
@wmay1991 no, this issue is raised here

**Comment by MexinaD** [comment]
@skprabhanjan  have you tried to follow the steps given in the demo to see if you can reproduce it?

**Comment by skprabhanjan** [comment]
@MexinaD , First I tried creating a datatable as mentioned in first step but failed to do it, So I tried to search for some datatable entry that already existed and had this bug, but I am not able to find out where and how(The second step, this is not fully clear) , Can you please help me on this and let me know as I am trying to solve this.
Thanks:)

**Comment by santoshmath** [comment]
@skprabhanjan it's just breadcrumb issue.

**Comment by skprabhanjan** [comment]
@santoshmath , I dont have much knowledge on this flow(Maybe it has many connected things I am missing).
Im trying to understand it, Can you please let me know how can I reproduce this issue .?
Thanks:)

**Comment by santoshmath** [comment]
send me contact request on skype santoshmath99

**Comment by skprabhanjan** [comment]
Hey @MexinaD and @santoshmath , I have fixed this issue and sent a PR #2183 , Here is a screenshot of how it looks now, Please clarify if its okay.
Thanks:)

![screen shot 2017-04-27 at 6 37 59 pm](https://cloud.githubusercontent.com/assets/17094832/25485080/258a1fa2-2b7a-11e7-8efd-8d085eba97ee.png)

**Comment by mbj36** [comment]
@santoshmath
