### ISSUE TITLE
Reskin - In Office and  Saving account profiles, no tab to show the data tables created

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2164]
1. Create a datatable and associate to office or saving account : Admin -> System -> Manage Datatables -> Create Datatable.
2, Go to the profile of an office or a saving account : 
For office : Admin -> Organization -> Manage Offices -> View any active office

**In  reskin**
![reskinoffice](https://cloud.githubusercontent.com/assets/8160209/25007679/e9f68950-2069-11e7-9097-51dac8392308.png)

**In community-app**
![communityoffice](https://cloud.githubusercontent.com/assets/8160209/25007697/fc5806aa-2069-11e7-86d8-1a407e4ed7c7.png)

For Saving account : Clients -> View an active client who has a saving account -> View a saving account

**In reskin**
![reskinsaving](https://cloud.githubusercontent.com/assets/8160209/25007717/10bfc074-206a-11e7-94f9-50855bec939d.png)

**In community-app**
![communtysaving](https://cloud.githubusercontent.com/assets/8160209/25007731/1ee4ab4c-206a-11e7-961c-5e3a3486514f.png)

**Comment by Anh3h** [comment]
Will like to take up the issue

**Comment by skprabhanjan** [comment]
@MexinaD , Is this issue still open.? If its open then I would try to fix it. Please clarify:)

**Comment by MexinaD** [comment]
@skprabhanjan , i don't know if the PR provided above is already reviewed but i know it hasn't been merged yet. @santoshmath  might help to answer that

**Comment by skprabhanjan** [comment]
@MexinaD , Thanks:)
@santoshmath , so shall I work on this issue or is it fixed.?

**Comment by santoshmath** [comment]
@mbj36 , let us know whether this issue is fixed in the latest PR. Otherwise let @skprabhanjan work on this.

**Comment by Anh3h** [comment]
i left a PR and @mbj36 and mohit requested some changes which i already implemented. Nethertheless i this that PR won't be valid again. So I will just check out again an do a clean PR.
thanks :)

**Comment by Anh3h** [comment]
I made a new clean PR. here is a link please check it out: https://github.com/openMF/community-app/pull/2189

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on  5/4/2017 on new_reskin branch and this issue is resolved.
