### ISSUE TITLE
Reskin: Buttons are blurred in view guarantors screen. 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2166]
1. Submit any loan for a client. 
2. Before Approval, go to More>Create Guarantor. Select existing client and fill required details & Submit it.
3. Then again go to More>view guarantor. 
4. On view guarantors page,

Without Reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/25263803/cf986404-267f-11e7-90e2-7094b19e30e8.png)

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/25263807/dae8c970-267f-11e7-977a-f52690315883.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 4/5/2017 on new_reskin branch and this issue is resolved.
