### ISSUE TITLE
Reskin:Misalignment in Interest Rate Chart 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2171]
Create Fixed Deposit product > View/Edit Interest Rate Chart > Create Interest Rate chart
radio button of "Is primary grouping by Amount*" is not well aligned
**Without Reskin**
![demo-irc1](https://cloud.githubusercontent.com/assets/13551795/25274435/b57768f4-2698-11e7-97c4-9b42e718b756.png)
![demo-irc2-](https://cloud.githubusercontent.com/assets/13551795/25274442/bb5c7e8a-2698-11e7-95bb-f15edcd94305.png)

**With Reskin**
![irc- 2017-04-21 11-27-14](https://cloud.githubusercontent.com/assets/13551795/25271068/89df04f2-268b-11e7-9941-c849997c3cc9.png)
![ircc-2017-04-21 12-13-48](https://cloud.githubusercontent.com/assets/13551795/25274402/8d4b6cea-2698-11e7-8d92-c218fc696182.png)
Same applies to Recurring deposit product,

**Comment by wmay1991** [comment]
I can take a look into this

**Comment by wmay1991** [comment]
I checkout the new_reskin branch and I am not seeing the same thing.

![image](https://cloud.githubusercontent.com/assets/12055979/25345863/0d935578-28e4-11e7-9ca3-308e1f995b65.png)

**Comment by wmay1991** [comment]
This is what I for Recurring Deposit Products.
![image](https://cloud.githubusercontent.com/assets/12055979/25345951/463fe06c-28e4-11e7-854d-5c0a54ab7264.png)

**Comment by MexinaD** [comment]
@wmay1991 you took the screenshot form develop branch and not form new_reskin branch

**Comment by wmay1991** [comment]
I pulled down new_reskin and looking into it

**Comment by santoshmath** [comment]
@mbj36 , plese review PR by @MexinaD

**Comment by mbj36** [comment]
@Anh3h Can you take it ? There are multiple alignment issues in edit interest rate and interest rate page. Ping me if you have any problem

**Comment by Anh3h** [comment]
sure

**Comment by Anh3h** [comment]
Sure

**Comment by mbj36** [comment]
Fixed
