### ISSUE TITLE
Reskin: In Prepay Loan page breadcrumb, It should be 'Prepay Loan' in stead of Repayment

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2175]
> Go to any client and click on Any active loan account and then click on the tab  'Prepay Loan' :

![reskin](https://cloud.githubusercontent.com/assets/23022667/25325065/0f1727fa-28e7-11e7-9e49-2abc49e25524.png)

**Comment by MexinaD** [comment]
I will try to work on this

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 4/5/2017 on new_reskin branch. This issue is fixed.
