### ISSUE TITLE
Reskin: Clicking on 'View Client'  in uploading documents for a client navigates to a wrong page.

### ISSUE THREAD

**Issue by skprabhanjan** [openMF/community-app#2184]
@santoshmath and @MexinaD, in uploading document page of a client, clicking the breadcrumb 'View Client' takes to an empty page, as the link it goes to is not correct.
Take a look here - https://demo.openmf.org#/addclientdocument/16

Attached the screenshot below( look at bottom left corner for url it goes to when clicked on 'view client')
Please clarify the issue, I will fix it as soon as it is clarified.
Thanks:)

![screen shot 2017-04-27 at 6 56 09 pm](https://cloud.githubusercontent.com/assets/17094832/25485471/ae3cb0a2-2b7b-11e7-8352-6bd626d3b21a.png)

**Comment by santoshmath** [comment]
@skprabhanjan , issue exists. Go ahead and fix it. :)

**Comment by skprabhanjan** [comment]
@santoshmath and @mbj36 , Its fixed , sent a PR #2185 , Please review:)
Thanks.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested  it on 4/5/2017 on new_reskin branch. This issue is resolved.
