### ISSUE TITLE
Reskin: In Create Group page, hovering mouse on 'x'(remove client) shows 'create group'

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2187]
1. Go to Groups and click on '+Create Group'.
2. Enter the inputs and add one or two clients
3. After adding , when you hover mouse on 'x' button('remove client from group' button) it is displaying 'Create Group' in stead of 'Remove Client'. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/25515581/2992cbe2-2c03-11e7-8ee4-29e40c3d387d.png)

**Comment by skprabhanjan** [comment]
@santoshmath , It exists for all the buttons , 'Add', 'Cancel','Submit' and 'x', I have fixed all of these and sent a PR #2188 , Please verify.
Thanks:)

**Comment by santoshmath** [comment]
@skprabhanjan Thank you.

**Comment by Anh3h** [comment]
Will like to take up this issue

**Comment by santoshmath** [comment]
@mbj36 , have you reviewed the PR of @Anh3h ?

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested in on new_reskin branch. This issue is resolved.
