### ISSUE TITLE
Installment fee per loan outstanding not available

### ISSUE THREAD

**Issue by makeraset** [openMF/community-app#2192]
Current practice in Cambodia we separate accrued income as two:

**1. Accrued interest receivable (AIR)**
I=PxR/360xN
I: Interest
P: Loan outstanding
R: Annual interest rate
N: Number of day
Action: Do loan classification per aging, No provision on AIR
**2. Accrued fee receivable (AFR)**
F: PxR/360xN
F: Installment fee per outstanding
P: Loan outstanding
R: Annual fee rate
N: Number of day
Action: Don't do loan classification but have provision on AFR and Due Amount(P+I+F) for schedule repayment "Equal Installments" keep equal for each installments.

So, Can we add Installment fee per outstanding in to Mifos?
Thanks,

**Comment by santoshmath** [comment]
@makeraset , will you add this question here: http://mifos.cloud.answerhub.com/index.html  ??

**Comment by santoshmath** [comment]
This is doubt/query rather than issue. Closing it.
