### ISSUE TITLE
Reskin&oldSkin: Wrong error when you run individual collection sheet which has no repayment at the specified date

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2193]
1. In the navigation bar, click "Individual collection sheet"
2. Select any branch, then fill any date that you know there is no repayment of any client at that date
3. Click the "collection sheet" button 
The error given is for collection sheet of groups and not individual collection sheet.

![collectionsheet](https://cloud.githubusercontent.com/assets/8160209/25697669/821189be-30c4-11e7-87ce-dbf5c8530876.png)

When you run the collection sheet
![collectionsheet1](https://cloud.githubusercontent.com/assets/8160209/25697671/866d0cf4-30c4-11e7-8116-b46fad55086e.png)

**Comment by DanCarl857** [comment]
PR: https://github.com/openMF/community-app/pull/2238

**Comment by mbj36** [comment]
@santoshmath retest and close it
