### ISSUE TITLE
Reskin: In Create charge page, "Charge Time Type" drop-down is displaying improper wordings.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2194]
Go to Admin>Products>Charges and click on "Create Charge"  and click on drop-down of the label 'Charge time type".

Reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/25699421/ba551efa-30e0-11e7-8838-fd9ddcd7e97c.png)

without Reskin: 

![demo](https://cloud.githubusercontent.com/assets/23022667/25699432/c4597d88-30e0-11e7-99cf-d22fb77e9e9b.png)

**Comment by wmay1991** [comment]
I can take a look at this.

**Comment by wmay1991** [comment]
I just did a PR for this.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 16/5/2017  on new_reskin  branch and this issue is resolved.
