### ISSUE TITLE
Reskin: "Open Saving Account" shouldn't  be shown on  Client's Edit  page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2195]
"Open Saving Account" should  be shown only  while client's create page and not on client's edit  page.

![reskin](https://cloud.githubusercontent.com/assets/23022667/25700436/6191c73c-30e5-11e7-8db4-8b1d4bcf7766.png)

**Comment by wmay1991** [comment]
I can look into this.

**Comment by wmay1991** [comment]
Create a PR for this

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested  it on 16/5/2017 on new_reskin branch. This issue is fixed.
