### ISSUE TITLE
Reskin: View Journal Entry Button is missing for each transaction in Transaction tab. 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2196]
1. Disburse a loan for a client.
2. In loan account , click on Transactions tab
3.  At the end of each  transaction , there should be a 'View Journal Entry'  button. 

Without reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/25701222/138e464c-30e9-11e7-8179-96a297946fe3.png)

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/25701230/20fede4a-30e9-11e7-91d7-65bffa48886f.png)

**Comment by Anh3h** [comment]
I will to work on this please

**Comment by mbj36** [comment]
@santoshmath  retest and close it

**Comment by santoshmath** [comment]
Tested it on 2/6/2017 on new_reskin branch. This issue is  fixed.
