### ISSUE TITLE
Reskin: 'View Receipt' is blurred when you hover mouse on any transaction in Transaction tab

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2197]
1. Disburse a loan for a client.
2. In loan account , click on Transactions tab
3. Hover mouse on any transaction and try to click on View receipt button.
>You can click on 'View Receipt' button, but it is blurred.

Without reskin:
![demo](https://cloud.githubusercontent.com/assets/23022667/25701412/ece21fea-30e9-11e7-89f5-a04730541750.png)

With Reskin:
![reskin](https://cloud.githubusercontent.com/assets/23022667/25701425/f6175134-30e9-11e7-88ad-10e100217895.png)

**Comment by dklamar** [comment]
I'll work on this

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 2/6/2017 and this issue  is resolved
