### ISSUE TITLE
Reskin: Upload loan  document is not working.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2202]
1.Go to any  client and click on the loan account. And then click on loan documents.
2. Then click 'Upload' button. Provide name, choose file and click 'Submit' button.
>Submit button is not working. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/25734264/ccb50dfa-317e-11e7-9830-e1e32752d287.png)

**Comment by mbj36** [comment]
@gkrishnan724

**Comment by gkrishnan724** [comment]
I'll take a look at this

**Comment by Anh3h** [comment]
@gkrishnan724 are you still looking into this issue?
If not I will like to look into it :)

**Comment by mbj36** [comment]
Go ahead @Anh3h

**Comment by gkrishnan724** [comment]
@Anh3h Go Ahead, If you find the problem please resolve it in these pages too:
-Upload Client Image
-Upload Client Signature
-Upload Client Documents

I guess all of them have the same problem :)

**Comment by Anh3h** [comment]
yea.
I managed to fix one of the issue which was the file not uploading properly. I will send the PR but the also exist a 500 error. So I think that should be a fineract issue

**Comment by gkrishnan724** [comment]
Yeah, I guess its a server side error It's not working in the old-skin either.

**Comment by santoshmath** [comment]
@gkrishnan724 , uploading loan document is working in old skin. But I am not sure why it's not working on demo instance. It's working on UAT instance and also latest code from apache/develop branch

**Comment by gkrishnan724** [comment]
Yeah It is working, my bad I just checked it on localhost now.

**Comment by Anh3h** [comment]
@santoshmath On my localhost it doesn't work 
![osl](https://cloud.githubusercontent.com/assets/20562458/26672018/7b499e36-46af-11e7-9d8b-b600ad91b80a.png)

Same in the demo instance
![osd](https://cloud.githubusercontent.com/assets/20562458/26672027/86ee2cc0-46af-11e7-8b42-d3a72c99d2a7.png)

**Comment by gkrishnan724** [comment]
Well, it does not work when the API URL is `demo.openmf.org` but it works when you have the platform locally installed. 
Old Skin (Working):
![desktop-animation](https://cloud.githubusercontent.com/assets/21004514/26676763/cbb7622c-46e6-11e7-8fb7-9f7b1f2fa7d7.gif)

**Comment by gkrishnan724** [comment]
But the same platform in new skin is not working: So this may be a client side issue I guess 
![reskin](https://cloud.githubusercontent.com/assets/21004514/26676788/e3b638c6-46e6-11e7-899a-359cc9638924.gif)

**Comment by MegaAlex** [comment]
Document and Image upload should be working on the demo instance now. S3 storage was enabled & not configured properly.

**Comment by mbj36** [comment]
@santoshmath  retest and close it

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
