### ISSUE TITLE
Reskin:Submit button not working when editing product mix

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2203]
Go to Products > Product Mix> Add 
after submitting , try to edit

**Comment by santoshmath** [comment]
Hi @Agnessy , I am unable to reproduce the issue. I am able  to add  product  mix and also I can edit and submit it. Did you check with latest code from new_reskin branch?

**Comment by mbj36** [comment]
@santoshmath Could you confirm the above issue ?

**Comment by santoshmath** [comment]
@Agnessy , I am not sure. Let's keep this issue open then.

**Comment by santoshmath** [comment]
Tested it on 17/5/2017 on new_reskin branch. This issue is resolved.
