### ISSUE TITLE
Reskin - Can not fetch all names when creating guarantor which is existing client

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2206]
1. Create a client and apply a loan
2. View the loan and in the "more" button select "create guarantor"
On filling the name of the client in the field of "name" with "Existing client" selected, other names are not fetched.
At https://demo.openmf.org/newbeta/ i tested with client "Aisha Hammad"
![fetchname](https://cloud.githubusercontent.com/assets/8160209/25793888/2c554400-33d7-11e7-9d34-0c9329940faa.png)

![fetchname1](https://cloud.githubusercontent.com/assets/8160209/25793894/307e231c-33d7-11e7-9465-7da059a6e894.png)

**Comment by Mastermaulik** [comment]
@botraunak Please look into this issue

**Comment by santoshmath** [comment]
@MexinaD , I am closing this as it's already reported here: #1868
