### ISSUE TITLE
Reskin - When the loan is overpaid, in the profile of the client it has a link for disburse

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2207]
1. Apply a loan to an active client
2. Approve, Disburse and make repayment by amount greater than the loan
In the profile of a client, the loan which is overpaid has a link to "disburse" instead of having a link to "transfer funds"

![overpayment](https://cloud.githubusercontent.com/assets/8160209/25795253/3d16879e-33dd-11e7-9e41-bbf5f46fa84a.png)

![overpay](https://cloud.githubusercontent.com/assets/8160209/25795257/400e0f94-33dd-11e7-87c8-b3d19a1e1b5b.png)

**Comment by gkrishnan724** [comment]
@MexinaD @santoshmath I can remove the disburse button if the loan is overpaid. but should I also include a button for transfer funds? I just want to know, if a loan is overpaid would there be always an option to transfer funds? and I guess the permissions would be same as `DISBURSE_LOAN`

**Comment by gkrishnan724** [comment]
@santoshmath I have created a PR #2255

**Comment by santoshmath** [comment]
@mbj36 FYI

**Comment by Mastermaulik** [comment]
@mbj36 Please look into this PR

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
