### ISSUE TITLE
Reskin: Edit Center page is not showing proper labels

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2208]
Go to Center, Create a center then click edit
Without Reskin

![cntr2](https://cloud.githubusercontent.com/assets/13551795/25795596/bc102ca2-33de-11e7-93c3-12aa4b959cd8.png)
With Reskin
![cntr3](https://cloud.githubusercontent.com/assets/13551795/25796587/bc4aa6a8-33e2-11e7-8eaf-17caf2acfd0c.png)

**Comment by Anh3h** [comment]
Will look into this please

**Comment by Mastermaulik** [comment]
@Anh3h , please look into this matter and provide a status update

**Comment by mbj36** [comment]
This issue is resolved
