### ISSUE TITLE
Reskin&oldSkin: Improper Label on  Create Client Page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2210]
Please Check the screenshot. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/25836684/732e10ee-34a6-11e7-9130-53c63979bcb6.png)

**Comment by DanCarl857** [comment]
PR: https://github.com/openMF/community-app/pull/2214

**Comment by MexinaD** [comment]
I couldn't find this in the latest new_reskin branch

**Comment by santoshmath** [comment]
@MexinaD ,  it  is  part of  next release. I tested it locally in my machine and found it.  Related issue: 
https://issues.apache.org/jira/browse/FINERACT-228

**Comment by MexinaD** [comment]
Okay @santoshmath

**Comment by DanCarl857** [comment]
@MexinaD you don't even see that label in the branch. So the fix adds it if its not there or fixes the label if its there. @santoshmath please take a look at the fix

**Comment by santoshmath** [comment]
@mbj36 , FYI

**Comment by mbj36** [comment]
@santoshmath Is this issue exists in old skin ? I don't see any label box in new_reskin , please be more clear about the issue

**Comment by santoshmath** [comment]
@mbj36, this bug is related to new feature and this new feature is available with next release. @DanCarl857 said in previous comment that his fix would resolve this bug after the release. That's why i told you to verify it.  :)

**Comment by mbj36** [comment]
@santoshmath Retest and close it
