### ISSUE TITLE
In 'Edit Report page', Report type is not properly aligned. 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2219]
Go to Admin>System>Manage Reports. And select any report and click on Edit button.

Without Reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/25885973/0bf8ab0e-3579-11e7-8a7e-5bbcb0de1205.png)

With Reskin:

![reskin](https://cloud.githubusercontent.com/assets/23022667/25885976/165a8464-3579-11e7-97a0-9f7e1620a474.png)

**Comment by sed8908** [comment]
I'd be happy to take a look at this.

**Comment by mdew192837** [comment]
I seem to have fixed it, will make pull request when Travis is up and running.

I committed on this branch. https://github.com/mdew192837/community-app/tree/2219EditReport

Screenshot is attached:
![screen shot 2017-05-14 at 9 46 38 pm](https://cloud.githubusercontent.com/assets/6820349/26041587/946eb9c4-38f3-11e7-9e1b-754f268f06f1.jpg)

**Comment by santoshmath** [comment]
@mbj36, FYI

**Comment by mdew192837** [comment]
Update: The proper fix is https://github.com/mdew192837/community-app/tree/Fix2219. Commit 53d4281

**Comment by santoshmath** [comment]
@mbj36, FYI

**Comment by mbj36** [comment]
@santoshmath retest and close it
