### ISSUE TITLE
Reskin - The transactions are not recorded when you write-off and when you recover the repayment

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2223]
1. In active loan, view the loan and go to More
2. Write-off the whole loan amount

In reskined
![writeoff](https://cloud.githubusercontent.com/assets/8160209/25943809/d1b6f596-3649-11e7-9edf-97f179694efe.png)

In community-app
![writeoff1](https://cloud.githubusercontent.com/assets/8160209/25943829/deb1611e-3649-11e7-9f89-71693c47e7c6.png)

And after write-off, when you recover the repayment
In reskin
![recovery](https://cloud.githubusercontent.com/assets/8160209/25943885/0b30ec64-364a-11e7-9c3e-04ce357a2a00.png)

In community-app
![recovery1](https://cloud.githubusercontent.com/assets/8160209/25943899/1624aeb2-364a-11e7-99a7-43c1ad9d9413.png)

**Comment by Mastermaulik** [comment]
@gkrishnan724 Please look into this

**Comment by gkrishnan724** [comment]
PR #2267

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
