### ISSUE TITLE
Reskin:"Edit Share Product" page is showing "Create Share Product"  heading

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2247]
Go to Admin>Products>Share Products>Create Share Product
After submit, try to edit it. 
"Edit Share Product" page is showing "Create Share Product"  heading, instead of Edit Share Product 
![sp](https://cloud.githubusercontent.com/assets/13551795/26145439/13a12be8-3af5-11e7-81dd-2277b6b8207e.png)
This issue exists in old skin and also in reskin.

**Comment by MexinaD** [comment]
Will work on this in new_reskin

**Comment by Anh3h** [comment]
Will look at this :)

**Comment by Anh3h** [comment]
@Mastermaulik PR looks good

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
