### ISSUE TITLE
Report: Loan Provision Report Enhancement	

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2254]
https://mifosforge.jira.com/browse/MIFOSX-2643(see attachments in this link)

Can the table report in the community-app be make in such a way that when you click on provision category it then shows all the loans with the following details:
Loan Acc #, No. of days overdue, Loan Balance, Overdue Balance, Interest, Amount

**Comment by bharathcgowda** [comment]
this is more of a new feature request.. we can use tableau or any other software for drill-down reports.. instead of building it on Mifos

**Comment by bharathcgowda** [comment]
closing this issue after discussing with Ed.
