### ISSUE TITLE
Jobs Scheduler UI improvement using Progress Bar

### ISSUE THREAD

**Issue by Ippezrobert** [openMF/community-app#2261]
Currently, in the community-app, if you want to know if all selected jobs have been run, you need to refresh to see if status is running or not. This is not sometimes frustrating since as an admin, i need to run all jobs daily before doing closing entry (Closing books of accounts) in a way that its kind of hard to know if jobs are completed. So its better we introduce progress bar to show status. https://mifosforge.jira.com/browse/MIFOSX-2703
We can use JQuery - https://jqueryui.com/progressbar
See attachment for mock-up!

![image](https://cloud.githubusercontent.com/assets/13125234/26574917/e6c38fc6-452b-11e7-8433-7c285b30ff83.png)

**Comment by gkrishnan724** [comment]
https://github.com/openMF/community-app/issues/1861 @Ippezrobert this is duplicated, an issue is already created.
