### ISSUE TITLE
Reskin: In Add Journal Entry, the additional tabs for debit and credit accounts are large than the first tab.

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2287]
Navigate to Accounting -> Add Journal Entry
Click the "+" sign in front of Debit label and Credit label, the additional tabs exceed the original tab.

In Reskin
![addjournalentry](https://user-images.githubusercontent.com/8160209/26879378-8612ce70-4b99-11e7-9c64-65c01312305d.png)

In community-app
![addjournalentry1](https://user-images.githubusercontent.com/8160209/26879388-90345e64-4b99-11e7-84a1-c07b641d2722.png)

**Comment by mbj36** [comment]
Fixed
