### ISSUE TITLE
Reskin: The button doesn't show directing of tags in Accounting Rule

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2292]
Navigate to Accounting -> Accounting Rule -> Add Rule 
After filling the neccessary field, select "List of accounts" in both sides, the buttons of the right handside doesn't shoe the direction of the movement of the tags.

In Reskin
![accrulearrow2](https://user-images.githubusercontent.com/8160209/26970412-f9197ee0-4d11-11e7-9356-f24a4786a381.png)

In community-app
![accrulearrow3](https://user-images.githubusercontent.com/8160209/26970419-01505aa2-4d12-11e7-9b94-364d9978683a.png)

Also in edit page of accounting rules
Navigate to Accounting -> Accounting Rule ->View a rule and "Edit"
When you select "List of accounts" in both sides, the buttons to move the tags doesn't show direction

In Reskin
![accrulearrow](https://user-images.githubusercontent.com/8160209/26970433-17f1e60e-4d12-11e7-9826-22f97b68041e.png)

In community-app
![accrulearrow1](https://user-images.githubusercontent.com/8160209/26970444-1f15a1aa-4d12-11e7-9bd8-895da633b7d4.png)

**Comment by MexinaD** [comment]
Fixed at #2294

**Comment by santoshmath** [comment]
@mbj36 FYI

**Comment by mbj36** [comment]
Fixed
