### ISSUE TITLE
Reskin: Buttons for shifting role to be selected doesn't show direction in edit page

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2296]
Navigate to Admin -. Users 
 View any user and then "Edit", the buttons to shift roles between available roles and selected roles doesn't show direction.

In Reskin 
![userarrow](https://user-images.githubusercontent.com/8160209/26976649-68557c6c-4d2d-11e7-859f-77ed5f6fb832.png)

In community-app
![userarrow1](https://user-images.githubusercontent.com/8160209/26976674-89557d18-4d2d-11e7-8c48-557dedeed646.png)

**Comment by santoshmath** [comment]
@mbj36 , FYI.

**Comment by mbj36** [comment]
Fixed
