### ISSUE TITLE
Reskin: Not Allowing to Reject 'view checker inbox' when create or edit user

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2303]
Admin > user >create user
after submit ,,  "Waiting For Checker Approval" then click details
then Reject,, when confirming  nothing happen
![reject](https://user-images.githubusercontent.com/13551795/27077414-aec73042-5038-11e7-8645-dc47d83ecb99.png)
can any one please look at it and  let me know if I am  wrong somewhere.

**Comment by gkrishnan724** [comment]
@Agnessy This is a valid issue Fixed it in the PR

**Comment by santoshmath** [comment]
@mbj36 , @Mastermaulik , FYI

**Comment by mbj36** [comment]
Fixed
