### ISSUE TITLE
When maker checker enabled, the popup to change the password doesn't disappear after you submit.

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2305]
1. Enable maker checker Admin -> System -> Configurations -> Enable maker checker
2. Create a user and fill all necessary fields and submit Admin -> User -> New User
3. Then go and view a user.
4. Click "change password" and fill the new password.
When you submit, the background change to detail page but the popup doesn't disappear
![submit](https://user-images.githubusercontent.com/8160209/27080931-cabe76b2-5046-11e7-83f7-a606eeb88f69.png)

**Comment by MYKatz** [comment]
@MexinaD I wasn't able to reproduce this issue.  Could you please double-check to make sure it still exists?

**Comment by MexinaD** [comment]
@MYKatz  This issue has already been fixed though i don't see any PR refered to it

**Comment by edcable** [comment]
Closed as fixed.
