### ISSUE TITLE
Reskin&Oldskin : Not understandable error when "Link savings" is blank during loan application

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2308]
1. Apply a loan to an active client Client -> View client -> New Loan
2. Fill all necessary fields and select "Create Standing Instruction at Disbursement" while you leave "Link savings" blank
The error thrown is not clear to a normal user

In Reskin
![savinglink](https://user-images.githubusercontent.com/8160209/27133564-3ec26a08-511b-11e7-85b3-88bb8823b810.png)

In community-app
![savinglink1](https://user-images.githubusercontent.com/8160209/27133572-46a7ee78-511b-11e7-8a58-c6eff765bc75.png)

**Comment by MexinaD** [comment]
Fixed

**Comment by santoshmath** [comment]
@Mastermaulik , FYI.
