### ISSUE TITLE
Reskin: Buttons in blue action bar on client page extend to second row

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2325]
The actions/buttons in the blue action bar on the client page extend to a second row even when the screen is maximized. See it compared to the original skin.

These should only be on one row. If we can't accommodate them on one blue action bar, we can move some of the actions to the more menu. +New Share Account and Transfer Client could be moved to More as they're not that common of tasks. 

![screen shot 2017-06-21 at 9 04 32 am](https://user-images.githubusercontent.com/823454/27394535-63a06fdc-5661-11e7-8f45-75eda263dd03.png)
![screen shot 2017-06-21 at 9 07 12 am](https://user-images.githubusercontent.com/823454/27394534-639d0f18-5661-11e7-966c-902d4c389b33.png)
Second point of feedback - is there a reason why these are independent buttons, in that they have whitespace between them. Originally they were supposed to just be a blue action bar.

**Comment by mbj36** [comment]
Okay @edcable i will have a look

**Comment by gkrishnan724** [comment]
Moved the `new share account` button to more:

This looks better?

![ckuebt](https://user-images.githubusercontent.com/21004514/27424689-90d895d6-5753-11e7-8ded-384174895c90.png)

**Comment by mbj36** [comment]
@edcable Can you please review the screenshot ? If you want any more changes
