### ISSUE TITLE
Reskin:Delete icon doesn't display for Charge Overview 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2328]
View the specific client > Charge overview > Go to specific charge
Action - delete button/icon doesn't display 
Without Reskin
![charge-1](https://user-images.githubusercontent.com/13551795/27471666-2f4e2c78-5801-11e7-8134-ccd4261c2421.png)
With Reskin
![charge-2](https://user-images.githubusercontent.com/13551795/27471707-588d136a-5801-11e7-894c-76cd9a6117fc.png)

**Comment by mbj36** [comment]
@MexinaD

**Comment by MexinaD** [comment]
@mbj36 Yes, i can work on this

**Comment by MexinaD** [comment]
@mbj36 also the delete-icon in the button of delete is not shown, should i solve it in the same PR?
in reskin
![deletecharge1](https://user-images.githubusercontent.com/8160209/27472866-bdc8635c-5805-11e7-88c4-e24b9e4a3e42.png)

in community-app
![deletecharge](https://user-images.githubusercontent.com/8160209/27472875-c6d06bca-5805-11e7-8877-7d85a82d8045.png)

**Comment by mbj36** [comment]
Yes

**Comment by MexinaD** [comment]
@mbj36  Solved, check it

**Comment by MexinaD** [comment]
@mbj36  i see this issue is fixed on the new release, i guess it can be closed now

**Comment by MexinaD** [comment]
@santoshmath you can test it first on your end

**Comment by santoshmath** [comment]
#Fixed.
