### ISSUE TITLE
Reskin: Client Share Account Overview is not well aligned

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2329]
Client > Share Account Overview.
Without Reskin

![share1](https://user-images.githubusercontent.com/13551795/27472486-378288e6-5804-11e7-9a40-0cf6e3e00c82.png)

With Reskin

![share-2](https://user-images.githubusercontent.com/13551795/27472514-4ff70bea-5804-11e7-86bc-a93245b0566f.png)

**Comment by mbj36** [comment]
This work is in TODO list for the app enhancements. So closing this
