### ISSUE TITLE
Reskin: The deleted transactions in charge overview doesn't show they are deleted

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2331]
1. Create a charge product with charge applies to "Client"... Admin -> Products -> Charge -> Create
2. Apply that charge to an active client
3. Pay half of the charge and then view the charge
4. On the transactions there is a button for delete the transaction, click to delete
After deletion, on reskin, it doesn't show that the transaction is deleted

In reskin
![deletetrans](https://user-images.githubusercontent.com/8160209/27476975-6b59e9a2-5813-11e7-89eb-587006f8f6ec.png)

In community-app
![deletetrans1](https://user-images.githubusercontent.com/8160209/27476979-6f201cdc-5813-11e7-8622-5663ceab3058.png)

**Comment by santoshmath** [comment]
@mbj36 FYI

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Hi @MexinaD , 
-If client charge is created and nothing is paid, that charge can be deleted.
-If client charge is created and only partial payment is done, the charge is not allowed to be deleted.
-If client charge is created and full payment is done at required due date, the charge gets closed.

All above 3 scenarios are working fine. So, closing this issue.
