### ISSUE TITLE
Description field should be non-mandatory in create RD/FD product

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2335]
Go to Admin>products and then either Recurring Deposit Products(RD) or Fixed Deposit(FD) products. 
Click on  'Create Fixed Deposit product'  or  'Create Recurring Deposit product'

After furnishing all the details, There is a field 'Description' which is mandatory. It should not be mandatory. 

![fd](https://user-images.githubusercontent.com/23022667/33251168-414620c2-d35b-11e7-8189-ab9d32334053.png)

**Comment by gkrishnan724** [comment]
Hi @santoshmath I have fixed this in my Wizard Implementation. I will reference this issue in the PR
