### ISSUE TITLE
After creating Savings account for client 'More' button is moving to next line

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2341]
It is because of one more label 'Update Default Savings'(check screenshot). If no savings account for client, 'More' button will be aligned in first line:
![more_alignement](https://user-images.githubusercontent.com/23022667/27683743-be383cac-5ce4-11e7-8279-90337a4efcdc.png)

**Comment by gkrishnan724** [comment]
@santoshmath  https://github.com/openMF/community-app/issues/2325. I believe it will be solved in this issue:
![image](https://user-images.githubusercontent.com/21004514/27684052-e806dc0e-5ce5-11e7-9fd2-d9d6af8ecbf2.png)
