### ISSUE TITLE
Reskin: New Bulk JLG Loan application  dropdown for Loan product not populating

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#2344]
New Skin:
![loan](https://user-images.githubusercontent.com/21004514/27761417-22d92424-5e79-11e7-83a8-43e4b04107be.png)

Old Skin:
![loan2](https://user-images.githubusercontent.com/21004514/27761420-24939a24-5e79-11e7-9e74-06e416edb393.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
This issues is fixed on new reskin branch.
