### ISSUE TITLE
Improvement Issues in Savings Account Overview of a Client

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2346]
1. In stead of INR , Currency symbol should be used for 'Current Balance' and 'Available Balance'(Check Screenshot)

![rupeesymbol](https://user-images.githubusercontent.com/23022667/27779712-7a5e6938-5fe2-11e7-9151-1f9e8f7caffb.png)

2. External Id and Currency Fields are missing in Savings Account Overview:
Old Skin:
![demo](https://user-images.githubusercontent.com/23022667/27779824-0a77804a-5fe3-11e7-95ff-2384a9f527bb.png)
Reskin:
![reskin](https://user-images.githubusercontent.com/23022667/27779836-14e7b0a4-5fe3-11e7-918a-fff763f8e663.png)

**Comment by santoshmath** [comment]
Related Pull Request: https://github.com/openMF/community-app/pull/2333

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Hi @mbj36 make it, for example, $ 400 rather than 400 $ :). Anyhow, not major issue, reducing it's priority rather than closing it.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on new reskin branch. This issue is fixed.
