### ISSUE TITLE
FD & RD account overview should show currency symbol rather than INR or USD

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2347]
Check the screenshot:

![reskin](https://user-images.githubusercontent.com/23022667/27780083-8bcf30ba-5fe4-11e7-9ebd-7f272c3923c5.png)

**Comment by santoshmath** [comment]
Related Pull Request: #2333

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Hi @mbj36 make it, for example, $ 400 rather than 400 $ :). Anyhow, not major issue, reducing it's priority rather than closing it.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on new reskin branch. This issue is resolved.
