### ISSUE TITLE
Some of the fields missing in FD account overview.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2348]
Check the screenshot:

old skin:
![demo](https://user-images.githubusercontent.com/23022667/27780463-aff5c8a8-5fe6-11e7-8d22-13b95165d3e3.png)

Reskin:
![reskin](https://user-images.githubusercontent.com/23022667/27780469-b70da764-5fe6-11e7-9ea1-7dc12fabd559.png)

**Comment by santoshmath** [comment]
Related Pull Request: #2333

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on new_reskin branch. This issue is resolved.
