### ISSUE TITLE
Summary of RD account is showing no values

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2349]
Check the screenshot: 

![reskin](https://user-images.githubusercontent.com/23022667/27780647-cc107230-5fe7-11e7-8c08-ad5855d8f99a.png)

**Comment by santoshmath** [comment]
Related Pull Request: #2333

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on new_reskin branch. This issue is resolved.

**Comment by santoshmath** [comment]
Hi @mbj36 make it, for example, $ 400 rather than 400 $ :).   Anyhow, not major issue, reducing it's priority rather than closing it.
