### ISSUE TITLE
Reskin: Unable to Create Loan Product and even not throwing any error

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2353]
Create a loan product with following simple configuration
Loan product name: lp1
Short name :	lp1
Currency:	US Dollar
Decimal Places :	2
Currency in Multiples Of	0

Terms
Terms vary based on loan cycle :	false
Principal:	10,000   ( Min: , Max : )
Number of Repayments:	12   ( Min: , Max:)
Repay Every:	1  Months
Nominal Interest Rate:	1   ( Min: , Max:)  Per month
Minimum days between disbursal and first repayment date	

Settings
Amortization;	Equal installments
Interest Method:	Flat
Interest Calculation Period:Daily
Arrears Tolerance	
Repayment Strategy	Penalties, Fees, Interest, Principal order

Days in year	Actual
Days in month	Actual

Recalculate Interest	No

Guarantee Requirements
Place Guarantee Funds On-Hold?	No

Loan Tranche Details
Enable Multiple Disbursals	false.
---------
>This is simple loan product which  I am unable to create. This blocker is due to recent merges.

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on new reskin branch. This issue is fixed.
