### ISSUE TITLE
Reskin: In 'Create Loan Product' page, multi-disbursal details are getting displayed though it is not checked.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2355]
Go to Admin>Products> Create Loan Product.
Scroll down or search for 'Enable Multiple Disbursals' 

![multi-tranche](https://user-images.githubusercontent.com/23022667/27863320-402eaeaa-61a7-11e7-80db-81eaeb0e1edf.png)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on new reskin branch. This issue is fixed.
