### ISSUE TITLE
Reskin: In new loan application 'Submit' and 'Cancel' button are not within the boundaries

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2367]
Go to any client and click on 'New Loan' and then select the loan product and scroll down  and observe the alignment of 'Cancel' and 'Submit' button.

Old Skin:
![newloanapplication_oldskin](https://user-images.githubusercontent.com/23022667/28237584-604a75b4-6960-11e7-8c30-d726e91e4b67.png)

Reskin:

![newloan_application_reskin](https://user-images.githubusercontent.com/23022667/28237585-68268278-6960-11e7-9082-d47a9c2d8644.png)

**Comment by mbj36** [comment]
@santoshmath can you retest and close it

**Comment by santoshmath** [comment]
Tested it on develop branch. This issue is fixed.
