### ISSUE TITLE
Reskin: All pentaho reports are not working

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2368]
Check the sample screenshot of client listing report:

![screenshot from 2017-07-17 17-40-22](https://user-images.githubusercontent.com/23022667/28267303-1dad9264-6b17-11e7-9bf5-8c3ef1603bdc.png)
![screenshot from 2017-07-17 17-40-37](https://user-images.githubusercontent.com/23022667/28267304-1db22e8c-6b17-11e7-85af-553327b2d318.png)

**Comment by mbj36** [comment]
@santoshmath Now pentaho reports are running but the red error bar is still showing up. You can test this issue and create another minor issue of just red bar showing up.

**Comment by santoshmath** [comment]
Tested it on develop branch. This issue is fixed. Waiting for staging server is updated with this fix and retest there before closing it.

**Comment by santoshmath** [comment]
Tested it on staging. This issue is resolved.
