### ISSUE TITLE
 Create Client or Loan template is not proper and not properly aligned.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2373]
In Demo:
![demo](https://user-images.githubusercontent.com/23022667/28303895-f6a4bb74-6bb2-11e7-9c0e-e04e1b39cdca.png)

In Reskin:
![reskin](https://user-images.githubusercontent.com/23022667/28303905-feefb7e8-6bb2-11e7-83b2-17058ab8507c.png)
![reskin1](https://user-images.githubusercontent.com/23022667/28303904-feca58c2-6bb2-11e7-98da-b54538fd89c3.png)

**Comment by anweshknayak** [comment]
@santoshmath can I take this up ?

**Comment by mbj36** [comment]
Go ahead. This issue exist in develop brsnch

**Comment by anweshknayak** [comment]
![screenshot from 2017-07-20 00 07 03](https://user-images.githubusercontent.com/8139783/28383749-e25663f6-6cdf-11e7-8a89-33964e30e617.png)

@mbj36 is this good ?

**Comment by mbj36** [comment]
No. It should be like https://demo.openmf.org/#/createtemplate

**Comment by anweshknayak** [comment]
@mbj36 can you tell from which branch it is hosted ?

**Comment by mbj36** [comment]
Develop_oldskin

**Comment by abhaychawla** [comment]
@mbj36 @gkrishnan724 Is the issue still open? Can I work on it?

**Comment by gkrishnan724** [comment]
Go ahead @abhaychawla

**Comment by abhaychawla** [comment]
Okay!
