### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2377]
npm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2-ext@0.0.6 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2-ext@0.0.6 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs2-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs2-ext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs2-ext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anwesh/gsoc/community-app/npm-debug.log

**Comment by anweshknayak** [comment]
cc @santoshmath @mbj36

**Comment by mbj36** [comment]
Fork the repo, clone it and inside community app folder just run three steps 
npm install
bower install
grunt serve
