### ISSUE TITLE
While Editing Client 'Select Saving Product'  option is displaying 

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2406]
'Select Saving Product'  option should  be  displayed only  while creating  client but  not editing client. Even now, we try to add saving product in editing client it doesn't  work. 

![screenshot from 2017-07-25 17-16-48](https://user-images.githubusercontent.com/23022667/28570816-7b302eb4-715d-11e7-9bd3-65937aa9fd41.png)

**Comment by gkrishnan724** [comment]
I believe this has been fixed

**Comment by mbj36** [comment]
@gkrishnan724 I have asked @santoshmath to test this. he will test and close it

**Comment by santoshmath** [comment]
this issue is fixed.
