### ISSUE TITLE
Meeting Details Entries are getting duplicated when you take new JLG loan application for the client

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2410]
This issue is not always reproducible but in certain cases this issue is reproducible.

Check the screenshot:

![jlgapplication](https://user-images.githubusercontent.com/23022667/28704255-00c0a31c-7387-11e7-99fb-78ee2cc61e47.png)

You can check it here on demo server:

https://demo.openmf.org/#/newindividualjlgloanaccount/113/274

**Comment by santoshmath** [comment]
@mbj36 , Just found that this issue was duplicate of #2016, raised on March 6.  Closing the #2016 and keeping this open.

**Comment by santoshconflux** [comment]
Not able to reproduce in recent version.
