### ISSUE TITLE
Need a Notes Field in Savings Deposit and Withdrawal page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2414]
There is no Notes Field while making deposits and withdrawals for savings account. We can see the same for Loan repayments page:

![loanrepayment](https://user-images.githubusercontent.com/23022667/28811031-714f2682-76aa-11e7-86c3-4ec766e3f1bd.png)

Notes Field should be added for both deposit and savings filed.

**Comment by edcable** [comment]
@gkrishnan724 When you get a chance to complete this fix, we have some more community members requesting it.

**Comment by gkrishnan724** [comment]
@edcable @santoshmath  This needs to be implemented in the back-end first, the platform does not support sending a notes field. CC: @nazeer1100126

**Comment by santoshmath** [comment]
@gkrishnan724 , This issue is raised at back end side https://issues.apache.org/jira/browse/FINERACT-241 and @Ippezrobert has been working on it.(See the comment section)

**Comment by ShruthiRajaram** [comment]
@santoshconflux  it looks like @Ippezrobert  has developed this feature. Kindly test
