### ISSUE TITLE
 Ability to edit and delete a note from Notes in client profile

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2419]
For now you can only add a note but after that you can not edit or delete it.
If it happens you want to correct the note you wrote, you will have to write another to correct the previous
![notes](https://user-images.githubusercontent.com/8160209/29277124-74e8e192-8119-11e7-850d-c3ca17a8f62f.png)

It is better to have edit and delete functionality

**Comment by gkrishnan724** [comment]
@Mexina I'll work on this

**Comment by santoshmath** [comment]
@gkrishnan724 , let me know whether it requires fix at Fineract side as well?

**Comment by gkrishnan724** [comment]
@santoshmath No, I had a look at it. The API for deleting and updating is available. This just needs to be done in the front-end side

**Comment by MYKatz** [comment]
Hi, I fixed this a little while back: https://github.com/openMF/community-app/pull/2641
