### ISSUE TITLE
The Payment type has a mandatory sign but it allow to submit when it is empty

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2423]
1. Apply a loan to an active client: Client -> New Loan -> submit and approve it
2. There should be no payment types under Admin -> Organization -> Payment Type
3. Click Disburse
4. Fill all the required fields, payment type will have empty drop down
![paymenttype](https://user-images.githubusercontent.com/8160209/29324173-e442cd78-81eb-11e7-9497-710ddea7ce04.png)

When you submit, it will submit successfully while the field is mandatory

**Comment by gkrishnan724** [comment]
@MexinaD should the paymentType be a mandatory field?

**Comment by MexinaD** [comment]
@gkrishnan724  I think not necessary

**Comment by Agnessy** [comment]
@MexinaD @gkrishnan724 @santoshmath @edcable 
I think this also exist when depositing in Recurring Deposit Account.  
![dee](https://user-images.githubusercontent.com/13551795/32159968-c3ea08ec-bd60-11e7-85eb-4c0c8194d424.png)
