### ISSUE TITLE
Ability to delete an employee

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2432]
For now when you create an employee through navigating Admin -> Organization -> Manage Employees
The employee is created and there is only the option to edit him/her.
What if an employee leave the organization? there should be also the button to delete him.
![employee](https://user-images.githubusercontent.com/8160209/29650298-d908212a-88a2-11e7-9727-cca7fb3bca57.png)

This should be after s/he unassigned to all activities in the system.

**Comment by santoshmath** [comment]
@mbj36 , @MexinaD , I think this issue requires to be resolved first at fineract side?

**Comment by MexinaD** [comment]
@santoshmath You are right

**Comment by santoshmath** [comment]
It's Finearct side related issue: https://issues.apache.org/jira/browse/FINERACT-494

**Comment by mbj36** [comment]
If it's fineract side, then shouldn't it be closed here ? @santoshmath

**Comment by MexinaD** [comment]
@mbj36 i think it can still be open as after i developed in fineract side, it will have to be developed in community app for user to be able to use the feature

**Comment by aks681** [comment]
If the backend is resolved, can I take up this issue? Looking for a good first contribution.

**Comment by awasum** [comment]
We should have a disable or deactivate button instead of delete. Finance data is sensitive and should never be deleted even if for a non actual financial case like this. What do you think?
