### ISSUE TITLE
Make 1st Jan of current year - Default Minimum date value in all datepicker

### ISSUE THREAD

**Issue by Ippezrobert** [openMF/community-app#2435]
Make 1st Jan of current year - Default Minimum date value in all datepicker and set today's date the max date

**Comment by santoshmath** [comment]
@Ippezrobert , How about dealing with future date pickers like holildays?

**Comment by Ippezrobert** [comment]
@santoshmath , I mean default Min date especially for transactions when books for previous FY has been closed. I think future dates are handled by max

Example

input type="text" datepicker-pop="dd MMMM yyyy"  is-open="opened3" min="minDate" max="'maxDate'" class="form-control"

Where minDate = '01 January 2017' for this year

**Comment by Stevenjin8** [comment]
Where are the datepickers?

**Comment by santoshmath** [comment]
@Ippezrobert , Will you reply  to @Stevenjin8 ?

**Comment by Stevenjin8** [comment]
I have the code

`$(document).ready(function() {
    $(function() {
        var d = new Date();
        var y = new Date(d.getFullYear(), 0, 1, 0, 0, 0, 0);
        $( "#datepicker" ).datepicker({ 
            changeYear: true,
            defaultDate: y,
            maxDate: d,
        });
    });
});`

I'm just not sure where to put it. I can't seem to find where `$(element).datepicker()` is run

**Comment by Stevenjin8** [comment]
oops wrong code 
`$(document).ready(function() {
    $(function() {
        var d = new Date();
        var y = new Date(d.getFullYear(), 0, 1, 0, 0, 0, 0);
        $( "#datepicker" ).datepicker({ 
            changeYear: true,
            minDate: y,
            maxDate: d,
        });
    });
});`

**Comment by santoshmath** [comment]
@gkrishnan724 , @mbj36 , FYI
