### ISSUE TITLE
Can not Undo Approval Share Account after adding Note

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2439]
Go to Client >> Apply share Account >> Approve >> Undo Approval
Without adding Note it submit successfully
After adding Note it throw error
![share-new](https://user-images.githubusercontent.com/13551795/29829484-3f860734-8ce8-11e7-97d8-a60bc14d2d4d.png)

**Comment by gkrishnan724** [comment]
@Agnessy  @santoshmath  I believe there is no support in the platform for adding a note while performing undo approval. However, I wanted to know whether we really need notes for this action since I am not able to find these notes available in the UI.

**Comment by santoshmath** [comment]
@mbj36 , @Mastermaulik , Will you confirm so that I can create this issue at Fineract side as well?

**Comment by santoshconflux** [comment]
Fixed. Notes field is removed while undoing approval.
