### ISSUE TITLE
Indian Rupee Currency  Symbol is not displaying properly in Loan Account overview and savings account overview

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2440]
Check the following Screenshots.

Savings Account:

![currencysymbol](https://user-images.githubusercontent.com/23022667/29859717-10ff692a-8d81-11e7-9028-c8a44c1509a8.png)

Loan Account:

![currcysymbol](https://user-images.githubusercontent.com/23022667/29859726-197795f0-8d81-11e7-89c6-3be7a1f1647a.png)

**Comment by luckyman000786** [comment]
@edcable @mbj36 @santoshmath This issue is not only in the community app but also in android client and self service app also and this Currency Symbol is coming from API request, so I think it should be solved in Apache Fineract.

**Comment by santoshmath** [comment]
@mbj36 , can you confirm this issue must be raised and fineract  side as well?

**Comment by luckyman000786** [comment]
@santoshmath @edcable @mbj36 I have raised this issue on the fineract side.

**Comment by santoshmath** [comment]
Can you share the fineract side issue link here and this issue link there?

**Comment by luckyman000786** [comment]
@santoshmath Here it is - [https://issues.apache.org/jira/browse/FINERACT-547](url)

**Comment by edcable** [comment]
Closed as no longer valid. Fineract issue has been closed and I couldn't repro in Community App.
