### ISSUE TITLE
Asterisk is missing in the field of creation of Share Product to show mandatory field

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2441]
1.During the creation of Share Product the form is not submitted without filling **Shares per Client**
2.When editing Share Product, if you remove **Shares per Client** ,there is a thrown error when submitting the form
![share](https://user-images.githubusercontent.com/13551795/29872220-49d8558e-8d97-11e7-8787-4bca982bc352.png)

**Comment by gkrishnan724** [comment]
@Agnessy While creating, Default Shares per client field is mandatory. However, when we are editing and removing it. all the minimum and maximum and default fields are mandatory
