### ISSUE TITLE
Share to be issued field doesn't show it is mandatory

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2444]
Create a share product: Admin -> Product -> Share Product -> Create
but don't fill the field for "share to be issued"
![sharetoissue](https://user-images.githubusercontent.com/8160209/29879311-6525943a-8dad-11e7-9fc4-c5d482e13fd3.png)

It will not submit but also it doesn't give any error
It is the same when you edit the page and empty that field

**Comment by anand1248** [comment]
Is this issue already taken up or may I work on this one?
