### ISSUE TITLE
Ability to delete Market Price periods in Share Product

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2445]
Go to Product >> Create Share Account >> Add Market Price Periods >> Submit 
Edit Share Product >> Remove Market Price Periods ..Submit
![market](https://user-images.githubusercontent.com/13551795/29909515-f037b086-8e2e-11e7-813b-55174e81319a.png)
When editing, Market Price periods can be removed but after submitting they are still there
And if you reedit again the deleted one are still there

**Comment by gkrishnan724** [comment]
@santoshmath @Agnessy please report this to the fineract side. I have checked this issue and the form is submitted to the platform correctly. The market price period is deleted while submitting but it seems that the platform is not deleting it.

**Comment by santoshconflux** [comment]
Backend ticket: https://issues.apache.org/jira/browse/FINERACT-680

**Comment by ShruthiRajaram** [comment]
@santoshconflux  kindly close this issue. The fix is available in https://github.com/apache/fineract/pull/503
