### ISSUE TITLE
Fixed Deposit Product should allow future End date

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2446]
Go to Product >> Create Fixed Deposit Product >> 
You can not set the future **End Date**
   
![fixed depo](https://user-images.githubusercontent.com/13551795/29910878-63bafa90-8e34-11e7-8b32-4f5687c365fd.png)

**Comment by mdew192837** [comment]
@santoshmath Is @Anh3h's fix sufficient? If so, we need to remove GCI task. https://codein.withgoogle.com/dashboard/tasks/5731526236962816/

**Comment by santoshmath** [comment]
@mdew192837 , Sure. Let me check and remove the issue.

**Comment by santoshmath** [comment]
@Anh3h , @mdew192837 , Tested  this issue.  It can take future date(by copy-pasting the date) but I am not able to pick future date through calender.

**Comment by aks681** [comment]
@santoshmath , can I take up this issue?

**Comment by mbj36** [comment]
@aks681 yes, go ahead

**Comment by AgnessMeena** [comment]
@mdew192837 @santoshconflux @aks681 @mbj36 @edcable  Hi, Thanks for Resolving this issue in the FDProduct Creation side
But i am still facing the same issue when editing Interest Rate Chart in both ways 
1. When editing Product 
![irc 2018-05-24 13-21-27](https://user-images.githubusercontent.com/13551795/40480084-1af8ac78-5f56-11e8-8d4c-e1ebb437c6fc.png)
2. And when editing itself(Not through edit product way)-when viewing product
![irc3 2018-05-24 13-22-17](https://user-images.githubusercontent.com/13551795/40480152-44f10e9e-5f56-11e8-8a0a-452687437134.png)
Looks like i can only copy and paste(unable to pic) the future end date., Can you take a look
