### ISSUE TITLE
Doesn’t fetch loan product number

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2466]
Create Loan product with Interest calculation period = Daily , set Is Variable Installments Allowed? 
Submit..Go to client > New Loan , submit> More > Edit Repayment Schedule 
At the Heading the loan product name should fetch it’s account number inside the brackets. 
**Old**
![variable1](https://user-images.githubusercontent.com/13551795/30319889-bf72142a-97b9-11e7-857a-5d78ec7b8433.png)
**New**
![variable](https://user-images.githubusercontent.com/13551795/30319908-cddbeafe-97b9-11e7-88a3-52809d687859.png)

**Comment by santoshmath** [comment]
@mbj36 , @Mastermaulik , please review the PR
