### ISSUE TITLE
When creating a guarantor who is existing client, the place to fill saving is not fetched 

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2468]
Apply a loan account to a client who has a saving account.
View the loan before approving it, go to More -> Create Guarantor
Leave the 'existing client' selected, fill the name of the same client
The system will display the client details but will not display the place to fill the saving account and amount for guarantee.
![createguarantor](https://user-images.githubusercontent.com/8160209/30332161-565c793e-97e2-11e7-99a7-adc959d2d742.png)
It is the same even when you fill another existing client
See https://demo.openmf.org/#/guarantor/1531

**Comment by santoshmath** [comment]
@mbj36, this is the major issue , must be addressed soon.

**Comment by luckyman000786** [comment]
@mbj36 Can I work on this issue ?

**Comment by gkrishnan724** [comment]
@MexinaD @santoshmath  According to the docs I found https://mifosforge.jira.com/wiki/spaces/docs/pages/72909221/How+to+Add+Remove+Modify+a+Guarantor+to+a+Loan+Account

I don't see that we need to also include the saving account and amount for a loan guarantor. If those fields need to be added, then this would be an enhancement  and I believe this should be also solved at the fineract side.

**Comment by MexinaD** [comment]
@gkrishnan724  see the screenshot of the RELEASE 17.07.01
![guarantor](https://user-images.githubusercontent.com/8160209/31442933-a1ef2d90-aea0-11e7-9024-77985a3b86b3.png)

**Comment by gkrishnan724** [comment]
@MexinaD Oh, then it is probably a bug, could you please provide the exact steps to reproduce the above screenshot? since in most cases, the platform does not return the accountLinkingoptions hence we are not able to see the options for account and amount. This might be a fineract side issue

**Comment by MexinaD** [comment]
@gkrishnan724  Apply a loan, then niew the loan profile, go to more and Create Guarantor
Select the existing guarantor, in the field to enter name, enter the name of the client who have an active saving account.
The system installed locally with current release provide the field to enter saving account and amount but demo does not.

**Comment by santoshconflux** [comment]
Fixed.
