### ISSUE TITLE
Loan Notes Is not well aligned 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2470]
Client  > New loan > submit > Notes
**OLD**
![notes1](https://user-images.githubusercontent.com/13551795/30370491-753a45c2-9880-11e7-88a4-88ca99729a76.png)
**NEW**
![notes2](https://user-images.githubusercontent.com/13551795/30370530-9542496e-9880-11e7-95ef-0f475bff816d.png)

**Comment by santoshmath** [comment]
@Agnessy , Loan notes are not displaying.

**Comment by santoshmath** [comment]
'Release Version' is getting displayed at next to 'Add' Notes button.

**Comment by luckyman000786** [comment]
@mbj36 @therajanmaurya Can I work on this issue ?

**Comment by mbj36** [comment]
Yes

**Comment by luckyman000786** [comment]
@mbj36 Can you tell me the html file of this ?

**Comment by luckyman000786** [comment]
I think now this issue can be closed
