### ISSUE TITLE
Charge creation

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2471]
Create Charge and attach Tax Group > Submit 
Edit Charge > Edit tax group > Submit
**I suggest**
Either It should allow modification of Tax Group OR
When editing charge the tax group drop down/lists should be disabled.
![tax-charge 2](https://user-images.githubusercontent.com/13551795/30370711-10ff2c70-9881-11e7-8c86-c7a8b751a9e9.png)

**Comment by MexinaD** [comment]
I think to allow modification of tax group can be done in back-end
@santoshmath, what do you think of the other suggestion?

**Comment by santoshmath** [comment]
@MexinaD, @Agnessy, I think while editing charge drop/down lists should be disabled.

**Comment by mbj36** [comment]
Fixed
