### ISSUE TITLE
 Client Identities

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2472]
Improper labels in Client > Identities ,, 
instead of **Document Type** there is **label.input.document-type**
instead of **Status** there is **Document Type**

**OLD**
![id1](https://user-images.githubusercontent.com/13551795/30371051-0badd734-9882-11e7-9bb0-74517a32a41c.png)
**NEW**
![id2](https://user-images.githubusercontent.com/13551795/30371092-1f52bf48-9882-11e7-8d91-1d029f0ca76c.png)

**Comment by mbj36** [comment]
@mexinaD I am sure you can take this up

**Comment by MexinaD** [comment]
@mbj36  Sure
