### ISSUE TITLE
Capital Value never used in share product creation

### ISSUE THREAD

**Issue by Nenge1** [openMF/community-app#2475]
Location admin->products->share products
The CapitalValue field seems to be useless in the form. It could be better if it fetches  the product of shares to be issued and the nominal interest when the user fill them
![image](https://user-images.githubusercontent.com/29059263/30467963-fce9bdec-99f0-11e7-9ecc-f3b1900f2dac.png)

**Comment by santoshmath** [comment]
@Nenge1 , it is included for future use.

**Comment by abhinavralhan** [comment]
@Nenge1 Could you make this more clear. What should the values be in this case?

**Comment by Nenge1** [comment]
The pull request regarding to this issues was merged
https://github.com/openMF/community-app/pull/2476
