### ISSUE TITLE
Create Survey is not working

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2481]
1. Navigate to Admin -> System -> Manage Survey, fill the basic information and proceed
2. Fill the fields of the "Add question"
3. Click Option and fill the fields and then Add the option
4. And then Add the Question
The system will bring the button for "Add Question" and "Create Survey" and at the right side, the created question
The button to add survey is not working and it doesn't give any error
![survey](https://user-images.githubusercontent.com/8160209/30596573-2bbfe76c-9d5d-11e7-98e4-73e89b8379b8.png)

**Comment by nazeer1100126** [comment]
Already PR is available on surveys https://github.com/openMF/community-app/pull/2433

**Comment by MexinaD** [comment]
Does the enhancement include viewing the survey and submit survey when you create on the client profile? @nazeer1100126

**Comment by santoshmath** [comment]
Now, Survey can be created.
