### ISSUE TITLE
Choosing "Select FD Products" Brings Unknown Results

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2483]
Go to Client > New Fixed Deposit > Choose Any product 
then Go back to select drop-down(As if you want to change product) , then choose “Select Fixed Deposit Product” ,, it bring unknown product
I think it was supposed to behave like loan application , that after the selection of the product the option of  “Select …...” shouldn't be there  .
![f0](https://user-images.githubusercontent.com/13551795/30733215-c035551c-9f7e-11e7-911d-89291535173a.png)
![f02](https://user-images.githubusercontent.com/13551795/30733262-e8d02998-9f7e-11e7-8ece-39feb96f82b4.png)
It also exist in Recurring Deposit Application.

**Comment by mdew192837** [comment]
Seems like issue is ready to review? Have we already created GCI issue? We should close that task to prevent confusion for students @santoshmath

**Comment by santoshmath** [comment]
@mdew192837 , Thank you for catching this. Just checked. Now, I am not able to select FD product. @gkrishnan724 , I think it is created regression.
