### ISSUE TITLE
Upload Client ID Document

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2488]
Create Client Identities , Upload Client Doc

1. Showing Improper labels , label.anchor.viewclienttranslate should be View Client.

2. Can not Upload document.
**new**
![idd](https://user-images.githubusercontent.com/13551795/30739320-8e26bfe0-9f95-11e7-83ca-2c5c8954c49a.png)
**old**
![ag](https://user-images.githubusercontent.com/13551795/30739358-b0b10dcc-9f95-11e7-8fb7-851148f463b6.PNG)

**Comment by anand1248** [comment]
May I look upon this issue?

**Comment by mbj36** [comment]
@anand1248 Sure! Let me know if you face any problem

**Comment by MexinaD** [comment]
The issue already have a pull request

**Comment by mbj36** [comment]
Fixed
