### ISSUE TITLE
To fetch the current date when assigning loan officer

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2493]
On the page of assigning loan officer [ which is the same page when you change loan officer ]
The field for date should fetch the date of that day like when you unassign the loan officer.
![unassign](https://user-images.githubusercontent.com/8160209/30900405-91a897e4-a36c-11e7-8687-0db339f06a81.png)

![assign](https://user-images.githubusercontent.com/8160209/30900409-950c6fb4-a36c-11e7-86ab-1dccfb5f4359.png)

**Comment by abhinavralhan** [comment]
Hi, I'd like to take this up.

**Comment by mbj36** [comment]
Sure @abhinavralhan

**Comment by abhinavralhan** [comment]
So, I was just going through the codebase. Could you confirm where I should be looking at? And, how do I get the same in test mode.
First time working on such a huge codebase
@mbj36

**Comment by mbj36** [comment]
Hi @abhinavralhan Great to hear that, you should be looking here https://github.com/openMF/community-app/blob/develop/app/views/loans/assignloanofficer.html 

Have you build the code ? It's just three steps - 

`npm install
bower install 
grunt serve` 

and you can test locally

**Comment by abhinavralhan** [comment]
@mbj36 The build is successful.
I wanted to ask, how do I go to the page where I can see about assigning loan officers on localhost. The homepage is login page itself. 
I wanted to make changes to the code and see how it responds, locally.

**Comment by mbj36** [comment]
Check out this - http://localhost:9002/?baseApiUrl=https://demo.openmf.org#/assignloanofficer/1591

**Comment by abhinavralhan** [comment]
Is this right?

![selection_025](https://user-images.githubusercontent.com/14059638/31144235-b233d286-a89d-11e7-94cc-c3fa4f3ebce4.png)

**Comment by mbj36** [comment]
After signin into app, try the above url

**Comment by abhinavralhan** [comment]
@mbj36 
So I'm there on the page but I'm getting this error. Basically, it is unable to find data for "To loan officer" field. It appears as below
![selection_026](https://user-images.githubusercontent.com/14059638/31150304-b27edd7c-a8b0-11e7-893b-5fd993b0a6e8.png)

Also how do I find the page which is used to "Unassign Loan officer". what would be the url

**Comment by mbj36** [comment]
We have our demo here - https://demo.openmf.org/#/viewloanaccount/1139 

Checkout the screenshot 
![selection_065](https://user-images.githubusercontent.com/9936881/31161349-fc740860-a8f3-11e7-8182-fd02a204ecf2.png)

Here you assign the loan officer and then it will be visible in `loan officer` field  which is just below the currency field, if you remove the loan officer from there, it will take you to `unassign loan` officer

**Comment by luckyman000786** [comment]
@mbj36 Can I work on it ?

**Comment by mbj36** [comment]
@abhinavralhan Are you working on it?  Feel free to ask if you still have any doubt

**Comment by luckyman000786** [comment]
Can you elaborate the issue ?

**Comment by abhinavralhan** [comment]
@mbj36 
I am working on it. Just had a few classes in the morning. I will get back to you with whatever doubts I have. Thankyou :+1:

**Comment by abhinavralhan** [comment]
@mbj36 
After making a change to some file locally, I save the file, stop the server. Run grunt serve again. Yet no changes are reflected on the required page. I have tried this on a few pages.
What could I be missing here?

**Comment by mbj36** [comment]
What are your changes ?

**Comment by abhinavralhan** [comment]
@mbj36 
Any simple change like just commenting out a block of code in https://github.com/openMF/community-app/blob/develop/app/views/loans/assignloanofficer.html or commenting out code in it's corresponding controller

**Comment by mbj36** [comment]
That's not possible @abhinavralhan. You might be doing some mistake.

**Comment by abhinavralhan** [comment]
@mbj36 
Hey, sorry I couldn't fix it. Angularjs is new for me as I'm more used to Angular 4. 
I do understand the codebase, and I recognised my mistake in the last step. 
I'll look for easier issues and try fixing them. Thanks for all the help regardless :+1:

**Comment by Agnessy** [comment]
Hi Can I try to Fix it?
