### ISSUE TITLE
Labels/Parameter names having single radio buttons should not be mandatory

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2495]
- Create Fixed Deposit Product  

- Create Recurring Deposit Product 
Is primary grouping by Amount shouldn't contain Asterisk. 
![radio1](https://user-images.githubusercontent.com/13551795/30959890-2808138a-a44a-11e7-8efe-5a7c7c729dfc.png)

**Comment by mdew192837** [comment]
Seems like @Agnessy 's pull request fixes this. Have we already created GCI task? If so, we need to remove it @santoshmath

**Comment by santoshmath** [comment]
@Agnessy , @mdew192837 , This issue is not yet resolved.

**Comment by AkashBhave** [comment]
I have fixed this issue with my pull request here: https://github.com/openMF/community-app/pull/2657
