### ISSUE TITLE
View Journal Entries button does not work from individual transaction

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2503]
View Journal Entries button (arrow) does not work.

Navigate to any loan account, then go to transactions tab and then attempt to click the arrow for view journal entries for an individual transaction. 

It won't click through an go to the journal entry.

**Comment by luckyman000786** [comment]
Can you tell where the function viewloantransactionjournalentries(transaction.id) is called ?

**Comment by mbj36** [comment]
@luckyman000786 There are many functions named viewJournalEntries(), I am not sure for which you are looking, Here is the Github search result - https://github.com/openMF/community-app/search?utf8=%E2%9C%93&q=viewJournalEntries%28%29&type=

**Comment by luckyman000786** [comment]
Can I work on this issue ? @edcable @mbj36

**Comment by mbj36** [comment]
Yes @luckyman000786

**Comment by luckyman000786** [comment]
@mbj36 @edcable Please review the pull request and merge it.

**Comment by mbj36** [comment]
Be patient.  It will be reviewed

**Comment by mbj36** [comment]
Fixed
