### ISSUE TITLE
Incorrect placeholder values.

### ISSUE THREAD

**Issue by anand1248** [openMF/community-app#2515]
![bug](https://user-images.githubusercontent.com/25207758/31354363-cd5c3bce-ad53-11e7-8372-7b9d7fa3fd02.jpg)
-  First block should display "Filter display by Name/Client/Staff/Office.

- Second block should display "Find By Name/Mobile/Client/External ID/Identifier".

**Comment by luckyman000786** [comment]
@mbj36 Can I work on this issue ?

**Comment by mbj36** [comment]
@luckyman000786 Sure

**Comment by mbj36** [comment]
Fixed
