### ISSUE TITLE
Active loans when the client is waiting the transfer to be accepted or rejected

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2528]
When you transfer a client to another branch but you have not accepted/rejected the transfer, the client loans which are active/due become inactive but those which are waiting to be approved and those waiting to be disbursed are still active. The same with saving ans shares
![transferclient](https://user-images.githubusercontent.com/8160209/31823739-c053c072-b5b5-11e7-8eda-031811bde4e7.png)

All loans, savings and shares has to be inactive until he is accepted or rejected

**Comment by MexinaD** [comment]
@santoshmath now when am trying to work on this issue, it seems it might be the issue in the platform
Can you help me to check so that i can be sure?

**Comment by santoshconflux** [comment]
Fixed and closed from Back end.:

https://issues.apache.org/jira/browse/FINERACT-623
