### ISSUE TITLE
Holidays are not displayed after creation

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2529]
When you create a holiday and submit, they are not displayed/listed as they are supposed to
Goto Admin->Organization->Manage Holidays-> Create holiday and submit
![holiday](https://user-images.githubusercontent.com/8160209/31876116-c76de7d6-b7d9-11e7-9d63-9377af37d490.png)

I tested on the local and checked the database, the holiday was stored on database

**Comment by santoshmath** [comment]
@MexianD , holidays are office specific. Checking your screenshot you didn't select the office.  Please close this issue, if you found it resolved.
