### ISSUE TITLE
Field in loan product/account shows it's mandatory while its not

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2530]
The field of "Calculate interest for exact days in partial period" in loan product creation and loan application shows it is mandatory while it is not.

For the configuration of the loan which does not require this field to be selected, users get unexpected result and hence it is a problem for new users
![mandatorysign](https://user-images.githubusercontent.com/8160209/31882309-0300d348-b7ef-11e7-80a5-123a4960396f.png)

**Comment by friscomm** [comment]
has anybody claimed this yet? I'd like to give it a shot if it's available to be worked on

**Comment by MexinaD** [comment]
@friscomm  It is already worked on, see the pull request referenced

**Comment by santoshmath** [comment]
@mbj36 , please check the  PR for this issue.

**Comment by mdew192837** [comment]
Have we already created the GCI task for this? We should post here for reference to remember to close the GCI task if this issue is already resolved @santoshmath

**Comment by santoshmath** [comment]
@mdew192837 , Yes. it is created. We  already shared this issue URL in GCI task. Do you think we should share GCI task link here too?

**Comment by santoshmath** [comment]
@MexinaD , Just checked. This issue not yet  resolved.

**Comment by MexinaD** [comment]
@santoshmath  the PR is not yet merged

**Comment by AkashBhave** [comment]
This issue should be fixed with my pull request here; https://github.com/openMF/community-app/pull/2702
