### ISSUE TITLE
Client Loan reschedule history

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [openMF/community-app#2532]
Hi,
When i create a Loan reschedule, and i want the supervisor user to approuve it, i can't see any menu that allow to do so. even if the view is acessable because if i copy the url with the loan id, i can see the demand i just created but can't acess it using menu.

**Comment by santoshmath** [comment]
Answer is posted here:

http://mifos.cloud.answerhub.com/questions/2358/qustion-by-kazacube-hsmaiti.html?childToView=2359#answer-2359
please continue the discussion there if you have any doubts.
