### ISSUE TITLE
The search field of reschedule loan in the menu Checker Inbox & Tasks not working

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [openMF/community-app#2535]
Hi,
In the Left menu **Checker Inbox & Tasks**, when i want to search for a reschedule loan.
i tape the name but nothing changes. i think its not working.
link: [https://demo.openmf.org/#/tasks](https://demo.openmf.org/#/tasks).
here is a screenshot of the search field:

![capture du 2017-10-25 17-52-26](https://user-images.githubusercontent.com/32460729/32044776-6adb1764-ba36-11e7-896e-467b5db5da71.png)

**Comment by edcable** [comment]
![Screenshot 2020-06-13 at 7 26 30 PM](https://user-images.githubusercontent.com/823454/84583289-d56e2600-adab-11ea-84e0-cda4f0681918.png)
![Screenshot 2020-06-13 at 7 26 19 PM](https://user-images.githubusercontent.com/823454/84583291-d69f5300-adab-11ea-80f8-b4269f706ae5.png)
Closing as invalid - works fine for me.
