### ISSUE TITLE
Bug: I can't see all the reschedule loan when i want to approuve them.

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [openMF/community-app#2536]
In the menu **Checker Inbox & Tasks**. when i want to approuve an old reschedule loan, i can't see it.
i have to approuve many loans to finally arrive to the one i want.
i think the probleme here is that the list of loans is limited (to 15 reschedule loan only), and we have to rejecte or approuve a number of reschedules to see the one we want.

here is a screenshot of the view:
![capture du 2017-10-25 17-52-26](https://user-images.githubusercontent.com/32460729/32011694-6dd15c32-b9ad-11e7-9d2b-f2291d8a2140.png)

and even the search field is not working.

Thank you.

**Comment by MexinaD** [comment]
Am working on this

**Comment by santoshmath** [comment]
@mbj36 ,  FYI
