### ISSUE TITLE
Loan data are not loaded (corrupted)

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [openMF/community-app#2539]
Hello, 
I have a big probleme. When i want to see a client's loan, i get a view with corrupted data.
here is a screenshot of the view:

![image](https://user-images.githubusercontent.com/32460729/32099435-2d38de96-bb08-11e7-9560-d5147e624280.png)

**Comment by kazacube-hsmaiti** [comment]
in the log i got this message:

{timestamp: 1509099806863, status: 500, error: "Internal Server Error",…}
error:"Internal Server Error"
**exception:"org.springframework.jdbc.BadSqlGrammarException"**

message:"**PreparedStatementCallback; bad SQL grammar** [select dd.id as id,dd.expected_disburse_date as expectedDisbursementdate, dd.disbursedon_date as actualDisbursementdate,dd.principal as principal,sum(lc.amount) chargeAmount, lc.amount_waived_derived waivedAmount,group_concat(lc.id) loanChargeId from m_loan l inner join m_loan_disbursement_detail dd on dd.loan_id = l.id left join m_loan_tranche_disbursement_charge tdc on tdc.disbursement_detail_id=dd.id left join m_loan_charge lc on  lc.id=tdc.loan_charge_id and lc.is_active=1 where dd.loan_id=? group by dd.id order by dd.expected_disburse_date]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mifostenant-sav.lc.amount_waived_derived' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

status:500
timestamp:1509099806863

**Comment by MexinaD** [comment]
@kazacube-hsmaiti did you add any sql satement in the system before the problem started?

**Comment by kazacube-hsmaiti** [comment]
@MexinaD i fond the problème, it was the version of sql server that i'm using (5.7).
i changed it to version 5.6 and it worked.
