### ISSUE TITLE
End Date shouldn't act as a mandatory field when editing teller

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2540]
Go to Organization >> Teller/Cashier Management .. New Teller, Set End date .. submit 
Edit Teller, empty end date field, submit,, nothing happen
it shouldn't act as a mandatory, since when creating teller it is not mandatory
![tuu](https://user-images.githubusercontent.com/13551795/32164404-7edf6958-bd70-11e7-8a08-eb0a160f2f95.png)

**Comment by yashasvi13** [comment]
Hi, @mbj36 @santoshmath This seems to me a server-side error. Please review.
![image](https://user-images.githubusercontent.com/28532515/34078817-7dc4b31e-e347-11e7-8455-271bb6220654.png)

**Comment by jonathanzhang53** [comment]
Does this issue still exist? I am unable to replicate it.

**Comment by santoshconflux** [comment]
Yes, it's fixed. Closing now.
