### ISSUE TITLE
Correct spelling error in label for "Repayment Scheduling Type"

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2550]
Navigate to Admin >> Organization >> Manage Holidays.

Click to create holiday, the label for the dropdown, repayment scheduling type, is misspelled:

![screen shot 2017-11-07 at 6 30 08 am](https://user-images.githubusercontent.com/823454/32498800-85c53ebc-c385-11e7-87fe-f130f15ac53d.png)

**Comment by santoshmath** [comment]
@mbj36 , please check the PR
