### ISSUE TITLE
Check Mandatory Fields are furnished or not before giving Green colour and Right Tick in Wizard implementation of products and accounts

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2554]
Currently, at any step of wizard, if we click 'Next' without furnishing mandatory details, it shows green color with right tick. 

It should be done for all the cases of wizard implementation.

**Comment by santoshmath** [comment]
Related issues: #1660 , #2299 , #2426

**Comment by ankit01ojha** [comment]
@santoshmath, I would like to work on this issue.

**Comment by mbj36** [comment]
Go ahead @ankit01ojha

**Comment by gkrishnan724** [comment]
@ankit01ojha I am already working on this :(, I will be sending a PR soon.

@santoshmath, would this UI do:

When required fields are not filled and we press next, then the indicator turns red.

and once we fill the required fields and press next then only the indicator will become green.

demo:
![firefox](https://user-images.githubusercontent.com/21004514/33793014-66eb7f1a-dcd5-11e7-83b7-c543ef5d2cb7.gif)

**Comment by ankit01ojha** [comment]
@gkrishnan724 , ok, if you already fixed this much, then go ahead.

**Comment by santoshmath** [comment]
@gkrishnan724 , It really works great. Go ahead and send the PR if everything is done.

**Comment by santoshmath** [comment]
@gkrishnan724 , just make sure you have done the same for all wizard implementation.
