### ISSUE TITLE
Unable to add a group  when you "Manage groups" in a center 

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2558]
1. Create a group in a certain office 
2. Create a center in a same office of the group created.
3. After submission, go to a profile of a center and "manage groups"
System does not fetch the group so as it can be added to the center

**Comment by ankit01ojha** [comment]
@mbj36 , I am working on this issue.

**Comment by ankit01ojha** [comment]
@santoshmath , I am a bit confused in the search box does it need to display all the groups or only the groups which are in ```Center Member(Groups)```.
![screenshot at 2018-01-03 19 49 22](https://user-images.githubusercontent.com/21126132/34523977-c461b0e4-f0bf-11e7-872c-8d7f9b5a84f0.png)
