### ISSUE TITLE
Add fees field when prepay a loan

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2560]
When you prepay a loan which has unpaid fees, the transaction amount is different from the summation of Principal and Interest ( which are the only amounts that are shown in the page ). This is because the transaction amount include the unpaid fees but no where it say so.
I was suggesting, the field for fees to be added so as to provide a clear details.
![prepay](https://user-images.githubusercontent.com/8160209/32875848-15942248-caab-11e7-9669-b0e871cab512.png)

**Comment by aks681** [comment]
Can I take up this issue?

**Comment by mbj36** [comment]
Hello @aks681 Surely you can take up the issue
