### ISSUE TITLE
In Loan  Provisioning Criteria, 'Sub-Standard' row should display just after 'Standard' row

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2587]
Go to organization > Provisioning Criteria.

Create a provisioning criteria with days , %age and affected accounts.

When view the provision, it displays as shown here:

![substd1](https://user-images.githubusercontent.com/23022667/33358224-47bd6706-d4ed-11e7-893a-e6e2526053d1.png)
![substd2](https://user-images.githubusercontent.com/23022667/33358225-47f9f310-d4ed-11e7-8f93-a0e5a73dcf02.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @Agnessy.

**Comment by ankit01ojha** [comment]
I think the PR fixes this issue.

**Comment by ankit01ojha** [comment]
@santoshmath , I have sorted them as per the category name.

**Comment by gkrishnan724** [comment]
@santoshmath should the screenshot by @ankit01ojha  be the desired output? and may I know why `SUB-STANDARD` should be after `STANDARD` is it just UI concern or something different?

**Comment by santoshmath** [comment]
@ankit01ojha , @gkrishnan724 , it should be just  sorted starting from Standard, Sub-Standard, Doubtful  and Loss.

**Comment by gkrishnan724** [comment]
Thanks @santoshmath, @ankit01ojha Please make the required changes

**Comment by ankit01ojha** [comment]
Thanks @santoshmath , @gkrishnan724. I'm working on it.

**Comment by ankit01ojha** [comment]
@mbj36 , this issue is fixed. It should be closed.

**Comment by santoshconflux** [comment]
Fixed.
