### ISSUE TITLE
In New saving application, ticking 'Is Overdraft Allowed' hiding 'Minimum balance.

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2602]
Go to any client and click on Savings and select any savings product.
In 'Terms' tick on 'Is Overdraft Allowed' and observe that  'Minimum balance which was appearing before gets hidden.

**Comment by Kanav-7** [comment]
@santoshmath Can I work on this issue?

**Comment by santoshmath** [comment]
@mbj36 , FYI

**Comment by gkrishnan724** [comment]
@santoshmath, are you sure minimum balance should be there for an overdraft? Since I think there is no point in having a minimum balance if you can overdraft.

**Comment by santoshmath** [comment]
Good Catch @gkrishnan724 . Sorry  for not thinking about it. :)

Closing this issue.
