### ISSUE TITLE
Ticking on Recalculate Interest & Place Guarantee Funds on Hold is not showing required fields related to them

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2603]
Go to any client and click on 'New Loan' .Select loan product and try to tick 'Recalculate Interest' or "Place Guarantee funds on Hold". It is going to the next step of workflow

![screenshot from 2017-11-30 15-23-43](https://user-images.githubusercontent.com/23022667/33424798-e032166c-d5e2-11e7-9c17-26c46287adce.png)

**Comment by gkrishnan724** [comment]
@santoshmath, the fields come as an additional step to avoid clustering. please take a look at this gif:
![wizard](https://user-images.githubusercontent.com/21004514/33477648-6cdc05b8-d6ac-11e7-82da-d4ff4a73c8d4.gif)
