### ISSUE TITLE
Right arrow icon missing

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2618]
Right arrow icons are missing :- 
![screenshot at 2017-12-01 20 43 45](https://user-images.githubusercontent.com/21126132/33496733-6186594e-d6f1-11e7-98b8-be59f4171539.png)

I am working on it.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, @Agnessy, and @santoshmath.
