### ISSUE TITLE
Mifos X Web App - Fix broken icons

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#2621]
When we moved from the old skin to new skin, a lot of icons are missing in buttons and inputs due to switching from `icon` classes to `fa` classes. Many of the classes are spelled incorrectly in the code. For this task, you are supposed to identify at least 10 places where icons are missing and fix them accordingly. 

For retrieving the old-skin, you would need to revert back the develop branch before the new skin commit by doing 
`git checkout 15b7cbca20484e0deb3dd418808ba481854da038`

You could compare this version in the hosted demo(https://staging.openmf.org/) which contains the latest skin and identify the places where the icons are not visible.

Eg:
Collection Sheet Buttons:

Old Skin:
![old](https://user-images.githubusercontent.com/21004514/33514480-a6b0cfc0-d77a-11e7-814f-df17813b9763.png)

New Skin:
![image](https://user-images.githubusercontent.com/21004514/33514443-16c45f9e-d77a-11e7-8766-edba2f2715a4.png)

Notice, the arrow icons on the buttons are missing. Ping me `@gkrishnan724` on gitter, if you face problems on loading the old skin.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @santoshmath.

**Comment by gkrishnan724** [comment]
This is a `GCI` issue.

**Comment by edcable** [comment]
@santoshconflux do we still consider this p1? I added a p3 tag as well.

**Comment by nnatarajan** [comment]
Is is possible that I can be assigned to this issue?

**Comment by nnatarajan** [comment]
At this point in time, the old skin icons and new skin icons appear identical. It appears that PRs [#2619](https://github.com/openMF/community-app/pull/2619) and [#2695](https://github.com/openMF/community-app/pull/2695) have already resolved this issue.

I think we can close this one out.
