### ISSUE TITLE
'Interest Rate Differential' field and 'Is Floating Rate' with radio button is missing in loan application

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2630]
1. Create a loan product with linked floating rate.

![floatingrate_loanproduct](https://user-images.githubusercontent.com/23022667/33552214-2c2b2a92-d91a-11e7-9175-99d383361643.png)

2. Go to client and take 'New Loan' for the client. 

>In Loan application, it is not showing. 

It should show similar like this:(Screeshot shared by @Immanuel)

![floating rate_loanapplication](https://user-images.githubusercontent.com/23022667/33552327-9a1678ae-d91a-11e7-8a95-c1d0cdc73df4.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @Agnessy.

**Comment by anoited007** [comment]
@santoshmath Is this issue only in the latest version?

**Comment by santoshmath** [comment]
Yes, try to submit loan application with loan product "lp-floatingrate"

https://staging.openmf.org/#/newclientloanaccount/1

**Comment by anoited007** [comment]
@santoshmath I have tried. It has the same issue.  By the way, how do I create the step by step loan creation as the one on staging?
![staging-demo](https://user-images.githubusercontent.com/27229090/33591907-ba167870-d9a1-11e7-95fd-6a3f08758247.png)

**Comment by santoshmath** [comment]
Define Base lending rate and differential lending rate in Admin>products>Floating rate

Create a loan product and while creating , link it to floating rate. (you can do it in 'Terms' section)

Take New loan application and try to submit it using this loan product.

**Comment by anoited007** [comment]
I was actually referring to the UI. It seems we are using the same version but some features on the staging server is not available in my version. For example the progress bar and most of the tool tips. Is it something I have to configure first?

**Comment by santoshmath** [comment]
Progress bar, tool tips will be available with next release  of Mifos  distribution.  Or fetch  the code  from Community-app develop branch.

**Comment by anoited007** [comment]
Alright. Thank you. So I guess the Floating rate issues will be fixed in that as well. Thank you @santoshmath  Much appreciated

**Comment by gkrishnan724** [comment]
@santoshmath @mbj36 Fixed the issue please review PR
