### ISSUE TITLE
Report and receipt customization

### ISSUE THREAD

**Issue by anoited007** [openMF/community-app#2636]
@santoshmath Will it be possible to allow clients to customize various reports and receipts? For example, users can have their company logo and some details on receipts issued.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @santoshmath.

**Comment by santoshmath** [comment]
@anoited007 , you can create customized report by writing required sql query(Go to Admin>System>Manage Reports). For advanced design, you can create report using Pentaho report designer and embed it in Mifos.

**Comment by santoshmath** [comment]
@anoited007 , Here we only report issues and for Q&A ,we have another channe:

http://mifos.cloud.answerhub.com/index.html

**Comment by anoited007** [comment]
@santoshmath What I am referring to is the receipts which are generated automatically when a transaction is made. For example when a loan repayment is made. I think if users are able set details like their company name and contact so that it appears on such receipts to be issued to their clients.

**Comment by santoshmath** [comment]
yes. Receipts are also type of reports
