### ISSUE TITLE
Show a 404 Not Found page when a user routes to unintended routes

### ISSUE THREAD

**Issue by ManrajGrover** [openMF/community-app#2650]
## Description

Currently, when a user routes to something other than intended routes, it shows a blank view with no message (see screenshot).

![screen shot 2017-12-12 at 12 48 34 pm](https://user-images.githubusercontent.com/5673050/33872197-e2c76ffa-df3b-11e7-8336-8dc665881aba.png)

## Fix

We should add an otherwise method in routes.js where if a route does not match the list of routes in routes.js, we show a 404 page to the user. Design of the page can be simple.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.
