### ISSUE TITLE
Error when you accept transfer of client

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2652]
1. Create two different offices
2. Create a client in one of the office
3. Go to its profile and click "Transfer client" and chose the other office to transfer and submit
3. Then click "Accept Transfer"
The system gives any error which does not relate to the operation made. 
![accepttransfer](https://user-images.githubusercontent.com/8160209/33887701-b226e6c6-df5b-11e7-9124-650dab69ec4f.png)

The system should have allowed the successfully transfer.

**Comment by santoshmath** [comment]
Hi  @MexinaD , just tested on staging. I am able to transfer a client from one office to other office.

**Comment by MexinaD** [comment]
@santoshmath , true. It works in staging but not in demo account

**Comment by ankit01ojha** [comment]
@santoshmath @MexinaD , yeah it's not working in the demo. I also got the same error as described in the screenshot.

**Comment by santoshmath** [comment]
@ankit01ojha , ping me on Hangout. I will show  you. (My mail id: santosh@confluxtechnologies.com)

**Comment by santoshconflux** [comment]
Tested on staging. Working fine.
