### ISSUE TITLE
 Trouble in account entries: taxes are not integrated in accounting

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [openMF/community-app#2653]
- I made a payment of a charge with taxes pre configurated, but when looking for the account entry i didn't found taxe item.

- to replicate the bug, configure taxes, create a charge and pay it.
- go to accounting and look for account entries: here you will not found the tax entry.

![image](https://user-images.githubusercontent.com/32460729/33894837-df9442f2-df56-11e7-929c-20bf1ffe0755.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @santoshmath, and @Agnessy.

**Comment by kazacube-hsmaiti** [comment]
for your information, it was working on a previous version but not in 17.01.07

**Comment by sharecodekzc** [comment]
@santoshmath @Agnessy 
still looking for support on this issue, tax on charges for savings and charges and interests loans. 
Tax configuration seems correct, but is not taken into account when validating the charges ; no withhold tax calculated in the accounting. 
Ready to give more details on our request, and looking for technical support to address this issue which is blocking for one of our customer

**Comment by santoshconflux** [comment]
@kazacube-hsmaiti , I just referred the following documentation about using tax with savings/FD/
RD while posting the interest. 

https://mifosforge.jira.com/wiki/spaces/docs/pages/129957925/Manage+Tax+configuration

There is no information regarding how to use taxes with charges. We can add tax group to the charge product but it doesn't show any results in account level.
If it's working before 17.07.1 as you mentioned in previous comment, could you give charge configuration(Charges applied to, Charge time type and Charge calculation)   with which you have used the tax group.

**Comment by santoshconflux** [comment]
I am able to use tax group for 'With Hold Tax' when interest is posted to the savings account. 1% of interest posted is debited as withhold tax.
You can check here:
https://staging.openmf.org/#/viewsavingaccount/48
username: mifos
password: password

**Comment by santoshconflux** [comment]
Not able to reproduce.
