### ISSUE TITLE
Unable  to upload document for client identities: throwing internal server

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2656]
For the following client:

https://staging.openmf.org/#/viewclient/18
(username/password  - mifos/password)
Go to Identities tab (where  driving license already uploaded)

Under 'Actions' tab, click on upload button and try to upload any image or pdf.

>no validation message is showing and checked through network showing 500:internal server error

**Comment by ankit01ojha** [comment]
I am working on it.

**Comment by mbj36** [comment]
@santoshmath  Can you retest this and close ?

**Comment by santoshconflux** [comment]
Tested on staging . Fixed.
