### ISSUE TITLE
I can't submit a Fixed Deposit Application for a client

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [openMF/community-app#2666]
Hello,
when i want to create a Fixed Deposit for a client, the button submit is not working and no exception is raised.
![image](https://user-images.githubusercontent.com/32460729/34107429-15cb58dc-e3f4-11e7-8752-9f53869867d2.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @Agnessy, and @santoshmath.

**Comment by kazacube-hsmaiti** [comment]
that was quick, do you confirm its a bug??

**Comment by ankit01ojha** [comment]
i am working on it.
