### ISSUE TITLE
Fund behavior 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2668]
1.Create Loan Product, select Fund with long name
2.Go to Client Do Loan Application, the fields are not well aligned

![fuund](https://user-images.githubusercontent.com/13551795/34157360-5196a342-e4d2-11e7-9866-e254e3f89a32.png)

The Fund field in Loan application(To a Client) should behave LIKE the fund Field in Loan Product Creation,,{The width of the Fund}
![ff](https://user-images.githubusercontent.com/13551795/34157452-9b837aa2-e4d2-11e7-848f-24946d1e90af.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @MexinaD.

**Comment by anweshknayak** [comment]
Im on this

**Comment by shubhshrma** [comment]
@anweshknayak you still working on it?

**Comment by AgnessMeena** [comment]
@mbj36 @shubhshrma @gkrishnan724 Hi, Can you consider even  in the Modification of loan account.
![fund-from 2018-05-22 15-29-26](https://user-images.githubusercontent.com/13551795/40362360-f748a6e8-5dd4-11e8-9b82-cd30c99063ce.png)

**Comment by muddlebee** [comment]
@Agnessy it has been fixed in #2851 . Please check that once. Let me know if this still exists

**Comment by muddlebee** [comment]
sure looks like I missed this. Will update today itself @Agnessy.

**Comment by santoshconflux** [comment]
Fixed.
