### ISSUE TITLE
Viewing Group Closed Savings

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2669]
1.Create saving to a group
2.Close that saving 
3.View closed savings
**Status** column shouldn't contain date
**Status** column should contain saving status and **Closed date** column should contain date
![jjh](https://user-images.githubusercontent.com/13551795/34157866-6bb757c4-e4d4-11e7-9840-a3a9ac919979.png)

**Comment by ankit01ojha** [comment]
I am working on it.
