### ISSUE TITLE
Apply/Redeem Shares

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2670]
1.Create share product
2.Apply to a client 
3.Apply Additional Share OR Redeem share
Submit Form without filling any field  >> There should be a thrown error since **Request Date** and **Total Number of Shares** are mandatory 
When you empty **Request Date** there is no thrown error but when you empty  **Total Number of Shares** there is a thrown error 
![ras](https://user-images.githubusercontent.com/13551795/34158490-b5c809ec-e4d6-11e7-9333-2f71772d773e.png)

**Comment by ankit01ojha** [comment]
I am working on it.
