### ISSUE TITLE
 List Of Standing Instructions 

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2673]
1.Go to client , Create Standing Instruction
2.View Standing Instructions
3.From the list of Standing Instructions , View one of them
4. Then on the top click **List Standing Instructions** 
It shows unknown page. 
![std](https://user-images.githubusercontent.com/13551795/34198526-ba28ecfe-e57b-11e7-8988-c9293a0a9d70.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @santoshmath.

**Comment by edcable** [comment]
Closed as fixed.
