### ISSUE TITLE
Missing Fields when Editing Charge

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2675]
1.Create Charge with **Charges applies to** = Client
2. Fill all necessary fields. Submit
3.Edit Charge 
**Charge payment by** field is not there, while it was available during charge creation.
![crc](https://user-images.githubusercontent.com/13551795/34200137-0c9ee9b6-e581-11e7-84ef-5833352d95c9.png)
Edit
![gvb](https://user-images.githubusercontent.com/13551795/34200229-564009a6-e581-11e7-852a-3a94841ae8c2.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @MexinaD.

**Comment by ankit01ojha** [comment]
I am working on this.

**Comment by gkrishnan724** [comment]
Hi @Agnessy According to the User-manual  https://mifosforge.jira.com/wiki/spaces/docs/pages/72908813/Charges `Charge payment by` field is only visible for loan charges. I believe the bug is `charge payment by` should not be there for creating client charges.

**Comment by Agnessy** [comment]
Thatc true @gkrishnan724

**Comment by ankit01ojha** [comment]
@Agnessy , so, I am sending the PR regarding the new issue ``` charge payment by should not be there for creating client charges.``` . Please rename this issue also. :)
