### ISSUE TITLE
Add buttons to upload and delete signature, when viewing client signature

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#2677]
In the community-app, go to Clients and click on any client. In order to upload a client signature, the user has to click on the More>>Upload Signature, same goes for deleting a signature. It would be much convenient if we had the upload and delete buttons when viewing the signature.

###  ScreenShot:
We could add an upload  & delete buttons in this modal
![sig1](https://user-images.githubusercontent.com/21004514/34246272-db80440a-e653-11e7-919d-ef445d48f728.png)

### Functionality:

- Delete button should appear only if a signature is present.

- Upload button should appear in all cases.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @santoshmath, and @mbj36.

**Comment by gkrishnan724** [comment]
This would be a GCI task

**Comment by risingone** [comment]
@gkrishnan724 I can take up this issue ? Will be my first contribution :)

**Comment by mbj36** [comment]
@risingone  Go ahead

**Comment by mbj36** [comment]
@risingone Sorry for interruption, we are keeping this task reserved for GCI students

**Comment by risingone** [comment]
@mbj36 Okay. I already started working on it but its fine.I understand.

**Comment by MYKatz** [comment]
@mbj36 could you please merge PR #2672?  Otherwise I would need to duplicate some methods.  Thanks!
