### ISSUE TITLE
Tooltip for Submitted and Pending Approval Should Display above Nav Bar

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2680]
## Description
The tooltip for "Submitted and Pending Approval" for loan and savings accounts displays beneath the left hand navigation bar when it should be on top.

## Steps to Reproduce
Navigate to any client, find a loan or savings account in the summary that has yellow/orange icon. Hover over it and see tooltip displayed beneath the lefthand drawer navigation. 

## Expected Behaviour

Full tooltip should be visible above the nav bar. 
<img width="588" alt="screen shot 2017-12-21 at 11 37 05 am" src="https://user-images.githubusercontent.com/823454/34272144-fb08e738-e643-11e7-8495-3fbe8bfdd6b6.png">

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by shubhshrma** [comment]
This issue can be closed now.

**Comment by edcable** [comment]
Closed as fixed.
