### ISSUE TITLE
Replace Deposit and Withdraw (Left & Right Arrows) Icons with something more intuitive

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2682]
## Description
On the client details page, under the Savings Summary, the quick action buttons for Deposit and Withdraw are a left and right arrow. 

Left and Right arrows are typically used for navigation which makes this confusing. Ideally representative icons could be chosen for each action but if not, an up and down arrow would make better sense here. 

See screenshot. 
<img width="765" alt="screen shot 2017-12-22 at 6 43 08 am" src="https://user-images.githubusercontent.com/823454/34301987-bf8f59bc-e6e3-11e7-90d2-82ebc8e88e4c.png">

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.
