### ISSUE TITLE
Selecting `Hindi`/`हिंदी`  in `Change the language` option anywhere on the app isn't working.

### ISSUE THREAD

**Issue by risingone** [openMF/community-app#2692]
## Description
Selecting `Hindi/हिंदी`  in `Change the language` option anywhere on the app isn't working.
All other languages are working fine. The problem is just with selecting Hindi.
## Steps to Reproduce
Just try changing the language to hindi, you'll find nothing happens.

## Expected Behaviour
On changing the language, the page should be translated.
## Actual Behaviour
No translation in case of changing the language to hindi.

## Settings
- Mifos X version: Version 17.07.01.RELEASE 
- Browser used: Chrome(Mac OS X 10_13_1)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @safiyu.

**Comment by risingone** [comment]
@mbj36 I would like to take up this issue ?

**Comment by gkrishnan724** [comment]
Sure @risingone
