### ISSUE TITLE
Scrollbar hiding under the header

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2693]
## Description
Scrollbar hiding under the header

## Steps to Reproduce
Admin -> Loan Products.

## Expected Behaviour
Scrollbar should start beneath header
## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any
![screenshot from 2017-12-27 23 27 08](https://user-images.githubusercontent.com/8139783/34389308-e43d70c6-eb5e-11e7-910e-e3b29e129865.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @santoshmath.

**Comment by gkrishnan724** [comment]
@anweshknayak This exists for all lists not only loan products. Nice find though :+1:

**Comment by abhaychawla** [comment]
@gkrishnan724 Can I work on this issue?
