### ISSUE TITLE
Create teller form is getting submitted even if description is not filled.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2696]
## Description
When a teller is created, if the description filled is not touched, the form is getting submitted (required mark is missing). Even though the description field is required. And the required mark is missing from the description.

## Steps to Reproduce
Admin>>Organisation>>create teller>> without touching the description field and filling all the required field>> click the submit button

## Expected Behaviour
It should show required field message and form should not be submitted when the submit button is clicked if description field is not touched.
## Actual Behaviour
Form is getting submitted if the description field is not touched.
## Settings
- Mifos X version: Version 17.07.01.RELEASE
- Browser used: chrome

## Screenshots, if any
In the screenshot below the form got submitted even if the description field is not filled.
![teller](https://user-images.githubusercontent.com/21126132/34412733-fc31b13c-ec04-11e7-859f-81b470cc3073.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @santoshmath, and @mbj36.

**Comment by ankit01ojha** [comment]
I am sending PR for this.

**Comment by gkrishnan724** [comment]
@ankit01ojha I don't understand why this is a bug. Please look at the user-manual description field is not supposed to be mandatory. https://mifosforge.jira.com/wiki/spaces/docs/pages/86114424/Teller+Cashier+Management

**Comment by gkrishnan724** [comment]
@ankit01ojha Sorry, I understood the bug now, the problem is description field is acting as mandatory while it is not supposed to be mandatory. So please remove the mandatory validation from the description field instead of making it mandatory.
