### ISSUE TITLE
```Submitted on``` field in Shares Application form is neither aligned nor working properly.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2701]
## Description
The issue has two parts:-
1. The``` submitted on``` field is not aligned properly.
2. The ```submitted on``` field is not behaving properly. When the date is selected it still shows validation message ``` required field``` ( as shown in the gif below).

## Steps to Reproduce
Client>>select any client>>new share account.

## Expected Behaviour
1. Alignment should be proper.
2. It should accept the date without showing any error message.

## Actual Behaviour
1.  ```submitted on```  field is not aligned properly.
2.  ```submitted on``` field is showing validation error message when any date is selected at first.
## Settings
- Mifos X version: Version 17.07.01.RELEASE
- Browser used: chrome.

##Screenshot:
![screenshot at 2017-12-29 22 23 59](https://user-images.githubusercontent.com/21126132/34442269-fd1bd72a-ece6-11e7-8ed6-327bc58e3d4a.png)

## Screencast : 

![peek 2017-12-29 23-01](https://user-images.githubusercontent.com/21126132/34443020-3b73e666-ecec-11e7-8c80-b3ae6b96217f.gif)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @santoshmath.

**Comment by ankit01ojha** [comment]
I am working on it.

**Comment by ankit01ojha** [comment]
@tanmayanand44 This issue has two parts which needs to be fixed. Although I was working on it and since, you have sent the PR, you can work on this issue.

**Comment by tanmayanand44** [comment]
@ankit01ojha Thanks.

**Comment by santoshconflux** [comment]
Duplicate https://github.com/openMF/community-app/issues/2972
