### ISSUE TITLE
the message is blinking again and again even if pointer is not moving

### ISSUE THREAD

**Issue by ShazamDC** [openMF/community-app#2703]
# Description
the message is blinking again and again even if the the pointer is not moving

## Steps to Reproduce
1.go to clients,create clients.
2.move the pointer to family members button or address button.
3. the starts blinking again and again when the pointer is at the upper part of the button and becomes normal when it is moved to lower part of button
3. the starts blinking again and again when the pointer is at the upper part of the button and becomes normal when it is moved to lower part of button
## Expected Behaviour
the message should stay there when the mouse stays in the range of add button
## Actual Behaviour
the message is blinking again and again if mouse is not moving
## Settings
- Mifos X version: Version 17.07.01.RELEASE
- Browser used:google chrome
##screenshots
![anima](https://user-images.githubusercontent.com/34887754/34449438-20863aa2-ed1e-11e7-890f-5ebf56c4661a.gif)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.
