### ISSUE TITLE
UI bug in "cashiersForTeller" page

### ISSUE THREAD

**Issue by shubhshrma** [openMF/community-app#2707]
## Description
The row containing the text input field and new cashier button is slightly going down due to text above it. 

## Steps to Reproduce
Go to admin > organization > teller/cashier > click on any teller
## Expected Behaviour
The container of the row should adjust height according to content
## Actual Behaviour
The container has fixed height.
## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Firefox

## Screenshots, if any
![screenshot from 2018-01-02 13-11-41](https://user-images.githubusercontent.com/20224346/34477356-a1d8a682-efbf-11e7-9faa-9c4825db243b.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by jervis446** [comment]
can i work on this?

**Comment by mbj36** [comment]
@jervis446  Yes

**Comment by jervis446** [comment]
![screenshot-2018-1-2 mifos x client 1](https://user-images.githubusercontent.com/22105326/34493029-07f163c8-f010-11e7-887b-90ff60c04f76.png)

**Comment by gkrishnan724** [comment]
Fixed as per #2711
