### ISSUE TITLE
Deposit Frequency is mandatory in Recurring Deposit Application

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2708]
## Description
Deposit Frequency is mandatory in Recurring Deposit Application.

## Steps to Reproduce
Client>>New Recurring Deposit.

## Expected Behaviour
Mandatory mark should be present in the Deposit Frequency field.

## Actual Behaviour
Mandatory mark is missing in the Deposit Frequency field and is throwing an error.
## Settings
- Mifos X version:17.07.01.RELEASE
- Browser used: Chrome

## Screenshots, if any
![screenshot at 2018-01-02 18 17 49](https://user-images.githubusercontent.com/21126132/34484432-9dffca38-efea-11e7-8445-addf81f21841.png)

As it is clear in the error message(the last one) that the deposit frequency is mandatory.

**Comment by ankit01ojha** [comment]
@gkrishnan724  @santoshmath , should the ```deposit period``` be also made mandatory?

**Comment by santoshmath** [comment]
@ankit01ojha , deposit frequency is mandatory.  You didn't provide deposit frequency so, it's throwing the error. Why did you raise this issue?

**Comment by ankit01ojha** [comment]
@santoshmath , the required field mark is missing in the deposit frequency field.
