### ISSUE TITLE
New loan application 

### ISSUE THREAD

**Issue by ShazamDC** [openMF/community-app#2712]
## Description
the size of the input box is depending on the options . that is why it is going out of the form box.the input box width is given auto.

## Steps to Reproduce
go to clients,click on any client,new loan.

## Expected Behaviour
the input box should not go out of box
## Actual Behaviour
the input box of fund is going out of form box 
## Settings
- Mifos X version: 17.07.01
- Browser used:chrome 

## Screenshots, if any
![newloanapp](https://user-images.githubusercontent.com/34887754/34498776-25165a3a-f029-11e7-9052-d773a3360a0e.PNG)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by risingone** [comment]
I would be taking this up if its fine.

**Comment by ShazamDC** [comment]
i am also taking this

**Comment by tanmayanand44** [comment]
I will also try this issue

**Comment by risingone** [comment]
@ShazamDC Sure, you can take this up, since you found the bug. When I saw this issue no one had commented so I did.

**Comment by anweshknayak** [comment]
duplicate of #2668 @mbj36

**Comment by bharathcgowda** [comment]
this issue is fixed, hence closing this
![image](https://user-images.githubusercontent.com/65952533/116776486-48e15a80-aa86-11eb-81a6-02b8be0ecdad.png)
