### ISSUE TITLE
Display relevant error messages when attempting to submit wizard for new notifications. 

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2717]
## Description
When attempting to save a new notification of the type scheduled, the wizard doesn't actually proceed to save during final step. 

No error message was displayed and it was only when I realized that the "Schedule Date" wasn't after the submission date that I understood why it wasn't being submitted. 

Error messages should be displayed reflecting why the wizard is not successfully being submitted.
 

## Steps to Reproduce
https://mobile.openmf.org  (mifos/password)

Go to Organization> Sms Campaigns and click on '+Create Campaign' 

Then, check 'Is Notification' (it  makes self service app notification in stead of sms)

Then,

Triggered Type : Scheduled
Schedule Date (select any date on or before the current date)

Business Rule: Active Loans 
 
Office: Head Office:

Loan Type: All
 
Loan Officer : All

Then once click on 'Proceed' Button, it's not going anywhere.

Relevant Error message should be displayed. 
  

![screen shot 2018-01-02 at 11 53 58 pm](https://user-images.githubusercontent.com/823454/34512721-f90ca49a-f018-11e7-96db-c1877737319b.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @santoshmath.

**Comment by aashish-ak** [comment]
Hey @santoshconflux  @edcable  I tried reproducing this issue and i set the scheduled date to `6thFeb` i.e today's date and i was able to create the campaign but when i tried editing the campaign, the uneditable scheduled date was visible as `7thFeb` which is after the submission date i.e `6thFeb` which is correct, that's why we're able to create a campaign successfully without any problem, I'm interested in working on this issue but now i'm a little confused, so please guide me a little.
Thanks

**Comment by aashish-ak** [comment]
@edcable @santoshconflux  A little help needed here!

**Comment by santoshconflux** [comment]
@aashish-ak , let me know.

**Comment by abhaychawla** [comment]
@santoshconflux It seems this issue is already resolved as pointed out by @punwai. I checked the previous dates are no longer selectable. I think we should close. Please verify.

**Comment by santoshconflux** [comment]
@edcable , while you were testing before raising this ticket, was there any business rule 'Active loans' as you mentioned in the description?  I can only see 'Active Loan Clients'  in business rule drop-down. 
Anyway, we will close this ticket as 'Proceed' button is working fine for other business rules. 
Cc: @abhaychawla , @punwai
