### ISSUE TITLE
Fix Typos in SMS Campaigns Views

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2718]
<img width="1157" alt="screen shot 2018-01-03 at 12 00 05 am" src="https://user-images.githubusercontent.com/823454/34512899-148421f2-f01a-11e7-8a15-eb0dd7ab0c0f.png">
<img width="1173" alt="screen shot 2018-01-03 at 12 04 25 am" src="https://user-images.githubusercontent.com/823454/34512900-149c4ba6-f01a-11e7-9c6d-3bb286875319.png">

## Description
There are several very glaring typos  in the SMS Campaigns module.

## Steps to Reproduce
1) Navigate to Organization >> SMS Campaigns. The title reads "SMScampaings" rather than SMS Campaigns. 
2) View Campaigns has a typo as well. From SMS Campaigns click any campaign to view it. Title says "View SMS Campain" instead of View SMS Campaign
3) Edit Campaigns has a typo too. From a Schedules SMS Campaign that is still pending, click edit. The next title should read Edit SMS Campaign but it says "Edit SMS Campain"

This all occurred on https://mobile.openmf.org with credentials mifos/password

See attached screenshots.
<img width="1148" alt="screen shot 2018-01-02 at 11 56 27 pm" src="https://user-images.githubusercontent.com/823454/34512887-f525f43e-f019-11e7-9e6b-70f79787d8f0.png">

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by santoshconflux** [comment]
Tested on https://mobile.openmf.org, Fixed.
