### ISSUE TITLE
Bug in user create and edit user - (admin) in available roles and selected roles section

### ISSUE THREAD

**Issue by luphieanza** [openMF/community-app#2721]
# Description
<h4>This bug can cause the admin user to create multiple roles that can impact a user can control any roles, this can cause users to cheat an office and staff their part.</h4>

# Steps to Reproduce a Bug
- Go To Mifos Community -app home page -> 
- then navigate to Admin Tab -> 
- choose Users -> 
- click Create User ->
- fill in any identity profile -> 
- at the time of filling the Available Roles section to Selected Roles (which is mandatory) then move the available roles in available roles to selected roles in large quantities (use Shift + right click mouse to select multiple roles) -> 
- if there are already many roles moved to selected click the submit button and see the results.

# Expected Behaviour
![expected-bug1](https://user-images.githubusercontent.com/20577131/34593240-3bbafbb8-f1fc-11e7-82a1-f2bdcfca05b9.png)
### At least limited when choosing the desired roles, do not get to take all the roles, it can cause incoming access to cheat easily.

![expected-bug2](https://user-images.githubusercontent.com/20577131/34593243-3dbe5c70-f1fc-11e7-9430-59c40a0a3ecd.png)
### When restricted this could allow the performance of mifos web app platform more secure and users will be able to trust with the security of this platform.

# Actual Behaviour
![actual-bug1](https://user-images.githubusercontent.com/20577131/34593410-3bf50474-f1fd-11e7-949c-42de6d2c2ee9.png)
![actual-bug2](https://user-images.githubusercontent.com/20577131/34593411-3d23fa12-f1fd-11e7-8b38-063f712db525.png)
![actual-bug3](https://user-images.githubusercontent.com/20577131/34593412-3ea0974c-f1fd-11e7-97e5-063927f8fd21.png) 
### This also happens when editing a user.

# Settings
- Mifos X version: 17.07.01.RELEASE | Mifos X Release Date: 14/Jul/2017 
- Browser used: Mozilla Firefox 57.0.3, already tried also in IE but even an error in the login view

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, @santoshmath, and @Agnessy.

**Comment by ankit01ojha** [comment]
I would like to work on it.

**Comment by ankit01ojha** [comment]
@luphieanza , https://mifosforge.jira.com/wiki/spaces/docs/pages/67141740/Users#Users-Add/RemoveUserRole . It does not say anything about the restrictions on selecting the number of roles.

**Comment by luphieanza** [comment]
yes GCI 2017 (Find And Report Three Bugs Or Usability Improvements In The Mifos X Web App).
try to read the description of the issue, sir.
