### ISSUE TITLE
Incorrect column names in "view closed loans"

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2723]
## Description
Incorrect column names in "view closed loans" in Loan Account Overview.

## Steps to Reproduce
Client>>Select an active client>>Loan Account Overview>>Click on view closed loans.

## Expected Behaviour
Correct columns names as per the data.
## Actual Behaviour
Incorrect column names as per the data.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: chrome

## Screenshots, if any
![screenshot at 2018-01-05 11 45 33](https://user-images.githubusercontent.com/21126132/34597642-f6c4f7e0-f20d-11e7-9626-318fb2c4e87e.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
