### ISSUE TITLE
Edit buttons not aligned properly

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2729]
## Description
Edit buttons not aligned properly throughout the webpage

## Steps to Reproduce
Admin->product->Loan Products

## Expected Behaviour
proper padding required

## Actual Behaviour
not aligned

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
![screenshot from 2018-01-05 16 14 07](https://user-images.githubusercontent.com/8139783/34606244-aad3d67c-f234-11e7-9b4e-d8466b607757.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by SupreethSudhakaranMenon** [comment]
As per the issue , @anweshknayak  , i have fixed the issue by properly aligning the edit button.
Below will be attaching the screenshot of the same.
![#2729](https://user-images.githubusercontent.com/45706852/54471111-e2cbe780-47d9-11e9-9df2-d61dbbfcb0dd.png)
