### ISSUE TITLE
Non-Uniformity of Clients,Groups,Centers list

### ISSUE THREAD

**Issue by zapdoss** [openMF/community-app#2736]
## Description
The three sections under Clients have tables, however the formatting is not uniform.

## Steps to Reproduce
Make the layout of the 3 sub sections uniform by separation of rows. In short making Groups and Centers subsections same as that of Clients, as there in the screenshots below.
## Actual Behaviour
Non Uniformity in the layout of the tables

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
![screenshot from 2018-01-06 04-32-16](https://user-images.githubusercontent.com/15995980/34632343-deb4105e-f29a-11e7-8fa5-804b364a021e.png)
![screenshot from 2018-01-06 04-32-22](https://user-images.githubusercontent.com/15995980/34632351-e54fa20c-f29a-11e7-8a32-e39ce9d4dd11.png)
![screenshot from 2018-01-06 04-32-37](https://user-images.githubusercontent.com/15995980/34632353-e87ff72e-f29a-11e7-9c32-064edbbba386.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, @anweshknayak, and @ankit01ojha.

**Comment by zapdoss** [comment]
I am working on the issue.
