### ISSUE TITLE
Proper alignment of buttons in any client

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2739]
## Description
Proper alignment of buttons in any client

## Steps to Reproduce
Clients -> choose any client -> Buttons like(View close loans and changes overview needs proper padding

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any
![screenshot from 2018-01-06 18 02 12](https://user-images.githubusercontent.com/8139783/34639839-99a41d06-f30d-11e7-9756-b90e7ab4ad96.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by anweshknayak** [comment]
on this
