### ISSUE TITLE
Scroll to top button not working 

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2742]
## Description
Provide a brief overview of the enhancement or issue.

## Steps to Reproduce
Scroll to top button at the right bottom corner doesn't work
Products -> Loan products -> Choose any loan product -> Scroll to top button at bottom doesn't work

## Expected Behaviour
Scroll to top should work wherever it is present 

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any
![screenshot from 2018-01-06 18 46 35](https://user-images.githubusercontent.com/8139783/34640131-1670e936-f313-11e7-8ef1-a10ccdd6da33.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by anweshknayak** [comment]
Im on this
