### ISSUE TITLE
Unable to select Date of Birth of Client before 1/01/2018

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2743]
## Description
Unable to select Date Of Birth of Client before 1/01/2018.

## Steps to Reproduce
Clients>>Create Client>>Select Date of Birth.

## Expected Behaviour
Able to select Date Of Birth before 1/01/2018.
## Actual Behaviour
Unable to select Date Of Birth before 1/01/2018.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-01-06 19 34 18](https://user-images.githubusercontent.com/21126132/34640484-77ba878c-f319-11e7-8638-cc463dedf963.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
