### ISSUE TITLE
Fields not aligned properly in charges of "New Application Loan" form.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2745]
## Description
While adding new charges the fields displayed are not properly aligned.

## Steps to Reproduce
Clients>>Select any client>>new loan >>select any product>>In the charges form, select add charges.

## Expected Behaviour
Fields are not properly aligned.
## Actual Behaviour
Fields should be properly aligned.
## Settings
- Mifos X version:  17.07.01.RELEASE 
- Browser used: Google-Chrome

## Screenshots, if any
![loan](https://user-images.githubusercontent.com/21126132/34641480-57e1f1c2-f32b-11e7-9211-69d7135ed35f.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
