### ISSUE TITLE
No validation for existing funds

### ISSUE THREAD

**Issue by anu-007** [openMF/community-app#2749]
## Description
Under organization >> manage funds there is no validation of existing funds i.e. if we edit an existing fund and leave it blank and hit save, then we didn't get any warning.

## Steps to Reproduce
organization >> manage funds edit any existing fund and leave it blank and hit save.

## Expected Behaviour
there should be a warning if we leave an existing field empty.

## Actual Behaviour
there is no warning if we leave an existing fund field empty.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: google-chrome 63

## Screenshots, if any
![screen shot 2018-01-07 at 2 54 09 am](https://user-images.githubusercontent.com/20153241/34644085-1b047a9c-f356-11e7-80d5-4542d26b298f.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by anu-007** [comment]
I like to work on this.
