### ISSUE TITLE
Buttons not aligned in Interest Rate charts

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2754]
## Description
Buttons not aligned in Interest Rate charts in Products subgroups(Fixed Deposits, Recurring deposits etc)

## Steps to Reproduce
Products ->Fixed Deposit Products -> Choose any product -> Edit Interest Rate charts

## Expected Behaviour
Should be aligned 

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any
![screenshot from 2018-01-07 03 08 07](https://user-images.githubusercontent.com/8139783/34644703-96e3e228-f361-11e7-9ab9-bc97e587d3cb.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @Agnessy.

**Comment by anweshknayak** [comment]
Claiming this
