### ISSUE TITLE
Overflow of table header in Incentives popup

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2755]
## Description
Overflow of table header in Incentives popup

## Steps to Reproduce
Products -> Fixed Deposit-> Products  -> Interest Rate Charts -> Create Interest -> Rate Chart Incentives

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
![commun](https://user-images.githubusercontent.com/8139783/34644755-a4524f52-f362-11e7-9716-8d0b84812f5d.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by anweshknayak** [comment]
claiming this

**Comment by anweshknayak** [comment]
@gkrishnan724 close this one instead of #2775 . Changed the title of PR here https://github.com/openMF/community-app/pull/2918
