### ISSUE TITLE
 Button alignment in templates subsection and accounting

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2756]
## Description
 Button alignment in templates subsection

## Steps to Reproduce
1. Templates -> Choose anyone -> Advance options 
2. Accounting ->Accural -> Run periodic accurals
## Settings
- Mifos X version: 
- Browser used:Chrome

## Screenshots, if any
![screenshot from 2018-01-07 04 18 01](https://user-images.githubusercontent.com/8139783/34644772-0d065142-f363-11e7-9217-87c2f31702a8.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by anweshknayak** [comment]
Claiming this

**Comment by tanmayanand44** [comment]
@anweshknayak Can I assist you on this issue.

**Comment by anweshknayak** [comment]
moving to #2775 closing this
