### ISSUE TITLE
Popover keeps on flashing in Create User

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2757]
## Description
The popover message for Override password expiry policy in create user section keeps on flashing and thus cannot be read properly.

## Steps to Reproduce
Admin -> Users -> Create User -> Hover the mouse over question mark sign for Override password expiry policy

## Expected Behaviour
Popover should be visible on hovering the mouse over question mark sign

## Actual Behaviour
Popover keeps on flashing on hovering the mover over question mark sign

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 68](https://user-images.githubusercontent.com/16948598/34644799-67062e24-f363-11e7-84a3-bf1b061e0ba6.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by abhaychawla** [comment]
I am working on this.

**Comment by ankit01ojha** [comment]
@abhaychawla , Can you please check if this error is present in other places too. If this issue is at other places too then you can change the name of the issue to ```Flashing popover```. And send a PR with a combined fix. Because this issue was same like this one https://github.com/openMF/community-app/issues/2703 .

**Comment by abhaychawla** [comment]
@ankit01ojha Sure, I'll check an create a single issue!
