### ISSUE TITLE
In Editing Templates, the Template Keys preview is out of bound.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2759]
## Description
The template keys in the preview are out of the box.

## Steps to Reproduce
Admin>>Templates>>Select any template(of long template keys)>>Edit Template.
## Expected Behaviour
It should be inside the box.
## Actual Behaviour
Long template keys are out getting out of the box.
## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-01-07 10 18 55](https://user-images.githubusercontent.com/21126132/34646702-ed99faa2-f394-11e7-9550-6db2113d865f.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.

**Comment by anweshknayak** [comment]
duplicate of #2373. You can proceed from there

**Comment by ankit01ojha** [comment]
@anweshknayak , thanks :)
Since, #2373 is GCI labeled so it should be fixed after the GCI.
I am closing this issue then.
