### ISSUE TITLE
Popover description is not showing the description in settings part of "Create loan application".

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2760]
## Description
The popover is not showing proper description in most of the fields of the settings part of "Create loan application".

## Steps to Reproduce
Admin>>Products>>Loan products>>Create loan product>>Go to Settings part>>hover over popover of  Interest calculation period, Interest calculation period, Moratorium etc.

## Expected Behaviour
Should display the description.
## Actual Behaviour
Not showing the description.
## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-01-07 10 36 48](https://user-images.githubusercontent.com/21126132/34646872-355c1f24-f399-11e7-8aed-3344a3daccc0.png)
![screenshot at 2018-01-07 10 53 11](https://user-images.githubusercontent.com/21126132/34646873-35ac46ca-f399-11e7-8c41-3f84ad23d235.png)
![screenshot at 2018-01-07 10 53 15](https://user-images.githubusercontent.com/21126132/34646874-35eaedb2-f399-11e7-9444-4dbdfcc3bde2.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
