### ISSUE TITLE
Form validation missing in certain fields of "Create Fixed Deposit Product" form.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2763]
## Description
Form validation is missing from ```Minimum Deposit Term* ```  & ```Valid form Date ``` and ```description``` is not marked required. 
## Steps to Reproduce
Admin>>Fixed Deposit Product>>Create Fixed Deposit.

## Expected Behaviour
An error message should be displayed when pressed next on these mentioned fields.
## Actual Behaviour
No error is displayed when pressed next in these mentioned fields.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-01-07 12 56 19](https://user-images.githubusercontent.com/21126132/34647537-0d6a396c-f3ab-11e7-9339-33c6fa283175.png)
![screenshot at 2018-01-07 12 56 43](https://user-images.githubusercontent.com/21126132/34647539-0dcc3fc2-f3ab-11e7-9cca-a6b9217c120f.png)
![screenshot at 2018-01-07 12 57 00](https://user-images.githubusercontent.com/21126132/34647540-0e0b5a90-f3ab-11e7-90f5-8f5e1f6204bc.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
