### ISSUE TITLE
Create Group screen has redundant/non-functioning buttons

### ISSUE THREAD

**Issue by MYKatz** [openMF/community-app#2764]
## Description
On the "create group" screen there are two buttons at the very bottom: next and previous.  The previous button does not work (in my testing) and the next button just functions as a submit button.  These buttons aren't necessary as there already are cancel and submit buttons.

## Steps to Reproduce
Go to clients -> groups -> create new group and scroll down

## Expected Behaviour
Cancel and submit buttons
## Actual Behaviour
Cancel and submit buttons, + nonfunctioning previous button and next button.
## Settings
- Mifos X version: 17.07.01.RELEASE (cloned from this repository)
- Browser used: Google chrome

## Screenshots, if any
![screenshot 42](https://user-images.githubusercontent.com/23515048/34647670-276e18b0-f33d-11e7-8f32-4f9591a3b95f.jpeg)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by ankit01ojha** [comment]
claiming this one :)

**Comment by ankit01ojha** [comment]
@MYKatz , Actually these buttons are not redundant. When an entity is created for group these buttons(which are the part of wizard) are used to move to the next form.
![screenshot at 2018-01-14 03 00 07](https://user-images.githubusercontent.com/21126132/34910322-4c12d2fa-f8d8-11e7-8616-804160647646.png)
