### ISSUE TITLE
Ambiguous "buttons" on create template

### ISSUE THREAD

**Issue by MYKatz** [openMF/community-app#2765]
## Description
On the "create template" screen, there are pieces of text one can click to add certain variables into a template.  They function fine, but their use is somewhat ambiguous, and may look like a glitch at first glance.

## Steps to Reproduce
Admin -> templates -> create template

## Expected Behaviour
Text should be styled as buttons, or at least have some indication that they are clickable (change of pointer to hand)
## Actual Behaviour
Buttons look like normal text and their use is not obvious.
## Settings
- Mifos X version: 17.07.01.RELEASE (cloned from this repository)
- Browser used: Google Chrome

## Screenshots, if any
I highlighted the text I'm talking about:
![screenshot 44](https://user-images.githubusercontent.com/23515048/34647691-e896c190-f33d-11e7-94d1-e521bed4c26f.jpeg)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by anweshknayak** [comment]
duplicate of #2373

**Comment by santoshconflux** [comment]
Tested on Staging. Fixed.
