### ISSUE TITLE
Validation and Popover issue in Floating Rate Section

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2766]
## Description
1) Asterisks are missing for fields From Date and Interest Rate which are required fields
2) Question mark help icons for popovers are not properly aligned for Floating Rate Name and Floating Rate Periods
3) Popovers keep on flashing on hovering mouse over the question mark icons of Floating Rate Name, Is Base Lending Rate
4) On creation of a floating rate, label for Is base lending rate is improperly aligned in the review page

Similar issues were present while creating and editing the floating rate.

## Steps to Reproduce
Products -> Floating Rates -> Create Floating Rate
Products -> Floating Rates -> Select any floating rate -> Edit

## Expected Behaviour
1) Asterisks should be present for all required fields
2) Proper alignment of question mark icons
3) Popover should be visible on hovering mouse over question mark icons
4) Label should be properly aligned

## Actual Behaviour
1) Asterisks are absent for some required fields
2) Some question mark icons are not properly aligned
3) Popover flashes on hovering mouse over some question mark icons
4) Label is improperly aligned 

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 73](https://user-images.githubusercontent.com/16948598/34647692-10b8c486-f3af-11e7-96f8-76196299414b.png)
![screenshot 74](https://user-images.githubusercontent.com/16948598/34647705-c69b05ca-f3af-11e7-85be-3543f0bafc59.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by abhaychawla** [comment]
I am working on this issue.

**Comment by ankit01ojha** [comment]
@abhaychawla , for popover blinking issue please see the comment in https://github.com/openMF/community-app/issues/2757.
