### ISSUE TITLE
Spelling Mistake on "add client identifier"

### ISSUE THREAD

**Issue by MYKatz** [openMF/community-app#2767]
## Description
There is a spelling mistake on add client identifier.

## Steps to Reproduce
Go to any client page, then click on the identities tab, then click add.

## Expected Behaviour
First option should be "National ID"
## Actual Behaviour
First option is "Natioanal ID"
## Settings
Mifos X version: 17.07.01.RELEASE (cloned from this repository)
Browser used: Google chrome

## Screenshots, if any
![screenshot 46](https://user-images.githubusercontent.com/23515048/34647711-d1ee3ea4-f33e-11e7-955a-fde3b990f890.jpeg)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by tanmayanand44** [comment]
@MYKatz @mbj36 Can I work on this issue?

**Comment by elisepope96** [comment]
@mbj36 @MYKatz If this is still open, I would like to work on it.

**Comment by ankit01ojha** [comment]
@elisepope96 yes, this issue is still open.

**Comment by santoshconflux** [comment]
fixed.
