### ISSUE TITLE
Breadcrumb links to nonexistent page in "add charge"

### ISSUE THREAD

**Issue by MYKatz** [openMF/community-app#2769]
## Description
The breadcrumb when adding a charge links to a 404 error.

## Steps to Reproduce
Go to any client page -> "+ add charge" -> click on "view client" in the breadcrumb.  

## Expected Behaviour
Goes back to the client's page (viewclient/[id]), ex: /viewclient/42
## Actual Behaviour
Goes to a nonexistent page, /viewclient/
## Settings
Mifos X version: 17.07.01.RELEASE (cloned from this repository)
Browser used: Google chrome

## Screenshots, if any
Clicking on the circled link takes the user to a 404 page
![screenshot 47](https://user-images.githubusercontent.com/23515048/34647758-63ca2c1a-f340-11e7-9c8a-635ac11a9b4a.jpeg)

**Comment by abhaychawla** [comment]
I will work on this issue.
