### ISSUE TITLE
Remove button should be more bold and informative

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2776]
## Description
Remove button should be more bold and informative

## Steps to Reproduce
Client -> Create client -> Add family members -> Remove

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any

![screenshot from 2018-01-07 19 24 00](https://user-images.githubusercontent.com/8139783/34650135-cee192c6-f3e1-11e7-9d9c-0edc2adea6ef.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by anweshknayak** [comment]
Claiming this
