### ISSUE TITLE
Scroll to top parent thread

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2777]
## Description
Scroll to top button to be implemented in missing pages

- [x] Report 
- [x] Accounting
- [x] Clients 

## Settings
- Mifos X version: 
- Browser used:

## Claiming this 
 Yes

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by anweshknayak** [comment]
@abhaychawla I have almost done it. Just some few work left. Will send a pr soon

**Comment by anweshknayak** [comment]
Have implemented most of it. What is left I will add to the checklist.
