### ISSUE TITLE
When viewing a Client, scroll button does not move in the proper direction

### ISSUE THREAD

**Issue by AkashBhave** [openMF/community-app#2779]
## Description
When viewing a Client, the list of DataTables does not scroll in the proper direction. Each button should scroll in its corresponding direction, but instead, both the _right_ and the _left_ buttons scroll in the _right_ direction.

## Steps to Reproduce

1. On the top nav-bar, click on Clients > Clients.
2. Select any Client from the list of clients.
3. Right below the Client's name, there should be a horizontal list of DataTable names. These include "General", "Address", "Family Members", etc.
4. There should be two arrow buttons on each side of the list, left (<) and right (>). Click on these buttons to scroll the list.

## Expected Behavior
Clicking the _right_ (>) button should scroll the list in the _right_ direction. Clicking the _left_ (<) button should scroll the list in the _left_ direction.

## Actual Behavior
Clicking the _right_ (>) button scrolls the list in the _right_ direction. Clicking the _left_ (<) button **also** scrolls the list in the _right_ direction.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Mifos X release date: 14/Jul/2017
- Browser used: Google Chrome, Version 63.0.3239.84 (Official Build) (64-bit)

## Screenshots
![gif](https://user-images.githubusercontent.com/16819026/34651931-9ae0eae4-f3a5-11e7-9206-d7cf389c5ed2.gif)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by tanmayanand44** [comment]
@AkashBhave @mbj36  Can I work on this?

**Comment by tanmayanand44** [comment]
@AkashBhave The left and right buttons are working fine.

**Comment by tanmayanand44** [comment]
![scroll](https://user-images.githubusercontent.com/33908900/34683687-cf55a8fe-f4c8-11e7-9bd8-c988dd848385.gif)

**Comment by AkashBhave** [comment]
@tanmayanand44 Interesting. It doesn't work on my end. Maybe it's a browser compatibility issue. If you look at my screenshot, you can see that both buttons go in one direction.

**Comment by tanmayanand44** [comment]
@AkashBhave Yes you are right. Can you recheck it.

**Comment by jonathanzhang53** [comment]
This is working correctly for me on Windows Chrome.

![scroll](https://user-images.githubusercontent.com/41968151/48654967-24d55000-e9d7-11e8-8ecd-ee5822d428d3.gif)

**Comment by santoshconflux** [comment]
Fixed.
