### ISSUE TITLE
Show items in drop-down in top navbar on hover

### ISSUE THREAD

**Issue by AkashBhave** [openMF/community-app#2781]
## Description
This is a usability improvement. The Mifos X web client would be easier to navigate if the items in a drop-down in the top navbar were shown on hover. That way, a user could simply hover over a drop-down menu, such as "Admin", and select where they want to navigate to. 

## Steps to Reproduce
1. Login to the Mifos X web client.
2. Navigate to any page, or stay on the home page.
3. This issue pertains to the navigation bar that is shown at the top of the screen. The items in the navbar include "Clients", "Accounting", "Reports", and "Admin".

## Expected Behavior
The user should be able to hover over a drop-down menu to view the items and to navigate to them.

## Actual Behavior
The user has to click on each of the drop-down menus to view the items and to navigate to them.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Mifos X release date: 14/Jul/2017
- Browser used: Google Chrome, Version 63.0.3239.84 (Official Build) (64-bit)

## Screenshots
![gif](https://user-images.githubusercontent.com/16819026/34653144-9a8b7450-f3b5-11e7-96ff-b41c41092884.gif)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by shubhshrma** [comment]
@AkashBhave are you working on this?

**Comment by AkashBhave** [comment]
@shubhshrma Yes, I am working on this issue at the moment.
