### ISSUE TITLE
Form Validation is missing from many fields in the app.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2784]
## Description
Form Validation is missing from many fields in the app. Because of that, these fields are not showing ```required fields``` beside them when they are not filled by the user( although they are required).

## List of locations where it is missing:-

- [x]  Create Standing Instructions
- [x]  Create Closure
- [x]  Migrate opening balances
- [x]  Frequent Postings
- [x] Add Journal Entries
- [x] Create Entity-Data Table Check
- [x] Currency Configuration
- [x] Create Payment Type
- [x] Create Campaign
- [x] Create Data Table
- [x] Create Hook
- [x] Add Account Number Preferences
- [x] Create Loan Product
- [x] Create Share Product
- [x] Create Recurring Deposit Product (valid from date)
- [x] Create Group
- [x] Add Financial Activity Mapping
- [x] Create User

## Expected Behaviour
```Required field``` message is not displayed
## Actual Behaviour
```Required field``` message should be displayed
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
@gkrishnan724 Would it be nice if I create a single commit and add all the changes or shall I create different commits for different files/forms.

**Comment by gkrishnan724** [comment]
@ankit01ojha, please create a list of places where this is happening and then start working on this
