### ISSUE TITLE
Holiday Table Overflow the content div 

### ISSUE THREAD

**Issue by Jov03** [openMF/community-app#2785]
## Description
Holiday table overflow the div with content class.

## Settings
- Mifos X version:17.07.01.RELEASE 
- Browser used:Chrome

## Screenshots
![screen shot 2018-01-08 at 2 49 20 pm](https://user-images.githubusercontent.com/15383669/34665234-6dbeb54c-f485-11e7-9881-20636514f78a.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by edcable** [comment]
Closing issue as fixed.
