### ISSUE TITLE
Validation message overlaps with dropdown in Create Entity Data Table Checks

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2789]
## Description
The validation messages overlap with the dropdowns while creation of an entity for data table checks.

## Steps to Reproduce
Admin -> Organisation -> Entity Data Table Checks -> Create Entity-Data Table Check
Leaving dropdowns blank press submit.

## Expected Behaviour
The validation messages for required fields should not overlap with the dropdowns.

## Actual Behaviour
The validation messages for required fields are overlapping with the dropdowns.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 83](https://user-images.githubusercontent.com/16948598/34675981-3d4b4570-f4b1-11e7-8007-49f40698df90.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by abhaychawla** [comment]
I am taking up this issue.
