### ISSUE TITLE
Create fixed deposit product form does not have numeric value validation.

### ISSUE THREAD

**Issue by Jov03** [openMF/community-app#2794]
## Description
Create fixed deposit product form does not have numeric value check validation which allows the user to fill the entire form with alphanumeric characters and when we submit only then error is displayed 

## Expected Behaviour
field where numeric values has to be entered should be validated as the user is filling the form.

## Settings
- Mifos X version: 17.07.01
- Browser used:Safari

## Screenshots, if any
![screen shot 2018-01-09 at 4 13 06 am](https://user-images.githubusercontent.com/15383669/34696970-dffce180-f4f6-11e7-812e-7f5fc35900ff.png)
![screen shot 2018-01-09 at 3 56 44 am](https://user-images.githubusercontent.com/15383669/34696980-e608a06e-f4f6-11e7-9422-274a20b1e948.png)
![screen shot 2018-01-09 at 4 04 36 am](https://user-images.githubusercontent.com/15383669/34696994-f78ea7a2-f4f6-11e7-846f-b956667cfbf8.png)
![screen shot 2018-01-09 at 4 05 08 am](https://user-images.githubusercontent.com/15383669/34696989-f3689656-f4f6-11e7-9cc7-d92c8a203fb4.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by Jov03** [comment]
I'll take up this issue.

**Comment by santoshconflux** [comment]
In terms, there is still no validation. 

![terms](https://user-images.githubusercontent.com/23022667/50753842-5fda5e00-1279-11e9-967e-3e2e7fa51047.png)

**Comment by abhaychawla** [comment]
@santoshconflux there is an existing PR for this: https://github.com/openMF/community-app/pull/3071

**Comment by Jov03** [comment]
@santoshconflux i have fixed this issue in PR #3071 the changes have been approved by both @abhaychawla and @ShruthiRajaram but @ShruthiRajaram asked to get successful travis build before she could merge the PR. Now Travis builds are failing due to issue explained in #3077 . I even raised this problem on mailing list looking forward for some help.

**Comment by santoshconflux** [comment]
Ok. Got your point.

**Comment by Nayan** [comment]
@santoshconflux @edcable related PR is already merged, so moving to ready for testing

**Comment by santoshconflux** [comment]
Thanks @Nayan
