### ISSUE TITLE
User can skip over steps by clicking on progress bar directly which does not validate the data, only clicking on next button does

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2795]
## Description
This issue occurs at following places:
- [x] Create Loan Product
- [x] Create Saving Product
- [x] Create Share Product
- [x] Create Fixed Deposit Product
- [x] Create Recurring Deposit Product

A progress bar indicates the operations of the user. While clicking on the next button validates the data on the current page, clicking directly on the progress bar does not. So there is no visual indication to the user that something must have gone wrong in the page skipped if he clicks directly on the progress bar.

## Steps to Reproduce
Admin -> Products -> Loan Products -> Create Loan Product
Admin -> Products -> Savings Products -> Create Saving Product
Admin -> Products -> Share Products -> Create Share Product
Admin -> Products -> Fixed Deposit Products -> Create Fixed Deposit Product
Admin -> Products -> Recurring Deposit Products -> Create Recurring Deposit Product
Click anywhere on the progress bar (notice no indication of validation)
Click on the next button (notice indication of validation)

## Expected Behaviour
The user should not be allowed to skip over the progress without proper validation of data in the current page. Otherwise, there is no visual indication and the user might get confused if he clicks directly on the progress bar. 

## Actual Behaviour
The progress bar does not validate the data on the page if the user directly clicks on the progress bar, it only validates by clicking the next button.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
Loan Product -> Clicking on the next button
![screenshot 86](https://user-images.githubusercontent.com/16948598/34708003-acbc0842-f536-11e7-9104-08a4965462a2.png)
Loan Product -> Clicking directly on the progress bar
![screenshot 87](https://user-images.githubusercontent.com/16948598/34708051-deafe5bc-f536-11e7-8b83-ad966b2f2a48.png)
Saving Product -> Clicking on the next button
![screenshot 89](https://user-images.githubusercontent.com/16948598/34708063-e9fc06ee-f536-11e7-9314-5f3af6c758f4.png)
Saving Product -> Clicking directly on the progress bar
![screenshot 88](https://user-images.githubusercontent.com/16948598/34708070-f5aa40f0-f536-11e7-9f11-438e8b9231da.png)
Share Product -> Clicking on the next button
![screenshot 101](https://user-images.githubusercontent.com/16948598/34756889-e7d7f6bc-f5f3-11e7-8fc0-720fd7f684b3.png)
Share Product -> Clicking directly on the progress bar
![screenshot 102](https://user-images.githubusercontent.com/16948598/34756902-0573504a-f5f4-11e7-9cd3-54d48973e69c.png)
Fixed Deposit Product -> Clicking on the next button
![screenshot 103](https://user-images.githubusercontent.com/16948598/34756917-257de9f4-f5f4-11e7-939b-c36c498c8d63.png)
Fixed Deposit Product -> Clicking directly on the progress bar
![screenshot 104](https://user-images.githubusercontent.com/16948598/34756927-2a63da50-f5f4-11e7-94e3-94c800a730ba.png)
Recurring Deposit Product -> Clicking on the next button
![screenshot 105](https://user-images.githubusercontent.com/16948598/34756941-393cc7c6-f5f4-11e7-98d4-6f779df5466a.png)
Recurring Deposit Product -> Clicking directly on the progress bar
![screenshot 106](https://user-images.githubusercontent.com/16948598/34756944-3e8738c4-f5f4-11e7-82e5-64bc6aeb64d2.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by abhaychawla** [comment]
I will work on this issue.

**Comment by gkrishnan724** [comment]
@abhaychawla I don't think we should restrict the user from skipping steps, a user might want to fill the details of the step later. Instead of restricting the user from skipping steps, a better method would be to validate when a user switches steps by clicking on the progress bar.

**Comment by abhaychawla** [comment]
Okay I'll work on an update

**Comment by abhaychawla** [comment]
@gkrishnan724 I have updated the PR. Please have a look.
