### ISSUE TITLE
Mifos X Web App - Fix Incorrect icon in Create Group page

### ISSUE THREAD

**Issue by Shivamkumar4848** [openMF/community-app#2797]
## Description
The icon of Add button in **Create Group** page is incorrect.

## Steps to Reproduce
Navigate to **Groups > Create Group**

## Expected Behaviour
There should be a **Plus(+)** icon in  **Add** Button

## Actual Behaviour
The Add button icon is showing **angle-double-right (>>)** icon

## Settings
- Mifos X version: **17.07.01.RELEASE**
- Browser used: **Firefox (Developer Edition) 58.0b13 (64-bit)**

## Screenshot:

![screenshot 29](https://user-images.githubusercontent.com/23031761/34732076-2c99ab02-f58a-11e7-8471-1bef0a92e42a.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by 96mohitm** [comment]
Hi, @mbj36 @ankit01ojha I want to take up this issue.

**Comment by ankit01ojha** [comment]
@Shivamkumar4848 i guess its fine to leave it the way it is as when you add a client it shows the added client to right side from the left side display. I guess its not an issue :)
![screenshot_2018-01-10-12-06-58](https://user-images.githubusercontent.com/21126132/34758985-70fa68fc-f5ff-11e7-961d-79d8f56e6664.png)
