### ISSUE TITLE
Fix Add button icon - Mifos X Web App

### ISSUE THREAD

**Issue by Shivamkumar4848** [openMF/community-app#2800]
## Description
When you view any center, there is an **Add group** button in general section.

## Steps to Reproduce
Navigate to Centres > View any center > General

## Expected Behaviour
In the general section, there should be a **plus (+)** icon in **Add group** button.

## Actual Behaviour
The icon is not showing in **Add group** button.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Firefox (Developer Edition)

## Screenshots:
![screenshot 28](https://user-images.githubusercontent.com/23031761/34766939-7702e720-f61c-11e7-8399-4f695f6fd585.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by siddharth2010** [comment]
I would like to work on this issue.

**Comment by siddharth2010** [comment]
Here it is.
![mifos](https://user-images.githubusercontent.com/32238400/34941754-148b1e48-fa1b-11e7-812c-59110971ec5a.png)

I am sending a pull request regarding this.
