### ISSUE TITLE
Mifos X Web App - Fix Delete button icon

### ISSUE THREAD

**Issue by Shivamkumar4848** [openMF/community-app#2801]
## Description
When you view any User, there is an option for delete user details.

## Steps to Reproduce
Navigate to Admin > Users > Click on any User 

## Expected Behaviour
There should be an icon of delete in the button.

## Actual Behaviour
No any icon in Delete button.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Firefox (Developer Edition)

## Screenshot:
![screenshot 33](https://user-images.githubusercontent.com/23031761/34768137-03f55f98-f620-11e7-8ec7-b0e05ba5464e.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by siddharth2010** [comment]
I would like to work on this issue

**Comment by siddharth2010** [comment]
Here it is:
![final2](https://user-images.githubusercontent.com/32238400/34942658-71fe1622-fa1e-11e7-89fc-4ec8b3076ca8.png)
I am sending a pull request regarding this.

**Comment by santoshconflux** [comment]
Not reproducible
