### ISSUE TITLE
Notes Field Streching Error - Mifos X Web App

### ISSUE THREAD

**Issue by Shivamkumar4848** [openMF/community-app#2802]
## Description
When you view any group, there is an option for add notes in the section of notes.
when you stretch it, there is no limit on that.
It can extend over card also.

## Steps to Reproduce
Navigate to Groups > View any group > Notes

## Expected Behaviour
The card should be extended in a limit of field.

## Actual Behaviour
It is extending over card also.

## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Firefox (Developer Edition)

## Screenshots, if any
![screenshot 35](https://user-images.githubusercontent.com/23031761/34770047-bcc5dd40-f625-11e7-8c70-1947a519f759.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by siddharth2010** [comment]
I would like to work on this issue

**Comment by siddharth2010** [comment]
@Shivamkumar4848 @mbj36 
This is the default size of the notes pane:
![notes](https://user-images.githubusercontent.com/32238400/34943466-cd30acaa-fa21-11e7-8204-da2cd22da98b.png)
I was thinking how about we restrict the resizing of the notes pane to vertical only.
This will solve the issue

**Comment by luckyman20** [comment]
@siddharth2010 We have to restrict on both vertical and horizontal as the user can stretch it to outside of card also.

**Comment by siddharth2010** [comment]
@luckyman20 Thats right. Thanks for pointing it out. I will take care about that as well.

**Comment by siddharth2010** [comment]
@luckyman20 hey, i just noticed, the vertical stretching wont be a problem. look:
![1](https://user-images.githubusercontent.com/32238400/34943725-dc9e7c66-fa22-11e7-88d9-6528a56084a1.png)
![screenshot from 2018-01-15 18-35-16](https://user-images.githubusercontent.com/32238400/34943734-e3fc8976-fa22-11e7-913a-1ce83e58e3e1.png)

**Comment by edcable** [comment]
Confirmed that this is still present.
