### ISSUE TITLE
Share Charge

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2808]
**Steps to Reproduce**
Create Charge with Charge Type = Share
Submit
When viewing or edit there is Charge Payment Mode.. And it wasn't there during creation..
And when you edit charge payment mode , after submitting .. it remains the previous value

 **Expected Behavior**
According to user manual, Charge Payment Mode should be available only in Loan Charge.

 **Actual Behavior**
It create Charge Payment Mode automatically.
**Screen-shot** 
![crg](https://user-images.githubusercontent.com/13551795/34824838-254d724a-f6e1-11e7-8c8b-7d42bb1fbf56.png)

**Comment by ankit01ojha** [comment]
i am working on it
