### ISSUE TITLE
Preview should only be displayed only when the user fills the form.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2816]
## Description
The preview should be displayed only when the user fills the form. Right now, it is displayed even if the user does not fill the form and only clicks on the preview from the progress bar.

## Steps to Reproduce
Eg:-
Admin>>Products>>Select any product (eg:- Loan products)>>Create>>click on the preview directly from the progress bar.

## Expected Behaviour
Preview should be displayed if the user does not fill the form.
## Actual Behaviour
Preview is displayed even if the user does not fill the form.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome, Firefox

## Screenshots, if any
![screenshot at 2018-01-14 18 46 58](https://user-images.githubusercontent.com/21126132/34916263-5d740784-f95b-11e7-9127-8152cac15bb0.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on it.
