### ISSUE TITLE
Number validation is missing in many fields of different forms.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2817]
## Description
Number validation is missing in many fields of different forms, because of which if a user inputs something other than a number it does not shows a message to warn user for only numeric values.

## List :-
- [ ] Loan Products
- [ ] Share Products
- [ ] Savings Product
- [ ] Charges
- [ ] Fixed Deposits Products
- [ ] Recurring Deposit Products

## Expected Behaviour
An error message should be displayed near the field warning the user.
## Actual Behaviour
No error message is displayed (except the API validation error, when the user submits the form).
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Crome, Firefox

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on it.

**Comment by abhaychawla** [comment]
The issue is similar to #2794

**Comment by ankit01ojha** [comment]
@abhaychawla , yes this issue is similar, but in this issue, I have tried to cover all the places where the issue is happening. So, that in a single issue all the fields can be fixed :)
