### ISSUE TITLE
Icons missing from delete/edit buttons in multiple pages

### ISSUE THREAD

**Issue by shubhshrma** [openMF/community-app#2820]
## Description
Icons are missing from buttons(mostly from delete but a few edit also).

## Steps to Reproduce
A list of pages that have buttons without icons that I found till now.
1. Accounting: chart of accounts, closing entries, accounting rules 

2. System: manage data table, manage roles and permissions, manage hooks, manage reports, scheduler jobs, configurations 

3. Products: charges, products mix

4. Templates

5. Organization: manage holidays, loan provisioning criteria

## Expected Behaviour
Buttons should have appropriate icons.

## Settings
- Mifos X version: 17.07.01
- Browser used: Firefox

## Screenshots, if any

![1](https://user-images.githubusercontent.com/20224346/34956576-c141d85a-fa4f-11e7-9d36-cdb8429499e1.png)
![2](https://user-images.githubusercontent.com/20224346/34956578-c3b4acf2-fa4f-11e7-96f0-b2e4110ba09f.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by shubhshrma** [comment]
I'll work on it.

**Comment by edcable** [comment]
Already fixed.
