### ISSUE TITLE
Blue colour is not shown when hovered over.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2821]
## Description
When hovered over lists in ```manage hooks``` , ```account number prefrences``` and in ```entity to entity mapping```.

## Steps to Reproduce
Admin>>System>>Add Hooks>>Hover over any list.
Admin>>System>>Account number prefrences
Admin>>System>>Entity to entity mapping
## Expected Behaviour
The blue colour of while hovering over the list is missing.
## Actual Behaviour
Blue colour during hover should be present
## Settings
- Mifos X version:  17.07.01.RELEASE
- Browser used: Google-Chrome,Firefox

## Screenshots, if any
![screenshot at 2018-01-16 19 19 10](https://user-images.githubusercontent.com/21126132/34992297-b2f93254-faf2-11e7-8970-fb41452c8501.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on it

**Comment by iknoorjobs** [comment]
@ankit01ojha Can I work on this issue?
