### ISSUE TITLE
Incorrect Format of Date in Fund Mapping

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2824]
## Description
The date format specified by settings is not being followed in Fund Mapping section of Organisation.

## Steps to Reproduce
Organisation -> Fund Mapping

## Expected Behaviour
The date format specified by settings should be followed.

## Actual Behaviour
The date format as mentioned by settings is not being followed.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 84](https://user-images.githubusercontent.com/16948598/35003159-f4747af8-fb11-11e7-98eb-0d1ee6743432.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by abhaychawla** [comment]
I'll work on this issue.
