### ISSUE TITLE
Changing the date format in settings does not update the date format at various places containing datepickers in the app

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2825]
## Description
On changing the date format in settings, it did not update the date format at places containing date pickers in the app.

## Steps to Reproduce
Mifos -> Settings -> Select any other date format
The date format doesn't get updated in date pickers of the app.

## Expected Behaviour
On changing the date format in settings, it should update the date format in date pickers of the app.

## Actual Behaviour
On changing the date format in settings, it does not update the date format in date pickers of the app.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 165](https://user-images.githubusercontent.com/16948598/35004032-bc1b0d2c-fb14-11e7-9362-387f7d8cdee6.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by abhaychawla** [comment]
I am working on this issue.
