### ISSUE TITLE
New version of mifos does not bring the information of the currency by countries

### ISSUE THREAD

**Issue by Hersan1962** [openMF/community-app#2826]
## Description
New version of mifos does not bring the information of the currency by countries
he currency table is empty and you can not define any product
The Global Settings tables are empty too

## Steps to Reproduce
When trying to register the currency and place the initial letter of the country, it does not bring information because the table is empty

**Comment by anweshknayak** [comment]
@Hersan1962 please provide steps to reproduce.

**Comment by santoshmath** [comment]
@Hersan1962 , I am able to select currencies from drop-down. 
![w3](https://user-images.githubusercontent.com/23022667/37136057-f63abff6-22c5-11e8-9ce7-e62b6d10ac09.png)
