### ISSUE TITLE
Input box not properly alligned 

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2827]
## Description
Input box not properly aligned in Organization
## Steps to Reproduce
Organization -> Manage Holiday -> Create Holiday

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
![screenshot from 2018-01-17 18 41 45](https://user-images.githubusercontent.com/8139783/35044728-782c33cc-fbb7-11e7-8777-09fab4ef318f.png)

### Claiming this

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by shubhshrma** [comment]
Can i work on this?

**Comment by anweshknayak** [comment]
sure go ahead
