### ISSUE TITLE
Staff Assignment History alignment

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2833]
**Steps to Reproduce**
Go to Center  >> More >> Staff Assignment History

**Expected Behavior**
Staff Assignment History should not overlap Release Version Link

![staff](https://user-images.githubusercontent.com/13551795/35152664-5b0612d0-fd34-11e7-88c5-0b7823578890.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
@mbj36 duplicate of #2723

**Comment by ankit01ojha** [comment]
@Agnessy , I have already created this issue and had sent the PR for this :)

**Comment by Agnessy** [comment]
@ankit01ojha Thanks, Let me edit.

**Comment by ankit01ojha** [comment]
@Agnessy are you working on this issue? If not, I would like to work on this.

**Comment by AgnessMeena** [comment]
Hi, @ankit01ojha am not working on it,, go on with it.
