### ISSUE TITLE
uib-tooltip for displaying Status has not been implemented everywhere in the app

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2836]
## Description
uib-tooltip has been used for displaying the status while hovering over the icon in clients and loan products page.
1) The same can be implemented in the groups and centers page, instead of displaying status as text near to the icon.
2) Also in the list of charges, the column 'Active' can be renamed to 'Status' and a similar colour coded icon along with tooltip can be used to denote whether it is active/inactive as done in other places of the app. Similar thing can be implemented at the Manage Employees page.

## Steps to Reproduce
Clients -> Clients (See tooltip when you hover over status icon)
Admin -> Products -> Loan Products (See tooltip when you hover over status icon)

Clients -> Groups (See no tooltip when you hover over status icon)
Clients -> Centers (See no tooltip when you hover over status icon)

Admin -> Products -> Charges (See active column which can be updated to status column)
Admin -> Organisation -> Manage Employees (See active column which can be updated to status column)

## Expected Behaviour
The status should be displayed in the same way everywhere in the app, using a colour coded icon along with a uib-tooltip.

## Actual Behaviour
The status is not being displayed in the same way everywhere in the app, using a colour coded icon along with a uib tooltip.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 176](https://user-images.githubusercontent.com/16948598/35158792-40f2bcd4-fd5e-11e7-8787-633381331a37.png)
![screenshot 179](https://user-images.githubusercontent.com/16948598/35158814-4d9b7d0e-fd5e-11e7-890c-36306cb23c9e.png)

As shown above, same should be implemented here:
![screenshot 177](https://user-images.githubusercontent.com/16948598/35158862-6b7b336e-fd5e-11e7-8262-f677c68d2f16.png)
![screenshot 178](https://user-images.githubusercontent.com/16948598/35158863-6bc8dda8-fd5e-11e7-9a29-d58175b90e54.png)
![screenshot 180](https://user-images.githubusercontent.com/16948598/35158861-6b33af1c-fd5e-11e7-811e-4b5ad767f9f3.png)
![screenshot 184](https://user-images.githubusercontent.com/16948598/35171108-95f41b2c-fd88-11e7-84ee-21c096942570.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by abhaychawla** [comment]
I'll work on this issue.
