### ISSUE TITLE
Redundant Breadcrumb link in Add/Edit Currency Configuration

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2839]
## Description
While adding/editing a currency configuration an unnecessary, redundant breadcrumb link is displayed.
The add/edit button should also hide on click.

## Steps to Reproduce
Admin -> Organisation -> Currency Configuration -> Add/Edit
A redundant breadcrumb link is displayed on top left. The add/edit button is still being displayed.

## Expected Behaviour
There is no requirement of displaying a redundant breadcrumb link while adding/editing a currency. Also, the add/edit button should hide on click.

## Actual Behaviour
A redundant breadcrumb link is displayed while adding/editing a currency. The add/edit button is still being displayed.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 186](https://user-images.githubusercontent.com/16948598/35172956-b54f64ca-fd8f-11e7-8bc1-1d8aabe27d52.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by abhaychawla** [comment]
I'll work on this issue.
