### ISSUE TITLE
Redundant Next/Previous Buttons in Share Products, Data Not Completely Showing Up

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2841]
## Description
There are redundant next/previous buttons in share products and complete data does not show up on the page even after clicking the buttons.

## Steps to Reproduce
Admin -> Products -> Share Products 
(Unnecessary next and previous button are being displayed at the bottom that do not work)

## Expected Behaviour
The complete data should be displayed and the next/previous buttons are not required as in other sections of products.

## Actual Behaviour
The complete data is not being shown and the next/previous buttons are being displayed without any use.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 190](https://user-images.githubusercontent.com/16948598/35174226-9c335e60-fd94-11e7-82d9-fb4ef803d092.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mbj36, and @ankit01ojha.

**Comment by abhaychawla** [comment]
I am working on this issue.
