### ISSUE TITLE
Paging missing 

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2842]
## Description
Paging missing in these places. Paging should be like present in Clients, Groups etc, so, that user doesn't have to scroll and scroll.

- [ ] Loan Products
- [ ] Savings Products
- [ ] Share Products
- [ ] Fixed Deposit Product
- [ ] Recurring Deposit Product
- [ ] Charges
- [ ] Manage Offices
- [ ] Manage Employees
- [ ] Provisioning Criteria
- [ ] Teller/Cash Management
- [ ] Manage Data Tables
- [ ] Manage Codes
- [ ] View Roles
- [ ] Manage Hooks
- [ ] Manage Reports
- [ ] All Reports
- [ ] Global Configurations
- [ ] Users
- [ ] Chart of Accounts

## Expected Behaviour
Paging should be present 
## Actual Behaviour
Paging is missing.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome, Firefox

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on it.

**Comment by abhaychawla** [comment]
@ankit01ojha All sections of products seemed not to have pagination, and the next/previous buttons in share products were non-functional so I removed them and now the complete data is shown on that page. Although you are right there should be pagination can we please confirm form @mbj36 or @gkrishnan724 before you work upon this as I seemed to do totally opposite of that just now after investigating the other sections of products.

**Comment by ankit01ojha** [comment]
@abhaychawla I guess you should not remove those buttons from Share Products if the list of Share Products is fixed then the newly added Products will be displayed and paging will be needed then.

**Comment by abhaychawla** [comment]
Sure, I can add them but as they were not present anywhere else I wanted to wait for a suggestion from one of the mentors about the pagination.

**Comment by ankit01ojha** [comment]
@abhaychawla , since it is not present in the Products (but it is present in clients, centers etc), that's why I created the issue and adding them for better UI.

**Comment by abhaychawla** [comment]
Okay
