### ISSUE TITLE
Share Products in not showing the newly added share product

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2843]
## Description
The list of Share Products is not showing the newly added share product in it.

## Steps to Reproduce
Admin>>Products>>Share Products>> Create new share product(fill all the required details along with the description)>>Check the product in the Share Product list.

## Expected Behaviour
Newly added Share Product should be displayed in the share products list.
## Actual Behaviour
Newly added Share Product is not shown in the share products list.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome.

**Comment by ankit01ojha** [comment]
@santoshmath can you please confirm this.

**Comment by abhaychawla** [comment]
@ankit01ojha I already figured that out in #2841 and have worked upon the same.

**Comment by santoshconflux** [comment]
@ankit01ojha , this issue  is no longer reproducible. https://staging.openmf.org
