### ISSUE TITLE
Unable to filter data, missing pagination in Reschedule Loan

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2846]
## Description
The Filter by Name field isn't working in Reschedule Loan Section of Checker Inbox and Tasks. Also, complete data is not being shown due to missing pagination.

## Steps to Reproduce
In the navigation bar present on the left, click Checker Inbox and Tasks -> Reschedule Loan
Try typing something in the filter by name text field. Data is not filtered.
Complete data is not being shown as pagination is missing.

## Expected Behaviour
The data should be filtered according to text present in the filter by name text field. Also, complete data should be visible via pagination as in other sections of Checker Inbox and Tasks.

## Actual Behaviour
The data is not being filtered according to text present in the filter by name text field and complete data is not visible due to missing pagination.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 217](https://user-images.githubusercontent.com/16948598/35185397-dbfbe32e-fe29-11e7-9822-09f0818f782b.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by abhaychawla** [comment]
I'll work on this issue.
