### ISSUE TITLE
Bread crumb missing in Attendance

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2847]
## Description
Bread crumb missing in Attendance.

## Steps to Reproduce
Clients>>Groups>>Select any group>>More>>Attendance
Clients>>Centers>>Select any center>>More>>Attendance

## Expected Behaviour
Bread crumb should be present in the attendance.
## Actual Behaviour
Bread crumb is not there in attendance.
## Settings
- Mifos X version:  17.07.01.RELEASE
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-01-20 23 37 13](https://user-images.githubusercontent.com/21126132/35186536-cd078640-fe3b-11e7-9333-a6ece7652e1d.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
i am working on this
