### ISSUE TITLE
Error message not aligned

### ISSUE THREAD

**Issue by sarthak-sehgal** [openMF/community-app#2850]
## Description
The error message displayed, "Please fill out this field", upon logging in with an empty password or username field is not aligned properly.

## Steps to Reproduce
Open the Mifos X webapp > Login with either the username or the password field empty

## Expected Behaviour
The error message should be pointing to the field which is empty.

## Actual Behaviour
The error message is not properly aligned and is not tagged to the field which is empty.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Firefox Developer Edition 58.0b16

## Screenshots, if any
When **username** is left **empty**:
![screenshot from 2018-01-23 00 48 09](https://user-images.githubusercontent.com/29003134/35239861-a8d9224a-ffd7-11e7-803e-20bf02464245.png)
When **password** is left **empty**:
![screenshot from 2018-01-23 00 45 37](https://user-images.githubusercontent.com/29003134/35239881-b6b5361a-ffd7-11e7-80f6-217e7bd8647b.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by sarthak-sehgal** [comment]
I am working on this.

**Comment by sarthak-sehgal** [comment]
It is an issue by Firefox and not a styling issue of Mifos X platform. Hence, closing this issue.
