### ISSUE TITLE
Before moving to next step in application process current mandatory fields should be filled

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2854]
## Description
Blocking the move next in application process if mandatory fields not complete in current page

## Expected Behaviour
Example : https://qsurvey.mozilla.com/s3/notes
Mozilla org sticks to this guideline
#2807  toast notifications can also be used here if user doesn't fill the mandatory fields and tried to move ahead. 

## Actual Behaviour
Can move ahead without filling mandatory fields.
## Settings
- Mifos X version: 
- Browser used:

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by iknoorjobs** [comment]
@anweshknayak Which form has to be done ?

**Comment by ankit01ojha** [comment]
@anweshknayak  and @iknoorjobs please see the comment in https://github.com/openMF/community-app/issues/2795 .  The user should be free to fill any part of the form in any sequence he desires. And the for the case if mandatory fields are not filled, the progress bar displays that the mandatory fields are not filled in that part of the form.

**Comment by anweshknayak** [comment]
@santoshmath @mbj36 @pranjal-goswami @edcable can you confirm if this is a workable issue? I think we should follow this feature as it reduces confusion amongst users. 

As per mifos org's mission 
>effectively and efficiently deliver responsible financial services to the  world’s 2 billion poor and unbanked.

I think most of the users would not have proper idea of how to prooceed. We can make things simple  and hassle free for them by following the feature above.

**Comment by santoshmath** [comment]
@anweshknayak , it's simple, when you go to next step , the current page mandatory filelds must be filled.

**Comment by anweshknayak** [comment]
Closing this then
