### ISSUE TITLE
Wrong error message, also showing ng code

### ISSUE THREAD

**Issue by sarthak-sehgal** [openMF/community-app#2855]
## Description
The error message being displayed upon entering an invalid date in the "Create holiday" section is wrong and is also displaying up Angular code which is not expected to be understandable by the user.

## Steps to Reproduce
Mifos Menu Bar >> Admin >> Organization >> Manage Holidays >> Create Holiday >> Enter name, from date, to date >> Select "Repayment Scheduling Type" as "Reschedule to specific date" >> Type in a wrong date (eg- 0 January 2018) in "Repayment Schedule To" >> Submit

## Expected Behaviour
The error message should be something like "Please enter a valid date"

## Actual Behaviour
The error message being displayed is "field is required
validation.msg.invalid.dateFormat.format -"

## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Firefox Developer Edition

## Screenshots, if any

![error msg issue open](https://user-images.githubusercontent.com/29003134/35450765-fda56088-02e6-11e8-8734-63ea9fd848f9.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by sarthak-sehgal** [comment]
Working on this.

**Comment by anweshknayak** [comment]
It is not showing the wrong message. Just it has not been added to https://github.com/openMF/community-app/tree/develop/app/global-translations. Check here.

**Comment by sarthak-sehgal** [comment]
@anweshknayak, yes, thanks for the help. Added. 😃
