### ISSUE TITLE
New Form wizard missing in "New Fixed Deposit" and "New Recurring Deposit" forms.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2862]
## Description
Form wizard is missing in the listed forms.

## Steps to Reproduce
Clients>>Select any client>>More>>New Fixed Deposit
Clients>>Select any client>>More>>New Recurring Deposit

## Expected Behaviour
Form wizard should be present

## Actual Behaviour
Form wizard missing

## Settings
- Mifos X version:  17.07.01.RELEASE 
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-02-02 17 59 48](https://user-images.githubusercontent.com/21126132/35733461-81ce09da-0843-11e8-87fe-2360145954f2.png)

![screenshot at 2018-02-02 18 00 21](https://user-images.githubusercontent.com/21126132/35733466-8af07ec6-0843-11e8-8b20-d8f863f13e17.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment]
I am working on this.
