### ISSUE TITLE
UI of Tax Configurations not consistent with the app

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2863]
## Description
The UI of tax configurations is not consistent with other places of the app. The card class has not been applied here.

## Steps to Reproduce
Admin -> Products -> Manage Tax Configurations

## Expected Behaviour
The UI of tax configurations should be consistent with the UI of the app.

## Actual Behaviour
The UI of tax configurations is not consistent with other places of the app.

## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Google Chrome

## Screenshots, if any
How it currently looks:
![screenshot 242](https://user-images.githubusercontent.com/16948598/35775951-51e9bb3e-09b9-11e8-9a11-ed9726020457.png)
It should look similar to:
![screenshot 243](https://user-images.githubusercontent.com/16948598/35775954-5a98da26-09b9-11e8-997a-8be4fde5a3f8.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by abhaychawla** [comment]
I'll work on this issue.
