### ISSUE TITLE
UI Bugs in Audit Trails Section of System

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2870]
## Description
1) The Audit Trails table has a horizontal scrollbar which keeps on reducing in width showing continuous movement dynamically. (It is not required)
2) Blue color is not shown on hover in the records of the table.
3) Unnecessary horizontal scroll bar while viewing any of audit entry details.

## Steps to Reproduce
Admin -> System -> Audit Trails -> Click any entry in table

## Expected Behaviour
The horizontal scrollbars are causing unnecessary behavior and can be removed. On hovering over a clickable record it should turn into a pointer as well as highlight record in blue.

## Actual Behaviour
The horizontal scrollbars are causing unnecessary behavior. Cannot identify that the records are clickable.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 254](https://user-images.githubusercontent.com/16948598/35819223-0f039866-0ac8-11e8-9898-01a1bff82012.png)
![screenshot 255](https://user-images.githubusercontent.com/16948598/35819222-0eaa90f4-0ac8-11e8-8bf8-1574e10a819b.png)
![screenshot 257](https://user-images.githubusercontent.com/16948598/35819334-6f31f552-0ac8-11e8-8fe5-0d8087d02f97.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by abhaychawla** [comment]
I'll work on this issue.
