### ISSUE TITLE
Inconsistency in Button Colours/Icons/Font

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2874]
## Description
Various buttons like edit, delete, view exist in the app and are inconsistent in their colour and/or icon/font at some places which is not a good user experience. (A few example screenshots are attached below)

The following is a list of those places where the inconsistency exists:
- [x] View User
- [x] Manage Offices
- [x] View Holiday
- [x] Standing Instructions History
- [x] View Provisioning Criteria
- [x] Create Entity Data Table Check
- [x] Teller/Cashier Management
- [x] Currency Configuration
- [x] Payment Type
- [x] View Data Table
- [x] View Code
- [x] View Role
- [x] View Hook
- [x] View entity to entity mapping
- [x] View survey
- [x] Audit Trails
- [x] View Report
- [x] Schedular jobs
- [x] Configurations
- [x] View Account number preferences
- [x] View External Services  
- [x] Loan Products
- [x] Savings Products
- [x] Share Products
- [x] Fixed Deposit Products
- [x] Recurring Deposit Products
- [x] View Charge
- [x] View Product Mix
- [x] Create/Edit Floating rate
- [x] Manage Tax Groups
- [x] View Template
- [x] View Transaction
- [x] Delete financial activity mapping
- [x] View chart of accounts
- [x] View Account Closure
- [x] View Accounting rules
- [x] View provisioning entries
- [x] Checker inbox and tasks
- [x] Home/Dashboard
- [x] Reports

## Steps to Reproduce
Inconsistency can be noticed by visiting following places:
Admin -> User -> Click any user (view user)
Admin -> Organisation -> Manage Offices -> Click any office (Assets, view data table entry)
Admin -> Organisation -> Click any holiday (view holiday)
Admin -> Organisation -> Standing Instructions History
Admin -> Organisation -> Provisioning Criteria -> Click any criteria (view provisioning criteria)
Admin -> Organisation -> Entity Data Table Checks -> Create Entity Data Table Check/Remove any entity data table check
Admin -> Organisation -> Teller/Cashier Management (View Cashiers for teller -> View Transaction)
Admin -> Organisation -> Currency Configuration -> Add/Edit
Admin -> Organisation -> Payment Type
Admin -> System -> Manage Data Tables -> Click any data table (view data table)
Admin -> System -> Manage Codes
Admin -> System -> Manage Roles and Permissions -> Click any role (view role)
Admin -> System -> Manage Hooks -> Click any hook (view hook)
Admin -> System -> Entity to entity mapping -> Click any mapping (view mapping)
Admin -> System -> Manage Surveys -> Click any survey (view/edit survey)
Admin -> System -> Audit Trails
Admin -> System -> Manage Reports -> Click on any report (view report)
Admin -> System -> Schedular jobs  
Admin -> System -> Configurations
Admin -> System -> Account number preferences -> Click any entry (view entry)
Admin -> System -> External services -> View any service
Admin -> Products -> Loan Products 
Admin -> Products -> Savings Products
Admin -> Products -> Share Products
Admin -> Products -> Fixed Deposit Products
Admin -> Products -> Recurring Deposit Products
Admin -> Products -> Charges -> Click any charge (view charge)
Admin -> Products -> Products Mix -> Click any product (view product)
Admin -> Products -> Floating Rates -> Create/Edit Floating rate
Admin -> Products -> Manage Tax Configurations -> Manage Tax Groups -> Create tax group / View any tax group -> Edit
Admin -> Templates -> Click any template (view template)
Accounting -> Search Journal Entries -> Search -> Click any transaction -> Click any entry on table (review journal entry) 
Accounting -> Accounts linked to financial activities -> Click any mapping -> Delete
Accounting -> Chart of accounts -> Click any account (view account)
Accounting -> Closing entries -> Click any entry (view entry)
Accounting -> Accounting rules -> Click any rule (view rule)
Accounting -> Provisioning entry
Checker inbox and tasks (from side navbar)
First screen on login
Reports (Run any report)

## Expected Behaviour
There should be a specific standard for the colours of buttons which should be followed in the entire app for better user experience.
The convention which can be followed is given below:
Home -> Blue with home icon
Dashboard -> Blue with tachometer icon
Create/Add -> Blue with plus icon
Edit/Recreate -> Blue with paper and pencil icon
Submit/Save/Confirm/Upload/Summary/Proceed -> Blue
Tree View -> Blue with graph icon
List View -> Blue with list icon
Import -> Blue with import icon
Export -> Blue with file icon
Download -> Blue with cloud icon
Refresh -> Blue with round arrow icon
Search -> Blue with magnifying glass icon
Change Password -> Blue with gear icon
Remove -> Blue with cross icon
Delete -> Red with trash icon
Activate/Enable -> Blue with unlock icon/Circular or normal green button with tick icon
Disable/Deactivate -> Red with lock icon/Circular or normal red button with cross icon
Approve/Disburse -> Green with tick icon
Reject -> Orange with cross icon
Cancel/Close/Back -> White
View -> Light Blue with eye icon
Filter -> Blue with funnel icon
Suspend -> Orange with cross icon
Error log -> Orange with exclamation mark icon
Run -> Blue with play icon
Next/Previous -> White with black arrow icon
Show -> Square blue button with plus icon
Hide -> Square blue button with minus icon
Allocate Cash -> Green with level down icon 
Settle Cash -> Orange with level up icon
Select All -> Blue
Deselect All -> White
Reset -> Blue with undo icon
Dividends -> Blue with archive icon
Initiate -> Blue with plus icon
Post -> Blue with briefcase icon

Class of button:
Blue -> btn-primary
White -> btn-default
Red -> btn-danger
Light Blue -> btn-info
Orange -> btn-warning
Green -> btn-success

## Actual Behaviour
Mostly buttons are blue. The delete button is red, orange or blue at different places. There are view and reject buttons at two different places, both are orange.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 347](https://user-images.githubusercontent.com/16948598/36345323-1935502e-144e-11e8-8603-c78acaff4cc6.png)
![screenshot 348](https://user-images.githubusercontent.com/16948598/36345355-c12770fa-144e-11e8-85cb-dd19b11eb0e2.png)
![screenshot 349](https://user-images.githubusercontent.com/16948598/36345360-edbc8088-144e-11e8-9f35-778cb0ebbe38.png)
![screenshot 425](https://user-images.githubusercontent.com/16948598/37109588-6d86a888-2260-11e8-9c6a-1498deb14ddd.png)
![screenshot 426](https://user-images.githubusercontent.com/16948598/37109587-6d45112a-2260-11e8-8ed4-91b349dfd99e.png)
![screenshot 401](https://user-images.githubusercontent.com/16948598/36892941-608ee2ea-1e2c-11e8-8870-62bbd7563198.png)
![screenshot 402](https://user-images.githubusercontent.com/16948598/36892940-60305eb4-1e2c-11e8-87df-d068a6b29c94.png)
![screenshot 403](https://user-images.githubusercontent.com/16948598/36893240-4743ef28-1e2d-11e8-8152-aa55dd0c60d0.png)
![screenshot 404](https://user-images.githubusercontent.com/16948598/36893239-46f3e21c-1e2d-11e8-95f0-32204057cfc8.png)
![screenshot 350](https://user-images.githubusercontent.com/16948598/36450002-97e4f274-16b2-11e8-8871-1e2f5c554876.png)
![screenshot 351](https://user-images.githubusercontent.com/16948598/36450001-9748d0ec-16b2-11e8-877c-9a442b435b8e.png)
![screenshot 359](https://user-images.githubusercontent.com/16948598/36860404-27b7a8f6-1da7-11e8-9e7d-957b38ab2a0e.png)
![screenshot 360](https://user-images.githubusercontent.com/16948598/36860402-277363d0-1da7-11e8-9af5-f12bc985f382.png)
![screenshot 361](https://user-images.githubusercontent.com/16948598/36861123-03594e04-1da9-11e8-934b-a537675e47b8.png)
![screenshot 427](https://user-images.githubusercontent.com/16948598/37143287-b738b2de-22e0-11e8-819e-64cebb4c75f7.png)
![screenshot 429](https://user-images.githubusercontent.com/16948598/37143765-1996a3fe-22e2-11e8-9afa-aa1d71a98682.png)
![screenshot 430](https://user-images.githubusercontent.com/16948598/37143767-1a0d0c74-22e2-11e8-91cd-2c074985a2cf.png)
![screenshot 431](https://user-images.githubusercontent.com/16948598/37143762-18d5dba6-22e2-11e8-9ef5-389d13716014.png)
![screenshot 362](https://user-images.githubusercontent.com/16948598/36863266-3a7d127a-1daf-11e8-89eb-4b4dd09e9d0a.png)
![screenshot 363](https://user-images.githubusercontent.com/16948598/36863433-aa30fcf8-1daf-11e8-9e8b-f52e03784b44.png)
![screenshot 364](https://user-images.githubusercontent.com/16948598/36863747-a1cb6d40-1db0-11e8-803d-2853243d231c.png)
![screenshot 365](https://user-images.githubusercontent.com/16948598/36863746-a18a74c0-1db0-11e8-9cf0-b66000a48725.png)
![screenshot 367](https://user-images.githubusercontent.com/16948598/36864119-baf2f63e-1db1-11e8-990f-9238fe165807.png)
![screenshot 368](https://user-images.githubusercontent.com/16948598/36864121-bb40e3da-1db1-11e8-8b25-0d351fef2ca9.png)
![screenshot 369](https://user-images.githubusercontent.com/16948598/36864117-baac457c-1db1-11e8-912f-9cd2ddc19ae7.png)
![screenshot 370](https://user-images.githubusercontent.com/16948598/36864295-423a142e-1db2-11e8-833a-5188b283d7e8.png)
![screenshot 371](https://user-images.githubusercontent.com/16948598/36864293-41edce20-1db2-11e8-90ee-3e525970ddd2.png)
![screenshot 373](https://user-images.githubusercontent.com/16948598/36864422-a5ccf59c-1db2-11e8-9b9a-fb0c449353f8.png)
![screenshot 374](https://user-images.githubusercontent.com/16948598/36864421-a57db374-1db2-11e8-9e5b-93b275942b7b.png)
![screenshot 375](https://user-images.githubusercontent.com/16948598/36864566-0f49a1be-1db3-11e8-951f-1a6c9375f756.png)
![screenshot 376](https://user-images.githubusercontent.com/16948598/36864568-0f90eb1e-1db3-11e8-8df4-b72ca40d4957.png)
![screenshot 377](https://user-images.githubusercontent.com/16948598/36864565-0f02f4c6-1db3-11e8-935a-39f05fada67a.png)
![screenshot 378](https://user-images.githubusercontent.com/16948598/36864784-abffc470-1db3-11e8-96d0-428b0924a847.png)
![screenshot 379](https://user-images.githubusercontent.com/16948598/36864783-abb5d130-1db3-11e8-8ed2-bad39b386a9c.png)
![screenshot 380](https://user-images.githubusercontent.com/16948598/36864927-1da10094-1db4-11e8-9d18-d45ab73ae004.png)
![screenshot 381](https://user-images.githubusercontent.com/16948598/36865026-5a2f3ae4-1db4-11e8-9a23-21df0cedf5be.png)
![screenshot 382](https://user-images.githubusercontent.com/16948598/36865024-59dd97f2-1db4-11e8-999e-287bb76f8912.png)
![screenshot 383](https://user-images.githubusercontent.com/16948598/36865376-5b11eb7c-1db5-11e8-8d42-090c8d78d54a.png)
![screenshot 384](https://user-images.githubusercontent.com/16948598/36865374-5ac4b9ba-1db5-11e8-9ed6-0281dbcbb596.png)
![screenshot 385](https://user-images.githubusercontent.com/16948598/36865506-be971c80-1db5-11e8-9a49-aeab6ac3ea7d.png)
![screenshot 386](https://user-images.githubusercontent.com/16948598/36865612-031a0002-1db6-11e8-9267-146d259de138.png)
![screenshot 387](https://user-images.githubusercontent.com/16948598/36865751-73381536-1db6-11e8-9663-ae6ef043be48.png)
![screenshot 388](https://user-images.githubusercontent.com/16948598/36865749-72e83ff2-1db6-11e8-84ee-0e4bbe80d10e.png)
![screenshot 432](https://user-images.githubusercontent.com/16948598/37272893-1b25c47e-25fe-11e8-87e7-38aa56f28e24.png)
![screenshot 389](https://user-images.githubusercontent.com/16948598/36866088-574ac264-1db7-11e8-9278-d64c45f8c1b2.png)
![screenshot 390](https://user-images.githubusercontent.com/16948598/36866273-d7f38d06-1db7-11e8-8221-0c5706c2eaf6.png)
![screenshot 391](https://user-images.githubusercontent.com/16948598/36866274-d83eb2ae-1db7-11e8-8e19-fe9e92f47934.png)
![screenshot 392](https://user-images.githubusercontent.com/16948598/36866275-d88b3c82-1db7-11e8-9d3a-6f268796354c.png)
![screenshot 393](https://user-images.githubusercontent.com/16948598/36866271-d7ab8132-1db7-11e8-9f7a-22152db6096d.png)
![screenshot 394](https://user-images.githubusercontent.com/16948598/36866387-2a165f0a-1db8-11e8-82f1-54785ece8453.png)
![screenshot 395](https://user-images.githubusercontent.com/16948598/36866386-29c95e1c-1db8-11e8-91e6-78dc22d42e55.png)
![screenshot 396](https://user-images.githubusercontent.com/16948598/36866565-9d017acc-1db8-11e8-858a-ebf5ff580973.png)
![screenshot 397](https://user-images.githubusercontent.com/16948598/36866564-9cb03acc-1db8-11e8-8839-8253f30bcaf5.png)
![screenshot 433](https://user-images.githubusercontent.com/16948598/37281366-c9cc562e-2616-11e8-8648-92ac21a92479.png)
![screenshot 398](https://user-images.githubusercontent.com/16948598/36866641-dea617d0-1db8-11e8-915e-28f54dca29a0.png)
![screenshot 405](https://user-images.githubusercontent.com/16948598/36893659-e4c97b9a-1e2e-11e8-95cb-d6d318a8bc5b.png)
![screenshot 406](https://user-images.githubusercontent.com/16948598/36893690-032ee930-1e2f-11e8-9356-003377eb08d3.png)
![screenshot 407](https://user-images.githubusercontent.com/16948598/36893847-8fbcc520-1e2f-11e8-963d-d8061fda40f5.png)
![screenshot 408](https://user-images.githubusercontent.com/16948598/36893846-8f6399fa-1e2f-11e8-8610-8349f6e48a1e.png)
![screenshot 409](https://user-images.githubusercontent.com/16948598/36893952-df2686b4-1e2f-11e8-98cd-9b4fdba9c25e.png)
![screenshot 410](https://user-images.githubusercontent.com/16948598/36894001-0ea9f916-1e30-11e8-8d8f-70d635d61773.png)
![screenshot 411](https://user-images.githubusercontent.com/16948598/36894210-a0d44e04-1e30-11e8-8bca-4cd749d6e38e.png)
![screenshot 412](https://user-images.githubusercontent.com/16948598/36894658-20c7720c-1e32-11e8-9dd2-e2816efc10e6.png)
![screenshot 434](https://user-images.githubusercontent.com/16948598/37286494-1d58c492-2628-11e8-8077-12c7079c8397.png)
![screenshot 435](https://user-images.githubusercontent.com/16948598/37286937-75f4ba06-2629-11e8-9a13-ef1f62a0e124.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

A possibly related issue is #2742: Scroll to top button not working .

**Comment by abhaychawla** [comment]
@mbj36 @gkrishnan724 I would like to work on this if it seems a valid issue?

**Comment by gkrishnan724** [comment]
Seems like a valid issue @abhaychawla, please make a checklist in the issue, regarding all the places where this inconsitensy exists and send a PR

**Comment by abhaychawla** [comment]
Okay!
