### ISSUE TITLE
Newly added fixed deposit application and recurring deposit applications are not being displayed in the client page

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2879]
## Description
Newly added fixed deposit application and recurring deposit applications are not being displayed in the client page( like the loan, shares, savings etc).

## Steps to Reproduce
Clients>>New Fixed Deposits>>Fill the details>>submit
Clients>>New recurring Deposits>>Fill the details>>submit

## Expected Behaviour
Newly added fixed deposit and recurring deposit applications should be displayed in the client page like the loan, shares, savings etc.
 
## Actual Behaviour
Newly added fixed deposit and recurring deposit applications are not being displayed in the client page like the loan, shares, savings etc.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-02-11 11 17 05](https://user-images.githubusercontent.com/21126132/36070312-edd85bb8-0f1d-11e8-8a3c-f66994afede1.png)
 I added new fixed deposits and recurring deposits and they are not below savings as separate rather than they are shown in the Savings Account Overview.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is #458: Closed loans (Closed (obligations met), Closed (rescheduled) etc) are displayed under active loan accounts tab.

**Comment by ankit01ojha** [comment]
I am working on it.
