### ISSUE TITLE
Greyish form does not match with the new UI

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2883]
## Description
There are certain forms which are grey in colour and they don't match up with the recent UI. And because of the grey colour, the required field message is not shown in red colour.

## Steps to Reproduce
1. Edit any loan account
2. Edit any fixed deposit account
3. Edit any recurring deposit account

## Expected Behaviour
Forms should be white colour as per the new UI ( eg:- Edit any Loan product)
## Actual Behaviour
Forms are grey in colour.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: google-chrome

## Screenshots, if any
It looks like this now:-
![screenshot at 2018-02-11 22 05 01](https://user-images.githubusercontent.com/21126132/36075628-a47beb60-0f77-11e8-9bd5-5770d0cc9241.png)

It should look like this:-
![screenshot at 2018-02-11 21 47 06](https://user-images.githubusercontent.com/21126132/36075644-d62f55de-0f77-11e8-86de-657572c9696c.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.
