### ISSUE TITLE
Redirect to start page

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2885]
## Description
Since there is nothing in start page. It gets redirected there sometimes after you restart grunt manually.

## Expected Behaviour
Should go to home page instead of showing start page

## Actual Behaviour
Shows start page 

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
![screenshot from 2018-02-12 15-07-54](https://user-images.githubusercontent.com/8139783/36090543-c0ac43c2-1006-11e8-9d6f-83e5d614af53.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by monikamaheshwari** [comment]
Wanted to work on this issue.
