### ISSUE TITLE
Setup Deploy to Heroku option

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2887]
## Description
Create a deploy to heroku button https://devcenter.heroku.com/articles/heroku-button

## Settings
- Mifos X version: 
- Browser used:

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by mbj36** [comment]
Why do you want to deploy to heroku ?

**Comment by anweshknayak** [comment]
> The button is ideal for customers, open-source project maintainers or add-on providers who wish to provide their customers with a quick and easy way to deploy and configure an app.

**Comment by mbj36** [comment]
We don't have any heroku setup -  this app is independent with Fineract backend, so there is no point of this button!
