### ISSUE TITLE
Tooltip label is not being replaced with the corresponding message at Penalties Receivable

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2889]
## Description
The tooltip is displaying the label of the message and not its corresponding text at Penalties Receivable (Accounting Section of Loan Products - Create/Edit)

## Steps to Reproduce
Admin -> Products -> Loan Products -> Create loan products
Admin -> Products -> Loan Products -> Select any product -> Edit

## Expected Behaviour
The tooltip label must be replaced with the correct corresponding message and be displayed.

## Actual Behaviour
The tooltip label is not being replaced with the corresponding text and label is being shown as it is.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 329](https://user-images.githubusercontent.com/16948598/36220769-da1100dc-11e1-11e8-9c6a-992284de3c8d.png)
![screenshot 328](https://user-images.githubusercontent.com/16948598/36220770-da58f50e-11e1-11e8-9090-512f86a52c52.png)

**Comment by abhaychawla** [comment]
I am working on this issue.

**Comment by ankit01ojha** [comment]
@abhaychawla , did you updated your branch??  I guess its fixed already, I am not getting this issue in create loan products :)
![screenshot at 2018-02-12 23 33 58](https://user-images.githubusercontent.com/21126132/36111846-832076a8-104d-11e8-9a60-172b3f0ec2e5.png)

**Comment by abhaychawla** [comment]
Yes its fixed I'll close the issue.

**Comment by abhaychawla** [comment]
I found a similar issue at another place so updated the same.

**Comment by santoshconflux** [comment]
Fixed.
