### ISSUE TITLE
Navbar enhancement

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2897]
## Description
Navbar's colour should be similar to the sidebar.
Too much contrast is not good as per UX standards

## Settings
- Mifos X version: 
- Browser used:

**Comment by ankit01ojha** [comment]
@anweshknayak , could you please provide any links to the UX standards you are referring to because, as a user, I don't find the contrast troublesome rather it makes it a little attractive  :)

**Comment by anweshknayak** [comment]
Yeah sure I will. In gsoc proposal.

**Comment by gkrishnan724** [comment]
@anweshknayak I honestly feel the existing navbar colors match nicely. We could re-open this based on opinions of more contributors.

**Comment by anweshknayak** [comment]
Sure no issue. 😃 I plan to put that in proposal.

**Comment by muddlebee** [comment]
@gkrishnan724 please open this issue. It has been approved by my mentors.
