### ISSUE TITLE
Fliter by name not working properly in navigation

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2898]
## Description
Fliter by name is not working properly in navigation.

## Steps to Reproduce
Sidebar -> Navigation -> Search by name(or filter by name)

## Settings
- Mifos X version: 
- Browser used: Firefox Quantum

**Comment by abhaychawla** [comment]
Hi, @anweshknayak what issue are you exactly facing? It seems to work properly on my side.

**Comment by anweshknayak** [comment]
It's working? You sure. I have not checked the develop branch. Just the one hosted

**Comment by anweshknayak** [comment]
Just it was not matching cases with the keyword. As in other filters. It shows different varieties of unwanted results. Not sure if it has been fixed

**Comment by abhaychawla** [comment]
You mean uppercase/lowercase text is not matched? While filtering the offices if I try to search for an office say Katuba, all the offices having Katuba as its Parent Office are also shown. Not sure if it is a bug though 😅  Otherwise, it is working fine with Loan Officers, Centers etc.

**Comment by ankit01ojha** [comment]
@anweshknayak , It's working fine on my side too :)
