### ISSUE TITLE
Inconsistency in the UI of the app

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2899]
## Description
At the following places, the white card container has not been implemented for the content instead it resides in the old grey container which is inconsistent with the new UI:
- [x] Create GL Account
- [x] Edit GL Account
- [x] AdHoc Query
- [x] Create AdHoc Query

## Steps to Reproduce
Accounting -> Chart of Accounts -> Add Account
Accounting -> Chart of Accounts -> Select any account -> Edit
Organisation -> AdHoc Query
Organisation -> AdHoc Query -> Create AdHoc Query

## Expected Behaviour
The UI should be consistent throughout the app and thus the grey container should be updated to white, card container for the content.

## Actual Behaviour
The UI is inconsistent at few places in the app, with the new white card container not implemented for the content.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 333](https://user-images.githubusercontent.com/16948598/36245516-7884f452-1251-11e8-891f-3fc2e7822aa5.png)
![screenshot 334](https://user-images.githubusercontent.com/16948598/36245517-78c93d9c-1251-11e8-8657-e7fbabf2124f.png)
![screenshot 335](https://user-images.githubusercontent.com/16948598/36245519-790e60e8-1251-11e8-9fd9-b78c099e43c8.png)
![screenshot 336](https://user-images.githubusercontent.com/16948598/36245520-795308ce-1251-11e8-857a-ae9583a7e334.png)
![screenshot 337](https://user-images.githubusercontent.com/16948598/36245515-783ff190-1251-11e8-9193-b7e019136574.png)

**Comment by abhaychawla** [comment]
I'll work on the issue.

**Comment by Nayan** [comment]
@edcable @santoshconflux  please mention the PR for the this issue

**Comment by santoshconflux** [comment]
@Nayan , Fyi
https://github.com/openMF/community-app/pull/2902
