### ISSUE TITLE
Default value of Transaction Date for the repayments of Approved loans is not correct.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2900]
## Description
The default value of Transaction Date for the repayments of Approved loans is not correct. The default value of the date is of future and when the form is submitted, it is showing the error message that future dates are not allowed.

## Steps to Reproduce
Clients>>Slect any client>>select any approved loans>>Click  Make Repayment

## Expected Behaviour
Either the default date should be of today or it should be vacant for users to enter.
## Actual Behaviour
The default date is of future which is wrong.
## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Google-Chrome

## Screenshots, if any
![screenshot at 2018-02-15 19 21 40](https://user-images.githubusercontent.com/21126132/36259835-7abea4b4-1285-11e8-9f1f-44210b17d2a6.png)

**Comment by ankit01ojha** [comment]
I am working on this.

**Comment by ShruthiRajaram** [comment]
@santoshconflux can you verify this bug. I think its not an issue.
As per my understanding, when the loan repayment screen is loaded by default it shows the next repayment date for the loan, this date can be either in past or future.  But if we override this functionality  and show only the current date it will mislead the data operator.

**Comment by santoshconflux** [comment]
@ShruthiRajaram , that's  correct. @ankit01ojha , the application always picks the  next repayment date in repayment page rather than current date. The current date  and repayment  date are always  matching if the repayment transaction is done on same date.
