### ISSUE TITLE
"Filter by name" field missing in "Manage Roles and Permissions"

### ISSUE THREAD

**Issue by sarthak-sehgal** [openMF/community-app#2904]
## Description
The Filter by name (search field) is not there in the "Manage Roles and Permissions" (view roles) section. It is difficult for the administrator to search for a name amongst hundreds of names in the list.

## Steps to Reproduce
Mifos Menu Bar >> Admin >> System >> Manage Roles and Permissions

## Expected Behaviour
There should be a "Filter by name" field present for simplifying the task.

## Actual Behaviour
Unlike other pages, there is no "Filter by name" search field present in the page.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Firefox, Chrome

## Screenshots, if any
![issue 2902](https://user-images.githubusercontent.com/29003134/36312266-d353e5f2-1353-11e8-8662-2b2bdfac71ee.png)

**Comment by alexnavis** [comment]
Create a new PR (#3301) based on in-active branch and resolved conflicts. Done testing on the same.
