### ISSUE TITLE
Revamp UI to use material design

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2910]
## Description
Revamp UI to use material design

## Steps to Reproduce

As done in https://github.com/openMF/web-self-service-app

@gkrishnan724 @gauravsaini03 @mbj36 @avikganguly01 

Would it be a good idea? :smile:  Would love to hear from you guys

**Comment by mbj36** [comment]
@anweshknayak It's not possible to completely change UI in 3 months of GSoC, we have been adding features and improving existing UI in every GSoC, UI changes takes time, if you see, we have 100s of file in views which will be very difficult to change. so there will be no material design thing, but we can certainly improve the existing UI

**Comment by anweshknayak** [comment]
@mbj36 I understand. Thanks :)
