### ISSUE TITLE
Deactivate button in Manage Surveys not working properly

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2913]
## Description
The deactivate button in Manage Surveys is not working properly, rather than deleting the survey when clicked it is redirecting to view the survey.

## Steps to Reproduce
Admin >> System >> Manage Surveys >> Click on deactivate on any of the surveys.

## Expected Behaviour
The survey which is selected to be deleted should be removed from the list.
## Actual Behaviour
When clicked it is redirecting to view the survey.
## Settings
- Mifos X version: Release Version: 17.07.01.RELEASE
- Browser used: Google Chrome

**Comment by ankit01ojha** [comment]
I am working on it.

**Comment by abhaychawla** [comment]
Don't you think rather than deleting the survey from the list when the user deactivates it you could just make it inaccessible? In this way, the user will be able to reactivate it in case he needs the same in future rather than recreating it.

**Comment by ankit01ojha** [comment]
@abhaychawla yeah, I was also thinking the same :)

**Comment by santoshmath** [comment]
Related issue is raised here for platform side:
https://issues.apache.org/jira/browse/FINERACT-530

**Comment by m-sameer** [comment]
@ankit01ojha This doesn't happen to me. The survey gets deactivated and the button becomes `Activate` but the button doesn't activate the survey when clicked.
Could explain more and give screenshots, please?

**Comment by santoshconflux** [comment]
@m-sameer , Did you check here? It's working fine. 

https://staging.openmf.org/#/surveys (mifos/password)

If you  still have doubts, ping me  on Skype: santoshmath99

**Comment by jonathanzhang53** [comment]
This is working fine for me. 

![survey](https://user-images.githubusercontent.com/41968151/48654901-67e2f380-e9d6-11e8-83b7-2048b105b405.gif)

**Comment by m-sameer** [comment]
@santoshconflux Yeah, this is working fine. Thank you.

**Comment by ankit01ojha** [comment]
@santoshconflux , It is working fine for me too now. I think the issue can be closed.
