### ISSUE TITLE
Unable to submit the survey form.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/community-app#2914]
## Description
Even after filling all the required details in the survey form, the form is not getting submitted. And no error is shown.
## Steps to Reproduce
Admin >> System >> Manage Surveys >> Create new survey >> Fill all the required details

## Expected Behaviour
New survey should be created
## Actual Behaviour
The form is not getting submitted and no error is shown.
## Settings
- Mifos X version: Release Version: 17.07.01.RELEASE
- Browser used: Google -Chrome

**Comment by ankit01ojha** [comment]
I am working on it.

**Comment by ankit01ojha** [comment]
@gkrishnan724 @abhaychawla @anweshknayak Do you all face the same issue??

**Comment by abhaychawla** [comment]
@ankit01ojha I am able to create the survey form. Rather there seems to be a different issue after it gets submitted the review page I was redirected had no data and was blank. Although a new entry was created and I was able to review it by clicking on it from Manage Surveys page. Could you recheck at your side as well?

**Comment by ankit01ojha** [comment]
@abhaychawla yeah, that happened to me earlier, but now its not getting submitted.

**Comment by santoshmath** [comment]
We are able to create survey but if we make any mistake, it won't throw any error or validation message.

**Comment by ankit01ojha** [comment]
@santoshmath ,ok, then i should close this issue.
