### ISSUE TITLE
Ununiform spacing below header

### ISSUE THREAD

**Issue by anweshknayak** [openMF/community-app#2921]
## Description
Ununiform spacing below header you see some white space. It shouldn't be there

## Screenshots, if any
![header](https://user-images.githubusercontent.com/8139783/37252709-0074e7d4-254c-11e8-824f-fbb97840680b.jpg)

It is after this https://github.com/openMF/community-app/pull/2727
@abhaychawla @gkrishnan724

**Comment by abhaychawla** [comment]
Its a minor issue with the number of pixels. It can be fixed by making the value of top: 51px/50px for mifos-reskin-ui-container. @gkrishnan724 Shall I resend the pull request?

**Comment by pbhagade0** [comment]
Hey,

I am a gsoc aspirant.
I am working on fixing this issue.

**Comment by shivanshxyz** [comment]
This issue is still open. If its not resolved can I start working on it?

**Comment by IOhacker** [comment]
In the latest version it is already fixed.

And you can check it ridht now at:

https://demo.mifos.io/#/home

**Comment by bharathcgowda** [comment]
closing this ticket as it already fixed in the latest release version.
