### ISSUE TITLE
Bar button at the top corner

### ISSUE THREAD

**Issue by monikamaheshwari** [openMF/community-app#2928]
## Description
The button at the top corner of the page.

## Steps to Reproduce
Either this button should execute some function like open menu else it should not have clicking option.

## Expected Behaviour
It has an click option but not doing anything

## Actual Behaviour
Should open menu.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome

## Screenshots, if any
![screen shot 2018-03-22 at 7 03 23 pm](https://user-images.githubusercontent.com/17271005/37773750-6c2336be-2e04-11e8-9bc5-62a336c6bccb.png)

**Comment by monikamaheshwari** [comment]
Working on it.

**Comment by ankit01ojha** [comment]
@monikamaheshwari, there is already an issue opened for this https://github.com/openMF/community-app/issues/2714 and a PR for this https://github.com/openMF/community-app/pull/2803.

**Comment by monikamaheshwari** [comment]
okay.
