### ISSUE TITLE
edit group option not working on local systems

### ISSUE THREAD

**Issue by pratyush1687** [openMF/community-app#2930]
## Description
after creating a new group and viewing it, if I click on edit blank screen appears

## Steps to Reproduce
click on add group
add details
view your group
click on edit

## Expected Behaviour
should show edit options as seen on demo.openmf.org
![image](https://user-images.githubusercontent.com/25077017/37874712-e1f2377e-3051-11e8-9620-9f0e7b2495e9.png)

## Actual Behaviour
doesn't show anything on local system
 
## Settings
- Mifos X version: 17.07.01
- Browser used:chrome

## Screenshots, if any
![image](https://user-images.githubusercontent.com/25077017/37874673-50f7b244-3051-11e8-9bd3-09767401d44e.png)
![image](https://user-images.githubusercontent.com/25077017/37874704-badc8018-3051-11e8-922a-064939818536.png)

**Comment by chandaaparna** [comment]
@gkrishnan724 : Could you please look into this issue.

**Comment by ShruthiRajaram** [comment]
The issue is fixed with - 2964

**Comment by Afadzie** [comment]
> The issue is fixed with - 2964

how do i find and use it please help

**Comment by masmos** [comment]
Even this Issue |The issue is fixed with - 2964|  directs shows that the issue was already asked here. I'm now getting confused because I have not seen the clear fix for this, Can someone kindly help Thanks
