### ISSUE TITLE
UI for editing submitted on date for groups

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2935]
## Description
This ticket is to implement the UI screen to allow for the submitted on date to be edited for a group that has already been created as requested in Apache Fineract at https://issues.apache.org/jira/browse/FINERACT-618

**Comment by m-sameer** [comment]
@edcable @santoshconflux This issue can be closed.

**Comment by santoshconflux** [comment]
@m-sameer , we close the ticket after testing.

**Comment by m-sameer** [comment]
@santoshconflux Okay. :)

**Comment by santoshconflux** [comment]
Tested on staging. Fixed.
