### ISSUE TITLE
'Submit' button not working in 'Migrate Opening Balances' in Accounting and throwing improper error

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2938]
1. Define financial activity for migrate opening balances(Accounting>Accounts linked to financial activity) )
2. Go to Accounting>Migrate opening balances, select the offiece.
3. provide and debit and credit amount same.
Check the  attached screenshot. 
![w2](https://user-images.githubusercontent.com/23022667/39416829-b0b1129c-4c6d-11e8-9a3d-b68f49579e36.png)

**Comment by MexinaD** [comment]
Hello @santoshmath i don't think if that is improper error
Can one account have a debit side and credit side at the same time?

**Comment by ShruthiRajaram** [comment]
@santoshconflux  kindly check and close the issue.

**Comment by jonathanzhang53** [comment]
@santoshconflux Just a notice, this is still up on GCI task list :)
