### ISSUE TITLE
Disbursement date when entered at first it gives "Required field"

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2939]
## Description
During loan account application, when you enter the disbursement date at first, it still say the field is required until you enter the second time.

## Steps to Reproduce
Create a loan product from Admin->Product->Loan Product
Create an active client from clients->Create clients
Go to that active client and apply a loan "New Loan" and enter the disbursement date in the field "Disbursed on", at first the system will still tell you that the field is required even when you have picked the date

## Expected Behaviour
The system should not give that error since the date is already filled

## Actual Behaviour
Throws a "Required field" error

## Settings
- Mifos X version: 18.3
- Browser used: Chrome

## Screenshots, if any
![disbursedate](https://user-images.githubusercontent.com/8160209/39423635-8a82a852-4c7b-11e8-9665-a1ee9e196bf5.png)

**Comment by santoshconflux** [comment]
Duplicate https://github.com/openMF/community-app/issues/2972
