### ISSUE TITLE
Selecting Reccuring brings Fixed Deposit Product

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#2942]
**Description**
Selecting Rec-curing deposit Products brings Fixed Deposit Products during loan application to the client.

**Steps to Reproduce**
Go to client >> More >> Create Rec-curing Deposit Product >> The drop-down list are fixed deposit products
That means Rec-curing application is not possible.

 **Expected Behavior**
The drop-down list should be Rec-curing Deposit products.

**Comment by santoshconflux** [comment]
Tested on staging. Fixed.
