### ISSUE TITLE
All actions on share account actions are not working on Mifos 18.03.01

### ISSUE THREAD

**Issue by Nenge1** [openMF/community-app#2948]
## Description
All actions on share account actions except submission.  Actions not working are share approval, rejection, applying additional share,reject additional shares, redeem shares, close share

## Steps to Reproduce
Go to 
1. client,
2. Browse client profile, Goto More->New share account, submit and then try to perform any action in the share account created.

## Settings
- Mifos X version: 18.03.01
- Browser used: Chrome, Firefox

**Comment by santoshconflux** [comment]
Related ticket: https://github.com/openMF/community-app/issues/2980
