### ISSUE TITLE
Tooltips not working for Pie chart in dashboard page

### ISSUE THREAD

**Issue by chandaaparna** [openMF/community-app#2950]
We have upgraded mifos to Version 18.03 and charts are not displayed in dashboard page. We have followed the below pull request:
https://github.com/openMF/community-app/pull/2869
After changing the above pull changes, we are able to see the charts on dashboard but the issue is we are not able to see the tooltips for pie chart. 
And the other issue is, we are able to see tooltips for bar charts but the alignment of tooltip is not proper as shown in the screenshot 
![image](https://user-images.githubusercontent.com/25208383/39810046-9ec2371c-53a9-11e8-9efb-420e71c02b22.png)

Could you please help us in resolving the tooltip issue for pie chart and tooltip proper alignment for bar chart.

**Comment by chandaaparna** [comment]
@smontanari, @frankmt @Nayan @amaehrle @siebrand : Can any of you look into this issue and help me in resolving this issue.

**Comment by muddlebee** [comment]
@chandaaparna thanks for raising the issue. I will fix it asap.

Thanks

**Comment by abhaychawla** [comment]
@anweshknayak let me know if I could help as well as the issue is a continuation
of the PR made by me which fixed the dashboards.
Ref: https://github.com/openMF/community-app/pull/2869#issuecomment-387694756

**Comment by muddlebee** [comment]
@abhaychawla sure you can take this one if you want to. I am into other issues as of now.

**Comment by abhaychawla** [comment]
Okay!
