### ISSUE TITLE
Unable  to approve share account which is already submitted. 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2951]
Try to approve following share account.

https://staging.openmf.org/#/shareaccount/20/approve

username/password : mifos/password

**Comment by Nenge1** [comment]
@santoshfinflux , this is a duplicate of the issue [issue #2948](https://github.com/openMF/community-app/issues/2948)

**Comment by ShruthiRajaram** [comment]
@santoshconflux  I was able to approve the application. Can you retest and close if issue is resolved?

**Comment by abiyats** [comment]
This fix has worked for me. I have checked it.

**Comment by abiyats** [comment]
Dear All,

I have found the fix here.

https://github.com/openMF/community-app/pull/2982/files


Regards,
Abiy A.

**Comment by jonathanzhang53** [comment]
@luckyman20 This is also one of the fixed issues that is GCI task.

**Comment by luckyman20** [comment]
@jonathanzhang53 Took the task down, thanks for informing.

@santoshconflux Can we close this issue now?

**Comment by saifromeo** [comment]
where do I get the 19.12 release? Neither do I see branch, nor tag, pls help
