### ISSUE TITLE
Admin can uncheck "ALL FUNCTION" permission checkbox which removes the admin privilages 

### ISSUE THREAD

**Issue by libinmjacob** [openMF/community-app#2952]
## Description
Admin user is allowed to uncheck "ALL FUNCTION" permission on Permissions:  Special screen. It drops the admin privileges for all the other admin user as well.
 Is there any way by which we can get the admin privileges back.

## Steps to Reproduce
Login to community app as admin. 
Navigate to Admin>>System>>Manage Roles And Permissions and select an admin user. Then on Permission:Special edit screen, uncheck "ALL FUNCTION" checkbox and check "ALL FUNCTION READ" checkbox and save.  Now the admin role has only read privileges.
 
## Expected Behaviour
"ALL FUNCTION" checkbox should not be editable, as it drops all admin privileges. 

## Actual Behaviour
After unchecking the "ALL FUNCTION" checkbox, admin user does not have write privileges. 

## Settings
- Mifos X version: 17.07.01
- Browser used: Chrome

**Comment by santoshconflux** [comment]
@libinmjacob, Permissions are given to roles and the roles assigned to users. If specific role permissions are modified, it would change the permission for all users who assigned with same role.
