### ISSUE TITLE
Drop-down calendar is not displaying properly when creating Fixed Deposit Product

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#2963]
**Steps to Reproduce**
Create FDP >  Interest Rate Chart > select End Date
 ![fd from 2018-05-24 13-35-10](https://user-images.githubusercontent.com/13551795/40480483-5874bcee-5f57-11e8-9b7c-cff333f41634.png)

**Expected Behavior**
It should be aligned like, when editing Fixed Deposit Product
![fddfrom 2018-05-24 13-38-24](https://user-images.githubusercontent.com/13551795/40480696-f62d0324-5f57-11e8-932a-ee34995e186d.png)

**Comment by bauripalash** [comment]
@Agnessy @santoshconflux I think I was able to fix this issue with the above mentioned PR. Please Check!

**Comment by santoshconflux** [comment]
@abhaychawla or @ShruthiRajaram will review the PR shortly.
