### ISSUE TITLE
Unable to edit Group

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#2964]
**Description**
Create Group > Edit

**Expected Behavior**
Should allow to edit, like
![edit](https://user-images.githubusercontent.com/13551795/40655873-4b2a054c-634b-11e8-96c4-3c26063816ec.png)

 **Actual Behavior**
It opens blank page

![edit3](https://user-images.githubusercontent.com/13551795/40656179-3eb484e4-634c-11e8-840f-5d1f0dd0f900.png)

Can someone check this issue

**Comment by chandaaparna** [comment]
@santoshconflux : Could you please try to resolve this?

**Comment by santoshconflux** [comment]
Already reported here: https://github.com/openMF/community-app/issues/2930
