### ISSUE TITLE
On employee creation, "joined on" field has no sign of showing it mandatory

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2965]
## Description
When creating an employee, a joined on filled has no sign of showing its mandatory

## Steps to Reproduce
Go to Admin, then Organisation, then manage employee, create employee, fill all the fields except the "joined on" field, when you submit you will get an error that the filed can not be blank

## Expected Behaviour
The field should have the sign to show that it should not be left blank

## Actual Behaviour
There is no sign to show the field is mandatory

## Settings
- Mifos X version: 18.03
- Browser used: Chrome

## Screenshots, if any
![joinedon](https://user-images.githubusercontent.com/8160209/40899968-225f035c-67d2-11e8-844e-a8383e6c7495.png)

**Comment by Rupeshiya** [comment]
@MexinaD  I would like to fix this issue. Can I go ahead ?

**Comment by MexinaD** [comment]
Yes @Rupeshiya
