### ISSUE TITLE
Account Usage is empty when editing the chart of account

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2966]
## Description
When editing the chart of account, the field of account usage do not come with the previous filled value

## Steps to Reproduce
Go to Account -> Chart of Account -> Create by filling all necessary fields including "Account Usage"
Then view the chart of account you created and edit, the "account usage" comes without the previous filled value

## Expected Behaviour
The field to have a value that was filled during creation

## Actual Behaviour
The field comes without a value

## Settings
- Mifos X version: 18.03
- Browser used: Chrome

## Screenshots, if any
![usage](https://user-images.githubusercontent.com/8160209/40904142-809f61fe-67e2-11e8-93e0-e23d8ad3490c.png)

**Comment by elirehema** [comment]
Fix #3025
