### ISSUE TITLE
Allow to specify transfer date when transferring client from one branch to another

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2968]
## Description
System should allow a user to input a date of transfer

## Steps to Reproduce
To to a client profile Clients, then click a button of "Transfer client" and go through the process

## Expected Behaviour
The system should be improved to request for the date of transfer

## Actual Behaviour
No place to fill the date and hence take current data as a transfer date

## Settings
- Mifos X version: 18.03
- Browser used: Chrome

**Comment by santoshconflux** [comment]
Duplicate of https://github.com/openMF/community-app/issues/3005
