### ISSUE TITLE
Some Fields still show 'Required field' even after inputting the value. 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2972]
And if you again click on disbursement date then the error 'Required Field' error goes. It happens in other  date picker scenarios as well. Most of the time, this issue arises  when data picker field is empty, ie.. not filled by the system. 

![1_loanapplicationpage](https://user-images.githubusercontent.com/23022667/42449757-83d6b178-839f-11e8-9a7e-7212fb9a01ac.png)

![2_shareapplicationpage](https://user-images.githubusercontent.com/23022667/42449758-84077dda-839f-11e8-8c78-118b43aaeb21.png)

![3_shareapplicationpage2](https://user-images.githubusercontent.com/23022667/42449759-8431bb04-839f-11e8-9046-e301c243c0a2.png)

![4_newfdapplication](https://user-images.githubusercontent.com/23022667/42449760-845d2686-839f-11e8-85e0-c2d0478fabf9.png)

**Comment by ankit01ojha** [comment]
Related issue https://github.com/openMF/community-app/issues/2701

**Comment by ankit01ojha** [comment]
@santoshconflux It is not limited to creating loan application, this is present in other places too.
