### ISSUE TITLE
Unable to create a new user despite of valid email address when Auto Generate Password is enabled

### ISSUE THREAD

**Issue by abhaychawla** [openMF/community-app#2974]
## Description
Unable to create a new user despite providing a valid email address, when auto-generate password is enabled. The server returns a validation error although the email provided is correct. The same email is accepted while editing another user.

## Steps to Reproduce
Admin -> Users -> Create user -> Fill all required details and Submit

## Expected Behaviour
The server should not return an error for a valid email address so that a new user can be created.

## Actual Behaviour
The server returns an error that the email address is invalid despite it being valid and thus a new user cannot be created.

## Settings
- Mifos X version: 18.03.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![screenshot 76](https://user-images.githubusercontent.com/16948598/42662263-9ddf7f4e-864e-11e8-95db-aae3c8e930d1.png)

**Comment by ShruthiRajaram** [comment]
@abhaychawla I am unable to reproduce this issue. I created a user in demo and gave a valid email address (auto-generate password enabled). On click of submit I received a mail on given address.

**Comment by abhaychawla** [comment]
@ShruthiRajaram Yes, I am able to create the user now with my email. Maybe the issue was at the fineract side and got resolved, we could close this.
