### ISSUE TITLE
Unable to Edit Group: Clicking on 'Edit' button in Group page leading to blank page.

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2976]
1. Go to any group which is on Submitted or Activated state. 
2. Click on Edit button in the group page.
3. The navigated page is showing blank page.

**Comment by ShruthiRajaram** [comment]
@santoshconflux  fix is available with this PR - https://github.com/openMF/community-app/pull/2978

**Comment by mbj36** [comment]
@santoshconflux  this can be tested and closed

**Comment by santoshconflux** [comment]
@ShruthiRajaram , @mbj36 , Unable to fetch latest code from develop branch to test this. I also sent mail regarding this.

**Comment by mbj36** [comment]
What error are you getting ? or may be you can try to clone and rebuild it ?

**Comment by mbj36** [comment]
@santoshconflux Did you get time to test this out on your machine ?

**Comment by santoshconflux** [comment]
@mohit, No. I am still not able to 'grunt serve'

**Comment by mbj36** [comment]
Can you show me the error ?

CC - @ShruthiRajaram

**Comment by santoshconflux** [comment]
@mbj36, Forwarded mail to u

**Comment by santoshconflux** [comment]
Tested it on staging. This issue  is fixed.
