### ISSUE TITLE
Not able to approve Additional share purchase request.

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2977]
I am able to apply additional shares but not able to approve them . Check here:

https://demo.openmf.org/#/shareaccount/108/approveadditionalshares (mifos/password)

**Comment by ShruthiRajaram** [comment]
@santoshconflux  this issue is not reproducible in staging (https://staging.openmf.org/#/shareaccount/4/approveadditionalshares). Looks like already fixed. Kindly retest.
