### ISSUE TITLE
Unable to Approve or Reject Share account application which is already submitted.

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2980]
YOu can try here:

https://staging.openmf.org/#/viewshareaccount/22

Fineract ticket: https://issues.apache.org/jira/browse/FINERACT-640

**Comment by santoshconflux** [comment]
Related ticket:
https://github.com/openMF/community-app/issues/2948

**Comment by santoshconflux** [comment]
@ShruthiRajaram , Able to reject  share application, but not able to approve. Showing the error:

validation.msg.sharesaccount.shares.requested.can.not.be.approved.exceeding.totalshares.issuable 

Showing above error even total shares are not exceeding.

**Comment by santoshconflux** [comment]
Fineract issue - Closed here and moved to https://issues.apache.org/jira/browse/FINERACT-664

**Comment by alvarojimenez99** [comment]
Hi,  I have created a share product, with a very basic configuration and when assigned to a client it does not let approve, reject or delete, and does not return any errors. 
Could you help me ?. 
Thank you.

![image](https://user-images.githubusercontent.com/8192253/61960926-20acf980-af8c-11e9-9a52-82cfd449aa64.png)

![image](https://user-images.githubusercontent.com/8192253/61960965-328e9c80-af8c-11e9-8186-22caf2defed0.png)
