### ISSUE TITLE
Unable to go to next page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2984]
Reported  by May Myint at https://issues.apache.org/jira/browse/FINERACT-619

Original Description: 
On the All Reports, Users and Configurations pages, I am unable to browse the pages as clicking on the page numbers does not work. 

If I sign out, refresh a few times and log back in, it will work for a few minutes and then stop working.

Tested in https://demo.openmf.org/#/home.

**Comment by ankit01ojha** [comment]
@santoshconflux ,its already been fixed  https://github.com/openMF/community-app/pull/2943,
issue similar to https://github.com/openMF/community-app/pull/2861 (please see the comments for the issue).

**Comment by santoshconflux** [comment]
@ankit01ojha , Thanks. Closing  now.
