### ISSUE TITLE
DataTable date fields: datepicker disables dates before 1st Jan of this year

### ISSUE THREAD

**Issue by terencemo** [openMF/community-app#3001]
## Description
When editing a datatable having date fields, the date field may need to have values of previous years, e.g for a Next of Kin datatable, the date of birth of the next of kin can be several years before. Hence we need to be able to select dates of previous years. Currently, the datepicker only enables dates from 1st Jan, 2018 (as 2018 is the current year).

## Steps to Reproduce
Create a client datatable for example Next of Kin and add a date column to it e.g date of birth. Then go to a client and try to enter this datatable data. Select the date field created earlier. You will see a calendar popup (datepicker).

## Expected Behaviour

You should be able to select any date in the past in a previous year.

## Actual Behaviour

Previous years are disabled and cannot be selected via datepicker.

## Settings
- Mifos X version: 18.03.01
- Browser used: Google Chrome

**Comment by loveloud** [comment]
hello, I'm an applicant for outreachy, I would love to fix this.i have already set up the community app locally.I seek further guidance on how to solve this issue

**Comment by terencemo** [comment]
@Hackingforlife this has already been fixed by PR https://github.com/openMF/community-app/pull/3008 but there is a related issue https://github.com/openMF/community-app/issues/3092 which I suggest you can fix instead. Otherwise you can copy-paste the changes from the above PR and add changes that fix both issues 3008 and 3092 since the reviewer of the above PR stated desire was that fixes for both issues be combined into a single PR.
