### ISSUE TITLE
Repayment Schedule Alignment 

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#3002]
**Description**
Repayment Schedule Alignment when the applied amount is large.
**Steps to Reproduce**
Apply loan to a client with a high amount of principle, submit
view repayment schedule.
the outstanding amount is not seen clearly(fully). 

**Screenshots**
![repayment](https://user-images.githubusercontent.com/13551795/44207663-c3e37500-a166-11e8-95c5-0e6790b153c5.png)

**Comment by elirehema** [comment]
@santoshconflux  can i work on this issue?

**Comment by aaryan01** [comment]
@santoshconflux Can I work on this issue? I think I might have a possible solution to it.
![screenshot from 2019-01-08 19-18-29](https://user-images.githubusercontent.com/31697449/50834725-cf844200-137a-11e9-9e5b-853572a83f1f.png)

**Comment by santoshconflux** [comment]
Thank for PR, @aaryan01

**Comment by santoshconflux** [comment]
@awasum , Could you please review this PR?
https://github.com/openMF/community-app/pull/3081

**Comment by awasum** [comment]
@santoshconflux  I am on it.
