### ISSUE TITLE
Penalties Receivable tooltip translation in Loan product 

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#3003]
**Steps to Reproduce**
Create loan Product with Accrual Accounting, submit
then edit product
Penalties Receivable  tool-tip under Asset  is not translated.

 **Screenshots**, if any
![penalty](https://user-images.githubusercontent.com/13551795/44209169-538b2280-a16b-11e8-892b-66af3a1c4d5c.png)

**Comment by jshokoor** [comment]
I would like to work on this issue as my contribution for the Outreachy internship application. I will submit my application with a link to this page for now, until further instruction.

**Comment by bauripalash** [comment]
@Agnessy @santoshconflux I think the PR mentioned above solves this issue. Take a look

**Comment by abhaychawla** [comment]
@bauripalash From next time please ensure that no one else is working on the issue before sending a PR directly. Comment and ask before you start working on the issue.

**Comment by bauripalash** [comment]
I apologise for any inconvenience made.

@abhaychawla but it was a task in Google Code-in that's why I didn't asked anybody! I apologise

**Comment by abhaychawla** [comment]
@bauripalash Its okay, it wasn't a mistake. Looks like we had a miscommunication here as the `GCI 2018` label was absent. You may go ahead and work on the specific issues freely if it is a GCI task once you claim it on its portal.

**Comment by bauripalash** [comment]
Thank You
