### ISSUE TITLE
Activation date field should throw error when edit center

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#3004]
**Steps to Reproduce**
Create center, then edit
empty activation date, submit, nothing happen
**Expected Behaviour**
should show error which shows its mandatory, like when creating center
![activation 2018-08-17 10-14-41](https://user-images.githubusercontent.com/13551795/44253300-d8c41500-a207-11e8-97a6-6e6669226089.png)

**Comment by santoshconflux** [comment]
Its throwing 500  internal server error.

**Comment by Rupeshiya** [comment]
@santoshconflux  @Agnessy   It's working fine in my case , I have tried as you have done ,getting expected output  that is 
```
 field is required
validation.msg.center.activationDate.cannot.be.blank -
```
I think there is no issue ,please check it again.

**Comment by santoshconflux** [comment]
Fixed.
