### ISSUE TITLE
ADDING TRANSFER DATE WHEN A CLIENT IS TRANSFERED FROM ONE BRANCH TO ANOTHER

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3005]
Related fineract ticket:
https://issues.apache.org/jira/browse/FINERACT-627

We need this feature in Mifosx. The current scenario is, when you want to transfer a client from one branch to another you do not need to choose which date the transfer was made, Mifos x picks the current date of the transfer. so for us we find it to be a big need to have a place to select a date when we are transferring a client from one branch to another. simply because most of the time our clients transfer are done with back dates. This helps put a real record concerning a client transfer.

**Comment by MexinaD** [comment]
Hello @santoshconflux 
This is a dublicate of #2968

**Comment by santoshconflux** [comment]
@MexinaD , That issue is closed.
