### ISSUE TITLE
☰ Button at Top Left Corner Does Nothing

### ISSUE THREAD

**Issue by bauripalash** [openMF/community-app#3037]
## Description
I tried clicking ☰ button at top left corner beside the MifosX logo , but it actually does nothing but wasting space.

## Steps to Reproduce
* Open MifosX Web App
* Login
* Try Clicking ☰ button at top left corner
* Nothing Happens

## Expected Behaviour
Do Something

## Actual Behaviour
Does Nothing

## Settings
- Mifos X version:  18.03.01.RELEASE 
- Browser used: Firefox Quantum on Ubuntu

## Screenshots, if any
![screenshot from 2018-11-08 11-25-37](https://user-images.githubusercontent.com/16154204/48194200-57959d80-e372-11e8-8b48-cc9281f33298.png)

**Comment by abhaychawla** [comment]
@bauripalash This is a duplicate of https://github.com/openMF/community-app/issues/2714 and a PR has already been sent. Kindly have a look at existing issues before creating a new one. Close this.

**Comment by bauripalash** [comment]
Apologise.
I tried searching for that kind of issue in issue searchbar, but as no results were showing so opened this issue.
Apologise!
