### ISSUE TITLE
Create Closure Button In Accounting Closures Needs More Padding

### ISSUE THREAD

**Issue by bauripalash** [openMF/community-app#3038]
## Description
Create Closure button in Account Closure needs a more padding

## Steps to Reproduce
* Open and Login MifosX Web App
* Visit Account Closure `/accounts_closure`

## Expected Behaviour
Create Closure button should be with padding to look good

## Actual Behaviour
Create Closure button is touching borders of container

## Settings
- Mifos X version:  18.03.01.RELEASE 
- Browser used: Firefox Quantum on Ubuntu and Chrome 70 for Android

## Screenshots, if any
![screenshot_2018-11-08-16-27-50](https://user-images.githubusercontent.com/16154204/48194924-5bc2ba80-e374-11e8-9bc8-e53b367f8170.png)

**Comment by elirehema** [comment]
Fixed #3042
