### ISSUE TITLE
Indian Currency in Currency field in Frequent Postings Not Showing Properly

### ISSUE THREAD

**Issue by bauripalash** [openMF/community-app#3039]
## Description
Indian Currency in Currency field of Frequent Postings Not Showing Properly 

## Steps to Reproduce
* Open and Login in MifosX
* Visit <https://demo3.openmf.org/#/freqposting>
* Take a Look in Currency field

## Expected Behaviour
Indian Currency Symbol Should be shown as ₹

## Actual Behaviour
Indian Currency Symbol is showing some weird characters

[**Extra Information**](https://www.fileformat.info/info/unicode/char/20b9/index.htm)

## Settings
- Mifos X version: 18.03.01.RELEASE 
- Browser used: Firefox Quantum on Ubuntu and Chrome 70 for Android

## Screenshots, if any
![screenshot_2018-11-08-16-40-55](https://user-images.githubusercontent.com/16154204/48196344-62533100-e378-11e8-8e1d-b1eb943e2f3d.png)

**Comment by abhaychawla** [comment]
Similar to https://github.com/openMF/community-app/issues/2440, this is a backend issue.

**Comment by bauripalash** [comment]
https://issues.apache.org/jira/plugins/servlet/mobile#issue/FINERACT-547
