### ISSUE TITLE
Need a new permission for Assign Staff and Unassign Staff for Loans & Savings

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3043]
If We go to System>Manage Roles and  Permissions ,  There is no choice of permission for Assign Staff & Unassign Staff under 'Loan Transactions' and 'Savings Transactions Category'.

Same must be added. 

Fineract ticket: 

https://issues.apache.org/jira/browse/FINERACT-654

**Comment by ShruthiRajaram** [comment]
For Loan - UPDATELOANOFFICER_LOAN and REMOVELOANOFFICER_LOAN for assign and unassign respectively. They come under he Loan Transactions
For Savings - UPDATESAVINGSOFFICER_SAVINGSACCOUNTand REMOVESAVINGSOFFICER_SAVINGSACCOUNT respectively for assign and unassign. These permissions are present under portfolio.

**Comment by edcable** [comment]
@santoshconflux Are we moving these or just leaving as is?

**Comment by santoshconflux** [comment]
@edcable, I didn't get you. This is already fixed and PR is sent by Shruthi. Waiting to be someone review it

**Comment by santoshconflux** [comment]
Tested on Staging. Fixed.
