### ISSUE TITLE
# Staff under Navigation should be integrated with table right above

### ISSUE THREAD

**Issue by jonathanzhang53** [openMF/community-app#3047]
## Description
When you select an office to navigate to its details with the navigation tool, the '# staff' is not aligned with the above table, and when taking a look at the html, is not even in the same table tag. It should be in the table to look better with same font size. Also, the number of staff is disproportionate and out of place.

## Steps to Reproduce
- Open https://demo.openmf.org
- Hover over the left toolbar
![image](https://user-images.githubusercontent.com/41968151/48308672-61b0cb00-e52f-11e8-88f9-fd74b2a814b6.png)
- Click navigation
- Click 'offices ()' button
- Select an office
- See issue to the right in the table

## Expected Behaviour
'# Staff' and the number should be with the other table values: 'opened on' and 'external id'.

## Actual Behaviour
'# Staff' and the number are outside of table and different from other lettering on the page.

## Settings
- Mifos X version: Release Version: 18.03.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
![image](https://user-images.githubusercontent.com/41968151/48294856-aadc1e80-e44c-11e8-914e-aea1f1716952.png)

**Comment by bauripalash** [comment]
I found the problem. I hope I'll be able to fix it within few hours

**Comment by bauripalash** [comment]
I think this issue is solved by #3049

**Comment by jonathanzhang53** [comment]
@bauripalash thanks. was going to fix it myself but I guess you beat me to it :)
