### ISSUE TITLE
Correcting Checker Inbox Labels

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3050]
If we go to Checker Inbox menu, there are 3 buttons. Approve, Delete and Reject. If we click on the button, it should show 'Confirm Approve?', 'Confirm Delete?' and 'Confirm Reject?' texts respectively in the pop menu.
In stead of 'Confirm' and 'Cancel' button , 'Yes' and 'No'  buttons needed.

![ss](https://user-images.githubusercontent.com/23022667/48339295-e3b70600-e68d-11e8-95e0-abbd33a16c73.png)

**Comment by bauripalash** [comment]
Seems to work fine!
What's the problem with `Confirm` and `Cancel` buttons. Please Clarify!

**Comment by elirehema** [comment]
Can i work on this?....
