### ISSUE TITLE
Issue with Balance sheet and Trial Balance when product is enabled is with Advanced Accounting

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3058]
There is an issue in Advanced Accounting Rule.
In the loan product setting, two charges (e.g., Servie charge and Loan Fees) are applied. One of the charges is linked to Accounts Payable (by using Advanced Accounting Rule).
When we run Balance Sheet/Trial Balance, the amount doesn't show up in the respective COA (Accounts Payable). But, the expected amount is showing in other COA (which is Fee Income in my example).

![sww](https://user-images.githubusercontent.com/23022667/49646830-64c3ac00-fa46-11e8-8da3-a6ed82120307.png)

This is loan product setting :

https://demo.openmf.org/#/viewloanproduct/673

Below is Loan Fees :
https://demo.openmf.org/#/viewcharge/266

Below is Service Charge :
https://demo.openmf.org/#/viewcharge/265
https://demo.openmf.org/#/viewcharge/266 https://demo.openmf.org/#/viewloanproduct/673
Below is disbursed loan account:
https://demo.openmf.org/#/viewloanaccount/2237

Below is Trial Balance report
Unable to render embedded object: File (w9GXoyr9HS7AgAAAABJRU5ErkJggg==) not found.
https://demo.openmf.org/#/viewloanaccount/2237
According to the product setting, Fee Income should be only 2000 credited.
Another 2000 should be credited to Accounts Payable.

https://demo.openmf.org/#/viewloanproduct/673

https://issues.apache.org/jira/browse/FINERACT-600

**Comment by bharathcgowda** [comment]
The bug in the advance accounting module where the system is not passing the accounting entries properly. there was issue earlier which was fixed by has been resurfaced again. have raised a ticket for the same in Fineract JIRA (https://issues.apache.org/jira/browse/FINERACT-1031)

**Comment by bharathcgowda** [comment]
closing this issue after discussing with Ed.
