### ISSUE TITLE
Cancel button for Reschedule Loan in Checker Inbox & Tasks Do Nothing

### ISSUE THREAD

**Issue by AgnessMeena** [openMF/community-app#3061]
## Description
Go to Checker Inbox & Tasks >> Reschedule Loan >> Approve Then Cancel, Nothing happen
It suppose  to cancel the page
![res](https://user-images.githubusercontent.com/13551795/49941983-10607680-fef5-11e8-809f-388560215bfd.png)

**Comment by Rupeshiya** [comment]
@santoshconflux  I would love to fix this .
Can I proceed ahead ?

**Comment by edcable** [comment]
@Rupeshiya please go ahead. I'll assign you to the issue.

**Comment by Rupeshiya** [comment]
Hi edcable,

Thanks for assigning me the issue.
Will fix it now.

**Comment by Rupeshiya** [comment]
@edcable  plz review .
