### ISSUE TITLE
Submit operation is done twice in edit share product

### ISSUE THREAD

**Issue by ShruthiRajaram** [openMF/community-app#3073]
## Description
 On clicking the submit button in edit share product, update share product API is called twice. 

## Steps to Reproduce
Step 1. Go to Admin->Products -> Share products->select any existing share product->edit
Step 2. Open inspect mode  - > click on submit. You will see that update API (Put request) is called twice. Or  add market price and submit. Though you added 1 market price, you will notice duplicate entry.

## Expected Behaviour
Update API should be called only once

## Settings

- Mifos X version: 17.07.01
- Browser used: Chrome
- OS: Windows 10

**Comment by santoshconflux** [comment]
Fixed.
