### ISSUE TITLE
Travis Build Failing

### ISSUE THREAD

**Issue by Jov03** [openMF/community-app#3077]
## Description

In recent PRs while testing travis is unable to register grunt karma task where as when tests are executed locally they work fine.
 
## Expected Behaviour

task should register successfully so that travis can execute tests.

## Actual Behaviour

Unable to register grunt karma task while building project.

## Screenshot from a failed build logs 
![screenshot from 2018-12-30 01-16-18](https://user-images.githubusercontent.com/15383669/50541755-1c755500-0bd2-11e9-84ba-fb55dc629c25.png)

## Screenshot from a successful build logs
![screenshot from 2018-12-30 01-27-05](https://user-images.githubusercontent.com/15383669/50541757-2c8d3480-0bd2-11e9-8350-f60dd2c63a0a.png)

**Comment by abhaychawla** [comment]
Fixed via https://github.com/openMF/community-app/pull/3087

**Comment by vorburger** [comment]
Closing (but note, new/separate #3111)
