### ISSUE TITLE
In share Product creation process, after entering all mandatory values for 'Terms' step , the navigation wizard indicates that all mandatory values are not added for 'Terms' step

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3080]
1) Go to Admin>Products>Share Products> Create Share Product.
2) Go step by step and enter all the values in 'Terms' step and go to next step:
> Terms step navigation wizard shows all mandatory values are not entered. check the screenshot.

![share product creation](https://user-images.githubusercontent.com/23022667/50675467-6025ef80-1014-11e9-91d9-92ce17baedf8.png)

**Comment by abhi40308** [comment]
@edcable  I tried to reproduce this issue and it seems to work fine. I did not get this error. Can someone else confirm this so we can close this issue?

**Comment by abhi40308** [comment]
![Screenshot 2020-06-19 at 12 41 44 AM](https://user-images.githubusercontent.com/26903230/85062224-b9acba80-b1c5-11ea-87d1-c8937005eb0b.png)

**Comment by edcable** [comment]
Still same issue for me. 
![Screenshot 2020-08-06 at 3 31 36 PM](https://user-images.githubusercontent.com/823454/89589188-02621680-d7fa-11ea-97e2-e9f0d61a280f.png)
![Screenshot 2020-08-06 at 3 30 36 PM](https://user-images.githubusercontent.com/823454/89589190-03934380-d7fa-11ea-80f4-9436d9a60d90.png)

**Comment by ikimbra** [comment]
I had the same issue when I was using version 18.03 and when I upgraded to 19.12 it is still the same issue. Is it that this is just on the windows users?
![Screenshot (153)](https://user-images.githubusercontent.com/69110649/93137536-4e9c5280-f6e6-11ea-9a9d-a4d716d0393a.png)
![Screenshot (154)](https://user-images.githubusercontent.com/69110649/93137540-51974300-f6e6-11ea-9966-a06b6f41ea00.png)

**Comment by edcable** [comment]
This is still an issue in Chrome on a Pixel Slate.

**Comment by spider0061** [comment]
@BLasan can you work on it please?

**Comment by BLasan** [comment]
> @BLasan can you work on it please?

Sure. I'll work on this
