### ISSUE TITLE
Not Required Group and Center

### ISSUE THREAD

**Issue by raakeshtomarnew** [openMF/community-app#3085]
Not required Group and Center
## Description
The Institution Not Required Group and center

## Steps to Reproduce
Hide Group in menu
Hide Center in menu

## Expected Behavior
Group and center in menu

## Actual Behavior
Not want center and group

## Settings

- Mifos X version: 18.0.3
- Browser used:google chrome
- OS:win7

**Comment by santoshconflux** [comment]
@raakeshtomarnew , Can we create user with no permissions - 'Read Group', and 'Read Center'?

**Comment by santoshconflux** [comment]
Closing this ticket as per my above comment.
