### ISSUE TITLE
Missing Information in Navigation page

### ISSUE THREAD

**Issue by SupreethSudhakaranMenon** [openMF/community-app#3090]
## Description
There is no information provided in the labels of Navigation Page

## Steps to Reproduce
You can use the demo version of the app provided https://demo.openmf.org/#/ or clone the repo into your local system and follow the instructions given in the page to how to run it locally on your machine.
Move the Cursor towards the side bar which comes across the screen and click on the Navigation button.
After which you can find a search bar used for filtering the name and just below that you have four labels
1) Offices()
2) Loan Officers
3) Centers
4) Groups
5) Clients
There is no data available for Loan Officers , Centers , Groups  and Clients and also Clients dropdown menu also does not function properly.

## Expected Behaviour
Labels other than Offices()  show no data  when clicked , so data should be provided and should be visible in case of the other four. 

## Actual Behaviour
Information should be visible , in the Loan Officers , Centers , Groups , Clients labels. 

## Settings
- Browser used: Google Chrome
- OS: Ubuntu 

## Screenshots
![All labels](https://user-images.githubusercontent.com/45706852/54377186-a9e12500-46aa-11e9-9eec-6da639e77864.PNG)
![Offices()_data](https://user-images.githubusercontent.com/45706852/54377206-b2396000-46aa-11e9-8c0e-e4b13567974e.PNG)
![Loan_nodata](https://user-images.githubusercontent.com/45706852/54377227-c1b8a900-46aa-11e9-8aee-e5177e48d2e4.PNG)
![Centers_nodata](https://user-images.githubusercontent.com/45706852/54377237-c54c3000-46aa-11e9-99b3-643b75692db5.PNG)
![Groups_nodata](https://user-images.githubusercontent.com/45706852/54377251-ca10e400-46aa-11e9-9efe-02a1af38aac5.PNG)
![Clients_notwork_nodata](https://user-images.githubusercontent.com/45706852/54377265-d006c500-46aa-11e9-8312-5aedb64293a4.PNG)

**Comment by abhaychawla** [comment]
@SupreethSudhakaranMenon This is how it is meant to work. It is not an issue. Please read the manual.
https://mifosforge.jira.com/wiki/spaces/docs/pages/82706692/Navigation+Tool
Kindly close the issue.

**Comment by santoshconflux** [comment]
Closing this ticket.
