### ISSUE TITLE
Play button alongside Run report button in Reports Section

### ISSUE THREAD

**Issue by SupreethSudhakaranMenon** [openMF/community-app#3091]
## Description
There should be a play button beside the Run report button which would help it look more interactive to the user.

## Steps to Reproduce
You can use the demo version of the app provided https://demo.openmf.org/#/ or clone the repo into your local machine and follow the instructions given in the page to how to run it locally on your machine.
After the setup is done ,  hover on the top navbar you can see the Reports -> Click on "All" -> Select any one of the below , for Eg., in this case let's go with the first one "A test report" -> You will be taken to the page where the run button will be visible to you.

## Expected Behaviour
![#2752](https://user-images.githubusercontent.com/45706852/54470874-c9c13780-47d5-11e9-852c-c6abd6d6fa1d.png)

## Actual Behaviour
![issue](https://user-images.githubusercontent.com/45706852/54470886-f2493180-47d5-11e9-8397-52bd04ccf58b.png)

## Settings
- Browser used: Firefox
- OS: Ubuntu

**Comment by abhaychawla** [comment]
The issue was already fixed by the PR https://github.com/openMF/community-app/pull/2922. Please close the issue if it cannot be reproduced on the `develop` branch of the repository when you clone it.

**Comment by santoshconflux** [comment]
Closing this ticket.
