### ISSUE TITLE
DataTable date+time fields: datepicker disables dates before 1st Jan of this year

### ISSUE THREAD

**Issue by terencemo** [openMF/community-app#3092]
## Description

This is similar to issue #3001 but is for a different data type and I believe merits to be a separate issue. When editing a datatable having date & time fields, the date field may need to have values of previous years, e.g for a Next of Kin datatable, the date of birth of the next of kin can be several years before. Hence we need to be able to select dates of previous years. Currently, the datepicker only enables dates from 1st Jan, 2018 (as 2018 is the current year).

## Steps to Reproduce

Create a client datatable for example Next of Kin and add a date column to it e.g date of birth. Then go to a client and try to enter this datatable data. Select the date field created earlier. You will see a calendar popup (datepicker).

## Expected Behaviour

You should be able to select any date in the past in a previous year.

## Actual Behaviour

Previous years are disabled and cannot be selected via datepicker.

## Settings

- Mifos X version: 18.03.01
- Browser used: Google Chrome

**Comment by edcable** [comment]
Fixed by #3008
