### ISSUE TITLE
Add Getting Started Doc to help new contributors to understand the code base

### ISSUE THREAD

**Issue by awasum** [openMF/community-app#3097]
Transfer this doc: https://docs.google.com/document/d/1oXQ2mNojyDFkY_x4RBRPaqS-xhpnDE9coQnbmI3Pobw/edit#heading=h.vhgp8hu9moqn to a Getting-Started.md file at the root of the source code for easy update and access.

**Comment by SupreethSudhakaranMenon** [comment]
Please refer to this one https://github.com/openMF/community-app/pull/3098

**Comment by awasum** [comment]
Thanks @SupreethSudhakaranMenon . @santoshconflux , there is a PR already for this issue: #3098

**Comment by santoshconflux** [comment]
The PR https://github.com/openMF/community-app/pull/3098 already merged. Closing this ticket. 
@awasum
