### ISSUE TITLE
Auto create staff when creating user

### ISSUE THREAD

**Issue by awasum** [openMF/community-app#3109]
We should be able to create a new staff/employee automatically when creating a new user on the system. We could have field which when selected will make the system to auto create a staff/employee on creating a new system user.

**Comment by santoshconflux** [comment]
The enhancement could be - if you don't select 'Staff' from drop-down menu while creating user, the staff should also be created with same First name and Last name and 'Is Loan Officer?' tick.

**Comment by awasum** [comment]
I dont think this is very important.
