### ISSUE TITLE
Link Getting-Started.md to be accessed from README.md for new contributors.

### ISSUE THREAD

**Issue by awasum** [openMF/community-app#3113]
See also issue #3097 

See PR #3098 

In README.md, Add link to Getting-started.md.

**Comment by urstrulykkr** [comment]
Hi there,
I would like to work on this.

**Comment by urstrulykkr** [comment]
Hi,
I would like to work on this issue.

**Comment by awasum** [comment]
Sorry. This has been fixed with this PR: https://github.com/openMF/community-app/pull/3098

Please pick another issue which does not link to a PR.

Let me close this to avoid confusion.

**Comment by urstrulykkr** [comment]
Sure.

**Comment by awasum** [comment]
Can you try this? https://github.com/openMF/community-app/issues/3104

It also involves a backend fix on Fineract

**Comment by urstrulykkr** [comment]
I will.
