### ISSUE TITLE
Enable Hidden Fields When Creating and Updating a Loan Account

### ISSUE THREAD

**Issue by awasum** [openMF/community-app#3119]
By default, when creating a loan account for a client, some/most loan details are missing.
Use the following to send a PR which fixes the issue so that hidden fields can be used when creating a new loan.

Details on mailing list here: https://sourceforge.net/p/mifos/mailman/message/36775622/

This involves modifying this file: https://github.com/openMF/community-app/blob/develop/app/scripts/config/UIconfig.json

As shown on the mailing list thread above

**Comment by junbetterway** [comment]
Let me take this one @awasum. Thanks
