### ISSUE TITLE
Fields are missing in new loan application page and edit loan application page in recent code

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3121]
New Screen: 
![new screen](https://user-images.githubusercontent.com/23022667/66454316-268f8280-ea85-11e9-9aac-8b6df33033aa.png)

Old Screen with Missing Fields , highlighted:

![old screen](https://user-images.githubusercontent.com/23022667/66454339-35763500-ea85-11e9-9a45-aad131f275f7.png)

**Comment by awasum** [comment]
Hi, Please check this commit: https://github.com/openMF/community-app/commit/906fb21cb33be9cb212d845dff6d24fb69161c89

It may already solve this issue. here is PR: https://github.com/openMF/community-app/pull/3120

**Comment by edcable** [comment]
Closed as resolved.
