### ISSUE TITLE
Landing page Loading issues

### ISSUE THREAD

**Issue by VampireNaeem** [openMF/community-app#3122]
The login page is taking so much time in loading, 

if we clear cache then it takes too long, often it crashes

**Comment by santoshconflux** [comment]
@VampireNaeem , where did you try, locally or?

**Comment by VampireNaeem** [comment]
> @VampireNaeem , where did you try, locally or?

Yeah locally and on Demo server too

**Comment by shivanshxyz** [comment]
The local setup fetches the API from demo server so when the demo server remains down then the local setup doesn't work either.

**Comment by shivanshxyz** [comment]
@VampireNaeem its not a bug so please close the issue

**Comment by VampireNaeem** [comment]
this is not the bug
