### ISSUE TITLE
Missing Description, Author, Repository and Homepage from package.json

### ISSUE THREAD

**Issue by lelouchB** [openMF/community-app#3127]
## Description
Add description, author, repository, homepage, to the package.json of the Mifos Community App.

## Steps to Reproduce
Add the above-mentioned information to the package.json file. Refer to [npm-package.json](https://docs.npmjs.com/files/package.json).

## Expected Behaviour

Package.json should have all the necessary information like description, author, repository and homepage.

## Actual Behaviour

Package.json has the necessary information. 
## Settings

- Mifos X version: 17.07.01.RELEASE
- Browser used: chrome
- OS:  window

**Comment by Rupeshiya** [comment]
Thanks for opening this issue @lelouchB

**Comment by lelouchB** [comment]
@Rupeshiya , this is for upcoming GCI, so if you can also add that label,
I am waiting for the access otherwise I would have added label already,
Thanks

**Comment by luckyman20** [comment]
@lelouchB Please be specific what details you want to be included.

**Comment by lelouchB** [comment]
@luckyman20  will do, can you add gci label to this issue

**Comment by Rupeshiya** [comment]
@lelouchB plz keep patience, will do that.

**Comment by luckyman20** [comment]
@lelouchB I have done my work, please do yours.

**Comment by lelouchB** [comment]
@luckyman20 Is this okay now?

**Comment by boyuan12** [comment]
Hi, may I try to working on this issue?

**Comment by lelouchB** [comment]
Yeah, sure

**Comment by boyuan12** [comment]
Please take a look on this PR I just created: https://github.com/openMF/community-app/pull/3181

Thanks.
