### ISSUE TITLE
No Validations for username and password length while creating self-service user

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3136]
**Summary:**
Self service mobile app expects minimum 5 characters for username and 6 characters for password. But while creating self service user on Web, there is no validation for username and password length

**Steps to Reproduce**
1) Go to client page> click on 'More' button.
2) In 'More' menu, click on 'Create Self Service user'
3) In next navigation page - create self service user page - provide username with less than 5 characters and uncheck 'Auto Generate password'.
4) Provide  password with less than 6 characters in password field.

**Expected Behaviour**
While entering the username, validation should appear saying 'username length should be minimum 5 characters'.

While entering the password, validation should appear saying 'password length should be minimum 6 characters'.

 **Actual Behaviour**
No password or username validation is appearing and accepting username or password of any length.

**Comment by santoshconflux** [comment]
@botraunak , Could you look into this ticket?

**Comment by botraunak** [comment]
@santoshconflux Sure, I'll look into this!

**Comment by shivanshxyz** [comment]
This issue is still open. Can I work on it?

**Comment by abhaychawla** [comment]
@thefossguy this issue is reserved for GCI students.

**Comment by nnatarajan** [comment]
@santoshconflux , can you please assign to me. This is one of the issues that Ed suggested that I work on.

**Comment by nnatarajan** [comment]
Is the validation only number of characters? Are there no other checks for password?

**Comment by nnatarajan** [comment]
Is is possible that I can be assigned to this issue?
