### ISSUE TITLE
Need meaningful tooltip for help link in 'Create Self user page'

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#3139]
## Steps to Reproduce
1) Go to client page> click on 'More' button.
2) In 'More' menu, click on 'Create Self Service user'
3) Observe the label against the button "Activate Self Service User".

## Expected Behaviour
Need meaningful label, "Activate Self Service User Help"

## Actual Behaviour
Refer the screenshot.
## Settings
 Mifos X version: 19.12.01 (Unreased)
- Browser used: Google Chrome
- OS: Ubuntu 18.04

## Screenshots
![s2](https://user-images.githubusercontent.com/23022667/69610650-3c1b3480-1052-11ea-824c-5d655e5cd3c9.png)

**Comment by OHassini** [comment]
Hi, I just fixed this issue, please have a look at my PR and any feedback will be welcome 😄 .
