### ISSUE TITLE
Keys defined multiple times in local-en.json

### ISSUE THREAD

**Issue by muskankhedia** [openMF/community-app#3141]
## Description
The keys in the file local-en.json in the global-translations folder has been defined multiple times which only creates complexity and increased the length of the file.

#### Points to be kept in mind:
The keys starting with # are meant for identification within the file for a particular section and need not be considered as redundant. Please don't remove those. Only remove redundancies such as label.heading.debitaccount occurring multiple times in a single section. If a single key is occurring multiple times but in different sections shift them under #Common under the correct key and remove them from those sections where it was occurring multiple times.

## Steps to Reproduce

Search for the redundant keys in the local-en.json file.

## Expected Behaviour

All the keys are required at most once in the file with proper management.

## Actual Behaviour

Some of the keys are present repeatedlu in the same file.

## Settings

- Mifos X version: 19.12.01(Unreleased)
- Browser used: Google Chrome
- OS: Fedora

## Screenshots
N/A

**Comment by abhaychawla** [comment]
@muskankhedia Please completely specify details under all the headings of the issue and remove the part about #Button from the entire description. Also, specify the settings/screenshot as N/A if those are not applicable for this issue.

**Comment by muskankhedia** [comment]
@abhaychawla I have updated it and will surely keep this in mind.
