### ISSUE TITLE
Some titles in the login page do not get translated

### ISSUE THREAD

**Issue by OHassini** [openMF/community-app#3157]
## Description
Some titles in the login page do not change when the language of the website is changed.

## Steps to Reproduce

Visit the login page of the Mifos X app and change the language via the dropdown in the top right corner.
## Expected Behaviour

The titles should change when the language is changed.
## Actual Behaviour

The titles remain the same when the language is changed.
## Settings

- Mifos X version: 
- Browser used:
- OS:

## Screenshots

![Clipboard01](https://user-images.githubusercontent.com/38397893/70387836-4c180a00-19aa-11ea-89ea-815706c3dd9a.jpg)

**Comment by abhaychawla** [comment]
@OussEmaDevCode Please update the description part under the Settings heading.
