### ISSUE TITLE
"Filter by Name" searching across extra fields in many components

### ISSUE THREAD

**Issue by punwai** [openMF/community-app#3163]
## Description
This issue is stemming on from #2909. Many components have a problem where the "Filter By Name" box filters items by ALL its attributes apart from name, even including attributes which are not shown in the table. As it is important for users to still be able to filter by other attributes apart from name, my suggestion to fix this is not to limit all search by name, but to limit it to other fields if require (eg. email), but specifying this in the search box.

## Steps to Reproduce
Admin > Users
- Try viewing an item by clicking on it and view its login name (an attribute not shown), return to the Users page and 
- Use the "Filter By Name" to search for an item by the login name found earlier.

## Expected Behaviour
Reports > All/Clients/Loans/Savings/Funds/Accounting: Filters only by Name

Users: Filters by Name/Email
Organizations > Manage Employees: Filters by only Name
Organizations > Manage Holidays: Filters by only Name
Organizations > SMS Campaigns: Filters by only Name
Organizations > AdHoc Queries: Filters by only Name

System > Data Table: Filters by only Name
System > Manage Codes: Filters by only Name
System > Manage Hooks: Filters by only Name
System > Manage Reports: Filters by only Name
System > Configurations: Filters by only Name

Products > List of Charges: Filters by only Name

## Actual Behaviour
Reports > All/Clients/Loans/Savings/Funds/Accounting: Filters by all fields

Users: Filters by all fields
Organizations > Manage Employees: Filters by all fields
Organizations > Manage Holidays: Filters by all fields
Organizations > SMS Campaigns: Filters by all fields
Organizations > AdHoc Queries: Filters by all fields

System > Data Table: Filters by all fields
System > Manage Codes: Filters by all fields
System > Manage Hooks: Filters by all fields
System > Manage Reports: Filters by all fields
System > Configurations: Filters by all fields

Products > List of Charges: Filters by all fields

## Settings
- Mifos X version: 19.12.01
- Browser used: Google Chrome
- OS: MacOS Mojave 10.14.3

## Screenshots
<img width="947" alt="Screenshot 2019-12-14 at 00 43 36" src="https://user-images.githubusercontent.com/28529491/70821817-9d8f2180-1e0e-11ea-9bb6-33f969e4be55.png">
<img width="393" alt="Screenshot 2019-12-14 at 00 43 26" src="https://user-images.githubusercontent.com/28529491/70821821-9ec04e80-1e0e-11ea-96ef-e91d13615739.png">

**Comment by abhaychawla** [comment]
@punwai Good work on the issue. Let us ensure the filtering is possible with all possible attributes of the data which are visible within the table instead of just name. The text of search fields can be generalized as just `Filter`.
