### ISSUE TITLE
https://demo.openmf.org/ not working

### ISSUE THREAD

**Issue by jannomeister** [openMF/community-app#3183]

**Comment by OHassini** [comment]
@jannomeister That's not an issue with the community app itself, it's just a server issue. You can use https://demo.mifos.io/ to prevent that.

**Comment by awasum** [comment]
Hi,

New demo server instance located here: https://demo.mifos.io/

API Doc instance: https://demo.mifos.io/api-docs/apiLive.htm

**Comment by mathekaJosef** [comment]
my url "http://localhost:9002/?baseApiUrl=https://demo.openmf.org#/" not working, please help.

**Comment by awasum** [comment]
http://localhost:9002/?baseApiUrl=https://demo.mifos.io/

**Comment by Abhirup-99** [comment]
@awasum this issue is still there even with demo.mifos.io. Can you suggest an alternative?
