### ISSUE TITLE
BUG:not able to approve a shares account.

### ISSUE THREAD

**Issue by bharathgowda27** [openMF/community-app#3191]
take the code base of 18.03.01 latest release

To reproduce the issue
> create a basic shares product 
> create a shares account to any client
> try to approve the shares account.

approve button is not hitting any APIs and hence not able to proceed further.

find below screenshot for reference
![image](https://user-images.githubusercontent.com/11355789/77505157-6823b680-6e88-11ea-8371-7010ee7683a5.png)

**Comment by edcable** [comment]
@Charulathakarthikeyan or @alexnavis Are you able to make a pull request with the fix from your commit reference above?

**Comment by alexnavis** [comment]
@edcable Will check and update by this week.

**Comment by BLasan** [comment]
@bharathgowda27 Can I work on this?

**Comment by spider0061** [comment]
@BLasan go ahead!

**Comment by bharathcgowda** [comment]
@BLasan  is this fixed?

**Comment by BLasan** [comment]
> @BLasan is this fixed?

Let me check this sir

**Comment by BLasan** [comment]
@bharathcgowda This is fixed. Button hits the API

**Comment by bharathcgowda** [comment]
@BLasan  Ok is the code merged? can we close this ticket then?

**Comment by BLasan** [comment]
> @BLasan Ok is the code merged? can we close this ticket then?

Yuh. We shall close this issue sir. Button works fine in the develop branch

**Comment by bharathcgowda** [comment]
Thank you for the confirmation @BLasan
