### ISSUE TITLE
Not able to submit new loan application with the submitted date as current system date (today's date)

### ISSUE THREAD

**Issue by subsnrao** [openMF/community-app#3204]
Observed in https://demo.mifos.io/#/createglaccount,
![image](https://user-images.githubusercontent.com/26272738/81130045-f600c000-8f63-11ea-999b-e299f441c03b.png)

**Comment by edcable** [comment]
@subsnrao I'm not able to reproduce this issue on https://dev.mifos.io. Can you try reproducing it there? Same credentials as https://demo.mifos.io.

**Comment by bharathcgowda** [comment]
closing this ticket as this issue doesnt exists
