### ISSUE TITLE
Angular Js is entering end of life in July 2021. 

### ISSUE THREAD

**Issue by Abhirup-99** [openMF/community-app#3252]
## Angular js is entering end of life in 2021 july and the app needs to migrate to ensure we remain up to date with the latest features and builds.

To ensure we are still up-to-date with the latest edition, we might have to migrate to either Angular, React or Vue.
## Steps to Reproduce
None

## Expected Behaviour
None
## Actual Behaviour
None
## Settings
None
- Mifos X version: 
None
- OS:
None

## Screenshots
None

**Comment by elirehema** [comment]
@Abhirup-99 can you give use enough detail and source of information, were you got this

**Comment by Abhirup-99** [comment]
@elirehema 
https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c
The blog from the angular team.

**Comment by elirehema** [comment]
@Abhirup-99  Check this Angular repo https://github.com/openMF/web-app

**Comment by Abhirup-99** [comment]
Sorry was unaware of it.
