### ISSUE TITLE
creating guarantor Some clients will not be seen in the drop down

### ISSUE THREAD

**Issue by francisguchie** [openMF/community-app#3253]
- **Browser used:** Mozilla and Chrome
- **OS:** Linux 18.04.01 LTS

**Actual  behavior:**
Some clients can not be seen even if the the response from
https://serveraddressOrname/fineract-provider/api/v1/clients
shows that all clients from table m_client are queried but not all show up in the response payload (pageItems: )

Only clients of MAIN PARENT BRANCH (branch id =1 ) will appear This does for self and non-self guarantor 
The Listed clients will include clients from BRANCH ID 1 and that Particular branch but the total shall be 200 and the user does not have the opportunity to filter the list generated. 

**Steps to reproduce: use steps below**
https://mifosforge.jira.com/wiki/spaces/docs/pages/85623288/How+to+Place+Guarantee+Funds+On-Hold

**Expected behavior:**
The page should load a limited list of clients avoid over loading the page but user should be able to select any client in the system by filtering the list using a branch selection, and a name of set of names 

Imagine a large database, the page should not load any data until the user filters this by branch and then later by client name or client id (if possible)

Please see image below how it should flow
![image](https://user-images.githubusercontent.com/22683654/87366092-5c5b1d80-c567-11ea-9005-75948d61d5a5.png)

- **Mifos X version**: Latest build of the Develop Branch

**Comment by elirehema** [comment]
Hello @francisguchie I once faced this problem and lastly I realized the platform limit fetched  data to 200.

**Comment by francisguchie** [comment]
@elirehema  the m_client table is queried for all records and only the first 200 are loaded onto the page for the user to select from. 

the user should be able to load the page first, select the branch in which the client is, and as the user types the name, the query is set to the server with parameters

**Comment by edcable** [comment]
Fixed by #3256
