### ISSUE TITLE
Can't select Default Savings Account when Creating New Share Account

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#3308]
## Navigate to any client with an active savings account, select New Share Account.

On the terms page, I am unable to select a savings account from drop down menu even if there's an active savings account for that member. 

It should display a list of savings accounts for that member that could be selected. 
![Screenshot 2020-09-22 at 4 42 21 PM](https://user-images.githubusercontent.com/823454/93948258-d390f880-fcf2-11ea-929a-a7c1d9a8d1d2.png)

**Comment by spider0061** [comment]
@BLasan can you please have a look at it.

**Comment by BLasan** [comment]
@bharathcgowda Shall we close the issue?

**Comment by bharathcgowda** [comment]
Thanks @BLasan
