### ISSUE TITLE
Bulk Import issue

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/community-app#3311]
The bulk import client from bulk import feature is not working.- throwing 500 internal server Error.

Tested on Fineract.dev instance, which is working as expected, whereas on the dev.mifos.io instance it is not.

Steps to reproduce,
1. go to admin->organization->bulk import
2.select client and download the client template for import(parameters for download: office: head office, Legal form: person, staff: any staff)
3.fill in the template and upload the same.
4.system will show the below-attached screenshot and error

{"timestamp":1601373977607,"status":500,"error":"Internal Server Error","message":"java.nio.file.AccessDeniedException: /opt/bitnami/tomcat/temp/MIME3715989654103796473.tmp","path":"/fineract-provider/api/v1/clients/uploadtemplate"}

![image](https://user-images.githubusercontent.com/65952533/94546067-0004c180-026b-11eb-8eb0-49ab16be7937.png)

You can also refer the import file which I used to reproduce the issue
[CLIENTS_PERSON2020-09-29.zip](https://github.com/openMF/community-app/files/5298214/CLIENTS_PERSON2020-09-29.zip)

**Comment by spider0061** [comment]
@BLasan can you have a look at it?

**Comment by BLasan** [comment]
> @BLasan can you have a look at it?

Sure :+1:

**Comment by BLasan** [comment]
@spider0061  Is this a valid endpoint? I checked the doc under clients APIs. But didn't find an API

**Comment by BLasan** [comment]
@bharathcgowda Sir, is this a valid end point? In docs I couldn't find this end point.

**Comment by BLasan** [comment]
@bharathcgowda Fill the necessary details in the xl sheet. It would work fine. Try the below file. It worked for me!

[CLIENTS_PERSON2020-11-09.xlsx](https://github.com/openMF/community-app/files/5510756/CLIENTS_PERSON2020-11-09.xlsx)

**Comment by BLasan** [comment]
Also there's an error with Entity type as when the file is going to be downloaded it will be saved as 'ENTTTTY'. Not 'ENTITY'. So cannot upload this type of files. Type will be assigned as null for those types of files @bharathcgowda

**Comment by bharathcgowda** [comment]
@BLasan  I tested on the latest instance and it is working as expected.
I guess the issue is with the dev.mifos.io instance only.
I am closing this ticket as I am able to successfully create bulk clients

**Comment by sujanpgowda** [comment]
Could you please share Any update on this @bharathcgowda facing this same issue. Thank you.
