### ISSUE TITLE
Error while accessing the application

### ISSUE THREAD

**Issue by saifromeo** [openMF/community-app#3314]
Team

I forked up the community app, built it successfully. No issues reported. After running 'grunt serve' the application keeps loading with the animation logo. No errors were shown in console (tried debug mode), no errros reported on the fineract server side as well.

While Inspecting the browser, I got the following errors

require.js:1961 GET http://172.105.39.59:9002/scripts/controllers/loanAccount/GLIMLoanAccountActionsController.js net::ERR_ABORTED 404 (Not Found)

require.js:1961 GET http://172.105.39.59:9002/scripts/controllers/loanAccount/ViewGLIMaccountController.js net::ERR_ABORTED 
require.js:168 Uncaught Error: Script error for "controllers/loanAccount/GLIMLoanAccountActionsController"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)

require.js:168 Uncaught Error: Script error for "controllers/loanAccount/ViewGLIMaccountController"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)

**Comment by awasum** [comment]
This is probably due to a name mismatch exception. The path name been used in a config declaration does not match the files on system. I will send a PR for this.

**Comment by awasum** [comment]
PR has been sent: https://github.com/openMF/community-app/pull/3315, will merge soon. Anyone wants to review and merge?
