### ISSUE TITLE
Unable to Edit the Shares Product

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/community-app#3327]
Unable to Modify the already created shares product. Submit button is not working

You can try out here:
https://openmf.github.io/community-app/?baseApiUrl=https%3A%2F%2Fdemo.fineract.dev&tenantIdentifier=default#/editshareproduct/2

![issue](https://user-images.githubusercontent.com/65952533/98686311-69114600-238e-11eb-9ce7-5dd208cc5a6b.png)

**Comment by tonic889** [comment]
I am able to reproduce this in my local repo as well, I will investigate and try to fix.

**Comment by bharathcgowda** [comment]
thank you for taking this up @tonic889

**Comment by bharathcgowda** [comment]
NOTE: support@habile.in . Habile team is currently working on this Issue.

**Comment by bharathcgowda** [comment]
closing this as the issue is fixed
