### ISSUE TITLE
GLIM application failure if loan product has charge that requires linked savings account

### ISSUE THREAD

**Issue by francisguchie** [openMF/community-app#3333]
When the user makes a GLIM Application for a loan product with a loan charges whose payment type is "Account Transfer" see image below, 
![image-2020-12-17-12-12-25-068](https://user-images.githubusercontent.com/22683654/103311495-92179400-4a2b-11eb-9407-2bf83e08a57b.png)
The Application hangs 

## Description
![image-2020-12-10-15-41-37-515](https://user-images.githubusercontent.com/22683654/103311635-ef134a00-4a2b-11eb-835d-f5b380dcae0d.png)

GLIM Application for a loan product that has a charge that requires a linked savings account. fineract will not submit the loan application it will send an error shown below. This error does not appear on the UI but rather in the Console of the browser 
##"Transaction is being rolled back. First erroneous request: \n{\"requestId\":0,\"statusCode\":500,\"body\":\"{
n \\\"developerMessage\\\": \\\"Request was understood but caused a domain rule violation.\\\",
n \\\"httpStatusCode\\\": \\\"403\\\",
n \\\"defaultUserMessage\\\": \\\"Errors contain reason for domain rule violation.\\\",
n \\\"userMessageGlobalisationCode\\\": \\\"validation.msg.domain.rule.violation\\\",
n \\\"errors\\\": [
n
{\\n \\\"developerMessage\\\": \\\"one of the charges requires linked savings account for payment\\\",\\n \\\"defaultUserMessage\\\": \\\"one of the charges requires linked savings account for payment\\\",\\n \\\"userMessageGlobalisationCode\\\": \\\"error.msg.loanCharge.requires.linked.account\\\",\\n \\\"parameterName\\\": \\\"id\\\",\\n \\\"args\\\": []\\n }

## Steps to Reproduce
Create a charge and make sure its payment type is by "**Account transfer**" and that this "**charge time type**" at disbursement see image below 
![image-2020-12-17-12-12-25-068](https://user-images.githubusercontent.com/22683654/103311768-40233e00-4a2c-11eb-8d07-90b5cb394838.png)
Create a loan product, add the charge created above to it
Select a group and click on GLIM Application, select the loan product above and fill in all other details, select a GSIM account to be linked to the GLIM 

## Expected Behaviour
1- If the charge set on the loan product is an an "account transfer type" then user should get a prompt or GLIM should **NOT** submit
2- If the charge set on the loan product is an an "Regular payment type" then GLIM should submit

## Settings

- Mifos X version: latest build (develop branch)
- Browser used: Chrome, New-Edge and Firefox
- OS: Windows 10, Ubuntu Linux

## Screenshots
![image-2020-12-10-15-41-37-515](https://user-images.githubusercontent.com/22683654/103313227-7793e980-4a30-11eb-85af-1c17b2d6cfb7.png)

**Comment by awasum** [comment]
PR https://github.com/openMF/community-app/pull/3334 has been merged for this issue. I am closing this now. Re-open it if this problem still occurs.
