### ISSUE TITLE
Change default baseAPIUrl

### ISSUE THREAD

**Issue by BLasan** [openMF/community-app#3335]
## Description
Cannot login to community app by using the default baseAPIUrl

## Steps to Reproduce
Change the baseApiUrl to https://dev.mifos.io in Gruntfile.js

## Expected Behaviour
Query parameter baseApiUrl will get changed to https://dev.mifo.io

## Screenshots
![communityapp-issue](https://user-images.githubusercontent.com/43112139/103473824-c049fa80-4dc2-11eb-9d32-cd47f8bb9fb2.gif)

**Comment by BLasan** [comment]
@spider0061 Shall we change the default baseApiUrl as I suggested for development purposes? From demo.mifos.io server, we cannot login to the system

**Comment by Abhirup-99** [comment]
use https://www.fineract.dev instead.
