### ISSUE TITLE
Client address fields are not coming

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/community-app#3336]
Enable client address configuration and try adding the address for a client.

When you click on the add address, the screen is blank and there are no fields to do the data entry(like address 1, state, city, etc)

check below screenshot for reference
![image](https://user-images.githubusercontent.com/65952533/103538163-b821b600-4ebb-11eb-8bc6-d6704e899d90.png)
![image](https://user-images.githubusercontent.com/65952533/103538207-ce2f7680-4ebb-11eb-9e5e-bdf8d7c22e12.png)

**Comment by raghu0812199** [comment]
hi @bharathcgowda i want to work on this issue can you please guide me

**Comment by bharathcgowda** [comment]
@raghu0812199  Thank you for taking initiative, did you try reproducing the issue by following the description provided?

login to https://openmf.github.io/community-app/?baseApiUrl=https%3A%2F%2Fdemo.fineract.dev&tenantIdentifier=default#/
username: mifos
password: password

click on create client ->try to add address (you will not get any fields to enter apart from address type selection dropdown)

Refer to screenshots above.

Let me know if you have any questions, we can connect on skype if required

**Comment by BLasan** [comment]
@bharathcgowda Sir, I would like to work on this issue. Before that we need to resolve the login issue.

**Comment by bharathcgowda** [comment]
@BLasan  I have informed the respective team to look into the log in issue.

**Comment by BLasan** [comment]
> @BLasan I have informed the respective team to look into the log in issue.

Thank you sir

**Comment by bharathcgowda** [comment]
Hi @BLasan, the login issue has been resolved :)
Let me know if you need any help on this issue.

**Comment by BLasan** [comment]
> Hi @BLasan, the login issue has been resolved :)
> Let me know if you need any help on this issue.

Sorry for being late. I'm taking a look now :)

**Comment by BLasan** [comment]
@bharathcgowda Address fields will be receiving after the button click
![Screenshot from 2021-01-27 21-35-11](https://user-images.githubusercontent.com/43112139/106018867-022b3f80-60e8-11eb-965f-0b303c19e4b4.png)

**Comment by BLasan** [comment]
This gives a validation error in address field.
![Screenshot from 2021-01-27 21-41-36](https://user-images.githubusercontent.com/43112139/106019551-c775d700-60e8-11eb-96e2-856127409802.png)

Payload for address field
```
addressLine1: "120/5"
addressLine2: "Maharagama"
addressLine3: "Pamunuwa"
addressTypeId: 36
city: "Colombo"
countryId: 19
isActive: true
stateProvinceId: 25
```

**Comment by BLasan** [comment]
@bharathcgowda Perhaps this validation issue is with the FINERACT server.

**Comment by bharathcgowda** [comment]
@BLasan  as we tested out, connection to dev.mifos.io would work from the latest community-app, but the issue persists on the latest codebase, we shall try locally and figure out if the issue is on the fineract first.
Thank you for all the digging  and support :)

**Comment by BLasan** [comment]
> @BLasan as we tested out, connection to dev.mifos.io would work from the latest community-app, but the issue persists on the latest codebase, we shall try locally and figure out if the issue is on the fineract first.
> Thank you for all the digging and support :)

np sir :)  I'll fix this issue
