### ISSUE TITLE
Tax field Edit/Add option not available on the Edit charge 

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/community-app#3337]
when you try to add a new tax group to the existing charge, the tax mapping field is disabled currently 

steps to reproduce
1. create a tax group
2. create a loan charge (without tax mapping)
3. edit the charge and try to add the tax group ( it doesn't allow to map as the field is disabled)

expected behaviour,
the system should allow changing the tax group on charge edits.

In practical scenarios, there would a requirement of changing the tax group or adding the tax group to the existing charge, for which we have to enable users to add/modify tax group during charge edit.

refer screenshot 
![image](https://user-images.githubusercontent.com/65952533/104466090-cddd5c80-55da-11eb-9778-640cd62297fb.png)

**Comment by sankha555** [comment]
@bharathcgowda may I please take this up?

**Comment by bharathcgowda** [comment]
Hi, Yes you can, Thank you @sankha555

**Comment by BLasan** [comment]
@sankha555 Are you working on this?

**Comment by sankha555** [comment]
Hey @BLasan , yep I am still working on it and have made some changes to the code. But I am not able to test it since the login isnt working for me, could you please help me out with the login. It would be great help.

![image](https://user-images.githubusercontent.com/54751139/105569628-2f36c580-5d69-11eb-8541-179770d2dbdd.png)

As can be seen here, the fineract uri returns that the server could not be found. The demo.mifos.io uri doesn't validate the credentials given in the docs. It is thus not being possible for me to login and test my changes. I have also tried other methods suggested by people on the repo and on the gitter channel but didn't work. Could you please help me in this regard to login successfully. @bharathcgowda ccing this to you if you could please help me and I could then complete the patch. Thanks in advance!

**Comment by BLasan** [comment]
> Hey @BLasan , yep I am still working on it and have made some changes to the code. But I am not able to test it since the login isnt working for me, could you please help me out with the login. It would be great help.
> 
> ![image](https://user-images.githubusercontent.com/54751139/105569628-2f36c580-5d69-11eb-8541-179770d2dbdd.png)
> 
> As can be seen here, the fineract uri returns that the server could not be found. The demo.mifos.io uri doesn't validate the credentials given in the docs. It is thus not being possible for me to login and test my changes. I have also tried other methods suggested by people on the repo and on the gitter channel but didn't work. Could you please help me in this regard to login successfully. @bharathcgowda ccing this to you if you could please help me and I could then complete the patch. Thanks in advance!

There's an issue with the login. I have already opened an issue for that. I'll try to get a response from @bharathcgowda sir as soon as possible regarding this issue.

**Comment by bharathcgowda** [comment]
Hello Team,

From the screenshot below, it looks like the front end is running
locally and trying to connect to fineract.dev server.
which gives me the feeling that the issue may not be because of the
community app and you are not connecting to the right server.

the correct server is
https://openmf.github.io/community-app/?baseApiUrl=https%3A%2F%2Fdemo.fineract.dev&tenantIdentifier=default#/

which is not yet working because of credentials not being reset yet.

dev.mifos.io Instance may have some infra issues, have informed the
respective team to look into it

Meanwhile, my suggestion is you can run the server locally and test it.

Regards,
Bharath
Lead Implementation Analyst | Mifos Initiative
Skype: live:cbharath4| Mobile: +91.7019635592
http://mifos.org  <http://facebook.com/mifos>
<http://www.twitter.com/mifos>

**Comment by sankha555** [comment]
@bharathcgowda Thanks a lot for the update. Also, could you please instruct me as to how I can login to the dashboard while testing it locally? Do I need to create a new user or are there some other procedures to be followed? Thanks!

**Comment by BLasan** [comment]
> @bharathcgowda Thanks a lot for the update. Also, could you please instruct me as to how I can login to the dashboard while testing it locally? Do I need to create a new user or are there some other procedures to be followed? Thanks!

I think you could use the default credentials for logging. mifos:password. Please re-correct this if I'm wrong @bharathcgowda

**Comment by BLasan** [comment]
If you are not working on this @sankha555 can I take up this issue ? @bharathcgowda

**Comment by bharathcgowda** [comment]
Yes you can :) @BLasan

**Comment by BLasan** [comment]
> Yes you can :) @BLasan

Will start fixing this tomorrow :)

**Comment by BLasan** [comment]
@edcable Sir, I think we can close this issue once @bharathcgowda sir or @spider0061 reviewed and approved the PR. (No drastic changes were added)

**Comment by BLasan** [comment]
> @edcable Sir, I think we can close this issue once @bharathcgowda sir or @spider0061 reviewed and approved the PR. (No drastic changes were added)
