### ISSUE TITLE
Default Login Credentials are not working

### ISSUE THREAD

**Issue by BLasan** [openMF/community-app#3341]
## Description
Cannot login to the Mifos platform by entering default credentials (username=mifos, password=password). This error occurs in both `dev.mifos.io` and `demo.mifos.io` baseAPIUrls.

## Expected Behaviour
Should be able to login using default credentials

## Actual Behaviour
Cannot login to the system using the above mentioned credentials.

**Comment by BLasan** [comment]
@bharathcgowda Sir, would you mind to take a look? Due to this developers cannot login to the system in order to validate their changes made.

**Comment by bharathcgowda** [comment]
Thank you for reporting this @BLasan 
It could be an infra issue, let me check with the respective team and get back
demo.mifos.io seems to be working, please check once

**Comment by BLasan** [comment]
Issue has been resolved
