### ISSUE TITLE
Add support for intro.js to community app

### ISSUE THREAD

**Issue by gsluthra** [openMF/community-app#338]
Add support for Intro.js to community app, so that newbies will find it easier to navigate and learn the UI. 

This ticket is just around integrating Intro.Js, and writing a Wiki page on how to add Intro.Js Help navigation to screen, so that then we can decide which screens will need Intro.JS navigation, and what help we wish to provide. 

More info on intro.js: http://usablica.github.io/intro.js/

**Comment by chanakaDe** [comment]
This is also a good selection.
http://bootstraptour.com/
Not very hard to configure.

**Comment by edcable** [comment]
I'm closing this ticket out as we're going to be adding support for pop-overs in the new web-app to support a configuration wizard at https://github.com/openMF/web-app/issues/800
