### ISSUE TITLE
Not able to view Journal Entries

### ISSUE THREAD

**Issue by BLasan** [openMF/community-app#3380]
## Description
When trying to view the Journal Entries for a transaction in Loan Account, it doesn't show up the necessary data. But the data will get fetched from the server. This might be valid for transactions in other accounts too.

## Screenshots
![Screenshot from 2021-04-15 18-22-15](https://user-images.githubusercontent.com/43112139/114872407-f2361880-9e17-11eb-91cf-b20fd70aa988.png)

**Comment by BLasan** [comment]
@bharathcgowda Please confirm this with the latest code base. If you face for the same issue please let me know

**Comment by bharathcgowda** [comment]
@BLasan  I was not able to find this issue on the Loan account, could you tell me the scenario or steps to reproduce?

**Comment by BLasan** [comment]
> @BLasan I was not able to find this issue on the Loan account, could you tell me the scenario or steps to reproduce?

Ok, will provide the steps :)

**Comment by BLasan** [comment]
@bharathcgowda  Here are the screenshots of the loan product
![Screenshot from 2021-04-19 16-02-44](https://user-images.githubusercontent.com/43112139/115223117-1603a200-a129-11eb-96c7-9a5d0cf041b9.png)
![Screenshot from 2021-04-19 16-02-54](https://user-images.githubusercontent.com/43112139/115223123-17cd6580-a129-11eb-9e0e-23e5c4149996.png)

Charge product screenshot
![Screenshot from 2021-04-19 16-04-32](https://user-images.githubusercontent.com/43112139/115223189-26b41800-a129-11eb-8dcc-d92c6de4b25a.png)

Loan Account Screenshots
![Screenshot from 2021-04-19 16-08-25](https://user-images.githubusercontent.com/43112139/115223780-cb365a00-a129-11eb-8480-e022b6dbc53b.png)
![Screenshot from 2021-04-19 16-08-38](https://user-images.githubusercontent.com/43112139/115223781-cd001d80-a129-11eb-9666-873820665a9e.png)
![Screenshot from 2021-04-19 16-08-47](https://user-images.githubusercontent.com/43112139/115223784-cd98b400-a129-11eb-97fa-995c8e1e2b9f.png)
![Screenshot from 2021-04-19 16-08-57](https://user-images.githubusercontent.com/43112139/115223786-ce314a80-a129-11eb-9cc5-0492d6b867c2.png)
![Screenshot from 2021-04-19 16-09-13](https://user-images.githubusercontent.com/43112139/115223788-cec9e100-a129-11eb-80c2-9abecda5707d.png)
![Screenshot from 2021-04-19 16-09-25](https://user-images.githubusercontent.com/43112139/115223789-cf627780-a129-11eb-8c57-5b986047b981.png)
![Screenshot from 2021-04-19 16-09-37](https://user-images.githubusercontent.com/43112139/115223794-cffb0e00-a129-11eb-956d-0e8597e5e619.png)
![Screenshot from 2021-04-19 16-09-55](https://user-images.githubusercontent.com/43112139/115223796-d093a480-a129-11eb-9ed1-0a90b5b7f1c0.png)
![Screenshot from 2021-04-19 16-09-59](https://user-images.githubusercontent.com/43112139/115223799-d12c3b00-a129-11eb-9d6e-4096910622dd.png)

**Comment by bharathcgowda** [comment]
Hi Benura,
As per the tagged screenshot, the accounting is "NONE" at the product level, hence you are not able to get the JEs. This is not an issue. hence closing it. 
Please select he accounting as CASH or ACCRUAL to enable accounting at loan level.
