### ISSUE TITLE
System picks incorrect GLs for Loan Disbursement Entries 

### ISSUE THREAD

**Issue by eroemma** [openMF/community-app#3416]
Hello, I have a situation with how the system makes System Entries at disbursement 
I have the GLs configured and mapped respectively for all Loan products and Savings products
**Loan product Configuration;**
Accounting = ACCRUAL UPFRONT 
Fund source = Till Cash (Account Type) Asset GL

**_Scenario:_**

At loan disbursement 
**Expected Entries**
Loan product (individual Business Loan)/Asset GL = **Debited**
Till Cash (Asset GL) = **Credited** 

**Actual Entries (system entries)**
Loan product (individual Business Loan)/Asset GL = **Debited**
Accounts Payable- suppliers (Liability GL) = **Credited** 

The problem here is the system selects Accounts payable -suppliers (Liability GL) instead of Till Cash (Asset GL)

What could cause such a thing?
How can I fix this issue and maybe how can transfers these balances to the Till Cash GL?
![COA](https://user-images.githubusercontent.com/61067720/129967695-ed057d91-a583-4c75-92dc-8ec5babddae2.jpg)
![Journal Entries after Loan Disbursement](https://user-images.githubusercontent.com/61067720/129967699-5084e9ba-0a1d-4a60-97ab-a4358ee5c62b.jpg)
![Loan Product Configurations](https://user-images.githubusercontent.com/61067720/129967701-af916bba-24a4-4825-b8b0-914207122a3f.jpg)

**Comment by francisguchie** [comment]
> Hello, I have a situation with how the system makes System Entries at disbursement
> I have the GLs configured and mapped respectively for all Loan products and Savings products
> **Loan product Configuration;**
> Accounting = ACCRUAL UPFRONT
> Fund source = Till Cash (Account Type) Asset GL
> 
> **_Scenario:_**
> 
> At loan disbursement
> **Expected Entries**
> Loan product (individual Business Loan)/Asset GL = **Debited**
> Till Cash (Asset GL) = **Credited**
> 
> **Actual Entries (system entries)**
> Loan product (individual Business Loan)/Asset GL = **Debited**
> Accounts Payable- suppliers (Liability GL) = **Credited**
> 
> The problem here is the system selects Accounts payable -suppliers (Liability GL) instead of Till Cash (Asset GL)
> 
> What could cause such a thing?
> How can I fix this issue and maybe how can transfers these balances to the Till Cash GL?
> ![COA](https://user-images.githubusercontent.com/61067720/129967695-ed057d91-a583-4c75-92dc-8ec5babddae2.jpg)
> ![Journal Entries after Loan Disbursement](https://user-images.githubusercontent.com/61067720/129967699-5084e9ba-0a1d-4a60-97ab-a4358ee5c62b.jpg)
> ![Loan Product Configurations](https://user-images.githubusercontent.com/61067720/129967701-af916bba-24a4-4825-b8b0-914207122a3f.jpg)

Kindly mention the version of Fineract you are using

**Comment by francisguchie** [comment]
@eroemma 

This could be a fineract issue as I have had this kind of issue before but i have not seen this again see this link https://issues.apache.org/jira/browse/FINERACT-1308

**Comment by eroemma** [comment]
@francisguchie 
Fineract Release Apache Fineract v1.5.0

Running on Version 17.07.01.RELEASE, then I restored the DB and upgraded it to Version 18.03.01.RELEASE and still the issue has not persisted.

**Comment by francisguchie** [comment]
@eroemma  
I think you are confusing these releases with fineract versions. They tease me too sometimes

Kindly stick to the latest release which is 21.07.01 (i.e Fineract v1.5.0)  see https://github.com/apache/fineract/releases and the latest release files in zip folder here https://sourceforge.net/projects/mifos/files/  

Just follow instructions here https://mifosforge.jira.com/wiki/spaces/docs/pages/2807201793/Mifos+X+21.07.01+Installation+Guide+with+Pentaho+plugin 
and stick with the latest - pack porting errors found in 17.07.01 and 18.03.01 might be a longer process for you

**Comment by eroemma** [comment]
@Francis Guchie ***@***.***> thank you for throwing more light
on the versions and release.
I will focus on the latest and test it.

Best regards.

**Comment by eroemma** [comment]
@francisguchie, I finally got the root of the issue and it was **Financial Activity mapping**, once the changes were done, all was something worth to smile about. cheers and thanks for guidance.

Best regard.

**Comment by eroemma** [comment]
The issue is sorted out
