### ISSUE TITLE
Is the project to integrate with Stellar still ongoing? I am interested in it

### ISSUE THREAD

**Issue by BruceTushabe** [openMF/community-app#3431]
## Settings

- Mifos X version: 
- Browser used:
- OS:

**Comment by francisguchie** [comment]
@BruceTushabe  
what is Stellar??

**Comment by BruceTushabe** [comment]
Stellar is a blockchain network that makes it possible to create, send, and trade digital representations of all forms of money: dollars, pesos, bitcoin, pretty much anything. It’s designed so all the world’s financial systems can work together on a single network.

Back in 2018, there was an initiative to build a stellar connector for mifos . I was following up on the same

**Comment by v3ss0n** [comment]
I think you have to ask at apache/fineract 
not on communityweb.

**Comment by francisguchie** [comment]
@BruceTushabe  
kindly close this issue as per @v3ss0n 's advise

**Comment by v3ss0n** [comment]
Thanks , steller is a crypto currency and blockchain  trying to make international payments easy..
As it is cryptocurrency we have to be careful when adding into an opensource project , steller also is quite volatile.

**Comment by BruceTushabe** [comment]
Thank you all for the feedback. Issue closed.
