### ISSUE TITLE
Uploading documents doesn't work

### ISSUE THREAD

**Issue by rahul-gill** [openMF/community-app#3485]
## Description
When uploading client documents, server error is received

## Steps to Reproduce
- go to clients from tabs at the top
- choose any client
- Go to documents tab
- Click on upload button
- fill in the details, and submit
- you'll this response
```json
{
"timestamp":1657455418278,
"status":500,"error":"Internal Server Error",
"message":"Access key cannot be null.",
"path":"/fineract-provider/api/v1/clients/1/documents"
}
```

**Comment by francisguchie** [comment]
@rrpawar96  @ikimbra have you noticed this before?

**Comment by francisguchie** [comment]
@rahul-gill  this issue was solved a long time ago
