### ISSUE TITLE
Failing to lononto Mifos demo site

### ISSUE THREAD

**Issue by htakawira** [openMF/community-app#3493]
Hello Mifos 

I am trying to log onto the Mifos demo site 

https://openmf.github.io/community-app/?baseApiUrl=https://demo.fineract.dev&tenantIdentifier=default#/

I am able to get the site open but i input the credentials :
Username : mifos
Password : password

I am getting the error message "Please try again, your credentials are not valid."

**Comment by francisguchie** [comment]
Hello htakawira,

I guess someone changed the password,  i would advise that you run your own
server





My Kind Regards





Francis Guchie Kirago

*Mobile:*

+232 79 194407

+256 70  5011852



*Skype:* francisguchie

*twitter*: @francisguchie

*Telegram: *232 79 19 44 07

*Whatsapp: *232 79 19 44 07
*LINKEDIN:* https://www.linkedin.com/in/francis-guchie-kirago-a4379617/
*Website: *https://guchietech.com
