### ISSUE TITLE
More Object-Oriented, more testable approach

### ISSUE THREAD

**Issue by Nayan** [openMF/community-app#70]
Now most of the code is in controllers objects. There are no additional models, nor additional services.

Putting behavior into 'models' and spreading responsibilities into 'services' is the main step toward a more Object-Oriented, more testable approach, leaving all the behavior in the Controllers sounds a lot more old school and "procedural", and usually harder to test and maintain

**Comment by edcable** [comment]
@gauravsaini03 @abhaychawla Should this issue remain open? I would think we can close it.

**Comment by abhaychawla** [comment]
Yes closing the issue.
