### ISSUE TITLE
Improvements in New JLG Loan application page

### ISSUE THREAD

**Issue by subramanyasn** [openMF/community-app#732]
1.It is difficult to select a particular client who apply for JLG Loan, for the clients with the same name. It would be better if Client ID is also displayed along with the name.
2. It would be better to have top check box for selecting all/to remove all clients.
3. Instead of generic Loan purpose it should be a dropdown infront of every client, so that individual client can select the Loan purpose.

![ui issue-49](https://f.cloud.github.com/assets/4114145/1928922/8efd68ce-7e8d-11e3-964a-800453d34534.png)

**Comment by chanakaDe** [comment]
Where I can find this loan application form ? In this new Community App develop branch ?

**Comment by edcable** [comment]
This issue has been fixed. 
![Screenshot 2020-06-13 at 10 35 46 PM](https://user-images.githubusercontent.com/823454/84585590-43bfe200-adc6-11ea-8461-0ffe90229ecd.png)
