### ISSUE TITLE
Issue with Percentage of Charges attached to Loans

### ISSUE THREAD

**Issue by subramanyasn** [openMF/community-app#738]
In Community app percentage of charge related to Loan is not working as expected. Issue raised in Jira Mifosx-827, Seems to be related to UI issue, discussing here.

Scenario 1:
*Create 2 charges-
a. 1% amount, due on Disbursement
b. 2% amount + Interest, due on Specified due date.
*Submit the new loan application for a client with the above mentioned charge  attached while submitting the application.
- Click on modify application in which % charge got modified, Click on cancel button.
- Click on Approve and click on disburse button.
  -> Not able to disburse the loan as error message displayed as "Meltdown in advanced accounting...sum of all charges is not equal to the fee charge for a transaction".

Scenario 2:
Not able to disburse Loan with the %amount+interest due on disbursement,error message displayed as "Meltdown in advanced accounting...sum of all charges is not equal to the fee charge for a transaction".

Scenario 3.
Charge is not getting mapped properly for the Loan disbursed with %amount due on disbursement, (Submit the Loan application with % amount -> Approve -> disburse -> Undo disbursal -> Undo approval -> Modify application -  do not modify any field in Modify application page click on save button. -> Approve -> Disburse the Loan.
The charge mapped differently in Repayment schedule page and in Transaction page.
![scenario-1 2](https://f.cloud.github.com/assets/4114145/1962588/1ecf8a54-828a-11e3-9fdf-4e4773e5dbe2.png)
![scenario-3-1](https://f.cloud.github.com/assets/4114145/1962589/1f06b600-828a-11e3-8bc0-9ce43d567dae.png)
![scenario-3-2](https://f.cloud.github.com/assets/4114145/1962590/23e7bae8-828a-11e3-8e4d-da2590e8cf0f.png)
![scenario-3-3](https://f.cloud.github.com/assets/4114145/1962591/23edb61e-828a-11e3-9b04-e8a5a2dd9aa6.png)

**Comment by francisguchie** [comment]
I see all the tests above are at or around disbursments and aprovals , what makes this error come at loan repayment. is it due to the undo and redo mentioned above?
